---
title: "내적"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

</br>

## 내적 (Inner product) 과 노름 (norm)

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_innerproduct}

#### 내적과 내적 공간

$\mathbb{F}$-벡터공간 $V$ 에서 정의된 $\phi : V \times V \to \mathbb{F}$ 가 모든 $u,\,u',\,v\in V$ 와 $c\in \mathbb{F}$ 에 대해 다음 성질을 만족하면 $\phi$ 를 $V$ 에서 정의된 **내적(Inner product)** 이라 한다.

&emsp; ($1$) $\phi (v,\,v) \ge 0$;

&emsp; ($2$) $\phi (v,\,v) = 0 \iff v = 0$;

&emsp; ($3$) $\phi (u + u', v)  = \phi (u,\, v) + \phi (u',\, v)$;

&emsp; ($4$) $\phi (cu,\,v) = c \phi (u,\,v)$;

&emsp; ($5$) $\phi (v,\, u) = \overline{\phi (u,\,v)}$.

[$x,\,y \in \mathbb{R}$ 에 대해 복소수 $z=x+iy$ 의 켤레복소수 $\overline{z}$ 는 $x-iy$ 이다. 즉 $\overline{x+iy}= x-iy$ 이다.]{.aside}

이것을 만족하는 함수는 어떤 것이든 내적이 될 수 있으며, 내적이 정의된 벡터공간을 **내적 벡터 공간(Inner product vector space)** 혹은 **내적 공간(Inner product space)**라 한다. 필드를 명시할 경우 $\mathbb{F}$-**내적 벡터 공간** 이라고 한다.흔히 두 백터의 내적을 $\langle u,\,v\rangle$ 로 쓰며 그 정의는 위의 $\phi$ 함수에 대해 $\langle u,\, v\rangle = \phi (u,\,v)$ 이다.$^\ast$ 

[$^\ast$ 물리학, 특히 양자역학에서는 소위 디렉 브라켓 기호를 사용하여 $\langle u,\, v\rangle$ 을 $\langle v\,|\,u\rangle$ 로 표기한다. $u,\,v$ 의 순서가 바뀌거 중간에 $\mid$ 가 삽입되는 것에 주의하라. ]{.aside}  
:::
:::

</br>

대표적인 내적 벡터 공간으로는 다음과 같은 것들이 있다.

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_innerproduct_R1_C1}

#### $\C^1$
$\mathbb{C}^1$, 즉 1차원 복소벡터공간에서의 내적을

$$
\langle c_1,\, c_2\rangle = c_1\overline{c_2}
$$

로 정의 할 수 있다. $\mathbb{R}^1$ 에서는

$$
\langle r_1,\, r_2 \rangle = r_1r_2
$$

로 정의할 수 있다.
:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_euclidean_innerproduct}

#### 유클리드 공간

$\mathbb{R}^n$ 에서 $x = (x_1,\ldots,\,x_n)$, $y=(y_1,\ldots,\,y_n)\in \mathbb{R}^n$ 의 내적을 $\langle x,\, y \rangle =  \sum_{i=1}^n x_i y_i$ 로 정의할 수 있으며 이렇게 내적이 정의된 공간을 **유클리드 공간 (Euclidean sapce)** 이라고 한다. 
:::

</div></br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_innerproduct_definded_by_intergration_in_R}

$[0,\,1]$ 구간에서 연속인 실함수로 이루어진 벡터공간에서의 내적을 아래와 같이 정의 할 수 있다.
$$
\langle f,\,g \rangle = \displaystyle \int_0^1 f(x)g(x)\, dx.
$$

복소공간에서는 다음과 같이 정의할 수 있다.

$$
\langle f,\,g \rangle = \displaystyle \int_0^1 \overline{f(x)}g(x)\, dx.
$$

:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_basic_properties_of_inner_product}

$V$ 가 $\mathbb{F}$-내적벡터공간이며 $u,\,v,\,w \in V,\, c \in \mathbb{F}$ 일 때 다음이 성립한다.

&emsp;($1$) 정해진 $u\in V$ 에 대해 $L_u(v) = \langle v,\,u \rangle$ 는 선형사상이다.

&emsp;($2$) $\langle 0,\, u\rangle = 0 = \langle u,\,0\rangle$.

&emsp;($3$) $\langle u,\, v+w \rangle = \langle u,\, v\rangle + \langle u,\, w \rangle$.

&emsp;($4$) $\langle u,\,c v\rangle = \overline{c} \langle u,\, v \rangle$.

&emsp;($5$) $\langle u,\, v \rangle = \overline{\langle v,\, u\rangle}$.
:::

</div></br>


::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_orthogonality_of_vector}

#### 벡터의 직교

두 벡터의 내적이 $0$ 일 때 두 벡터는 서로 **직교한다(be orthogonal, be perpendicular)** 고 한다. $\{v_1,\ldots,\,v_n\}$ 의 서로 다른 두 벡터가 모두 직교한다면 $\{v_1,\ldots,\,v_n\}$ 을 직교하는 벡터의 집합이라고 한다. 
:::
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_orthogonal_linearity}
내적벡터 공간 $V$ 에서의 영벡터가 아닌 벡터의 집합 $\{v_1,\ldots,\,v_n\}$ 이 직교하는 벡터의 집합이면 선형 독립이다.
:::

</div></br>

::: {.proof}
$\sum_i c_i v_i = 0_V$ 이라 하자. 선택된 $v_j$ 에 내적을 취하면,

$$
0 = \left\langle \sum c_i v_i,\, v_j \right\rangle = \sum_i c_i \langle v_i,\,v_j \rangle = c_j \langle v_j,\,v_j\rangle
$$

이다. $\langle v_j,\, v_j\rangle >0$ 이므로 $c_j= 0$ 이며 $j=1,\ldots,\,n$ 에 대해서 성립한다. 즉 $\{v_1,\ldots,\,v_n\}$ 은 선형독립이다. $\square$
:::

</br>

이로부터 다음 명제가 자연스럽게 나온다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-LA_number_of_orthogonal_vectors}
유한차원 내적벡터공간에서 직교하는 벡터의 갯수는 그 차원보다 많을 수 없다.
:::

</div></br>

:::{.proof}
@lem-LA_number_of_basis 를 보라.
:::


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_norm}
#### 노름 과 거리함수

$\mathbb{F}$-벡터공간 $V$ 에서 벡터의 **노름(norm)** 은 다음을 만족하는 함수이다.

&emsp; ($1$) $\forall v\in V,\, \|v\| \ge 0$, 

&emsp; ($2$) $\|v\| = 0 \iff v=0$,  

&emsp; ($3$) $\forall c\in \mathbb{F},\, \|cv\|= |c|\|v\|$, 

&emsp; ($4$) $\forall u,\,v\in V,\, \|u+v\| \le \|u\| + \|v\|$.

노름이 부여된 벡터공간을 **노름공간(normed space)** 이라고 한다. 노름공간 $V$ 에서의 **거리함수** 혹은 **metric** $d:V \times V \to [0, \infty)$ 는

$$
d(u, v) = \|u-v\|
$$

로 정의된다. 

:::
:::

</br>

벡터공간에서의 내적과 마찬가지로 노름 역시 공간에 부여된 특정 조건을 만족하는 함수이다. 내적벡터공간은 그 자체로 거리공간인데 이것은 내적에 의해 노름과 거리함수가 자연스럽게 정의되기 때문이다. 참고로 노름공간은 거리함수가 부여된 벡터공간이지만 엄밀한 의미에서의 거리공간은 벡터공간이 아닐 수도 있으며, 단지 적절한 거리함수가 정의된 집합이면 거리공간이다. 여기서는 거리함수가 부여된 벡터공간인 노름공간만을 생각한다.

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_norm_space_1}

#### $L_p$ 노름

$V=\mathbb{R}^n$ 에 대해 $v=(v_1,\ldots,\,v_n)$ 일 때 $p\in \mathbb{Z}_+$ 에 대해 

$$
\|v\|_p = \left(\sum_{i=1}^n |v_i|^p\right)^{1/p}
$$

도 노름이다. 이것을 $L_p$ 노름이라고 한다. 유클리드 노름은 $L_2$ 노름이다.

$$
\|v\|_\infty = \max\{ |v_1|, \ldots,\,|v_n|\}
$$

역시 노름이며 $L_\infty$ 노름이라고 한다. $L_p$ 노름과 $L_\infty$ 노름이 @def-LA_norm 의 조건을 만족한다는 것을 보이는 것은 독자에게 맡긴다. $L_p$ 노름에서 $\|u+v\|_p\le \|u\|_p+\|v\|_p$ 를 [민코프스키 부등식](https://en.wikipedia.org/wiki/Minkowski_inequality) 이라고 한다.

:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_innerproduct_norm}

내적 백터공간 $V$ 의 두 벡터 $u,\,v$ 에 대해 다음이 성립한다. 

&emsp;($1$)  $\langle u,\,v \rangle = 0 \implies \langle u + v, u+v\rangle = \langle u, u\rangle^2 + \langle v, v\rangle^2$.

&emsp;($2$) $|\langle u,\,v \rangle | \le \sqrt{\langle u, u\rangle \langle v,v \rangle}$.

:::

</div></br>

::: {.proof}

뒤에 사용하겠지만 일단은 임시방편으로 $\langle v, v\rangle = \|v\|^2$ 라고 하자. @def-LA_innerproduct 에 의해 $\|v\|\ge 0$ 이며 $\|v\|=0 \iff v=0$ 임을 알 수 있다. ($1$) 은 쉽게 보일 수 있다. ($2$) $v=0$ 일 때는 자명하다. 이제 $v\ne 0$ 일 경우만을 생각하자. $w=\|v\|^2 u - \langle u,\, v\rangle v$ 라고 하면, $\|w\|^2\ge 0$ 이므로, 

$$
\begin{aligned}
\|w\|^2 = \langle w, w\rangle &= \|v\|^4 \|u\|^2- \|v\|^2 \overline{\langle u, v\rangle}\langle u, v\rangle - \|v\|^2 \langle u, v \rangle \langle v, u \rangle + \|v\|^2 |\langle v, u\rangle |^2\\
& = \|v\|^2(\|u\|^2 \|v\|^2 -  |\langle u,v\rangle| ) \ge 0
\end{aligned}
$$

이다. 즉 $\|u\|^2\|v\|^2 \ge |\langle u, v\rangle|$ 이다. $\square$

:::

</br>

위에서는 임시변통으로 $\langle v, v\rangle = \|v\|^2$ 라고 했지만 이렇게 정의된 함수는 실제로 거리함수이다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_norm_of_innerproduct_space}

#### 내적 공간의 노름

$\mathbb{F}$-내적벡터공간에서 $\sqrt{\langle v,\, v\rangle}$ 은 거리함수이다.

:::

</div></br>

::: {.proof}

@def-LA_innerproduct 에서의 ($1$), ($2$) 로부터 @def-LA_norm 의 ($1$), ($2$) 가 성립함을 알 수 있다. @def-LA_innerproduct 의 ($4$) 로 부터 $\|cv\|^2= |c|^2 \|v\|^2$ 라는 것을 알 수 있으며 $\|cv\|\ge 0$ 이므로 $\|cv\| = |c|\|v\|$ 이다.

이제 ($4$) 를 보이자. 

$$
(\|u\|+\|v\|)^2 - \|u+v\|^2 = 2\|u\|\|v\|- \langle u, v\rangle - \langle v, u \rangle
$$

인데 $\mathbb{R}$-내적벡터공간에서는 

$$
\langle u, v\rangle = \langle v, u\rangle \le |\langle u, v\rangle |
$$

이며 $\mathbb{C}$-벡터공간에서는 

$$
\langle u, v\rangle + \langle v, u\rangle = \text{Re}(\langle u, v\rangle) \le |\langle u, v\rangle|
$$

이므로 @prp-LA_innerproduct_norm 의 ($2$) 를 이용하면

$$
(\|u\|+\|v\|)^2 - \|u+v\|^2 = 2\|u\|\|v\|- \langle u, v\rangle - \langle v, u \rangle \ge 2\|u\|\|v\| - |\langle u, v\rangle| \ge 0
$$

임을 알 수 있다. $\square$

:::

</br>

실제로 내적벡터공간은 거리공간이지만 내적 없이 거리함수만 정의된 공간도 있다. 여기서는 주 관심사가 내적벡터공간이기 때문에 노름 혹은 거리함수를 말할 때는 내적에 의해 정의된 $\|v\| = \sqrt{\langle v, v \rangle}$ 만을 의미한다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_norm_in_innerproduct_space}

내적 백터공간 $V$ 의 두 벡터 $u,\,v$ 에 대해 다음이 성립한다. 

&emsp;($1$) 피타고라스 정리 : $\langle u,\,v \rangle = 0 \implies \|u + v\|^2 = \|u\|^2 + \|v\|^2$.

&emsp;($2$) 코시-슈바르츠 부등식 :$|\langle u,\,v \rangle | \le \|u\| \|v\|$.

&emsp;($3$) 삼각부등식 : $\|u+v\| \le \|u\|+ \|v\|$.

&emsp;($4$) 평행사변형 공식 : $\|u+v\|^2+\|u-v\|^2 = 2\|u\|^2+2\|v\|^2$.
:::

</div></br>

::: {.proof}
($1$), ($2$), ($3$) 은 이미 보였다. ($4$) 는 쉽게 보일 수 있다.
$\square$
:::

</br>

## 정규직교기저

### 정규직교벡터와 정규직교기저 {#sec-LA_orthonomal_vectors_and_orthonormal_basis}

내적벡터공간 $V$ 의 기저 $\{h_i\}$ 를 생각하자. 두 벡터 $u=\sum_i u_i h_i,\, v= \sum_j v_j h_j$ 의 내적은 다음과 같다.

$$
\begin{aligned}
\langle u,\, v\rangle &= \left\langle \sum_i u_i h_i, \sum_j v_j h_j \right\rangle \\
&= \sum_i u_i\left\langle h_i,\, \sum_j v_j h_j \right \rangle \\
&= \sum_{i, j} u_i \overline{v_j} \langle h_i,\, h_j \rangle .
\end{aligned} 
$$ {#eq-innerproduct}


즉 각각의 기저의 쌍에 대한 내적을 알면 벡터의 내적을 계산 할 수 있다. 그런데 만약 서로 다른 두 기저벡터의 내적이 $0$ 이라면, 즉 기저들이 직교한다면 $\|h_i\|^2$ 만을 생각해도 되기 때문에 계산이 쉬워질 것이다. 거기에 더하여 기저벡터의 노름이 모두 1 이라면 더욱 쉬워질 것이다. 이것을 만족하는 기저를 정규직교기저라고 한다.


</br>

::: {.callout-note appearance="simple" icon="false"}

::: {#def-LA_orthonormal_Basis}

#### 정규직교벡터와 정규직교기저

내적벡터공간의 벡터의 집합 $\{v_1,\ldots,\,v_n\}$ 의  직교하는 벡터의 집합이며 벡터의 노름이 모두 $1$ 일 때, 즉 $\langle v_i,\,v_j\rangle = \delta_{ij}$ 일 때 **정규직교벡터 (orthonormal vectors)** 라 한다. 정규직교기저벡터가 선형독립임은 @prp-LA_orthogonal_linearity 에서 보았다. 정규직교벡터가 벡터공간의 기저일 때 이 기저를 **정규직교기저 (orthonormal basis)** 라 한다. 
:::
:::


</br>

우리는 @prp-LA_orthogonal_linearity 와 @cor-LA_number_of_orthogonal_vectors 를 통해 유한차원 내적벡터공간의 서로 직교하는 벡터의 갯수는 벡터공간의 차원보다 작거나 같다는 것을 안다. 정규직교기저가 되기 위해서는 정규직교벡터의 숫자가 차원과 같아야 하는데 이것은 뒤에 [그람-슈미트 과정과 정규직교기저](#sec-LA_gram_schmidt) 에서 자연스럽게 알게 된다. 

</br>

### 정규직교벡터의 성질 {#sec-LA_properties_of_orthonormal_vectors}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_properties_of_orthonormal_vectors}

$\{e_1,\ldots,\,e_m\}$ 이 $\mathbb{F}$-내적벡터공간 $V$ 에서의 정규직교벡터일 때 다음이 성립한다.


&emsp;($1$) $\{e_1,\ldots,\,e_m\}$ 은 선형독립이다.

&emsp;($2$) $a_1,\ldots,\,a_m\in \mathbb{F}$ 일 때 $\|a_1e_1 + \cdots + a_me_m \|^2 = |a_1|^2 + \cdots + |a_m|^2$ 이다.

&emsp;($3$) (**베셀 부등식 (Bessel's inequality)**) $v\in V$ 일 때 $|\langle v,\,e_1\rangle + \cdots + \langle v,\,e_m\rangle|^2 \le \|v\|^2$ 

:::

</div></br>

::: {.proof}

($1$) $c_1,\ldots,\,c_m\in \mathbb{F}$ 에 대해 $c_1e_1 + \cdots +c_me_m=0_V$ 이라고 하자. $0 = \langle 0_V,\,e_j\rangle =c_j$ 이므로 $c_1=\cdots = c_m=0$ 이다. 따라서 $\{e_1,\ldots,\,e_m\}$ 은 선형독립이다.

($2$) $v=a_1e_1+\cdots+a_me_m$ 이라고하자. $\|a_1e_1+\cdots + a_me_m\|^2 = \|v\|^2 = \langle v,\, v\rangle$ 이며,

$$
\langle v,\, v\rangle = \left\langle \sum_i a_ie_i , \sum_j a_j e_j\right\rangle = \sum_{i, j} a_i \overline{a_j}\langle e_i,\, e_j \rangle = \sum_i |a_i|^2.
$$

($3$) $w = \langle v, e_1\rangle e_1 + \cdots + \langle v,\,e_m\rangle e_m$ 이라 하자. $v=w+(v-w)$ 이며 

$$
\langle v-w,\,w\rangle =\sum_{i=1}^m \langle v,\,e_i\rangle \langle v-w,\, e_i\rangle = \sum_{i=1}^m \langle v,\, e_i\rangle \left( \langle v,\,e_i\rangle - \langle w,\, e_i \rangle\right) = 0
$$

이다. 따라서, 

$$
\|v\|^2 = \|w\|^2 + \|v-w\|^2 \ge \|w\|^2
$$

이다. $\square$

:::

</br>


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_properties_of_orthonormal_basis}

$(e_1,\ldots,\,e_n)$ 이 $\mathbb{F}$-내적벡터공간 $V$ 에서의 정규직교기저일 때 다음이 성립한다.


&emsp;($1$) $v\in V$ 에 대해 $\displaystyle v=\sum_{i=1} \langle v,\,e_i\rangle e_i$ 이다.

&emsp;($2$) $u,\,v\in V$ 에 대해 $u=\sum_{i}u_i e_i,\, v=\sum_j v_j e_j$ 일 때 $\displaystyle \langle u,\,v \rangle = \sum_{i=1}^n u_i\overline{v_i}$ 이다. 

:::

</div></br>

::: {.proof}

($1$) $v=\sum_i^n c_i e_i$ 일 때 $\langle v,\,e_j\rangle = c_i$ 이다.

($2$) $\displaystyle \langle u,\,v\rangle = \sum_{i,j} \langle u_ie_i,\,v_je_j\rangle = \sum_{i,j} u_i\overline{v}_j \langle e_i,e_j\rangle = u_i\overline{v_j}$. $\square$

::: 

</br>

### 정규직교기저벡터에 대한 연산자의 행렬 표현 {#sec-LA_matrix_representation_of_operator_using_orthonormal_basis}

$L\in \mathcal{L}(V)$ 라 하자. $\mathcal{B}=(e_i)$ 이 정규직교기저벡터일 때 $L$ 는

$$
L(e_j) = \sum_{k=1}^n A_{kj}e_k
$$

라 하자.

$$
\langle L(e_j),\, e_i\rangle = \sum_{k=1}^n \langle A_{kj}e_k,\, e_i\rangle = \sum_{k=1}^n A_{kj} \langle e_k,\, e_i\rangle = A_{ij}
$$

이다. 즉,

$$
A_{ij} = \langle L(e_j),\, e_i \rangle
$$

이다.

</br>


정규직교기저를 이용하면 내적이나 행렬 계산을 포함한 많은 것이 편해진다. 그렇다면 당연한 질문을 던질 수 있다. 어떤 조건에서 정규직교기저를 얻을 수 있는가? 답은 언제나이다. 내적벡터공간에서는 어떤 기저든 한 기저를 구했다면 그 기저를 바탕으로 정규직교기저를 얻을 수 있다. 한 기저에서 정규직교기저를 구하는 방법은 여러가지가 있지만 그중에서 한가지를 알아보도록 하자.


</br>

## 그람-슈미트 과정과 정규직교기저 {#sec-LA_gram_schmidt}

### 벡터에 대한 정사영 (Projection) {#sec-LA_projection_on_vector}

두 벡터의 내적이 $0$ 일 때 두 벡터는 직교한다(be perpendicular)고 하며, 한 벡터가 다른 벡터의 스칼라곱일 때 두 벡터가 **평행하다(be parallel)** 고 한다. 내적벡터공간 $V$ 의 두 벡터 $u,\,v$ 가 주어졌다고 하자. 이 때 $v$ 의 $v$ 에 대한 Projection $\text{Proj}_u v$ 를 아래와 같이 정의하자.

$$
\text{Proj}_{u}v = \dfrac{\langle v,\, u\rangle}{\langle u,\, u\rangle} u
$$

$\text{Proj}_u v$ 는 $u$ 에 평행하며 ($u$ 의 스칼라곱이니 당연하다), $v-\text{Proj}_u v$ 는 $v$ 에 직교한다. 즉

$$
\langle  v , \,v-\text{Proj}_{u} v \rangle  = 0
$$

이다. $v = \text{Proj}_u v + (v - \text{Proj}_u v)$ 이므로 $v$ 를 $u$ 에 대해 수직한 벡터와 평행하는 벡터의 합으로 표현 할 수 있다.

</br>

### 그람-슈미트 과정 (Gram-Schmidt Process) {#sec-LA_gram-schimidt_process}

그람-슈미트 과정을 통해 유한차원 내적 벡터공간에서 주어진 독립 벡터를 이용하여 같은 갯수의 정규 직교 벡터를 얻을 수 있다. $n$ 차원 내적 벡터 공간 $V$ 에서 $m$ 개의 독립벡터 $\{v_1,\ldots,v_m\}$ 이 주어졌다고 하자. (당연히 $m \le n$ 이다). 정규직교벡터의 집합 $\{e_1,\ldots,\,e_m\}$ 을 그람-슈미트 과정을 수행하여 얻을 수 있다. 그람-슈미트 과정을 귀납적으로 표현하면 다음과 같다.

::: {.callout-tip title="그람-슈미트 과정" appearance="minimal"}
$1$. 우선 $u_1 =  v_1$, $e_1 = \dfrac{u_1}{\|u_1\|}$ 라 한다.

$2$. 우리가 $u_1,\ldots,\,u_{k-1}$ 을 얻었을 때 (즉, $e_1,\ldots,e_{k-1}$ 을 얻었을 때) $u_k$ 와 $e_k$ 는 다음과 같이 얻는다.  

$$
u_k = v_{k} - \sum_{j=1}^{k-1} \text{Proj}_{e_j} v_k = v_k-\sum_{j=1}^{k-1} \left\langle v_k,\, e_j \right\rangle e_j,\qquad e_k = \dfrac{u_k}{\|u_k\|} \;.
$$

:::

</br>

이제 이렇게 해서 얻은 $\{e_1,\ldots,\,e_m\}$ 이 정규직교벡터의 집합이라는 것을 보이자.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_gram_schmidt}
위 과정을 통해 얻은 $\{e_1,\ldots,\,e_m\}$ 은 orthonomal 하다. 즉, $\langle e_i,\, e_j\rangle = \delta_{ij}$ 이다.
:::

</div></br>

::: {.proof}
$e_k = \dfrac{u_k}{\|u_k\|}$ 로 정의되었으므로 $\|e_k\|^2=1$ 이다. 따라서 $i\ne j$ 일 때 $\langle e_i,\, e_j\rangle = 0$ 임을 보이면 된다. 수학적 귀납법을 통해 보일 것이며 우선 $\langle u_2,\,u_1\rangle = 0$ 임을 보이자.

$$
\begin{aligned}
\langle u_2,\, u_1 \rangle &= \langle v_2- \langle v_2,\, e_1\rangle e_1,\, v_1 \rangle  = \langle v_2,\,v_1\rangle - \langle v_2,\,e_1 \rangle \langle e_1,\, v_1\rangle \\
&= \langle v_2,\,v_1\rangle - \dfrac{1}{\|v_1\|} \langle v_2,\,v_1\rangle \|v_1\| = 0
\end{aligned}
$$

이다. 이제 $u_{k}$ 는 $u_1,\ldots,\,u_{k-1}$ 와 모두 직교한다고 가정하자. 임의의 $j\le k$ 에 대해,

$$
\begin{aligned}
\langle u_{k+1},\, u_j\rangle  &= \left\langle v_{k+1}- \sum_{i=1}^{k} \langle v_{k+1},\, e_i\rangle e_i,\, \|u_j\|e_j \right\rangle \\
&= \|u_j\| \langle v_{k+1},\, e_j\rangle  - \|u_j\| \sum_{i=1}^k \langle v_{k+1},\, e_i \rangle \langle e_i,\, e_j\rangle \\
&= \|u_j\| \langle v_{k+1},\,e_j\rangle -\|u_j\|\sum_{i=1}^{k} \langle v_{k+1},\, e_i\rangle \delta_{ij} \\
&= \|u_j\| \langle v_{k+1},\,e_j\rangle -\|u_j\| \langle v_{k+1},\,e_j\rangle  = 0.
\end{aligned}
$$

이다. 따라서 $\{e_1,\ldots,\,e_m\}$ 은 orthonormal 하다. $\square$

:::

</br>

이제 우리는 다음의 중요한 결론을 얻는다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_orthonormal_basis}
$V$ 가 유한차원 내적벡터공간이며 $\mathcal{B}_V= (v_i)$ 가 $V$ 의 기저일 때 $\mathcal{B}_V$ 로부터 정규직교기저를 얻을 수 있다.
:::

</div></br>

::: {.proof}
$\mathcal{B}_V$ 는 선형독립이므로 Gram-Schmidt 과정을 통해 얻은 정규직교벡터는 $V$ 의 정규직교기저이다. $\square$

:::

</br>

그람-슈미트 과정은 내적벡터공간에 기저가 주어지면 이 기저의 선형결합으로 정규직교기저를 얻을 수 있음을 보장한다. 우리는 앞서 @thm-LA_uppertriangular_matrix_complex_field 에서 유한차원 $\mathbb{C}$-벡터공간에서의 모든 연산자는 어떤 기저에서 상삼각 행렬로 표현된다는 것을 보였다. 유한차원 $\mathbb{C}$-내적벡터공간에서는 정규직교기저에대해 상삼각 행렬로 표현되는 것을 보이자.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_schure}

#### 슈어 정리 (Schur's Theorem)

유한차원 $\mathbb{C}$-내적벡터공간 $V$ 에서 정의된 연산자 $L\in \mathcal{L}(V)$ 는 어떤 정규직교기저에서 상삼각행렬로 표현된다.
:::

</div></br>

::: {.proof}
$V$ 를 $n$ 차원 $\mathbb{C}$-내적벡터공간이라 하자. @thm-LA_uppertriangular_matrix_complex_field 에서 $L\in \mathcal{L}(V)$ 는 어떤 기저 에서 상삼각행렬로 표현된다는 것을 보였다. 이 기저를 $\mathcal{B}_V = \{v_1,\ldots,\,v_n\}$ 이라 하고, 그람-슈미트 과정을 통해 얻은 정규직교기저를 $\{e_1,\ldots,\,e_n\}$ 이라 하자. 즉 $e_i \in \text{span}(v_1,\ldots,\,v_i)$ 이다. 그렇다면, 그람 슈미트 과정으로부터

$$
\text{span}(e_1,\ldots,\,e_j) = \text{span}(v_1,\ldots,\,v_j), \quad j=1,\ldots, n
$$

임을 안다. $L$ 가 $\mathcal{B}_V$ 에서 상삼각 행렬로 표현되므로 $L(v_i) \in \text{span}(v_1,\ldots,\,v_i)$ 이며, 따라서

$$
(v_i) \in \text{span}(v_1,\ldots,\,v_i) = \text{span}(e_1,\ldots,\,e_i)
$$

이다. 즉 $L$ 는 정규직교기저에서 상삼각 행렬로 표현된다. $\square$
:::

</br>

::: {.callout-important}

내적벡터공간에서 항상 정규직교기저를 구할 수 있으며, 정규직교기저에서 여러 계산이 편해지기 때문에 정규직교기저를 가정하고 문제를 푸는 경우가 많다.

:::

<br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_reisz_representation_theorem_1}

#### Riesz 의 표현 정리 1 (Reisz Representation theorem 1) {#sec-LA_Reisz_representation_theorem_1}

유한차원 내적벡터공간 $V$ 에서 정의된 선형 범함수 $\varphi$ 는 어떤 벡터 $v\in V$ 에 대한 내적으로 표현 될 수 있다. 즉,

$$
\varphi (u) = \langle u,\, v\rangle
$$

이다. 또한 선형 범함수를 내적으로 표현할 수 있도록 해 주는 벡터 $v$ 는 유일하다. 

:::

</div></br>

::: {.proof}

$(e_1,\ldots,\,e_n)$ 이 $V$ 의 정규직교기저라 하자. $u=\sum a_i e_i$ 라고 하면 

$$
\begin{aligned}
\varphi (u) &= \varphi \left(\sum_i a_i e_i\right) = \sum_i a_i \varphi(e_i) = \sum_i \langle u,\,e_i\rangle  \varphi(e_i) \\ 
&= \sum_i \langle u,\, \overline{\varphi (e_i)}e_i \rangle \\ 
&= \left\langle u,\, \sum_i \overline{\varphi(e_i)} \, e_i \right\rangle
\end{aligned}
$$

이므로, $v = \sum_i \overline{\varphi (e_i)}e_i$ 로 잡으면 된다. 이제 유일성을 보이자. $\varphi (u) = \langle u,\, v\rangle = \langle u,\,v'\rangle$ 이라 하자. 모든 $u\in V$ 에 대해 $\langle u, v-v'\rangle =0$ 이므로 $u=v-v'$ 을 생각하면 $v=v'$ 이어야 한다. $\square$

:::

::: {.callout-warning appearance="minimal" icon="false"}

Reitz 의 표현정리는 유한차원 내적벡터공간에서만 성립하며 무한차원에서는 성립하지 않는다. @exr-axler_6_B_15 를 보라.
:::

</br>

## 조르당-폰 노이만 정리 {#sec-jordan_von_neumann_theorem} 

우리는 앞서 @prp-LA_norm_of_innerproduct_space 에서 내적벡터공간에는 자연스러운 거리함수가 존재한다는 것을 보였다. 즉 내적공간은 거리공간이다. 그렇다면 어떤 조건에서 거리공간은 내적공간이 될 수 있을까를 말해주는 것이 조르당-폰 노이만 정리이다. 결론적으로 말하자면 거리공간에 사다리꼴 공식이 성립한다면 내적공간이 되며 이것을 조르당-폰 노이만 정리라고 한다. 우선 실벡터 공간에 대해서 보이고 이후 복소벡터 공간에서 보이도록 하자. 다만 이것의 증명을 위해서는 연속에 대한 해석학적인 지식이 필요하다.

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_jordan_von_neumann_1}

$\mathbb{R}$-거리 공간 $V$ 에서 함수 $\phi : V \times V \to [0, \infty)$ 를 다음과 같이 정의하자.

$$
\phi (u, v)= \dfrac{\|u+v\|^2-\|u-v\|^2}{4}. 
$$ {#eq-innerproduct_from_norm_in_R}

이 때 모든 $u,\,v\in V$ 에 대해 평행사변형 공식 $\|u+v\|^2 + \|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 를 만족한다면 $u,\,u',\,v\in V$ 에 대해 다음이 성립한다.

$$
\phi(u+u', v)= \phi(u, v) + \phi(u', v)
$$

:::

</div>

</br>

::: {.proof}

평행사변형 공식으로 부터

$$
\|u-v\|^2 = 2\|u\|^2+2\|v\|^2-\|u+v\|^2
$$ 

임을 안다. 이를 이용하면 (다음줄로의 계산에서 변경되는 부분에 밑줄을 그었다.)

$$
\begin{aligned}
\phi(u+u',v) &= \dfrac{1}{4} \left(\underline{\|u+u'+v\|^2} -\|u+u'-v\|^2\right)\\
&=  \dfrac{1}{4} \left( \underline{-\|u-u'+v\|^2}+2\|u+v\|^2+2\|u'\|^2 - \underline{\|u+u'-v\|^2}\right)\\
&=  \dfrac{1}{4} \left( -2\|u\|^2 -2\|u'-v\|^2 +2\|u+v\|^2+2\|u'\|^2 \right)\\
&= \dfrac{1}{2} \left( \|u+v\|^2 + \|u'+v\|^2-\|u\|^2-\|u'\|^2 -2\|v \|^2 \right) \\
\phi(u,v) + \phi(u', v) &=\dfrac{1}{4} \left( \|u+v\|^2-\underline{\|u-v\|^2}+\|u'+v\|^2-\underline{\|u'-v\|^2} \right) \\
&= \dfrac{1}{4} \left[2\|u+v\|^2 - 2\|u\|^2-2\|v\|^2 + 2\|u'+v\|^2 -2\|u'\|^2-2\|v\|^2\right]\\
&= \dfrac{1}{2} \left[ \|u+v\|^2 +\|u'+v\|^2 -\|u\|^2 -\|u'\|^2 - 2\|v\|^2\right] \\
\end{aligned}
$$

이므로 $\phi (u+u',v) = \phi(u,v)+\phi(u', v)$ 이다. $\square$

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_jordan_von_neumann_2}

@lem-LA_jordan_von_neumann_1 과 같은 조건에서 $u,\,v\in V,\, c\in \mathbb{R}$ 일 때 다음이 성립한다.

$$
\phi (cu, v) =  c\phi (u, v).
$$
:::

</div></br>

::: {.proof}

$S= \{c\in \mathbb{R}: \phi (cu,v)=c\phi (u, v)\}$ 일 때 $S=\mathbb{R}$ 임을 보이자. 우선 $0,\, 1\in S$ 임은 자명하다. 또한

$$
0 = \phi (0, v) = \phi (u-u, v) = \phi(u, v) + \phi (-u, v)
$$

으로부터 $\phi (-u, v)=-\phi(u, v)$ 임을 안다. 즉 $-1\in S$ 이다. 

이제 $c\in S\implies c+1\in S$ 임을 보이자. @lem-LA_jordan_von_neumann_1 의 결과를 이용해 다음과 같이 보일 수 있다.

$$
\begin{aligned}
\phi((c+1)u, v) &= \phi (cu+u, v)+ \phi (u, v)  \\
&= \phi (cu, v)+ \phi(u, v) \\ 
&=c\phi (u, v)+ \phi (u, v)= (c+1)\phi(u, v).
\end{aligned}
$$

이제 $c\in S \implies c-1\in S$ 임을 다음과 같이 보일 수 있다.

$$
\phi ((c-1)u, v)= \phi (cu-u, v)= \phi (cu, v) + \phi (-u, v)= (c-1)\phi (u, v)
$$

이로부터 $\mathbb{Z}\subset C$ 임을 안다. $\mathbb{Q}\subset S$ 임을 보이자. $m, n\in \mathbb{Z},\, n\ne 0$ 에 대해 $c=m/n$ 이라 하자. 

$$
n\phi (cu, v) = \phi (ncu, v)= \phi (mu, v)= m \phi (u, v)= cn \phi(u, v)
$$

이므로 $\phi (cu, v) = c\phi (u, v)$ 이다. 즉 $\mathbb{Q} \subset S$ 이다.

이제 임의의 정해진 $u,\,v\in V$ 에 대해 $\mathbb{R}\mapsto \mathbb{R}$ 함수 $f,\,g$ 를 $f(x) = x\phi (u, v)$, $g(x) = \phi(xu, v)$ 로 정의하자. 앞서의 결과로부터 $x\in \mathbb{Q}$ 일 때 $f(x)=g(x)$ 임을 안다. $f(x)$ 는 연속함수이다. 

$$
g(x)-g(x_0) = \phi(xu, v) - \phi (x_0u, v) = \phi((x-x_0)u, v)
$$

이므로 $\displaystyle \lim_{x \to x_0} g(x) = g(x_0)$ 이다. 즉 $g$ 도 연속함수이다. $\mathbb{Q}$ 는 $\mathbb{R}$ 에 대해 조밀한 부분집합이며 모든 $x\in \mathbb{Q}$ 에 대해 $f(x)=g(x)$ 이므로 모든 $x\in \mathbb{R}$ 에 대해 $f(x) = g(x)$ 이다. (@Rudin1976, Chapter 4, Exercises 4) $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_jordan_von_neumann_theorem}

#### 실벡터공간에서의 조르당-폰 노이만 정리

$\mathbb{R}$-거리벡터공간 $V$ 에 대해 다음은 동치이다.

&emsp;($1$) $V$ 는 $\mathbb{R}$-내적벡터공간이다.

&emsp;($2$) 모든 $u,\,v\in V$ 에 대해 평행사변형 공식이 성립한다.

:::

</div></br>

::: {.proof}

($1 \implies 2$) 는 @prp-LA_norm_in_innerproduct_space 에서 보였다.

($2 \implies 1$) @eq-innerproduct_from_norm_in_R 가 @def-LA_innerproduct 를 만족한다는 것은 @lem-LA_jordan_von_neumann_1 과 @lem-LA_jordan_von_neumann_2 를 이용하여 보일 수 있다. $\square$

:::

</br>

이제 복소벡터공간에서 증명하자. 

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_jordan_von_neumann_3}

$\mathbb{C}$-거리공간 $V$ 에서 함수 $\psi : V \times V \to \mathbb{C}$ 를 다음과 같이 정의한다.

$$
\psi (u, v) = \dfrac{\|u+v\| - \|u-v\| + i\|u+iv\| -i \|u-iv\|}{4}
$$ {#eq-innerproduct_from_norm_in_C}

이 때 모든 $u,\,v\in V$ 에 대해 평행사변형 공식 $\|u+v\|^2 + \|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 를 만족한다면 $u,\,u',\,v\in V$ 에 대해 다음이 성립한다.

$$
\psi(u+u', v)= \psi(u, v) + \psi(u', v)
$$
:::

</div>

</br>

::: {.proof}

$\psi$ 를 실수부 $\psi_R$ 과 허수부 $\psi_I$ 로 분리하자. 즉

$$
\psi_R (u, v) = \dfrac{\|u+v\| - \|u-v\|}{r},\qquad \psi_I(u, v) = \dfrac{\|u+iv\| -\|u-iv\|}{4}
$$

로 놓으면 $\psi(u, v) = \psi_R(u, v)+ i\psi_I (u, v)$ 이다. $\psi_R(u+u',v)= \psi_R(u,v) + \psi_R(u',v)$ 인것은 @lem-LA_jordan_von_neumann_1 에서 보였다. $\psi_I(u, v) = \psi_R(u, iv)$ 이므로 $\psi_I(u+u',v)= \psi_I(u,v) + \psi_I(u',v)$ 이다. $\square$

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_jordan_von_neumann_4}

$\mathbb{C}$-거리공간 $V$ 에서 @lem-LA_jordan_von_neumann_3 에서 정의된 함수 $\psi$ (@eq-innerproduct_from_norm_in_C) 는 $c \in \mathbb{F}$ 에 대해 다음을 만족한다.

$$
\psi (cu, v) = c\psi(u, v). 
$$

:::

</div></br>

::: {.proof}
@lem-LA_jordan_von_neumann_3 의 증명과 같이 $\psi_R$ 과 $\psi_I$ 를 정의하자. $\psi_R(cu, v) = c\psi_R (u, v)$ 는 실벡터 거리공간에서의 경우와 마찬가지이다. $\psi_I (u, v) = \psi _I (u, iv)$ 이므로 $\psi_I (cu, v) = c\psi_I (u, v)$ 이다. 따라서 $\psi (cu, v) =  c\psi (u, v)$ 이다. $\square$

:::

</br>

이제 우리는 다음과 같은 결론을 내릴 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_jordan_von_neumann_theorem2}

#### 복소벡터공간에서의 조르당-폰 노이만 정리

$\mathbb{C}$-거리벡터공간 $V$ 에 대해 다음은 동치이다.

&emsp;($1$) $V$ 는 $\mathbb{C}$-내적벡터공간이다.

&emsp;($2$) 모든 $u,\,v\in V$ 에 대해 평행사변형 공식이 성립한다.

:::

</div>
</br>

이제 우리는 $\mathbb{F}$-벡터공간에서 내적과 노름의 관계에 대해 알게 되었다. 즉 내적벡터공간은 노름공간이며, 노름공간에서 정의된 거리함수가 평행사변형 공식을 만족하면 내적을 정의 할 수 있다. $\mathbb{F}^n$ 에 대해서는 다음을 보자.

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_L1_not_innerproduct_space}

@exm-LA_norm_space_1 에서 정의된 $L_p$ 노름은 $p\ne 2$ 일 경우를 제외하면 내적을 정의 할 수 없다. $V=\mathbb{C}^n$  에 대해 $u=(1, 0, \ldots, 0)$, $v=(0, 1, 0, \ldots,\,0)$ 이라고 하자.

$$
\begin{aligned}
{\| u+v \|_p}^2 + {\| u-v \|_p}^2 &= 2^{1+2/p} , \\
2({\| u \|_p}^2 + {\| v \|_p}^2) &= 4
\end{aligned}
$$

이므로 조르당-폰 노이만 정리를 만족하기 위해서는 $p=2$ 이어야 한다.

:::

</div>

</br>

## 직교 여공간 (Orthogonal complement) 과 Orthogonal projection

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_orthogonal_complement}

#### 직교 여공간

벡터공간 $V$ 의 부분집합 $U$ 에 대해 $U$ 전체 원소에 대해 수직인 벡터의 집합은 벡터공간을 이루며 이를 $U$ 에 대한 **직교 여공간 (orthogonal complement)** 이라 하고 $U^\perp$ 라 쓴다. 즉,

$$
U^\perp = \{ v\in V : \langle v,\, u\rangle = 0 \text{ for every }u\in U\}
$$

이다.
::: 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_orthogonal_complement_is_a_vector_space}

벡터공간 $V$ 의 부분집합 $U$ 에 대해 다음이 성립한다.

&emsp;($1$) $\{0_V\}^\perp = V$, $V^\perp = \{0_V\}$,

&emsp;($2$) $U^\perp$ 는 $V$ 의 부분벡터공간이다.

&emsp;($3$) $U \cap U^\perp  \subset \{0_V\}$,

&emsp;($4$) $U\subset W \implies W^\perp \subset U^\perp$,

&emsp;($5$) $U^\perp = \langle U\rangle^\perp$.

:::

</div></br>

::: {.proof}

($1$), ($2$) 는 생략한다.

($3$) $v\in U \cap U^\perp$ 이면 $\langle v,\, v\rangle = 0$ 이므로 $v=0_V$ 일 수 밖에 없다.

($4$) $v\in W^\perp$ 이면 $v$ 가 모든 $W$ 의 집합에 대해 수직하므로 $U\subset W$ 인 모든 $u\in U$ 에 대해서도 수직하다. 따라서 $v \in U^\perp$ 이다. 즉 $W^\perp \subset U^\perp$ 이다. 

($5$) $U \subset \langle U \rangle$ 이므로 $\langle U\rangle^\perp \subset U^\perp$. 역으로 $\langle U \rangle$ 의 모든 원소는 $U$ 의 원소의 일차결합이므로 $U^\perp \subset \langle U \rangle^\perp$ 이다. 즉 $U^\perp = \langle U \rangle^\perp$. $\square$

:::

</br>

우리는 다음을 보일 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_generated_subspace_and_orthogonal_compliment}

벡터공간 $V$ 와 유한차원 부분공간 $U$ 에 대해 $V = U \oplus U^\perp$ 이다.

:::

</div></br>

::: {.proof}
$U$ 의 정규직교기저를 찾아 $\{e_1,\ldots,\,e_n\}$ 이라 하자. $v\in V$ 에 대해 $u=\sum_{i=1}^n \langle v,\, e_i\rangle$, $w=v-u$ 라고 하면 $j=1,\ldots,\,n$ 에 대해

$$
\langle w, e_j\rangle = \langle v, e_j \rangle - \langle u, e_j\rangle = 0
$$

이므로 $w\in U^\perp$ 이다. @prp-LA_orthogonal_complement_is_a_vector_space 의 ($3$) 에 따라 $U\cap U^\perp = \{0_V\}$ 이므로 @prp-LA_condition_for_direct_sum 에 따라 $V=U \oplus U^\perp$ 이다.

:::

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_orthogonal_space_in_infinite_dimensional_vector_space}

#### 무한차원 벡터공간에서의 직교여공간

위의 @prp-LA_generated_subspace_and_orthogonal_compliment 는 $U$ 가 무한차원 벡터공간일 때 성립하지 않는 수 있다는 것을 보일 수 있다. $[-1,\,1]$ 구간에서 연속인 함수의 집합 $C_{[-1, 1]}$ 는 벡터공간이며 내적을

$$
\langle f,\, g\rangle = \int_{-1}^1 f(x)\, g(x) \, dx
$$

로 정의 할 수 있다. $U\le C_{[-1, 1]}$ 이 다음과 같이 정의되어다고 하자.

$$
U = \{ f\in C_{[-1, 1]}: f(0)=0\}.
$$

$U$ 는 $C_{[-1,\,1]}$ 의 부분공간이며 $U \ne C_{[-1,1]}$ 이다. $U^{\perp}$ 를 생각 할 수 있으며 $0$ 함수는 $U^{\perp}$ 에 포함되므로 $U^{\perp}\ne \varnothing$ 이다. $g\in U^\perp$ 라고 하자. $f_n(x)$ 를 $g(x)$ 와 $n\in \mathbb{Z}_+$ 에 대해 다음과 같이 정의한다.

$$
f_n(x) = \left\{\begin{array}{ll}  g(x) &; \text{if } |x|> \dfrac{1}{n} \\ \dfrac{g(1/n)}{1/n}x \qquad &;\text{if } 0\le x \le \dfrac{1}{n} \\ \dfrac{g(-1/n)}{-1/n}x & \text{if } 0<x<\dfrac{1}{n} \\ \end{array}\right.
$$


$f_n(0)=0$ 이며 $f_n(x)$ 는 $[-1,\,1]$ 에서 연속인 함수이다. 즉 $f_n \in U$ 이다. 그렇다면 

$$
\begin{aligned}
\int_{-1}^1 f_n(x)\, g(x)\, dx &= \int_{-1}^{-\frac{1}{n}} g^2(x)\, dx + \int_{\frac{1}{n}}^1 g^2(x)\, dx \\[0.3em]
&+ \dfrac{g\left(\frac{1}{n}\right)}{\frac{1}{n}} \int_{0}^{\frac{1}{n}}xg(x)\, dx - \dfrac{g\left(-\frac{1}{n}\right)}{\frac{1}{n}}\int_{-\frac{1}{n}}^0 xg(x)\, dx 
\end{aligned}
$$

이다. 적분에 대한 평균값 정리에 의해 $\int_{0}^{1/n}xg(x) \, dx = n x_1 g(x_1)$ 을 만족하는 $x_1\in \left(0, \frac{1}{n}\right)$ 이 존재하며, $\int_{-1/n}^0 xg(x)\,dx = -nx_2 g(x_2)$ 를 만족하는 $x_2\in \left(-\frac{1}{n}, 0\right)$ 이 존재한다. 따라서, 

$$
\begin{aligned}
\int_{-1}^1 f_n (x)\, g(x)\, dx &= \int_{-1}^{-\frac{1}{n}} g^2(x)\, dx +\int_{\frac{1}{n}}^1 g^2(x)\, dx + g\left(\frac{1}{n}\right) x_1 g(x_1) + g\left(-\frac{1}{n}\right)x_2 g(x_2)
\end{aligned}
$$

이다. $n \to \infty$ 극한에서 $\displaystyle \int_{-1}^1 f_n (x) g(x) \, dx = \int_1^1 g^2(x) \, dx=0$ 이어야 하며 이를 만족하는 $g(x) = 0$ 뿐이다. 


:::

</div>

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_uniqueness_of_orthogonal_decomposition}

유한차원 벡터공간 $V$ 에 대해 $v\in V$ 는 어떤 $u\in U$ 와 $w\in U^\perp$ 에 대해 $v = u+w$ 로 나타낼 수 있으며, 이를 만족하는 $u,\,w$ 는 유일하다.

:::

</div></br>

::: {.proof}
@prp-LA_generated_subspace_and_orthogonal_compliment 에 따라 $V=U\oplus U^\perp$ 이다. 이제 $U$ 의 정규직교기저 $\{e_1,\ldots,\,e_n\}$ 과 $U^\perp$ 의 정규직교 기저 $\{f_1,\ldots,\,f_m\}$ 에 대해 $u = \sum_i a_i e_i + \sum_j b_j f_j$ 를 만족하는 $a_i,\, b_j$ 가 존재한다. $u= \sum_i a_i e_i$ 이며 $w=\sum_j b_j f_j$ 이다. 이 때 $u,\,w$ 가 유일하게 정해진다는 것은 자명하다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-LA_dimension_relation_of_orthogonal_complement}

$V$ 가 유한차원 벡터공간일 때 $U\le V$ 에 대해 다음이 성립한다.

&emsp;($1$) $\dim (V) = \dim(U) + \dim(U^\perp)$.

&emsp;($2$) $(U^\perp)^\perp = U$.

:::

</div></br>

### Orthogonal projection {#sec-LA_orthogonal_projection}


::: {.callout-note appearance="minimal"}
::: {#def-LA_projection_operator}

#### Projection

연산자 $P\in \mathcal{L}(V)$ 가 $P^2=P$ 일 때 $P$ 를 **projection** 이라 한다.

:::
:::

예를 들어 $T\in \mathcal{L}(\mathbb{R}^2)$ 이 $T(x,\,y) = (x, 0)$ 으로 정의되었다고 하자. $T$ 는 선형사상이며 $T^2(x,\,y)$$= (x,\,0)$$= T(x,\,y)$ 이므로 $T$ 는 projection 이다. 이처럼 projectiion 은 우리가 기하학적으로 생각하는 그 projection 을 추상화 한 것이다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_range_of_projection}

$\text{im}(P)$ 는 $P$-불변 부분 공간이다.

:::

</div></br>

::: {.proof}

$u\in \text{im}(P)$ 이면 $P(v)=u$ 인 $v\in V$ 가 존재하며, $P(u)=P^2(v) = P(v) = u$ 이므로 $\text{im}(P)$ 는 $P$ 불변 부분 공간이다. $\square$

:::


</br>

벡터공간 $V$ 와 projection $P\in \mathcal{L}(V)$ 에 대해 $U = \text{im}(P)$ 라 하자. $U$ 가 유한차원 부분공간이라면 $V=U \oplus U^\perp$ 이라는 것을 안다. 또한 @prp-LA_uniqueness_of_orthogonal_decomposition 에서 보인 것처럼 $V$ 가 유한차원이라면 $v\in V$ 에 대해 $v=u+u',\, u\in U,\, u'\in U^{\perp}$ 가 되도록 하는 $u,\,u'$ 은 유일하다. 이제 반대로 $U \le V$ 에 대해 $v\in V$ 는 어떤 $u\in U$ 와 $u'\in U^\perp$ 의 합으로 유일하게 표현 될 수 있다는 것을 안다. 이렇게 어떤 부분공간 $U$ 를 치역으로 갖는 projection 다음과 같이 따로 정의할 수 있다.


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_orthogonal_projection}
#### Orthogonal projection

벡터공간 $V$ 의 유한차원 부분공간 $U$ 를 치역으로 갖는 projeciton 을 $V$ 에 대한 $U$ 로의 **orthogonal projection** 이라고 하며 $P_U$ 라고 쓴다.

:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_properties_of_orghogonal_projection}
$U$ 가 $V$ 의 유한차원 부분벡터공간 일 때 다음이 성립한다. 증명은 쉬우므로 생략한다.

&emsp;($1$) $u \in U \implies P_U (u) = u$.

&emsp;($2$) $w \in U^\perp \implies P_U(w) = 0$.

&emsp;($3$) $\ker (P_U) = U^\perp, \,\text{im}(P_U) = U$.

&emsp;($4$) $v-P_U (v) \in U^\perp$.

&emsp;($5$) $P_U^2 = P_U$.

&emsp;($6$) $\|P_U (v) \| \le \|v\|$.

&emsp;($7$) $e_1,\ldots,\,e_m$ 이 $U$ 의 정규직교기저이고 $v\in V$ 이면 다음이 성립한다.

$$
P_U(v) = \langle v,\,e_1\rangle e_1 + \cdots + \langle v,\,e_m \rangle e_m.
$$
:::

</div>

</br>

Reisz 표현 정리(@thm-LA_reisz_representation_theorem_1) 에서는 유한차원 벡터공간 $V$ 에서의 모든 선형 범함수는 각각 유일하게 정해진 어떤 벡터에 대한 내적과 같다는 것을 보였다. 


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_reisz_representation_theorem_2}

#### Reisz 의 표현정리 2

유한차원 벡터공간 $V$ 에서 각각의 $v\in V$ 에 대해 $\varphi \in V^\ast$ 를 다음과 같이 정의 할 수 있다.

$$
\varphi_v(u) = \langle u,\,v\rangle.
$$

이 때 $v \mapsto \varphi_v$ 는 $V$ 에서 $V^\ast$ 로의 전단사 함수이다.

:::

</div></br>

::: {.proof}

$\Phi : V \to V^\ast$ 를 $\Phi(v) = \varphi_v$ 로 정의하자. $\Phi$ 가 단사임은 @thm-LA_reisz_representation_theorem_1 에서 보였다. 이제 $\Phi$ 가 전사임을 보이자. $\varphi \in V^\ast$ 일 때 $\varphi=0$ 이면 $\varphi = \varphi_{0_V}$ 이다. 이제 $\varphi \ne \varphi_{0_V}$ 에서만 생각해도 된다. $\ker \varphi \ne V$ 이므로 $(\ker \varphi)^\perp \ne \{0_V\}$ 이다.

$w\in (\ker \varphi)^\perp,\, w\ne 0_V$ 일 때

$$
v = \dfrac{\overline{\varphi (w)}}{\|w\|^2} w
$$ {#eq-LA_reisz_representation_theorem_2_1}

라면 $v\in (\ker \varphi)^\perp$ 이다. 양변에 노름을 취하면

$$
\|v\| = \dfrac{|\varphi (w)|}{\|w\|}
$$ {#eq-LA_reisz_representation_theorem_2_2}

이다. 그렇다면

$$
\varphi (v) = \dfrac{|\varphi(w)|^2}{\|w\|^2} = \|v\|^2
$$

이 된다. $u\in V$ 에 대해

$$
u = \left( u - \dfrac{\varphi (u)}{\varphi (v)} v \right) + \dfrac{\varphi(u)}{\|v\|^2} v
$$

이다. $(\cdots)$ 는 $\ker \varphi$ 에 포함되며 $v\in (\ker \varphi)^\perp$ 이므로 $v$ 와 수직이다. 따라서

$$
\langle u,\, v\rangle = \dfrac{\varphi(u)}{\|v\|^2} \langle v,\, v\rangle = \varphi (u)
$$

이며, 이로부터 우리는 임의의 $\varphi \in V^\ast$ 에 대해 내적으로 표현되는 $\varphi_v$ 를 얻었다. 즉 $\Phi$ 는 전사이며, 따라서 $\Phi$ 는 전단사이다. $\square$

:::

</br>

$\F=\R$ 일 경우는 $\Phi$ 가 선형사상이 되어 쉽게 풀 수 있다. @exr-axler4_6_C_13 을 보라.



</br>

## 최소화문제와 의사역행렬

### 최소화 문제 {#sec-LA_minimization_problems}


::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_distance_to_subspace}

#### 부분공간 까지의 거리

$U$ 가 $V$ 의 부분공간일 때 $v\in V$ 로부터 $U$ 까지의 거리 $\|v-U\|$ 는

$$
\|v-U\| := \min \{\|v-u\|,\, u\in U\} 
$$

로 정의된다.

:::
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_distance_to_subspace}
$V$ 가 유한차원 내적벡터공간이고 $v\in V$, 이며 $U$ 가 $V$ 의 부분공간일 때, $v$ 에서 $U$ 까지의 거리는 $v$ 에서 $P_U (v)$ 까지의 거리와 같다. 즉, 

$$
\|v-U\| = \|v-P_U(v)\|
$$

이다.
:::

</div></br>

::: {.proof}

임의의 $u\in U$ 에 대해 $\|v-P_U (v)\| \le \|v-u\|$ 임을 보이면 된다. $\|P_Uv - u\| \ge 0$ 이므로,

$$
\begin{aligned}
\|v-P_U (v) \|  &\le \|v-P_U (v) \| +\|P_U(v) - u\| \qquad & &; \|P_U(v) - u\| \ge 0\\
&\le\|v-u\| & &; \text{Triangle inequality}
\end{aligned}
$$

이다. $\square$
:::

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_approximation_of_sin_function}

#### 사인 함수의 다항식 근사

$[-\pi,\, \pi]$ 구간에서 $\sin$ 함수를 실계수 다항식으로 근사한다고 하자. 정해진 차수의 다항식 $p(x)$ 에 대해

$$
\int_{-\pi}^\pi \left| \sin x - p(x)\right|^2\, dx
$$

를 최소화하도록 $p(x)$ 의 계수를 정하는 것도 한가지 방법이다. 이제 $C[-\pi,\, \pi]$ 를 $[-\pi,\,\pi]$ 구간에서의 연속인 실함수의 집합으로 정의하면 $C:=C[-\pi,\, \pi]$ 는 벡터공간이며 $f,\,g\in \in C$ 일 때 $C$ 에서의 내적을 아래와 같이 정의 할 수 있다는 것을 안다. (@exm-LA_innerproduct_definded_by_intergration_in_R)

$$
\langle f,\, g\rangle := \int_{-\pi}^{\pi} f(x)\,g(x)\, dx
$$


$\sin \in C[-\pi,\, \pi]$ 이다. 이제 $p(x)$ 를 5차 이하의 다항식으로 제한하자. 그리고 5차 이하의 차수를 갖는 다항식의 집합 $\R_5[x]$ 에 대해 $\R_5[x]\le C[-\pi,\, \pi]$ 이다. $\{1,\,x,\,x^2,\,x^3,\,x^4,\,x^5\}$ 가 $\R_5[x]$ 의 기저이며 그람-슈미트 과정을 이용하여 $\R_5[x]$ 에서의 정규직교기저를 구할 수 있다. 

:::

</div>

</br>

### 의사 역사상 {#sec-LA_pseudoinverse}

$L \in \mathcal{L}(V,\,W)$, $b\in W$ 이 주어졌을 때 방정식 

$$
Lx = b
$$

를 만족하는  $x\in V$ 를 찾는 문제는 선형방정식 혹은 선형 시스템을 푸는 문제이다. $\dim (V) \ne \dim (W)$ 라면 정사각 행렬이 아니기 때문에 역행렬을 이용하여 풀 수 없으며, 따라서 해가 많이 존재하거나, 아니면 해가 아예 존재하지 않을 수도 있다. 이 경우 $\|Lx-b\|$ 를 최소화 하는 $x\in V$ 의 값을 구하는 문제가 유용한 경우가 많다.

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_pseudoinverse_1}

$L\in \mathcal{L}(V,\,W)$ 일 때 $L|_{(\ker (L))^\perp}$ 는 $(\ker L)^\perp \mapsto \text{im}(L)$ 동형사상이다.

:::

</div></br>

::: {.solution}

$L|_{(\ker (L))^\perp}$ 가 $(\ker (L))^\perp \mapsto \text{im}(L)$ 전단사 임을 보이면 된다. $v\in \ker \left(L|_{(\ker (L))^\perp}\right)$ 이면 $v\in (\ker (L))^\perp \cap \ker (L)$ 이므로 $v=0$ 이다. 즉 $L|_{(\ker (L))^\perp}$ 는 단사이다. 

또한 $\text{im}\left( L|_{(\ker (L))^\perp}\right) \subset \text{im}(L)$ 임은 자명하다. $w\in \text{im}(L)$ 이면 $w = Lv$ 인 $v\in \mathcal{M}_{n}(\mathbb{F})$ 가 존재하며 @prp-LA_generated_subspace_and_orthogonal_compliment 에 따라 어떤 $x\in\ker L,\, (\ker L)^\perp$ 에 대해 $v=x+y$ 이다. 이 때 $L|_{(\ker (L))^\perp} y = w$ 이므로 $w\in \text{im}\left( L|_{(\ker (L))^\perp}\right)$ 이며 따라서  $\text{im}\left( L|_{(\ker (L))^\perp}\right) = \text{im}(L)$ 이다. 즉 $L\in \mathcal{M}_{m\times n}(\mathbb{F})$ 전사이다. $\square$

:::

</br>

@prp-LA_pseudoinverse_1 를 행렬의 입장에서 보자. $V=(\ker L)^\perp \oplus (\ker L)$ 이며 $W=(\text{im}(L))\oplus (\text{im}(L))^\perp$ 이다. $(\ker L)^\perp$ 의 기저 $\mathcal{B}_{V+} = (e_1,\ldots,\,e_n)$ 을 확장하여 $V$ 의 기저 $\mathcal{B}_V=(e_1,\ldots,\,e_n,\,e_{n+1},\ldots,\,e_N)$ 를 구성 할 수 있다. $\mathcal{B}_{W+}=(f_1,\ldots,\,f_n)$ 이 $\text{im}(L)$ 의 기저이며 이를 확장하여 $W$ 의 기저 $\mathcal{B}_W=(f_1,\ldots,\,f_n,\,f_{n+1},\ldots,\,f_{M})$ 을 구성 할 수 있다. 그렇다면 이 기저에 대한 $L$ 의 행렬표현은 다음과 같다.

$$
[L]_{\mathcal{B}_V,\mathcal{B}_W} = \begin{bmatrix} [L]_{\mathcal{B}_{V+}, \mathcal{B}_{W+}} & \bf{0} \\ \bf{0} & \bf{0}\end{bmatrix} .
$$

이 때 $[L]_{\mathcal{B}_{V+}, \mathcal{B}_{W+}}$ 는 $n \times n$ 가역행렬이다. 



</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_pseudo_inverse}

#### 의사역행렬

$L\in \mathcal{L}(V,\,W)$ 에 대해 다음과 같이 정의된 $L^+\in \mathcal{L}(W,\,V)$ 를 $L$ 의 **무어 펜로즈 역사상 (Moorre-Penrose inverse)** 혹은 **의사역사상 (pseudo inverse map)** 라고 한다.

$$
L^+ w = \left(L|_{\left(\ker (L)\right)^\perp}\right)^{-1} P_{\text{im}(L)} w.
$$


:::
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_pseudoinverse_2}

위의 @def-LA_pseudo_inverse 에서 

&emsp;($1$) $w\in (\text{im}(L))^\perp$ 이면 $L^+w = 0_V$ 이고,

&emsp;($2$) $w\in \text{im}(L)$ 이면 $Ly = w$ 를 만족하는 $y\in (\ker L)^\perp$ 는 $y=L^+w$ 가 유일하다. 

:::

</div></br>

::: {.proof}

($1$) $w\in (\text{im}(L))^\perp$ 이면 $P_{\text{im}(L)}w=0_W$ 이므로 $L^+w=0_V$ 이다.

($2$) $w\in \text{im}(L)$ 이면 $P_{\text{im}(L)}w=w$ 이다. $V = (\ker L) \oplus (\ker L)^\perp$ 이므로 모든 $x\in \ker L$ 과 어떤 유일한 $y\in (\ker L)^\perp$ 에 대해 $w=L(x+y)$ 이며 $\left(L|_{\left(\ker (L)\right)^\perp}\right)^{-1}w=y$ 이므로 $LL^+w = Ly = w$ 이다. $\square$

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_pseudoinverse_3}

유한차원 벡터공간 $V$ 에 대해 $L\in \mathcal{L}(V,\,W)$ 일 때 다음이 성립한다.

&emsp;($1$) $L$ 이 가역사상이면 $L^+=L^{-1}$ 이다.

&emsp;($2$) $LL^+=P_{\text{im}(L)}$ 이다.

&emsp;($3$) $L^+L = P_{(\ker (L))^\perp}$ 이다.
:::

</div></br>

::: {.proof}

($1$) $L$ 이 가역사상이면 $\ker L = \{0_V\}$ 이므로 $(\ker L)^\perp = V$ 이고 $P_{\text{im}(L)} = P_W = I$ 이다. 따라서 $L^+ = L^{-1}$ 이다.

($2$) $w\in \text{im}(L)$ 이면 @lem-LA_pseudoinverse_2 ($2$) 에서 보였듯이 $LL^+w = w$ 이다. $w\in (\text{im}(L))^\perp$ 이면 역시 @lem-LA_pseudoinverse_2 ($2$) 에서 보였듯이 $LL^+w=0_W$ 이다. 즉 $LL^+ = P_{\text{im}(L)}$ 이다.

($3$) $v\in (\ker L)^\perp$ 라면 $Lv =w\in \text{im}(L)$ 이며 $L^+ Lv = v$ 이다. $v\in \ker L$ 이면 $L^+Lv=0_V$ 이므로 $L^+L = P_{(\ker L)^\perp}$ 이다. $\square$

:::

</br>

이로부터 우리는 다음을 쉽게 보일 수 있다. 그리고 왜 $L^+$ 가 $L$ 의 의사 역행렬인지 알 수 있다.

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_pseudoinverse}

유한차원 벡터공간 $V$ 에 대해 $L\in \mathcal{L}(V,\,W)$ 일 때 다음이 성립한다.

&emsp;($1$) $L$ 이 전사이면 $LL^+=I_W$ 이다.

&emsp;($2$) $L$ 이 단사이면 $L^+L=I_V$ 이다.
:::

</div></br>

::: {.proof}
*trivial*
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_pseudoinverse_2}

유한차원 벡터공간 $V$ 에 대해 $L\in \mathcal{L}(V,\,W)$ 이고 $b\in W$ 라고 하자.

&emsp;($1$) $x\in V$ 일 때 $\|L(L^+b)-b\| \le \|Lx-b\|$ 이며 등호는 $x\in L^+b +\ker L$ 일 때만 성립한다. 

&emsp;($2$) $x\in L^+ b+\ker L$ 이면 $\|L^+b\|\le \|x\|$ 이며 등호는 $x=L^+b$ 일 때만 성립한다.

:::

</div></br>

::: {.proof}

($1$) $x\in V$ 에 대해 $Lx-b = (Lx - LL^+b) + (LL^+b -b)$ 이다. @lem-LA_pseudoinverse_3 ($2$) 에 따라 $(Lx-LL^+b) \in \text{im} (L)$ 이며 $(LL^+b - b)\in (\text{im}L)^\perp$ 이다. 따라서 

$$
\|Lx-b\| = \|(Lx - LL^+b) + (LL^+b -b)\| = \|Lx-LL^+b\| + \|LL^+b - b\|
$$

이다. 

($2$) $x\in L^+b + \ker L$ 이면 $x-L^+b \in \ker L$ 이다. $x=(x-L^+b) +L^+b$ 이며 $L^+$ 의 정의에 의해 $L^+b \in (\ker L)^\perp$ 이므로

$$
\|x\| = \|(x-L^+b) +L^+b\| = \|x-L^+b\| +\|L^+b\|
$$

이다. $\square$

:::

</br>

::: {.callout-important icon="false"}

#### 최소화 문제의 해

원래의 우리는 주어진 $L \in \mathcal{L}(V,\,W)$ 과 $b\in W$ 에 대해 $\|Lx-b\|$ 를 최소화 하는 $x$ 를 찾고자 했다. @thm-LA_pseudoinverse_2 로부터 우리는 $x=L^+b$ 일 때 최소가 됨을 알았다. 

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_1}
#### Axler4th 6.C.1

$v_1,\ldots\,v_m\in V$ 일 때 다음을 보여라.

$$
\{v_1,\ldots,\,v_m\}^\perp = \left(\text{span}(v_1,\ldots,\,v_m)\right)^\perp.
$$

:::

</div></br>

::: {.solution}

$x\in\{v_1,\ldots,\,v_m\}^\perp$ 이면 임의의 $v\in \text{span}(v_1,\ldots,\,v_m)$ 에 대해 $\langle x,\, v\rangle = \left\langle x,\, \sum_{j=1}^m v_j\right\rangle = 0$ 이므로 $x\in \left(\text{span}(v_1,\ldots,\,v_m)\right)^\perp$ 이다. 즉 $\{v_1,\ldots,\,v_m\}^\perp \subset \left(\text{span}(v_1,\ldots,\,v_m)\right)^\perp$ 이다.

$y \in \left(\text{span}(v_1,\ldots,\,v_m)\right)^\perp$ 이면 당연히 $i=1,\ldots,\,m$ 에 대해 $\langle y,\,v_i\rangle = 0$ 이므로 $y\in \{v_1,\ldots,\,v_m\}^\perp$ 이다. 즉 $\left(\text{span}(v_1,\ldots,\,v_m)\right)^\perp \subset\{v_1,\ldots,\,v_m\}^\perp$ 이다.
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_2}
#### Axler4th 6.C.2

$U\le V$ 이고 $(u_1,\ldots,\,u_m)$ 이 $U$ 의 기저이며 $(u_1,\ldots,\,u_m,\,v_1,\ldots,\,v_n)$ 이 $V$ 의 기저라고 하자. 그람 슈미트 과정이 여기에 적용되어 정규직교기저 $(e_1,\ldots,\,e_m,\, f_1,\ldots,\,f_n)$ 을 구성한다면 $(e_1,\ldots,\,e_m)$ 은 $U$ 의 정규직교기저이며 $(f_1,\ldots,\,f_m)$ 은 $U^\perp$ 의 정규직교기저임을 보여라.

:::

</div></br>

::: {.solution}

그람 슈미트 과정에서 우리는 $\text{span}(u_1,\ldots,\,u_m) = \text{span}(e_1,\ldots,e_m)$ 임을 안다. 따라서 $(e_1,\ldots,\,e_m)$ 은 $U$ 의 정규직교기저이고, 이로부터 $(f_1,\ldots,\,f_m)$ 은 $U^\perp$ 의 정규직교기저임을 안다.
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_4}
#### Axler4th 6.C.4

$e_1,\ldots,\,e_n \in V$ 가 $k=1,\ldots,\,n$ 에 대해 $\|e_k\|=1$ 이며 모든 $v\in V$ 에 대해

$$
\|v\|^2 = |\langle v,\,e_1\rangle|^2 + \cdots + |\langle v,\,e_n\rangle|^2
$$

라면 $e_1,\ldots,\,e_n$ 이 $V$ 의 정규직교기저임을 보여라.

:::

</div></br>

::: {.solution}

$v=e_j$ 라면 $1=\|e_j\|^2 = \|e_j\|^2 + \sum_{i=1,\,i\ne j}^n |\langle e_j,\,e_i\rangle |^2$ 이므로 $|\langle e_i,\,e_j\rangle|^2 = \delta_{ij}$ 이다. 즉 $\{e_1,\ldots,\,e_n\}$ 은 정규직교벡터이다. $\dim (V)> n$ 이면 어떤 $\|v\|^2 > \sum_{i=1}^n |\langle v,\,e_i\rangle|^2$ 이어야 하므로 $\dim (V) = n$  이다. 즉 $(e_1,\ldots,\,e_n)$ 은 $V$ 의 정규직교기저이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_5}
#### Axler4th 6.C.5

$V$ 가 유한차원 벡터공간이며 $U\le V$ 이다. $P_{U^\perp}= I-P_U$ 임을 보여라.

:::

</div></br>

::: {.solution}

$v\in V$ 에 대해 $v=u+w,\, u\in U,\, w\in U^\perp$ 가 유일하게 정해지며 $P_U (v) = u$ 이고, $P_{U^\perp}=w$ 이다. 따라서 $P_{U^\perp} + P_U = I$ 이다.


:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_6}
#### Axler4th 6.C.6

$V$ 가 유한차원 벡터공간이며 $L\in \mathcal{L}(V,\,W)$ 일 때 다음이 성립함을 보여라.

$$
L = LP_{(\ker L)^\perp} = P_{\text{im}(L)}L
$$

:::

</div></br>

::: {.solution}

trivial
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_7}
#### Axler4th 6.C.7

$X,\,Y$ 가 $V$ 의 유한차원 부분공간일 때 $P_XP_Y=0$ 일 필요충분조건은 모든 $x\in X,\, y\in Y$ 에 대해 $\langle x,\,y\rangle =0$ 인 것임을 보여라.

:::

</div></br>

::: {.solution}

$P_XP_Y=0$ 이면 $Y \le X^\perp$ 이므로 모든 $x\in X,\, y\in Y$ 에 대해 $\langle x,\,y \rangle = 0$ 이다. 

모든 $x\in X,\, y\in Y$ 에 대해 $\langle x,\, y\rangle =0$ 이면 $P_XP_Y=0$ 임은 자명하다. 
:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_8}
#### Axler4th 6.C.8

$U$ 가 $V$ 의 유한차원 부분벡터공간이고 $v\in V$ 라고 하자. $\varphi \in U^\ast$ 를 

$$
\varphi (u) := \langle u,\,v\rangle
$$

라고 정의한다. Reisz 표현정리 (@thm-LA_reisz_representation_theorem_1) 를 내적벡터공간 $U$ 에 적용하면 

$$
\varphi (u) = \langle u,\,w\rangle
$$

을 만족하는 $w\in U$ 가 존재해야 한다. $w=P_Uv$ 임을 보여라.

:::

</div></br>

::: {.solution}

$V=U\oplus U^\perp$ 이므로 $v=x+y$ 인 $x\in U,\, y\in U^\perp$ 가 유일하게 존재한다. $\langle u,\,y\rangle = 0$ 이므로 $\langle u,\, v\rangle = \langle u,\,y\rangle$ 이며 $y=P_U v$ 이므로 $w=y=P_Uv$ 이다.

:::


</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_9}
#### Axler4th 6.C.9

유한차원 내적 벡터공간 $V$ 에서 정의된 projection $P$ 가 모든 $v\in V$ 에 대해 $\|Pv\| \le \|v\|$ 라고 하자. $P=P_U$ 인 어떤 $U\le V$ 가 존재함을 보여라.

:::

</div></br>

::: {.solution}

$U = \text{im}(P)$ 라고 하자. $u\in U$ 이면 어떤 $v\in V$ 에 대해 $u=Pv$ 이다. 이 때 

$$
\|Pu\|=\|P^2v\| = \|Pv\| = \|u\|
$$ 

이다. 또한 당연히 $v\not\in U$ 이면 $\|Pv\|=\|0_V\| = 0$ 이다. 따라서 $P=P_U$ 이다.

:::

</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_11}

#### Axler4th 6.C.11

$U$ 가 $V$ 의 유한차원 부분공간이며 $L\in \mathcal{L}(V)$ 일 때 다음이 동치임을 보여라.

&emsp;($a$) $U$ 는 $L$-불변 부분공간이다.

&emsp;($b$) $P_U L P_U = L P_U$ 이다.

:::

</div></br>

::: {.solution}

($a\implies b$) $U$ 가 $L$ 불변부분공간이라고 하자. $v \in V$ 에 대해 $P_Uv = u \in U$ 라 하자. $P_ULP_U(v) = P_UL(u)=L(u)$ 이며 $LP_U(v)= L(u)$ 이므로 $P_ULP_U = LP_U$ 이다.

($b \implies a$) $P_U L P_U = L P_U$ 라고 하자. $u\in U$ 에 대해 $Lu \not\in U$ 이면 $P_ULP_U \ne LP_U$ 이므로 모순. 따라서 $U$ 는 $L$ 부분공간이다.
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_12}

#### Axler4th 6.C.12

$V$ 가 유한차원이며 $L\in \mathcal{L}(V)$ 이고 $U\le V$ 라고 하자. 아래 두 명제가 동치임을 보여라.

&emsp;($a$) $U$ 와 $U^\perp$ 가 $L$-불변부분공간이다.

&emsp;($b$) $P_UL = LP_U$ 이다.

:::

</div></br>

::: {.solution}

($a\implies b$) $v\in V$ 라면 어떤 $x \in U,\, y\in U^\perp$ 에 대해 $v=x+y$ 이며 이를 만족하는 $x,\,y$ 는 유일함을 안다. $P_ULv = LP_Uv = Lx$ 이다. 

($b\implies a$) $P_UL = LP_U$ 임을 가정하자. $u\in U$ 라면 $LP_U u = Lu \in \text{im}{P_UL} \le U$ 이므로 $U$ 는 $L$-불변부분공간이다. $v\in U^\perp$ 라면 $LP_U=0_V$ 이므로 $P_ULv=0_V$ 이어야 하며 따라서 $Lv\in U^\perp$ 이다. 즉 $U^\perp$ 도 $L$-불변부분공간이다.
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_13}

#### Axler4th 6.C.13

$V$ 는 유한차원 $\R$-벡터공간이며 각각의 $v\in V$ 에 대해 $\varphi_v \in \mathcal{L}(V,\,\R)$ 을 

$$
\varphi_v(u):= \langle u,\,v\rangle
$$

로 정의하자. 

&emsp;($a$) $v\mapsto \varphi_v$ 는 $V\mapsto V^\ast$ 단사임을 보여라.

&emsp;($b$) ($a$) 를 이용하여 $v\mapsto \varphi_v$ 가 $V \mapsto V^\ast$ 동형사상임을 보여라.

:::

</div></br>

::: {.solution}

($a$) $v,\,v'\in V$ 에 대해 $\varphi_v=\varphi_{v'}$ 이면 모든 $u\in V$ 에 대해 $\langle u,\,v\rangle = \langle u,\,v'\rangle$ 이므로 $v=v'$ 이다. 

($b$) $\Phi : V \to V^\ast$ 를 $\Phi(v) = \varphi_v$ 라고 하자. $v_1,\,v_2\in V,\, c\in \R$ 에 대해 $\Phi (v_1+cv_2) = \varphi_{v_1+cv_2}$ 이며, 

$$
\varphi_{v_1+cv_2} (u)= \langle u,\, v_1+cv_2\rangle = \varphi_{v_1}(u) + c\varphi_{v_2}(u)
$$

이므로 $\Phi(v_1+cv_2) = \Phi(v_1)+c\Phi(v_2)$ 이다. $\Phi\in \mathcal{L}(V,\,V^\ast)$ 이며 단사이므로 $\Phi$ 는 동형사상이다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_14}

#### Axler4th 6.C.14

$(e_1,\ldots,\,e_n)$ 이 $V$ 의 정규직교기저라고 하자. 이 정규직교기저의 쌍대기저는 Reisz 의 표현정리 2 (@thm-LA_reisz_representation_theorem_2) 에서의 범함수의 그것과 같음을 보여랴.

:::

</div></br>

::: {.solution}

$e_i$ 의 쌍대벡터를 $e^\ast_i$ 라고 하고 $\varphi_i(u)= \langle u,\,e_i\rangle$ 이라고 하자. 

$$
\varphi_i(e_j) = \langle e_j,\,e_i\rangle = \delta_{ij} = e_i^\ast(e_j)
$$

이다. 
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_15}

#### Axler4th 6.C.15

$\R^4$ 에서 

$$
U = \text{span}((1,1,0,0),\, (1,1,1,2))
$$

일 때 $\|u-(1,2,3,4)\|$ 를 최소화 하는 $u\in U$ 를 찾아라.

:::

</div></br>

::: {.solution}
$v=(1,2,3,4)$ 라고 하자. $e_1 = \left(\dfrac{1}{\sqrt{2}},\dfrac{1}{\sqrt{2}}, 0, 0\right)$ 과 $e_2 = \left(0,\,0,\dfrac{1}{\sqrt{5}},\dfrac{2}{\sqrt{5}}, 0, 0\right)$ 는 $U$ 의 정규직교기저이며, $\|u-(1,2,3,4)\|$ 를 최소화 하는 $u$ 는 $P_U(1,2,3,4)$ 이므로,

$$
u=\langle v,\,e_1\rangle e_1 + \langle v,\,e_2\rangle e_2 = \left(\dfrac{3}{2}, \dfrac{3}{2}, \dfrac{11}{5}, \dfrac{22}{5}\right)
$$

이다. 

:::


</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_19}

#### Axler4th 6.C.10

$V$ 는 유한차원 벡터공간이며 $L\in \mathcal{L}(V)$ 는 projection 이면 $L^+=L$ 임을 보여라.

:::

</div></br>

::: {.solution}

$L$ 이 projection 이므로 $L^2=L$ 이며 $L = P_{\text{im}(L)}$ 이다. 또한 $(\ker (L))^\perp = \text{im}(L)$ 이므로 $L|_{(\ker L)^\perp} = I|_{\text{im}(L)}$ 이다. @def-LA_pseudo_inverse 로 부터 $L^+w = L$ 이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_20}

#### Axler4th 6.C.20

$V$ 가 유한차원벡터공간이며 $L\in \mathcal{L}(V,\,W)$ 일 때 다음이 성립함을 보여라.

$$
\ker (L^+) = (\text{im}(L))^\perp\qquad \text{and} \qquad \text{im}(L^+) = (\ker L)^\perp,
$$

:::

</div></br>

::: {.solution}

($1$) $\ker (L^+) = (\text{im}(L))^\perp$ 를 보이자. @def-LA_pseudo_inverse 로부터 $L^+w = 0_V \iff P_{\text{im}(L)}= 0_V$ 따라서 $\ker (L^+) = (\text{im}(L))^\perp$

($2$) $\text{im}(L^+) = (\ker L)^\perp$ 를 보이자.$u\in \text{im}(L^+)$ 이면 $u\in \text{im}\left((L|_{(\ker L)^\perp})^{-1}\right)$ 이므로 $u\in (\ker L)^\perp$ 이다. 즉 $\text{im}(L^+) \subset (\ker L)^\perp$ 이다.


$u \in (\ker L)^\perp$ 라고 하자. $u=0_V \in \text{im}(L^+)$ 이다. $u\ne 0_V$ 일 때 $w=Lu\ne 0_W$ 라고 하자. 

$$
L^+w = \left(L|_{(\ker L)^\perp}\right)^{-1}P_{\text{im}L}w = \left(L|_{(\ker L)^\perp}\right)^{-1} w = u
$$

이므로 $u \in \text{im}(L^+)$ 이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_22}

#### Axler4th 6.C.22

$V$ 가 유한차원 벡터공간이며 $L\in \mathcal{L}(V,\,W)$ 일 때 다음이 성립함을 보여라.

$$
LL^+L = L,\qquad L^+LL^+ = L^+.
$$

:::

</div></br>

::: {.solution}
@lem-LA_pseudoinverse_3 ($2$) 로부터 $LL^+=P_{\text{im}(L)}$ 이므로

$$
LL^+L = P_{\text{im}(L)}L = L.
$$

@lem-LA_pseudoinverse_3 ($3$) 으로부터 $L^+L=P_{(\ker L)^\perp}$ 이므로

$$
L^+LL^+ = P_{(\text{ker}L)^\perp} L^+ = L^+.
$$

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_6_C_23}

#### Axler4th 6.C.23

$V,\,W$ 가 유한차원 벡터공간이며 $L\in \mathcal{L}(V,\,W)$ 일 때 다음이 성립함을 보여라.

$$
\left(L^+\right)^+ = L.
$$

:::

</div></br>

::: {.solution}

$M=L^+$ 라고 하면 $M^+\in \mathcal{L}(W,\,V)$ 이다. $v\in V$ 에 대해 

$$
M^+v = \left(M|_{(\ker M)^\perp} \right)^{-1} P_{\text{im}(M)} v
$$

@exr-axler4_6_C_20 에서 보였듯이 $\text{im}(M) = \text{im}(L^+) = (\ker L)^\perp$ 이므로 

$$
P_{\text{im}(M)}v= P_{\text{im}(L^+)}v = P_{(\ker L)^\perp} v = 0_W
$$

이다. 즉 $v\in \ker L \implies \left(L^+\right)^+v = 0_W$ 이다. 


이제 $v\in (\ker L)^\perp$ 인 경우를 생각해보자. 앞서 보았듯이 $P_{\text{im}(M)}=P_{(\ker L)^\perp}$ 이므로 $M^+v = \left(M|_{(\ker M)^\perp} \right)^{-1}v$ 이다. 역시 @exr-axler4_6_C_20 에서 보였듯이 $(\ker L^+)=(\text{im}(L))^\perp$ 이며 @cor-LA_dimension_relation_of_orthogonal_complement ($2$) 로부터
$(\ker L^+)^\perp=\left((\text{im}(L))^\perp\right)^\perp = \text{im}(L)$ 이므로

$$
 \left(M|_{(\ker M)^\perp}\right)^{-1} = \left(\left.L^+\right|_{\text{im}(L)}\right)^{-1}
$$

이다. $Lv=w$ 라고 하면 $L^+Lv = L^+w$ 이며 $L^+L = P_{(\ker L)^\perp}$ 이므로 $L^+Lv = v$ 이다. 따라서 

$$
v\in (\ker L)^\perp \implies \left(\left.L^+\right|_{\text{im}(L)}\right)^{-1}v = Lv
$$

이다. 

모든 $v\in V$ 는 유일하게 정해지는 $x\in (\ker L)$ 과 $y\in (\ker L)^\perp$ 의 합으로 나타 낼 수 있다. 이에 대해 

$$
(L^+)^+ v = (L^+)^+(x+y) = (L^+)^+ y = Lv
$$

이므로 $\left(L^+\right)^+ = L$ 이다. 

:::

</br>

## 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_A_5}
#### Axler 6.A.5

$T\in \mathcal{L}(V)$ 이며 모든 $v\in V$ 에 대해 $\|T(v)\|\le \|v\|$ 이다. 이 때 $T-\sqrt{2}I$ 는 가역임을 보여라.

:::

</div></br>

::: {.solution}

$(T-\sqrt{2}I)(v)=0_V$ 라 하자. $v\ne 0_V$ 이면 $\|\sqrt{2}I(v)\|=\sqrt{2}\|v\| > \|v\| \ge \|T(v)\|$ 이므로 성립하지 않는다. $\ker (T-\sqrt{2}I)=\{0_V\}$ 이므로 가역이다.
::: 

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_A_6}
#### Axler 6.A.6

$u,\,v\in V$ 일 때 $\langle u,\,v\rangle=0$ 일 필요충분조건은 모든 $a\in \mathbb{F}$ 에 대해 $\|u\| \le\|u+av\|$ 임을 보여라.

:::
</div></br>

::: {.solution}
$\langle u,\,v\rangle =0$ 이면 $\|u+av\|^2-\|u\|^2 = |a|^2\|v\|^2 \ge 0$ 이다.  따라서 $\|u+av\| \ge \|u\|$ 이다.

모든 $a\in \mathbb{F}$ 에 대해 $\|u\|\le \|u+av\|$ 라고 하자.

$$
\|u+av\|^2-\|u\|^2 = a\langle v,\,u\rangle + \overline{a}\langle u,\,v\rangle + |a|^2 \|v\|^2 \ge 0
$$

이어야 한다. $u,\,v$ 에 대해 $a=t\|v\|\langle u,\,v\rangle$ 이라 놓을 수 있다. 이 때 $t\in \mathbb{R}$ 이라 하자.

$$
0\le \|u+av\|^2-\|u\|^2 = (2t\|v\| - t^2\|v\|^2) |\langle u,v\rangle |^2
$$

이어야 하는데 $t > \|v\|$ 이면 위배된다. 따라서 $\langle u,\,v\rangle = 0$ 이어야 한다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_A_9}

#### Axler 6.A.9

$u,\,v\in V$ 이고 $\|u\|\le 1$ 이며 $\|v\|\le 1$ 이면 다음이 성립함을 보여라.

$$
\sqrt{1-\|u\|^2}\sqrt{1-\|v\|^2} \le 1-|\langle u,\,v\rangle |.
$$

:::
</div><./br>

::: {.solution}

우선 $\|u\|^2+\|v\|^2 \ge 2\|u\|\|v\|$ 임을 안다. 또한 $\|u\|\|v\| \ge |\langle u,\,v\rangle|$ 임을 안다.

$$
\begin{aligned}
(1-\|u\|)^2 (1-\|v\|^2) &= 1-\|u\|^2-\|v\|^2 + \|u\|^2\|v\|^2  \\
&\le 1-2\|u\|\|v\| + \|u\|^2\|v\|^2 \\
&= (1-\|u\|\|v\|)^2 \le (1-|\langle u,\,v\rangle |)^2.
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_A_11}

#### Axler 6.A.11

양수 $a,\,b,\,c,\,d$ 에 대해 다음이 성립함을 보여라.

$$
16 \le (a+b+c+d) \left( \dfrac{1}{a}+\dfrac{1}{b}+\dfrac{1}{c}+\dfrac{1}{d} \right)
$$

:::

</div></br>

::: {.solution}

$x,\,y\in \mathbb{R}^4$ 이며 $x=(\sqrt{a},\,\sqrt{b},\,\sqrt{c},\,\sqrt{d})$, $y=(1/\sqrt{a},\,1/\sqrt{b},\,1/\sqrt{c}\,1/\sqrt{d})$ 라 하면, $|\langle x,\,y\rangle|^2 \le \|a\|^2\|b\|^2$ 이므로, 

$$
4^2=16 \le  (a+b+c+d) \left( \dfrac{1}{a}+\dfrac{1}{b}+\dfrac{1}{c}+\dfrac{1}{d} \right).
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_A_18}

#### Axler 6.A.18

$p>0$ 라고 하자. $\mathbb{R}^2$ 에서 노름이 $\|(x,\,y)\| = (x^p+y^p)^{1/p}$ 가 되도록 하는 노름은 $p=2$ 일 때만 존재함을 보여라.

:::

</div></br>

::: {.solution}

$u=(1, 0), v=(0, 1)$ 이라 하자. $\|u+v\|^2+\|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 이므로, $2 + (1+(-1)^p)^{2/p}= 4$ 이어야 한다. 즉 $1+(-1)^p = 2^{2/p}$ 이어야 하며, 이를 만족하는 $p$ 는 $2$ 뿐이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler-6_A_19_20}

내적벡터공간에서 내적을 노름의 합으로 표현 할 수 있다. 

&emsp;($1$) 내적이 정의된 실벡터공간 $V$ 에서 $u,\,v\in V$ 에 대해 다음이 성랍함을 보여라.

$$
\langle u,\,v \rangle = \dfrac{1}{4} \left[\|u+v\|^2 - \|u-v\|^2\right].
$$

&emsp;($2$) 내적이 정의된 복소벡터공간 $V$ $u,\,v\in V$ 에 대해 다음이 성랍함을 보여라.

$$
\langle u,\, v\rangle = \dfrac{1}{4} \left[\| u+v\|^2 - \|u-v\|^2 + i \|u+iv\|^2 - i \|u-iv\|^2 \right].
$$

:::

</div></br>

::: {.solution}

($1$) 실벡터 공간에서 $\langle u,\,v\rangle = \langle v,\, u\rangle$ 이다. 따라서,

$$
\begin{aligned}
\left[\|u+v\|^2 - \|u-v\|^2\right] &= \langle u + v, u+v\rangle - \langle u-v,\, u-v\rangle \\
&= \|u\|^2 + \|v\|^2 + 2 \langle u,\,v\rangle -\|u\|^2 -\|v\|^2 +2 \langle u,\, v\rangle \\
& = 4\langle u,\, v\rangle
\end{aligned}
$$

이다.

($2$) 

$$
\begin{aligned}
\left[\| u+v\|^2 -\right. & \left. \|u-v\|^2 +  i \|u+iv\|^2 - i \|u-iv\|^2 \right] \\
&= \langle u+v,u+v\rangle -\langle u-v, u-v\rangle +i \langle u+iv, u+iv\rangle - i \langle u-iv,\,u-iv \rangle \\
&= 2\langle u, v\rangle + 2\langle v, u \rangle +2 \langle u,\,v\rangle - 2 \langle v, u\rangle \\
&= 4\langle u,\, v\rangle
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-operator_orthogonal_to_every_vector}

내적 $\mathbb{F}$-벡터공간에서 정의된 연산자 $T\in \mathcal{L}(V)$ 가 모든 $v\in V$ 에 대해 $\langle Tv,\,v\rangle = 0$ 이면 $T=0$ 임을 보여라.

:::

</div></br>

::: {.solution}

$T\in \mathcal{L}(V)$ 가 $0$ 라는 것은 모든 $u,\,v \in V$ 에 대해 $\langle Tu,\,v\rangle =0$ 인것과 동치이다. $\mathbb{F}=\mathbb{R}$ 일 경우,

$$
\langle T u,\,v \rangle =  \dfrac{1}{4} \left[\langle T(u+v),\, u+v \rangle - \langle T(u-v),\, u-v\rangle \right]
$$

이므로 $\langle Tu,\,v\rangle =0$ 이다. 따라서 $T=0$ 이다. $\mathbb{F}=\mathbb{C}$ 인 경우,

$$
\begin{aligned}
\langle T u,\,v \rangle &=  \dfrac{1}{4} \left[\langle T(u+v),\, u+v \rangle - \langle T(u-v),\, u-v\rangle  \right] \\
&\qquad \qquad + \dfrac{i}{4} \left[\langle T(u+iv),\, u+iv \rangle - \langle T(u-iv),\, u-iv\rangle  \right] \\
\end{aligned}
$$

이므로 $\langle Tu,\, v\rangle =0$ 이다. 따라서 $T=0$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_A_22}
$a_1,\ldots,\,a_n\in\mathbb{R}$ 에 대해 다음이 성립함을 보이시오.

$$
\left(\dfrac{\sum_{i=1}^n a_n}{n}\right)^2 \le \dfrac{\sum_{i=1}^n a_n^2}{n}
$$

:::

</div></br>

::: {.solution}

$u,\,v\in \mathbb{R}^n$ 을 $u=(a_1,\ldots,\,a_n)$, $v=(1,\ldots,\,1)$ 이라 하자. $\langle u,\,v\rangle = \sum a_n$, $\|u\|\|v\| = \sqrt{n}\left(\sum a_n^2\right)$ 이며 코시-슈바르츠 부등식에 따라 $|\langle u, v \rangle | \le \|u\|$ 이므로, 

$$
\left(\dfrac{\sum_{i=1}^n a_n}{n}\right)^2  = \dfrac{1}{n^2}|\langle u, v\rangle|^2 \le \dfrac{1}{n^2} (\|u\|\|v\|)^2=\dfrac{\sum a_n^2}{n}
$$

이다. 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_A_27}

#### Alxer 6.A.27, 28
벡터공간 $V$ 의 부분집합 $C$ 가 $u,\,v\in C \implies \frac{1}{2}(u+v)\in C$ 를 만족한다고 하자. 이 때 임의의 $w\in V$ 에 대해 $\|w-v\|$ 를 최소로 하는 $u\in C$ 가 많아야 하나만 존재한다는 것을 보여라. 이것을 보이기 위해 우선 $u,\,v,\,w\in V$ 에 대해

$$
\left\|w-\frac{1}{2}(u+v)\right\|^2 = \dfrac{\left(\|w-u\|^2 + \|w-v\|^2\right)}{2} - \dfrac{\|u-v\|^2}{4}
$$

임을 보이고 필요하다면 이것을 이용하시오.

:::

</div></br>

::: {.solution} 

평행사변형 공식 $\|u+v\|^2 +\|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 를 이용한다.

$$
\begin{aligned}
\left\|w-\frac{1}{2}(u+v)\right\|^2 &= \left\|\dfrac{1}{2}(w-u) + \dfrac{1}{2}(w-v)\right\|^2 \\
&= 2 \left\|\dfrac{1}{2} (w-u) \right\|^2 + 2\left\|  \dfrac{1}{2}(w-v)\right\|^2 - \left\|\dfrac{1}{2}(u-v)\right\|^2 \\
&= \dfrac{\|w-u\|^2 +\|w-v\|^2}{2} - \dfrac{1}{4} \|u-v\|^2.
\end{aligned}
$$

이므로 $u,\,v\in C$ 일 때

$$
\left\|w-\frac{1}{2}(u+v)\right\|^2  \le \dfrac{\|w-u\|^2 +\|w-v\|^2}{2}
$$

이며 등호는 $u=v$ 일 때만 성립한다는 것을 알 수 있다. $v_1,\,v_2$ 가 $\|w-v\|$ 를 최소화 하는 두 벡터이고 $u\ne v$ 라면 위 식에 위배된다. 따라서 $u=v$ 이어야 한다. 즉 $\|w-v\|$ 를 최소화 하는 $C$ 의 벡터는 많아야 하나만 존재 할 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_B_4}

$[-\pi,\,\pi]$ 구간에서 연속인 $\mathbb{R}\mapsto\mathbb{R}$ 함수의 집합 $C_{[-\pi,\pi]}$ 는 벡터공간이며 여기에 내적을 다음과 같이 부여하면 내적벡터공간이 된다.

$$
\langle f,\, g\rangle = \int_{-\pi}^\pi f(x)\, g(x)\, dx.
$$

이 때 

$$
\left\{\dfrac{1}{\sqrt{2\pi}}\right\} \bigcup \left\{ \dfrac{\cos (nx)}{\sqrt{\pi}} : n\in \mathbb{Z}_+\right\} \bigcup \left\{ \dfrac{\sin (mx)}{\sqrt{\pi}} : m\in \mathbb{Z}_+\right\}
$$

는 $C_{[-\pi,\,\pi]}$ 에서의 정규직교벡터의 집합임을 보여라.

:::

</div></br>

::: {.solution}

계산해 보면 

$$
\begin{aligned}
\int_{-\pi}^{\pi} \left(\dfrac{1}{\sqrt{2\pi}}\right) \left(\dfrac{\cos (nx)}{\sqrt{\pi}}\right) \, dx &= \int_{-\pi}^{\pi} \left( \dfrac{1}{\sqrt{2\pi}} \right) \left( \dfrac{\sin (nx)}{\sqrt{\pi}}\right) \, dx = 0,  \\
\int_{-\pi}^{\pi} \left(\dfrac{1}{\sqrt{2\pi}}\right)^2 \, dx &= 1, \\
\int_{-\pi}^{\pi} \left(\dfrac{\cos (nx)}{\sqrt{\pi}}\right) \left( \dfrac{\sin (mx)}{\sqrt{\pi}}\right) \, dx &= 0, \\
\int_{-\pi}^{\pi} \left(\dfrac{\cos (nx)}{\sqrt{\pi}}\right) \left(\dfrac{\cos (mx)}{\sqrt{\pi}}\right)\, dx &= \int_{-\pi}^{\pi} \left( \dfrac{\sin (nx)}{\sqrt{\pi}}\right)  \left( \dfrac{\sin (mx)}{\sqrt{\pi}}\right)\, dx = \delta_{mn}
\end{aligned}
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_B_10}

내적벡터공간 $V$ 에서 선형독립인 $\{v_1,\ldots,\,v_m\}$ 를 생각하자. 이 때, 

$$
\text{span}(v_1,\ldots,\,v_j) = \text{span}(e_1,\ldots,\,e_j),\qquad \forall j=1,\ldots,\,m
$$

를 만족하는 정규직교벡터의 집합 $\{e_1,\ldots,\,e_m\}$ 은 모두 $2^m$ 가지임을 보여라.

:::

</div></br>

::: {.solution}

Induction 을 통해 보이자. $m=1$ 일 경우 $\text{span}(v_1)= \text{span}(e_1),\, \|e_1\|=1$ 인 $e_1$ 은 $\pm v_1 /\|v_1\|$ 뿐이다. $m=n$ 일 때 성립함을 가정하자. 선형 독립인 $\{v_1,\ldots,\,v_{n+1}\}$ 을 생각한다. 가정에 의해

$$
\text{span}(v_1,\ldots,\,v_j) = \text{span}(e_1,\ldots,\,e_j),\qquad \forall j=1,\ldots,\,n
$$

인 정규직교벡터의 집합 $\{e_1,\ldots,\,e_n\}$ 은 $2^n$ 개이며 이중 하나로 고정되었다고 하자. 

$$
\text{span}(v_1,\ldots,\,v_{n+1}) = \text{span}(e_1,\ldots,\,e_{n+1}),
$$

이려면 $v_{n+1} = \sum_{k=1}^{n+1} c_k e_k$ 을 만족하는 $c_1,\ldots,\,c_{n+1}$ 이 존재해야 하며 이 때 $c_{n+1} \ne 0$ 이다. $\{e_1,\ldots,\,e_n\}$ 은 정해져 있으므로 

$$
e_{n+1} = \dfrac{1}{c_{n+1}} \left(v_{n+1} - \sum_{k=1}^n \langle v_{n+1}, e_k\rangle e_k \right)
$$ 

이며 $\|e_{n+1}\|=1$ 이므로 2가지로 정해진다. 정해진 $\{e_1,\ldots,e_n\}$ 에 대해 $\{e_1,\ldots,\,e_{n+1}\}$ 이 2가지로 정해지므로 가능한 정규직교벡터의 갯수는 $2^{n+1}$ 이 된다. 


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_B_11}

벡터 공간 $V$ 에 두가지의 내적 ${\langle \cdot ,\cdot \rangle}_1$ 과 ${\langle \cdot,  \cdot \rangle}_2$ 가 부여되며 $\langle v, w\rangle_1 = 0 \iff \langle v, w\rangle_2=0$ 가 성립한다면 모든 $v,\,w\in V$ 에 대해 어떤 상수 $c$ 가 존재하여 $\langle v, w \rangle_1 = c\langle v, w \rangle_2$ 이어야 함을 보여라.

:::

</div></br>

::: {.solution}

영벡터가 아닌 $w\in V$ 를 고정하고 $\phi_w (v) = \langle v,w\rangle_1,\, \psi_w(v) = \langle v, w\rangle_2$ 라고 하자. $\phi_w,\,\psi_w \in \mathcal{L}(V, \mathbb{F})$ 이다. $\ker (\phi_w) = \ker (\psi_w)$ 이면 @exr-axler_3_B_30 에서 보였듯이 어떤 $c_w\in \mathbb{F}$ 에 대해서 $\phi_w (v) = c_w\psi_w (v)$ 이다. 역시 영벡터가 아닌 $u\in V$ 를 고정하고 $\phi_u(v)= \langle v, u\rangle_1$, $\psi_u(v)= \langle v, u \rangle_2$ 라고 하자. $w$ 를 고정했을 때와 같이 어떤 $c_w\in\mathbb{F}$ 에 대해 $\phi _u (v) = c_u \psi_u (v)$ 이다. 

내적의 정의에 의해 $\phi_w(w)>0, \psi_w(w)>0$ 이므로 $c_w$ 는 양의 실수이다. 같은 이유로 $c_u$ 도 양의 실수이다. 또한 내적의 정의로부터 $\phi_u(w) = \overline{\phi_w(u)}$ 이고 $\psi_u (w)= \overline{\psi_w(u)}$ 인데 전자로부터 $c_u \psi_u (w) = c_w\overline{\psi_w(u)}$ 이므로 $c_u = c_w$ 이다. $c=c_w$ 라고 하자. $u, w$ 는 영벡터가 아닌 임의의 $V$ 의 벡터이므로 $\langle v, w \rangle_1 = c\langle v, w \rangle_2$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_B_12}

유한차원 벡터공간 $V$ 에 두가지의 내적 ${\langle \cdot , \cdot \rangle}_1$ 과 ${\langle \cdot,  \cdot \rangle}_2$ 가 부여되었다고 하자. 각각의 내적에 대한 노름 $\| \cdot \|_1$ 과 $\|\cdot \|_2$ 을 생각 할 수 있다. 이 때 어떤 양수 $c$ 가 존재하여 모든 $v\in V$ 에 대해 $\|v\|_1 \le c\|v\|_2$ 가 성립함을 보여라.

:::

</div></br>

::: {.solution}

$(u_1,\ldots,\,u_n)$ 을 $\langle \cdot, \cdot \rangle_2$ 에서의 정규직교기저라고 하고 $M= \max\{{\|u_i\|_1} : i=1,\ldots,n\}$ 이라고 하자. $v=\sum_{i=1}^n a_i u_i$ 라면 $\|v\|_2 = \sqrt{\sum_{i=1}^n |a_i|^2}$ 이며, 

$$
{\|v\|_1}^2 = \sum_{i, j=1}^n a_ia_j \langle u_i, u_j \rangle_1 
$$

이다. 이 때 스칼라 $a_i$ 에 대해

$$
{\|a_iu_i\|_1}^2 = |a|^2\langle u_i, u_i\rangle_1 \le |a_i|^2M^2 = M^2{\|a_iu_i\|_2}^2
$$

이므로 $\|a_i u_i\|_1 \le M\|a_iu_i\|_2$ 임을 알 수 있다. 이제 $v=\sum_{i=1}^n a_i u_i$ 라면 삼각부등식을 이용하여,

$$
{\|v\|_1}^2 = {\left\|\sum_{i=1}^n a_i u_i \right\|_1}^2 \le \left(\sum_{i=1}^n \|a_i u_i\|_1\right)^2 \le \left( \sum_{i=1}^n M |a_i|\right)^2 = M^2{\|v\|_2}^2
$$

이므로 $\|v_1\|_1 \le M \|v_1\|_2$ 가 성립한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_B_13}

내적벡터공간 $V$ 에 대해 $\{v_1,\ldots,\,v_m\}\in V$ 는 선형독립이다. 모든 $i=1,\ldots,m$ 에 대해 $\langle w, v_i\rangle >0$ 인 $w\in V$ 가 존재함을 보여라.

:::

</div></br>

::: {.solution}

그람 슈미트 방법을 통해 $\{v_1,\ldots,\,v_m\}$ 로부터 정규직교벡터 $\{e_1,\ldots,\,e_m\}$ 을 얻을 수 있으며 이 벡터들은 다음의 성질을 만족한다.

&emsp; ($1$) $\langle e_i, e_j \rangle = \delta_{ij}$, 

&emsp; ($2$) $\text{span}(v_1,\ldots,v_k)= \text{span}(e_1,\ldots,\,e_k), \qquad k\le m$.



이제 수학적 귀납법을 통해 증명한다. $m=1$ 일 때는 $w=v_1$ 이 존재한다. $w'$ 이 $\langle w', v_i\rangle>0$, $(i=1,\ldots,\,n)$ 이라고 가정한다. $w=w'+ce_{n+1}$ 이라 놓자. $i=1,\ldots,\, n$ 에 대해 

$$
\langle w,\, v_i\rangle = \langle w', v_i\rangle + c\langle e_{n+1}, v_i\rangle = \langle w', v_i\rangle >0
$$

이다. $\langle w, v_{n+1}\rangle = \langle w', v_{n+1}\rangle + c\langle e_{n+1} , v_{n+1}\rangle$ 이며 그람 슈미트 과정에서 $\displaystyle u_{n+1} = v_{n+1} - \sum_{j=1}^n \langle v_{n+1}, e_j\rangle e_j$, $e_{n+1}= \dfrac{u_{n+1}}{\|u_{n+1}\|}$ 임을 안다.

$$
\langle u_{n+1},\, v_{n+1} \rangle = \|v_{n+1}\|^2 - \sum_{j=1}^n |\langle v_{n+1}, e_j\rangle|^2 > 0
$$


이므로 $\langle e_{n+1}, v_{n+1}\rangle >0$ 이다. 따라서 적절한 $c$ 값을 통해 $\langle w, v_{n+1}\rangle >0$ 이 되도록 할 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_B_14}

$\{e_1,\ldots,\,e_n\}$ 이 $V$ 의 정규직교기저이며 $\{v_1,\ldots,\,v_n\} \subset V$ 는

$$
\| e_i - v_i \| < \dfrac{1}{\sqrt{n}},\qquad i=1,\ldots,\,n
$$

을 만족한다고 하자. 이 때 $\{v_1,\ldots,\,v_n\}$ 은 $V$ 의 기저임을 보여라.

:::

</div></br>

::: {.solution}

$u_1,\ldots,\,u_n\in V$ 일 때 $\|u_1+u_2\| \le \|u_1\| + \|u_2\|$ 로부터 

$$
\left\|\sum_{i=1}^n u_i\right\|^2 \le \left(\sum_{i=1}^n \|u_i\|\right)^2 \le \sum_{i=1}^n \|u_i\|^2
$$

임을 알 수 있다. 이제 이를 이용하여 $\{v_1,\ldots,\,v_n\}$ 이 선형독립임을 보이고자 한다. $\sum_{i=1}^n c_i v_i=0_V$ 이라 하자. 

$$
\left\|\sum_{i=1}^n c_i (e_i-v_i)\right\|^2 = \left\| \sum_{i=1}^n c_i e_i + \sum_{i=1}^n c_i v_i\right\|^2 =\sum_{i=1}^n |c_i|^2 \tag{1}
$$

이며, 

$$
\left\|\sum_{i=1}^n c_i (e_i-v_i)\right\| ^2 \le \sum_{i=1}^n |c_i|^2 \|e_i-v_i\|^2 < \dfrac{1}{n}\left(\sum_{i=1}^n |c_i|^2\right) \tag{2}
$$


이다. ($1$) 과 ($2$) 로부터 $c_1 = \cdots = c_n = 0$ 임을 안다. 즉 $\{v_1,\ldots,\,v_n\}$ 은 선형독립이며, $\dim (V)=n$ 이므로 기저이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_B_15}

$C_{[-1, 1]}$ 은 $[-1,\,1]$ 구간에서 연속인 실함수의 집합이며 여기서의 내적 $\langle f,\, g \rangle$ 은 다음과 같이 정의되었다.

$$
\langle f,\,g\rangle = \int_{-1}^1 f(x)\, g(x)\,dx.
$$

$\phi \in \mathcal{L}(C_{[-1, 1]}, \mathbb{R})$ 이 $\phi (f) = 0$ 으로 정의 되었을 때 모든 $f\in C_{[-1, 1]}$ 에 대해 $\phi (f)= \langle f,\, g\rangle$ 을 만족하는 $g\in C_{[-1, 1]}$ 은 존재하지 않는다는 것을 보여라.

:::

</div></br>

::: {.solution}

*to be done.*

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_C_2}

$U$ 가 $V$ 의 유한차원 부분공간일 때 $U^\perp = \{0_V\} \iff U=V$ 임을 보여라. 

:::

</div></br>

::: {.solution}

$U^\perp = \{0_V\}$ 이면 $U$ 의 정규직교기저 $\mathcal{B}=\{e_1,\ldots,\,e_m\}$ 에 대해 $v\in V \implies v \in \text{span}(\mathcal{B})$ 이므로 $U=V$ 이다. $U=V$ 라면 $U^\perp \{0_V\}$ 임은 자명하다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_6_C_7}

유한차원 내적공간 $V$ 에 대해 $P\in \mathcal{L}(V)$ 가 $P^2=P$ 이며 $\ker (P)$ 의 모든 벡터는 $\text{im}(P)$ 의 모든 벡터에 대해 직교한다고 하자. 그렇다면 어떤 $U\le V$ 에 대해 $P=P_U$ 임을 보이시오.

:::

</div></br>

::: {.solution}

$\ker (P)$ 와 $\text{im}(P)$ 가 직교하므로 @thm-LA_rank_nullity 에 의해 $\ker (P) \cap \text{im}(P) =\{0_V\}$ 이다. 또한 $\text{im}(P_U)=U$ 이므로 $U=\text{im}(P)$ 라 놓으며 조건을 만족한다.

:::
