---
title: "스펙트럼 정리와 특이값 분해"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---


{{< include ../../latexmacros.qmd >}}

</br>

## 스펙트럼 정리

### $\C$-스펙트럼 정리 {#sec-LA_complex_spectral_theorem}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_spectrum_theorem_for_complex_vector_space}

#### $C$-스펙트럼 정리

유한차원 $\C$-벡터공간 $V$ 에서 정의된 $N \in \mathcal{L}(V)$ 에 대해 다음 세 명제는 동치이다.

&emsp;($1$) $N$ 는 정규연산자이다.

&emsp;($2$) $N$ 는 어떤 정규직교기저에서 대각행렬로 표현된다.

&emsp;($3$) $N$ 의 고유벡터로 $V$ 의 정규직교기저를 구성 할 수 있다.
:::

</div>

::: {.proof}

($1 \implies 2$) 는 @prp-LA_diagonality_of_norma_matrix 에서 대각행렬로 표현하도록 하는 기저가 존재함을 알며 이 기저는 직교기저 $\mathcal{B}_0=(v_1,\ldots,\,v_n)$. $\mathcal{B} = (u_i=v_i/\|v_i\|)$ 는 정규직교기저이다.

($2\implies 3$) $\mathcal{B}=(e_1,\ldots,\,e_n)$ 이 $N$ 을 대각행렬로 표현는 정규직교기저라고 하고 이 대각행렬을 $\bf{N}$ 이라고 하자. $n_i = N_{ii}$ 라고 하면 $N_{ij}= \langle N(e_j),\,e_i\rangle = n_i\delta_{ij}$ 이므로 $N(e_j)= n_j e_j$ 이다. 즉 $\mathcal{B}$ 는 $N$ 의 고유벡터이다.

($3 \implies 1$) $\mathcal{B} = (e_1,\ldots,\,e_n)$ 가 $V$ 의 정규직교벡터이며 $N$ 의 고유벡터의 집합이라고 하자. $N(e_i)= n_i e_i$ 일 때 $\langle N(e_i),\,e_j\rangle = n_i$ 이며 $\langle N^\ast(e_i),\, e_j\rangle = \overline{n_i}$ 이다. $v=\sum_i a_i e_i$ 에 대해

$$
\begin{aligned}
\| Nv \|^2 &= \langle Nv,\,Nv\rangle =\sum_{i, j} a_i \overline{a_j} \langle e_i,e_j\rangle = \sum_j |a_i|^2, \\[0.3em]
\|N^\ast v\|^2 &=  \langle N^\ast v,\, N^\ast v\rangle = \sum_j |a_i|^2 = \|Nv\|^2
\end{aligned}
$$

이므로 $N$ 은 정규연산자이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_hermitian_normal_on_C}

유한차원 $\C$-벡터공간에서 정의된 정규연산자의 고유값이 모두 실수이면 이 정규연산자는 에르미트 연산자이다.

:::

</div>

::: {.proof}

@thm-LA_spectrum_theorem_for_complex_vector_space 로부터 정규연산자 $H$ 의 고유벡터의 집합이며 벡터공간의 기저인 $\mathcal{B}=(e_1,\ldots,e_n)$ 가 존재한다. $H_i e_i = h_i e_i$ 라고 하자. @prp-LA_hermite_tvv 를 이용하자. $u=\sum_i a_i e_i$ 라고 하면

$$
\langle H(u),\, u \rangle- \overline{\langle H(u),\, u \rangle} = \sum_i (h_i-\overline{h_i}) |a_i|^2 = 0
$$

이므로 $H$ 는 에르미트연산이다. $\square$
:::

</br>

### $\R$-스펙트럼 정리를 위해 미리 알아야 할 것들{#sec-LA_prerequisite_for_spectral_theorem_on_real_field}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_invirtible_deformation}

에르미트 연산자 $L\in \mathcal{L}(V)$ 에 대해  실수 $b,\,c$ 가 $b^2-4c <0$ 이면 $L^2+bL+cI$ 은 가역이다.
:::

</div>

::: {.proof}

영벡터가 아닌 벡터 $v\in V$ 에 대해

$$
\begin{aligned}
\langle (L^2+b L+cI) v,\, v \rangle &= \langle Lv,\,Lv \rangle + b\langle Lv,\,v \rangle + c\langle v,\,v \rangle \\[0.3em]
&= \|Lv\|^2 + b\langle Lv, \,v\rangle + c\langle v,\,v\rangle
\end{aligned}
$$

이다. 코시-슈바르츠 부등식으로부터,

$$
|b\langle Lv,\,v\rangle | \le |b| \cdot \|Lv\|\cdot\|v\|
$$

임을 안다. 즉 $b\langle Lv,\,v\rangle  \ge -|b| \|Lv\|\|v\|$ 이며,

$$
\begin{aligned}
\langle (L^2+b L+cI) v,\, v \rangle \rangle  & = \|Lv\|^2 + b\langle Lv ,\,v\rangle + c\langle v,\,v\rangle \\[0.3em]
& \ge \|Lv\|^2-|b|\|Lv\|\|v\| + c\|v\|^2 \\[0.3em]
&= \left(\|Lv\| - \dfrac{|b|\|v\|}{2}\right)^2 + \left(c-\dfrac{b^2}{4}\right)\|Lv\|^2 >0
\end{aligned}
$$

이다. $\ker (L^2+bL+cI) =\{0\}$ 이므로 $L^2+bL+cI$ 는 가역이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_factorization_of_polinomial}
$n$ 차 실계수 다항식 $p(x)$ 는 1차식들과 2차식의 곱들로, 2차식의 경우 $f(x)$ 라 했을 때 $f(x)=0$ 을 만족하는 실수가 존재하지 않도록 아래와 같이 분해된다.

$$
p(x) = c(x-\lambda_1) \cdots (x-\lambda_m)(x^2 + b_1x + c_1)\cdots (x^2 + b_M x + c_M)
$$

이 때, $c,\,\lambda_1,\ldots,\,\lambda_m,\,b_1,\ldots,\,b_M,\,c_1,\ldots,\,c_M$ 은 실수이며, $i=1,\ldots,\,M$ 에 대해 $b_i^2<4c$ 이다.
:::

</div>

::: {.proof}

$p(x) = a_0 +a_1x + \cdots + a_nx^n,\, a_i\in \mathbb{R}$ 가 실수근 $\lambda_1,\ldots,\,\lambda_m$ 을 가지면 $\prod_{i=1}^m (x-\lambda_i)$ 로 우선 분해되고, 나머지는 2차식의 곱으로 분해된다는 의미이다. 대수학의 기본정리에 의해 $n$ 차 다항식은 (중근을 중복하여 세면) $n$ 개의 근을 가진다. 실수가 아닌 복소수 $\lambda$ 를 근으로 가진다고 하자.

$$
p(\lambda) = a_0 + a_1 \lambda + \cdots + a_n \lambda^n = 0
$$

이며 위의 식에 켤레복소수를 취하면

$$
\overline{p(\lambda)} = a_0 + a_1 \overline{\lambda} + \cdots + a_n \overline{\lambda^n} = 0
$$

이므로 $\overline{\lambda}$ 를 근으로 가진다. 즉 실계수 다항식 $p(x)$ 의 근은 실수이거나 복소수와 켤레복소수의 쌍이다. 복소수를 근으로 갖기 위해서는 $b_i^2<4c_i$ 이어야 한다. $\square$

:::

</br>

### $\R$-스펙트럼 정리 {#sec-LA_real_spectral_theorem}

$\C$-벡터공간에서의 스펙트럼 정리는 모든 다항식은 복소근을 갖는다는 대수학의 기본 정리로부터 모든 $\C$-벡터공간의 연산자는 복소수 영역에서 고유값을 가진다는 것을 아는 것으로 부터 시작한다. 그러나 실계수 다항식은 실근을 갖지 않을 수 있기 때문에 이 방법을 사용 할 수 없다. $\R$-벡터공간에서도 스펙트럼 정리가 존재하는데 $\C$-벡터공간의 경우보다 증명이 다소 복잡해지는 것은 이런 이유 때문이다.

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_hermitian_real_matrix_eigenvalue}
유한차원 $\R$-벡터공간 $V$ 에서의 에르미트 연산자는 고유값을 가진다.
:::

</div>

::: {.proof}

$n=\dim (V)$ 라고 하자. 영벡터가 아닌 $v \in V$ 을 생각하자. $L\in \mathcal{L}(V)$ 가 에르미트 연산자라고 하자. $\{v,\, Lv,\ldots,\, L^n v\}$ 는 포함된 벡터의 갯수가 $n$ 보다 많으므로 선형종속이며, 따라서

$$
0_V=c_0 v + c_1 Lv + \cdots + c_n L^n v
$$

를 만족하는 nontrivial 한 $\{c_i\}$ 가 존재한다. @lem-LA_factorization_of_polinomial 에 의해,

$$
\begin{aligned}
c_0 v + & c_1 Lv + \cdots + c_n L^nv \\
&= c(L-\lambda_1 I)\cdots (L-\lambda_m I) (L^2 +b_1 L+c_1 I)\cdots (L^2 +b_M L+c_MI)(v)
\end{aligned}
$$

로 분해 할 수 있다. 이 때 $i=1,\ldots,\,M$ 에 대해 $b_i^2<4c_i$ 이다. @lem-LA_invirtible_deformation 에 의해 $(L^2 +b_iL+c_iI)$ 형태의 연산자는 가역이다. 그렇다면 최소한 하나의 $L-\lambda_j I$ 꼴의 행렬이 가역행렬이 아니며, 이 때의 $\lambda_j$ 가 고유값이다. 즉 $L$ 는 고유값을 가진다.$\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_self_adjoint_matrix_and_invariable_space}

유한차원 $\R$-벡터공간 $V$ 에서 정의된 에르미트 연산자 $L$ 에 대해 $U\le V$ 가 $L$ 에 대한 불변부분공간일 때,

&emsp;($1$) $U^\perp$ 도 $L$에 대한 불변부분공간이다.

&emsp;($2$) $L|_U$ 도 에르미트 행렬 이다.

&emsp;($3$) $L|_{U^\perp}$ 도 에르미트 행렬 이다.

:::

</div>

::: {.proof}
($1$) $u\in U,\, v\in U^\perp$ 라 하자. $Lu\in U$ 이며 $L$ 이 에르미트 연산자이므로,

$$
\langle Lv,\, u\rangle = \langle v,\, Lu\rangle =0
$$

이다ㅏ. 즉 $Lv\in U^\perp$ 이므로 $U^\perp$ 도 $L$-부분공간이다. 

($2$) $u_1,\,u_2\in U$ 에 대해,

$$
\langle L|_U u_1,\,u_2\rangle = \langle Lu_1,\, u_2 \rangle = \langle u_1,\, Lu_2\rangle = \langle u_1,\,L|_Uu_2\rangle
$$

이므로 $L|_U$ 도 대칭행렬 이다.

($3$) ($1$), ($2$) 로 부터 자명하다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_matrix_under_two_invariant_subspace}

유한차원 $\R$-벡터공간 $V$ 에서 정의된 연산자 $L$ 이 에르미트 연산자이고 $U,\,W \le V$ 가 $L$ 에 대한 불변부분공간이며 $V= U \oplus W$ 이면 $L$ 은 어떤 기저에서 블럭대각행렬이 된다.
:::

</div>

::: {.proof}

$u\in U$ 이면 $Lu\in U$ 이고 $w\in W$ 이면 $Lw \in W$ 이다. $V = U \oplus W$ 이므로 $U$ 의 정규직교기저 $(e_i)$ 와 $W$ 의 정규직교기저 $(\bf{f}_j)$ 에 대해 $\mathcal{B}=\{e_i\}\cup \{f_j\}$ 는 $V$ 의 기저이며 $[L]_\mathcal{B}$ 는 블럭대각행렬이 된다. $\square$ 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-LA_symmetric_matrix_digoalization} 
유한차원 $\R$-벡터공간에서 정의된 에르미트 연산자는 어떤 기저에서 대각행렬이 된다.
:::

</div>

::: {.proof}

유한차원 $\R$-벡터공간 $V$ 에서 정의된 에르미트 연산자 $L$ 을 생각하자. $n =\dim(V)$ 에 대한 수학적 귀납법을 이용한다. $n=1$ 일 때는 자명하므로 $k<n$ 인 에르미트 연산자는 어떤 기저에서 대각행렬로 표현된다고 가정하자.

$[L]$ 이 $n \times n$ 에르미트 연산자일 때 고유값이 항상 존재므로(@lem-LA_hermitian_real_matrix_eigenvalue) 고유벡터 가운데 하나 $u_1$ 을 선택하여 $U=\text{span}(u_1)$ 를 만들면 $U$ 은 $V$ 에 대한 $L$-불변부분공간이며 @lem-LA_self_adjoint_matrix_and_invariable_space 에서 보였듯이 $U^\perp$ 도 불변부분공간이다. $V = U \otimes U^\perp$ 이므로 @lem-LA_matrix_under_two_invariant_subspace 에서 보였듯이 어떤 직교 변환에 의해 $1$ 행렬과 $(n-1)\times (n-1)$ 행렬로 블록대각행렬이 된다. $(n-1)\times (n-1)$ 행렬은 귀납법의 가정에 의해 대각행렬이 되므로 $\bf{A}$ 는 대각행렬이 된다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_spectrum_theorem_for_real_vector_space}

#### $\R$-스펙트럼 정리

유한차원 $\R$-벡터공간에서 정의된 연산자 $L$ 에 대해 아래 세 명제는 동치이다.

&emsp;($1$) $H$ 는 에르미트 연산자이다.

&emsp;($2$) $H$ 어떤 정규직교기저에서 대각행렬로 표현된다.

&emsp;($3$) $H$ 의 고유벡터로 $H$ 의 정규직교기저를 구성 할 수 있다.

:::

</div>

::: {.proof}
($1\implies 2$) @lem-LA_symmetric_matrix_digoalization 로부터 대각행렬로 표현하도록 하는 기저가 존재함을 알며 이 기저는 직교기저 $\mathcal{B}_0=(v_1,\ldots,\,v_n)$. $\mathcal{B} = (e_i=v_i/\|v_i\|)$ 는 정규직교기저이다.

($2 \implies 3$) 위의 $\mathcal{B}$ 의 각각의 $e_i$ 는 $L$ 의 정규직교기저이다.

($3 \implies 1$) $\mathcal{B}=(e_1,\ldots,\,e_n)$ 정규직교 기저이며 각각 실수 $c_1,\ldots,\,c_n$ 을 고유값으로 갖는 고유벡터라고 하자. 이 기저에 대한 $H$ 의 행렬 표현 $\bf{H}$ 에 대해 $H_{ij}=\langle H e_j,\,e_i\rangle = c_i\delta_{ij}$, 이며

$$
\overline{H_{ji}}=\overline{\langle He_i,\, e_j\rangle} \langle e_j,\,He_i\rangle = \overline{c_i}\delta_{ij}= c_i\delta_{ij} = H_{ij}
$$

이므로 @prp-LA_hermitian_matrix_representation_and_hermitian_operator 에 의해 $H$ 는 에르미트 연산자이다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4th_7_B_4}

#### Axler4th 7.B.4

유한차원 복소벡터공간에서의 정규연산자가 반대칭 연산자일 필요충분조건은 모든 고유값이 허수인 것임을 보여라.

:::

</div>

::: {.solution}

반대칭 연산자의 정의에 대해서는 @exr-axler4_7_A_12 를 보라. $B$ 가 정규연산자이며 반대칭 연산자라고 하자. $v_i$ 가 고유값 $c_i$ 에 대한 $B$ 의 고유벡터라고 하면 $\langle Bv_i,\,v_i\rangle = c_i\|v_i|^2$ 이며 $\langle Bv_i,\,v_i\rangle = -\langle v_i,\,Bv_i\rangle = -\overline{c}_i\|v_i\|^2$ 이다. 즉 $\overline{c_i} = -c_i$ 이므로 $c_i$ 는 복소수이다.

정규연산자 $B$ 의 모든 고유값이 허수라고 하자. $\mathcal{B}=(e_1,\ldots,\,e_n)$ 이 $B$ 의 고유벡터로 이루어진 $V$ 의 정규직교기저라고 하고 $c_i$ 가 $e_i$ 에 대한 고유값이라고 하자. $u=\sum_i a_ie_i,\, v=\sum_j a_j e_j$ 에 대해 

$$
\langle Bu,\, v\rangle = \sum_{i} c_i a_i\overline{b_i} = - \sum_i\overline{c_i} a_i \overline{b}_i = -\langle u,\, Bv\rangle 
$$

이므로 $B^\ast = -B$ 이다. 즉 $B$ 는 반대칭 연산자 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4th_7_B_8}

#### Axler4th 7.B.8

유한차원 복소벡터공간에서의 연산자 $N$ 이 정규연산자일 필요충분조건은 $N$ 의 모든 고유벡터가 $N^\ast$ 의 고유벡터인 것임을 보여라. 

:::

</div>

::: {.solution}

$N$ 이 정규연산자임을 가정하자. $N$ 을 대각화하는 정규직교기저를 $\mathcal{B}=(e_1,\ldots,\,e_n)$ 이라고 하고 각각의 고유값을 $c_i$ 라고 하자. $N^\ast e_i = \sum_j a_j e_j$ 라고 하면

$$
a_k = \left\langle \sum_j a_j e_j,\, e_k\right\rangle = \langle N^\ast e_i ,\,e_k\rangle = \langle e_i,\,Ne_k\rangle = \overline{c_k} \delta_{ik}
$$

이므로 $N^\ast e_i = \overline{c_i}e_i$ 이다. 즉 $e_i$ 는 $\overline{c_i}$ 의 고유값을 갖는 $N^\ast$ 의 고유벡터이다.

이제 연산자 $N$ 에 대해 $N^\ast$ 의 고유벡터가 $N$ 의 고유벡터라고 하자. $N$ 은 상삼각 행렬로 대각화된다. 이 기저를 $\mathcal{B}=(e_1,\ldots,\,e_n)$ 이라고 하자. 이 기저에서

$$
N_{ij} = \langle Ne_j,\,e_i\rangle,\, N^\ast_{ij} = \langle N^\ast e_j,\,e_i\rangle = \langle e_j,\, Ne_i\rangle = \overline{N_{ji}}
$$

이다. $[N]_{\mathcal{B}}$ 가 상삼각행렬이므로 $i>j$ 일 때 $N_{ij}=0$ 이며 따라서 $[N^\ast]_{\mathcal{B}}$ 는 하삼각행렬이다. $Ne_1 = N_{11}e_1$ 이므로 $N$ 의 고유벡터이며 가정에 의해 $N^\ast$ 의 고유벡터이다 따라서 $N^\ast e_1 = \sum_{j}\overline{N_{1j}}e_j = [N^\ast]_{11}e_1$ 이어야 한다. 즉 $j\ge 2$ 에 대해 $N_{1j}=0$ 이어야 한다. 

$Ne_2 = N_{12}e_2+N_{22}e_2=N_{22}e_2$ 이므로 $e_2$ 역시 $N$ 의 고유벡터이며, 따라서 $N^\ast$ 의 고유벡터이다. $N^\ast e_2 = \overline{N_{2j}}e_j$ 이므로 $j\ne 0$ 이면 $N_{2j}=0$ 이다. 이것을 반복하면 $N$ 의 고유벡터가 $N^\ast$ 의 고유벡터라면 $N$ 은 정규행렬임을 알 수 있다.

:::



</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4th_7_B_9}

#### Axler4th 7.B.9

유한차원 복소벡터공간에서의 연산자 $N$ 이 정규연산자일 필요충분조건은 어떤 다항식 $p(t) \in \C[t]$ 에 대해 $p(N) = N^\ast$ 인 것이다.

:::

</div>

::: {.solution}

$N^\ast = p(N)$ 이면 $N$ 이 정규연산자임은 자명하다. 이제 $N$ 이 정규연산자일 때 어떤 다항식 $p(t)$ 에 대해 $N^\ast =p(N)$ 임을 보이자. $N$ 이 정규연산자이므로 어떤 정규직교기저 $\mathcal{B}=(e_1,\ldots,\,e_n)$ 에서 대각행렬이며 이 기저에서 $N^\ast$ 역시 대각행렬이이며 $N^\ast_{ii}=\overline{N_{ii}}$ 이다. 벡터공간이 $n$ 차원이라고 하고 다항식 $p(t)$ 를 $i=1,\ldots,\,n$ 에서 $p(N_{ii})=\overline{N_{ii}}$ 인 $n$ 차 라그랑쥬 다항식이라고 하자. 

$$
p(N)(e_i) = \overline{N_{ii}}e_i = N^\ast_{ii}e_i = N^\ast (e_i)
$$

이다. 모든 기저에서 성립하므로 $N^\ast = p(N)$ 이다.

:::


</br>

## Positive, Positive definite 행렬과 제곱근 행렬

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_pisitive_definite_matrix}

#### Positive Definite 행렬 와 제곱근 행렬

에르미트 연산자 $L$ 이 임의의 벡터 $v$ 에 대해 $\langle Lv,\, v \rangle > 0$ 일 때 $L$ 을 **positve** 혹은 **positive definite** 라 하고 $\langle Lv,\, v \rangle \ge 0$ 일 때 $L$ 을 **non-negative** 혹은 **positive semidefinite** 라 한다. $L$ 가 positive 이거나 positive definite 일 때  $L=R^2$ 인 연산자 $R$ 이 존재하면 $R$ 을 $L$ 의 **제곱근 연산자** 라고 하고 $\sqrt{L}$ 라고 쓴다. 

:::
:::


</br>

::: {.callout-warning icon="false"}

#### 용어의 혼란을 막기 위해

예를 들어 S. Axler 의 *Linear Algebra Done Right* 의 경우 $\langle Lv,\,v\rangle \ge 0$ 일 때 $L$ 를 *positive* 라고 정의한다(3rd Ed. pp 225). 그러나 K. Hoffman, R. Kunze 의 *Linear Algebra* 의 경우에는  $\langle Lv,\,v\rangle > 0$ 일 때 positive 라고 정의한다(2nd Ed. pp 329). 여기서는 더 직관적인 non-negative, positive 라는 용어를 사용하기로 한다.

:::


</br>

### Non-negative 연산자의 성질

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_properties_of_posivive_definite_matrix}

유한차원 $\C$-벡터공간에서 정의된 연산자 $L$ 에 대해 다음은 동치이다.

&emsp; ($1$) $L$ 은 non-negative 이다.

&emsp; ($2$) $L$ 은 에르미트행렬이며 모든 고유값은 non-negative 하다

&emsp; ($3$) $L$ 은 어떤 정규직교기저에서 대각성분이 모두 음수가 아닌 대각행렬로 표현된다.

&emsp; ($4$) $L$ 의 non-negative 제곱근 연산자가 존재한다.


::: 

</div>

::: {.proof}
($1 \implies 2$) $L$ 이 non-negative 이므로 정의에 의해 에르미트 행렬이다. $c$ 가 $L$ 의 고유값이고 $v$ 가 $c$ 에 대한 고유벡터 일 때, $0 \le \langle Lv,\, v\rangle = c \|v\|^2$ 이므로 $c \ge 0$ 이다.

($2 \implies 3$) $L$ 이 에르미트 행렬이므로 스펙트럼 정리에 의해 대각화되며 대각성분이 고유값이다. 따라서 모든 대각성분은 실수이며 음수가 아니다.

($3 \implies 4$) $L$ 을 대각화 하는 정규직교 기저를 $\mathcal{B}=(e_1,\ldots,\,e_n)$ 이라고 하고 그 고유값을 $c_1,\ldots,\,c_n$ 이라고 하자. $R(e_i) = \sqrt{c_i}e_i$ 인 연산자 $R$ 은 에르미트 이며 $L$ 의 제곱근 연산자이다.

($4 \implies 1$) $L$ 의 non-negative 제곱근 연산자를 $R$ 이라고 하자. $R$ 은 에르미트 연산자이며 $L=RR=R^\ast R$ 이므로 $L^\ast=L$ 이다. 즉 $L$ 은 에르미트 연산자이다. 또한 $\langle Lv,\,v\rangle = \langle R^\ast Rv,\,v\rangle = \|Rv\|^2\ge 0$ 이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_uniqueness_of_squareroot_matrix}

유한차원 벡터공간에서 non-negative 연산자의 non-nagative 한 제곱근 연산자는 유일하다.

:::

</div>

:::{.proof}

non-negative 연산자 $L$ 에 대한 non-negative 제곱근 연산자 $R$ 이 존재함을 안다. $R$ 역시 에르미트 연산자이므로 어떤 정규직교기저 $(e_1,\ldots,e_n)$ 에서 $c_i\ge 0$ 에 대해 $Re_i=c_ie_i$ 이며 $Le_i = c_i^2e_i$ 이다. 즉 $R$ 을 대각화하는 정규직교기저는 $L$ 을 대각화하는 정규직교기저이다. 이 정규직교기저에 대해 $Re_i = \sqrt{c_i}e_i$ 로 정해지므로 $R$ 은 유일하다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_squareroot_matrix}

유한차원 벡터공간에서 정의된 연산자 $M$ 에 대해 $M^\ast M$ 는 non-negative 연산자이다.

:::

</div>

::: {.proof}

$(M^\ast M)^\ast = M^\ast M$ 이므로 $M^\ast M$ 은 에르미트 연산자이다. $\langle M^\ast Mv,\,v\rangle = \|Mv\|^2 \ge 0$ 이므로 non-negative 이다. $\square$
:::

</br>

위의 명제는 non-negiatve $L$ 에 대해 $\sqrt{L}$ 이 정확하게 정의됨을 의미한다.

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
::: {#exr-LA_zero_of_non_negative_operator}

$L \in \mathcal{L}(V)$ 이 non-negative 이고 $v\in V$ 에 대해 $\langle Lv,\,v\rangle = 0$ 이면 $Lv=0$ 임을 보여라.

:::

</div>

::: {.solution}

$\langle Lv,\,v\rangle= \langle \sqrt{L}v,\, \sqrt{L}v\rangle =\|\sqrt{L}v\|^2 = 0$ 이므로 $Lv=0$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4th_7_C_6}
#### Axler4th 7.C.6
두 non-negative 연산자의 합도 non-negative 임을 보여라.

:::

</div>

::: {.solution}

$L,\,M$ 이 non-negative 이면 $\langle (L+M)v,\,v\rangle = \langle Lv,\,v\rangle + \langle Mv,\,v\rangle \ge 0$. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4th_7_C_7}
#### Axler4h 7.C.7

$L$ 이 non-negative 이며 가역인 연산자이고 $M$ 이 non-negative 이면 $L+M$ 이 가역임을 보여라.

:::

</div>

::: {.solution}

@exr-LA_axler4th_7_C_6 에 의해 $L+M$ 은 non-negative 이다. $\langle (L+M)v,\, v\rangle > 0$ 이므로 positive definite 이다. 따라서 $L+M$ 은 대각화 가능하며 모든 대각성분이 양수이므로 가역이다.

:::
</br>


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4th_7_C_8}
#### Axler4h 7.C.8

$L$ 이 non-negative 일 필요충분조건은 $L$ 의 의사역행렬 $L^+$ 가 non-negative 인 것이다.

:::

</div>

::: {.solution}

to be done

:::
</br>

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4th_7_C_9}
#### Axler4h 7.C.9

$L \in \mathcal{L}(V)$ 이 non-negative 이고 $S\in \mathcal{L}(W,\,V)$ 이면 $S^\ast LS$ 는 non-negative 임을 보여라.

:::

</div>

::: {.solution}

$\langle S^\ast LSv,\,v\rangle = \langle S^\ast \sqrt{L}\sqrt{L}S v,\,v\rangle = \|\sqrt{L}Sv\|^2 \ge 0$.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4th_7_C_10}
#### Axler4h 7.C.10

Non-negative $L\in \mathcal{L}(V)$ 에 대해 $Lu=v,\, Lv=u$ 이면 $u=v$ 임을 보여라.

:::

</div>

::: {.solution}


$$
\begin{aligned}
\|v-u\|^2 &= \|L(u-v)\|^2 = \langle L(u-v),\, L(u-v)\rangle = \langle L(u-v),\, v-u\rangle \\[0.3em]
&= - \langle L(u-v),\, u-v\rangle \le 0
\end{aligned}
$$

이므로 $L(u-v)=0$ 이며 따라서 $u=v$ 이다.

:::
</br>


## 특이값 분해

### 특이값 {#sec-LA_singular_value}

우리는 앞에서 정사각 행렬에 대한 특이값 분해를 알아보았다. 이제 일반적인 행렬에 대한 특이값 분해를 보기로 하자. 여기서는 행렬을 주로 다룰 것이며 지금까지와는 다르게 굵은 글씨체로 하지 않겠다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_singular_value_of_matrix}

#### 특이값
$\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 $\sqrt{\bf{A}^\ast \bf{A}}$ 의 고유값을 **특이값(singular value)** 라 한다. 특이값을 열거할때는 보통 가장 큰 값부터 내림차순으로 열거한다. 따라서 특이값 $s_1,\ldots,\,s_n$ 이라고 하면 $s_1 \ge s_2 \ge \cdots \ge s_n$ 을 의미한다.

:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_properties_of_AAast}

$\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 다음이 성립한다.

&emsp;($1$) $\bf{A}^\ast \bf{A}$ 는 positive 행렬이다.

&emsp;($2$) $\ker (\bf{A}^\ast \bf{A}) = \ker (\bf{A})$.

&emsp;($3$) $\text{im}(\bf{A}^\ast \bf{A}) = \text{im}(\bf{A}^\ast)$.

&emsp;($4$) $\text{rank}(\bf{A}) = \text{rank}(\bf{A}^\ast) = \text{rank}(\bf{A}^\ast \bf{A})$
 
:::

</div></br>

::: {.proof}

($1$) $(\bf{A}^\ast \bf{A})^\ast = \bf{A}^\ast \bf{A}$ 이므로 $\bf{A}^\ast \bf{A}$ 는 에르미트 행렬이다. 또한 $\langle \bf{A}^\ast \bf{Au},\, \bf{v}\rangle = \|\bf{Au}\|^2\ge 0$ 이므로 $\bf{A}^\ast \bf{A}$ 는 positive 이다.

($2$) $u\in \ker(\bf{A}^\ast \bf{A}) \implies \langle \bf{A}^\ast \bf{Au},\, \bf{v}\rangle = \|\bf{Au}\|^2=0$ 이므로 $\bf{u}\in \ker (\bf{A})$. 역으로 $\bf{u}\in \ker \bf{A}$ 이면 $\bf{Au}=\bf{0}$ 이므로 $\bf{A}^\ast \bf{A u}=0$ 이며, 따라서 $\bf{u}\in \ker (\bf{A}^\ast \bf{A})$. 따라서 $\ker (\bf{A}^\ast \bf{A}) = \ker (\bf{A})$.

($3$) @thm-LA_kernel_image_of_adjoint_operator 과 ($2$) 로부터 $\text{im}(\bf{A}^\ast \bf{A}) = (\ker(\bf{A}^\ast \bf{A}))^\perp = (\ker (\bf{A}))^\perp = \text{im}(\bf{A}^\ast)$ 임을 안다. 

($4$) @exr-LA_axler4th_7_A_7 로부터 $\text{rank}(\bf{A}) = \text{rank}(\bf{A}^\ast)$. ($3$) 으로부터 $\text{rank}(\bf{A}^\ast) = \text{rank}(\bf{A}^\ast \bf{A})$. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_properties_of_singular_value}

$\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 일 때 다음이 성립한다.

&emsp;($1$) $\bf{A}$ 가 단사일 필요충분조건은 $0$ 이 $\bf{A}$ 의 특이값이 아닌 것이다.

&emsp;($2$) $\bf{A}$ 의 0 이 아닌 특이값의 갯수는 반복되는 것도 갯수를 합치면 $\text{rank}(\bf{A})$ 와 같다. 

&emsp;($3$) $\bf{A}$ 가 전사일 필요충분조건은 $\bf{A}$ 의 특이값의 갯수가 $n$ 인 것이다. 

:::

</div>

::: {.proof}

($1$) $\bf{A}$ 가 단사 $\iff \ker (\bf{A}) = \{0\} \iff \ker(\bf{A}^\ast \bf{A})= \{0\}$ 

($2$) $\bf{A}$ 가 에르미트 이므로 $\dim (\bf{A})$ 는 $\bf{A}$ 의 $0$ 이 아닌 고유값의 갯수(반복되는 것도 포함하여)와 같다. @prp-LA_properties_of_AAast 의 ($4$) 에 따라 $\bf{A}$ 의 특이값의 갯수는 $\text{rank}(\bf{A})$ 와 같다.

($3$) ($2$) 에 의헤 당연하다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_linear_isometry_and_singular_values}

정사각 행렬 $\bf{S}$ 에 대해 다음은 동치이다.

&emsp;($1$) $\bf{S}$ 는 linear isometry 이다.

&emsp;($2$) $\bf{S}$ 의 특이값이 $1$ 뿐이다.

:::

</div>

::: {.proof}

($1 \implies 2$) $\bf{S}$ 가 linear isometry 이면 $\bf{S}^\ast\bf{S}=\bf{I}$ 이며 따라서 $\bf{S}$ 의 특이값은 $1$ 뿐이다.

($2\implies 1$) $\bf{S}$ 의 특이값이 $1$ 뿐이면 $\bf{S}^\ast\bf{S}$ 의 고유값이 $1$ 뿐이므로 $\bf{S}^\ast\bf{S} = \bf{I}$ 이다. 따라서 $\bf{S}$ 는 linear isometry 이다. $\square$

:::


</br>

### 특이값 분해 {#sec-LA_SVD}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_for_svd}

영행렬이 아닌 $\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 의 $0$ 이 아닌 특이값 $s_1,\ldots,\,s_M$ 에 대해 $\mathcal{M}_{n}(\mathbb{F})$ 에 속하는 정규직교벡터 $\{\bf{e}_1,\,\ldots,\,\bf{e}_n\}$ 와 $\mathcal{M}_m(\mathbb{F})$ 에 속하는 정규직교벡터 $\{\bf{f}_1,\ldots,\,\bf{f}_m \}$ 가 존재하여 $\bf{v}\in \mathcal{M}_n(\mathbb{F})$ 에 대해

$$
\bf{Av} = \sum_{j=1}^M s_j \langle \bf{v},\, \bf{e}_j\rangle \bf{f}_j
$$

이다. 

:::

</div></br>

::: {.proof}

$\bf{A}$ 의 특이값의 갯수는 $n$ 개이다. 특이값을 $s_1,\ldots,\,s_n$ 이라고 하고 관례를 따라 $s_1 \ge \cdots\ge s_n$ 이라고 하면 $s_1 \ge \cdots \ge s_M >0$ 이며 $s_{M+1}= \cdots = s_{n}=0$ 이다. $\bf{A}^\ast\bf{A}$ 의 고유값 ${s_i}^2$ 에 대한 정규화된 $\bf{A}^\ast\bf{A}$ 의 고유벡터를 $\{\bf{e}_i: i=1,\ldots,\,n\}$ 라고 하자. 그리고 $j=1,\ldots,\,M$ 에 대해 

$$
\bf{f}_j = \dfrac{\bf{Ae}_j}{s_j},\qquad j=1,\ldots,\,M
$$

이라고 하자. 그렇다면, 

$$
\langle \bf{f}_j,\, \bf{f}_i\rangle = \dfrac{1}{s_is_j}\langle \bf{Ae}_j, \bf{Ae}_i\rangle = \dfrac{1}{s_is_j}\langle \bf{A}^\ast\bf{Ae}_j, \bf{e}_i\rangle = \dfrac{s_j}{s_i}\langle \bf{e}_j,\, \bf{e}_i \rangle = \delta_{ij}
$$

이다. 즉 $\{\bf{f}_j : j=1,\ldots,\,M\}$ 은 정규직교벡터의 집합이다. 이제 $\{\bf{f}_j\}$ 를 확장하여 $\mathcal{M}_m(\mathbb{F}$ 의 정규직교기저 $\{\bf{f}_1,\ldots,\,\bf{f}_m\}$ 을 만들 수 있다. 

 $\{\bf{e}_i\}$ 는 $\mathcal{M}_n(\mathbb{F})$ 의 정규직교기저이므로 $\bf{v}\in \mathcal{M}_n(\mathbb{F})$ 는

$$
\bf{v} = \sum_{i=1}^n \langle \bf{v},\, \bf{e}_i \rangle \bf{e}_i
$$

이다. 그렇다면, 

$$
\bf{Av} =  \sum_{i=1}^n \langle \bf{v},\, \bf{e}_i \rangle \bf{Ae}_i = \sum_{i=1}^M s_i \langle \bf{v},\, \bf{e}_i \rangle \bf{f}_i
$$

이다. $\square$ 

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_eigenvector_for_signular_value}

#### 특이벡터

@prp-LA_for_svd 에서 정의된 $\mathcal{M}_n(\mathbb{F})$ 의 정규직교기저벡터 $\bf{e}_1,\ldots,\,\bf{e}_n$ 를 행렬 $\bf{A}$ 에 대한 **오른쪽 특이벡터 (right singular vectors)** 라고 한다. 또한 $\mathcal{M}_m(\mathbb{F})$ 의 정규직교기저벡터 $\bf{f}_1,\ldots,\,\bf{f}_m$ 을 **왼쪽 특이 벡터(left singular vectors)** 라고 한다.

:::
:::

</br>

왼쪽과 오른쪽이라는 이름은 특이값 분해에 대해 알게되면 자연스럽다.

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_svd_1}

#### 1차 특이값 분해

$\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 가 $M=\text{rank} (\bf{A}) \ge 1$ 이라고 하자. 이 때 서로 직교하는 열벡터로 구성된 $\bf{B}\in \mathcal{M}_{m \times M}(\mathbb{F})$ 과 대각행렬 $\bf{D}\in \mathcal{M}_{M \times M}(\mathbb{F})$ 그리고 역시 서로 직교하는 열벡터로 구성된 $\bf{C}=\mathcal{M}_{n \times M}(\mathbb{F})$ 에 대해 

$$
\bf{A} = \bf{BDC}^\ast
$$

이다.
:::

</div></br>

::: {.proof}

@prp-LA_for_svd 을 생각하자. 이제 $\bf{B} = \begin{bmatrix} \bf{f}_1 & \cdots & \bf{f}_M\end{bmatrix}$ 라 하고 $\bf{D}$ 는 $D_{ij}= s_j\delta_{ij}$ 가 되도록 하며 $\bf{C} = \begin{bmatrix} \bf{e}_1 & \cdots \bf{e}_M \end{bmatrix}$ 라고 하자. 

$$
\bf{BDC}^\ast\bf{v}= \bf{BD}\begin{bmatrix} \langle \bf{v},\,\bf{e}_1\rangle \\ \vdots \\ \langle \bf{v},\, \bf{e}_M\rangle \end{bmatrix} = \bf{B}\begin{bmatrix} s_1\langle \bf{v},\,\bf{e}_1\rangle \\ \vdots \\ s_M\langle \bf{v},\, \bf{e}_M\rangle \end{bmatrix} = \sum_{i=1}^M s_i \langle \bf{v},\, \bf{e}_i \rangle \bf{f}_i = \bf{Av}
$$


이다. 임의의 벡터 $\bf{v}$ 에 대해 성립하므로 $\bf{A} = \bf{BDC}^\ast$ 이다. $\square$
:::

</br>

@thm-LA_svd_1 은 실제 계산에서 잘 사용하지 않으며, 약간 변형된 형태로 많이 사용한다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_svd_2}

#### 2차 특이값 분해

$\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 가 $\text{rank} (\bf{A}) \ge 1$ 이라고 하자. 이 때 서로 직교하는 열벡터로 구성된 $\bf{U}\in \mathcal{M}_{m \times m}(\mathbb{F})$ 과 대각성분이 1이며 나머지 성분은 0 인 직사각행렬 $\bf{\Sigma}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 그리고 역시 서로 직교하는 열벡터로 구성된 $\bf{V}=\mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 

$$
\bf{A} = \bf{U\Sigma V}^\ast
$$

이다.

:::

</div></br>

::: {.proof}

@prp-LA_for_svd 를 생각하자. $\bf{U} = \begin{bmatrix} \bf{f}_1 & \cdots & \bf{f}_m\end{bmatrix}$ 라 하고 $\bf{V}= \begin{bmatrix} \bf{e}_1 & \cdots \bf{e}_n\end{bmatrix}$ 라고 하자. (@thm-LA_svd_1 의 $\bf{B},\, \bf{D}$ 보다 큰데, 왼쪽 특이벡터와 오른쪽 특이벡터 전체를 사용한다.)

@thm-LA_svd_1 에서 $\bf{D}$ 는 $M \times M$ 행렬이며 $M \le \text{min}(m, n)$ 이다. $m \times n$ 행렬 $\bf{\Sigma}$ 을 1행 1열부터 $M$ 행 $M$ 열 까지를 $\bf{D}$ 와 같은 값을 가지며 나머지는 $0$ 인 행렬로 정의하자. 그렇다면, 임의의 $\bf{v}\in \mathcal{M}_{n}(\mathbb{F})$ 에 대해 

$$
\begin{aligned}
\bf{U\Sigma V}^\ast \bf{v} = 
\bf{U\Sigma}\begin{bmatrix} \langle \bf{v},\,\bf{e}_1\rangle \\ \vdots \\ \langle \bf{v},\, \bf{e}_M\rangle \\ \langle \bf{v},\, \bf{e}_{M+1}\rangle \\ \vdots \\ \langle \bf{v},\,\bf{e}_n \rangle \end{bmatrix} = 
\bf{U} \begin{bmatrix} s_1\langle \bf{v},\,\bf{e}_1\rangle \\ \vdots \\ s_M\langle \bf{v},\, \bf{e}_M\rangle \\ 0 \cdot \langle \bf{v},\, \bf{e}_{M+1}\rangle \\ \vdots \\ 0 \cdot  \langle \bf{v},\,\bf{e}_n \rangle \end{bmatrix} = \sum_{i=1}^M s_i \langle \bf{v},\, \bf{e}_i \rangle \bf{f}_i = \bf{Av}
\end{aligned}
$$

이다. 즉 $\bf{A} = \boldsymbol {U\Sigma V}$ 이다. $\square$

:::


많은 경우 @thm-LA_svd_2 의 형태로 특이값 분해를 사용한다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_adjoint_of_svd}

$\bf{A} \in \mathcal{M}_{m\times n}(\mathbb{F})$ 의 오른쪽 특이벡터와 왼쪽 특이벡터는 각각 $\bf{A}^\ast$ 의 왼쪽 특이벡터와 오른쪽 특이벡터이다. $\bf{A}$ 가 $0$ 이 아닌 특이값 $s_1 \ge \cdots \ge s_M>0$ 을 가질 때 $\bf{u}\in \mathcal{M}_m(\mathbb{F})$ 에 대해

$$
\bf{A}^\ast\bf{u} = \sum_{j=1}^M s_j\langle \bf{u},\,\bf{f}_j\rangle \bf{e}_j
$$

이다.

:::

</div></br>

::: {.proof}

$\bf{A}= \bf{U\Sigma V}^\ast$ 이므로 $\bf{A}^\ast = \bf{V\Sigma}^\ast \bf{U}^\ast$ 이다. 그런데 $\bf{\Sigma}$ 는 대각성분은 실수이며, 대각성분을 제외한 행렬은 모두 $0$ 이므로  $\bf{\Sigma}^\ast = \bf{\Sigma}^T$ 이다. 즉 $\bf{V\Sigma}^T\bf{U}^\ast$ 는 $\bf{A}^\ast$ 의 특이값 분해이다. $\bf{U} = \begin{bmatrix} \bf{f}_1 & \cdots & \bf{f}_m\end{bmatrix}$ 이며 $\{\bf{f}_j\}$ 는 $\mathcal{M}_m(\mathbb{F})$ 의 정규직교기저이므로 $\bf{u} = \sum_{j=1}^m \langle \bf{u},\,\bf{f}_j\rangle \bf{f}_j$ 이다. 따라서, 

$$
\bf{A}^\ast\bf{u} = \sum_{j=1}^m \langle \bf{u},\, \bf{f}_j\rangle \bf{V\Sigma}^T\bf{U}^\ast \bf{f}_j = \sum_{j=1}^M s_j \langle \bf{u}_j,\, \bf{f}_j\rangle \bf{e}_j
$$

이다. $\square$


:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_inverse_matrix_using_svd}

$\bf{A}$ 가 가역행렬이라고 하자. $\bf{A}= \bf{U\Sigma V}^\ast$ 일 때 

$$
\left(\overline{\bf{\Sigma}}\right)_{ij} = \left\{\begin{array}{ll} 1/\Sigma_{ii} \qquad &\text{if } i=j,\, s_i \ne 0 \\ 0&\text{otherwise} \end{array} \right.
$$

$$
\bf{A}^{-1} =  \bf{V\overline{\Sigma} U}^\ast 
$$

이다.

:::

</div></br>

::: {.proof}

$\bf{A}$ 가 가역행렬이면 정사각 행렬이며, @prp-LA_properties_of_singular_value 에 따라 $\bf{\Sigma}$ 는 대각성분이 모두 $0$ 이 아닌 대각행렬이며 따라서 $\bf{\Sigma\overline{\Sigma}} = \bf{I}$ 이다. 이를 이용하면

$$
\bf{A}(\bf{V\overline{\Sigma} U}^\ast)  = (\bf{U\Sigma V}^\ast)(\bf{V\overline{\Sigma} U}^\ast)= \bf{U\Sigma \overline{\Sigma} U}^\ast = \bf{UU}^\ast = \bf{I}
$$

이다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_7_E_1}

#### Axler4th 7.E.1

$L\in \mathcal{L}(V,\,W)$ 이다. $L=0$ 인 것의 필요충분 조건은 $L$ 의 모든 특이값이 $0$ 인 것임을 보여라.

:::

</div></br>

::: {.solution}

$L=0$ 이면 $L^\ast L=0$ 이므로 $L$ 의 모든 특이값이 $0$ 이다. $L$ 의 모든 특이값이 $0$ 이면 @prp-LA_properties_of_singular_value ($2$) 에 의해 $\text{rank}(L)=0$ 이므로 $L=0$ 이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_7_E_2}

#### Axler4th 7.E.1

$L\in \mathcal{L}(V,\,W)$ 이며 $s>0$ 이다. $s$ 가 $L$ 의 특이값일 필요충분조건은 어떤 nonzero vector $v\in V,\, w\in W$ 에 대해 $Lv=sw$ 이며 $L^\ast w = sv$ 임을 보여라. (이런 조건을 만족하는 $v,\,w$ 를 **슈미트 쌍(Schmidt pair)** 라고 한다.)

:::

</div></br>

::: {.solution}

$s$ 가 $L$ 의 특이값이라고 가정하자. @prp-LA_for_svd 에서 $v=e_j,\, w=f_j$ 라고 잡으면 $Lv = sw$ 이다. 또한 $s^2 v = L^\ast L v = sL^\ast w$ 이므로 $L^\ast w = sv$ 이다.

$Lv=sw$ 이며 $L^\ast w=sv$ 라면 $L^\ast L v= s^2 v$ 이므로 $s$ 는 $L$ 의 특이값이다.
:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_7_E_3}

#### Axler4th 7.E.3

$L\in \mathcal{L}(\mathbb{C}^2)$ 이다. $L$ 의 고유값은 $0$ 이며 특이값은 $0,\,5$ 인 예를 들어라. 

:::

</div></br>

::: {.solution}

$\begin{bmatrix}0 &0 \\5 & 0\end{bmatrix}$
:::


</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_7_E_4}

#### Axler4th 7.E.4

$L\in \mathcal{L}(V,\,W)$ 이고 $s_1$ 이 $L$ 의 가장 큰 특이값이며 $s_n$ 이 가장 작은 특이값이라고 하자. 

$$
\{\|Lv\| : v\in V,\, \|v\|=1\}=[s_n,\,s_1]
$$

임을 보여라.
:::

</div></br>

::: {.solution}

$L^\ast L \in \mathcal{L}(V)$ 의 고유기저 $\{e_1,\ldots,\,e_n\}$ 와 특이값 $s_1,\ldots,\,s_n$ 에 대해 $v=\sum_{j=1}^n \langle v,\,e_j\rangle e_j$ 라고 하면 
$$
\|Lv\|^2 =\langle L^\ast L v,v\rangle = \sum_{j=1}^n s_j^2 |\langle v,\,e_j\rangle|^2
$$

이다. $\sum_{j=1}^n |\langle v,\,e_j\rangle|^2 = \|v\|^2=1$ 이므로 문제가 성립한다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_7_E_5}

#### Axler4th 7.E.5

$L\in \mathcal{L}(\mathbb{C}^2)$ 가 $T(x,\,y) = (-4y,\,x)$ 로 정의되었다. $L$ 의 특이값을 구하라.
:::

</div></br>

::: {.solution}

표준기저에 대한 행렬형태는 $\begin{bmatrix} 0 & -4 \\ 1 & 0 \end{bmatrix}$ 이므로 특이값은 $1$ 과 $4$ 이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_7_E_7}

#### Axler4th 7.E.7

$L\in \mathcal{L}(V)$ 가 에르미트 이거나 $\mathbb{F}=\mathbb{C}$ 이고 $L$ 이 정규행렬이라고 하자. $\lambda_1,\ldots,\,\lambda_n$ 이 $L$ 의 고유값이며 고유공간의 차원에 맞추어 중복되어 있다. $L$ 의 특이값은 $|\lambda_1|,\ldots,\,|\lambda_n|$ 임을 보여라.
:::

</div></br>

::: {.solution}

주어진 조건의 연산자는 모두 고유값 분해가 가능하며 차이는 에르미트 행렬은 고유값이 실수이며, 정규행렬은 복소수이다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_7_E_8}

#### Axler4th 7.E.8

$L\in \mathcal{L}(V,\,W)$ 이고 $s_1,\ldots,\,s_m$ 이 $s_1\ge \cdots \ge s_m > 0$ 이며 $e_1,\ldots,\,e_m$ 은 $V$ 의 정규직교벡터이고 $f_1,\ldots,\,f_m$ 은 $W$ 의 정규직교벡터이며 $v\in V$ 에 대해

$$
Lv = s_1 \langle v,\,e_1\rangle f_1 + \cdots + s_n \langle v,\,e_n\rangle f_n
$$

이라고 하자.

&emsp;($a$) $f_1,\ldots,\,f_m$ 은 $\text{im}(L)$ 의 정규직교기저임을 보여라.

&emsp;($b$) $e_1,\ldots,\,e_m$ 은 $(\ker(L))^\perp$ 의 정규직교기저임을 보여라.

&emsp;($c$) $s_1,\ldots,\,s_m$ 은 $L$ 의 양수인 특이값임을 보여라.

&emsp;($d$) $k \in \{1,\ldots,m\}$ 이면 $e_k$ 는 $L^\ast L$ 의 고유벡터로 그 고유값이 $s_k^2$ 임을 보여라.

&emsp;($e$) 모든 $w\in W$ 에 대해 다음이 성립함을 보여라.

$$
LL^\ast w = s_1^2 \langle w,\,f_1\rangle f_1 + \cdots + s_m^2 \langle w,\,f_m\rangle f_m.
$$

:::

</div></br>

::: {.solution}

($a$) $Lv$ 가 정규직교벡터 $\{f_1,\ldots,\,f_m\}$ 의 선형결합이므로 $f_1,\ldots,\,f_m$ 은 $\text{im}(L)$ 의 정규직교기저이다.

($b$) $\{e_1,\ldots,\,e_m,\,e_{m+1},\ldots,\,e_M\}$ 이 $V$ 의 정규직교기저라고 하면 $k>m$ 에 대해 $L(e_k) = 0$ 이므로 $\{e_{m+1},\ldots,\,e_M\}$ 이 $\ker(L)$ 의 정규직교기저이다. 따라서 $\{e_1,\ldots,\,e_m\}$ 이 $(\ker(L))^\perp$ 의 정규직교기저이다.

($c$) $\langle L^\ast L (e_i),\,e_j\rangle = \langle L(e_i),\, L(e_j)\rangle = s_{i}^2 \delta_{ij}$ 이므로 $s_i^2$ 는 $L^\ast L$ 의 고유벡터 $e_i$ 에 대한 고유값이다. 따라서 $s_i$ 는 $L$ 의 양수인 특이값이다.

($d$) ($c$) 에서 보였다.

($e$) $\{f_1,\ldots,\,f_m,\,f_{m+1},\ldots,\,f_M\}$ 이 $W$ 의 정규직교기저라고 하자. $w\in W$ 는 $w=\sum_{j=1}^M c_j f_j$ 로 표현 할 수 있다. 

$$
\langle L^\ast L e_i,\, w\rangle = \sum_{j=1}^M \overline{c_j} s_i \langle f_i,\,
$$
:::

</br>

## 특이값 분해의 활용

### 행렬의 노름 {#sec-LA_norm_of_matrix}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_norm_of_matrix}

$\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 의 가장 큰 특이값을 $s_M$ 이라고 하면 다음이 성립한다.

$$
\forall \bf{v}\in \mathcal{M}_n(\mathbb{F}),\qquad \|\bf{Av}\| \le s_M \|\bf{v}\|.
$$
:::

</div></br>

::: {.proof}

@thm-LA_svd_2 의 증명과정에서 $\bf{Av} = \sum_i s_i \langle \bf{v},\, \bf{e}_i \rangle \bf{f}_i$ 임을 알았다. 이를 이용하면

$$
\begin{aligned}
\|\bf{Av}\|^2 &= \left\| \sum_{i=1}^M s_i \langle \bf{v},\, \bf{e}_i \rangle \bf{f}_i \right\|^2  \le \sum_{i=1}^M  |s_i \langle \bf{v},\, \bf{e}_i\rangle|^2 \le {s_M}^2 \sum_{i=1}^M |\langle \bf{v},\, \bf{e}_i\rangle|^2 \le {s_M}^2 \|\bf{v}\|^2
\end{aligned}
$$

이다. 마지막 부등호는 베셀 부등식(@prp-LA_properties_of_orthonormal_vectors ($3$)) 으로부터 성립한다. 따라서 $\|\bf{Av}\| \le s_M \|\bf{v}\|$ 이다. $\square$
:::


</br>

@prp-LA_norm_of_matrix 의 최대 특이값 $s_M$ 을 갖는 벡터는 ${s_M}^2$ 의 고유값에 대한 $\bf{A}^\ast\bf{A}$ 의 고유벡터이므로 항상 존재한다. $\bf{v}\ne \bf{0}$ 에 대해 

$$
\dfrac{\|\bf{Av}\|}{\|\bf{v}\|} \le s_M
$$

이므로 $s_M$ 은 선형사상에 의해 증가하는 벡터의 크기의 비율의 상한을 정의한다. 만약 $\|\bf{v}\|=1$ 이라면 $\|\bf{Av}\| \le s_M$ 이다. 이제 행렬의 노름을 정의하자. 앞서 설명했던과 같이 동등한 값이 여러개 있지만 그중 다루기 편한 것으로 정의하고 이후 동등한 명제에 대해 설명하기로 한다.₩

</br>


::: {.callout-note appearance="minimal" icon="false"}
::: {#def-LA_norm_of_matrix}

#### 행렬의 노름

$\bf{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 의 노름 $\|\bf{A}\|$ 는 다음과 같이 정의된다.

$$
\|\bf{A}\| := \max \{ \|\bf{Av}\| : \|\bf{v}\|=1\} 
$$


:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_anothor_definitions_of_matrix_norm}

#### 노름의 다양한 정의

행렬 $\bf{A}$ 에 대해 다음 네 값은 같다. 즉 행렬의 노름에 대해 4가지 동등한 정의가 존재한다.

&emsp;($1$) $\max \{ \|\bf{Av}\| : \|\bf{v}\|=1 \}$

&emsp;($2$) $\max \{ \|\bf{Av}\| : \|\bf{v}\|\le 1 \}$

&emsp;($3$) $\bf{A}$ 의 최대 특이값.

&emsp;($4$) $\max \left\{ \dfrac{\|\bf{Av}\|}{\|\bf{v}\|} : \bf{v} \ne \bf{0}\right\}$. 

:::

</div></br>

::: {.proof}

($3$) 과 ($4$) 가 같다는 것은 앞에서 설명했다. ($2$) 에서 $\|\bf{Av}\|$ 를 최대로 하는 값이 $|\bf{v}\|<1$ 이면 $\bf{u}=\dfrac{\bf{v}}{\|\bf{v}\|}$ 에 대해 $\|\bf{u}\|=1$ 이며 $|\bf{Au}\| > \|\bf{Av}|$ 이므로 모순된다. 따라서 ($2$) $\|\bf{Av}\|$ 를 최대로 하는 $\|\bf{v}\|$ 는 $\|\bf{v}\|=1$ 일 때이다. 따라서 ($1$) 의 값과 ($2$) 의 값은 같다.

($4$) 의 값에 대해 $\dfrac{\|\bf{Av}\|}{\|\bf{v}\|} = \left\|\bf{A} \left(\dfrac{\bf{v}}{\|\bf{v}\|}\right) \right\|$ 이므로 ($1$) 의 값과 같다. 따라서 위의 네 값은 같다.

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_properties_of_matrix_norm}

행렬의 노름 $\|\cdot \|$ 에 대해 다음이 성립한다.

&emsp;($1$) $\|\bf{A}\|\ge 0$. 

&emsp;($2$) $\|\bf{A}\|=0 \iff \bf{A} =\bf{0}$.

&emsp;($3$) $c\in \mathbb{F}$ 에 대해 $\|c\bf{A}\| = |c|\|\bf{A}\|$.

&emsp;($4$) $\|\bf{A} +\bf{B}\| \le \|\bf{A} \|+\|\bf{B}\|$. 

&emsp;($5$) $\|\bf{A}\| \|\bf{v}\| \ge \|\bf{Av}\|$.

&emsp;($6$) $\|\bf{A^\ast}\| = \| \bf{A}\|$. 

:::

</div></br>

::: {.proof}

($1$) 노름의 정의에 의해 자명하다.

($2$) $\bf{A}=0$ 이면 당연히 $\|\bf{A}\|=0$ 이다. $\|\bf{A}\|=0$ 이면 모든 $\bf{v}$ 에 대해 $\bf{Av}=\bf{0}$ 이어야 하므로 $\bf{A}=\bf{0}$ 이다.

($3$) $\|c\bf{Av}\| = |c|\|\bf{Av}\|$. 

($4$) $\|(\bf{A}+\bf{B})\bf{v}\| = \|\bf{Av}+\bf{Bv}\|  \le \|\bf{Av}\| +\|\bf{Bv}\|$.

($5$) @prp-LA_anothor_definitions_of_matrix_norm 의 ($4$) 로 부터 $\|\bf{A}\| \ge \dfrac{\|\bf{Av}\|}{\|\bf{v}\|}$ 이다. 

($6$) $\|\bf{A}^\ast\bf{v}\|^2 = \langle \bf{AA}^\ast\bf{v},\, \bf{v}\rangle \le \bf{v} \le \|\bf{AA}^\ast\bf{v}\|\|\bf{v}\|$ 이며 ($5$) 로 부터 

$$
\|\bf{AA}^\ast\bf{v}\| = \|\bf{A}(\bf{A}^\ast\bf{v})\| \le \|\bf{A}\|\|\bf{A}^\ast\bf{v}\|\|\bf{v}\|
$$

이므로 $\|\bf{A}^\ast\bf{v}\|^2 \le \|\bf{A}^\ast\bf{v}\|\|\bf{A}\|\bf{v}\|$ 이다. 따라서 $\dfrac{\|\bf{A}^\ast\bf{v}\|}{\|\bf{v}\|} \le \|\bf{A}\|$ 이므로 매트릭스 노름의 정의에 의해 $\|\bf{A}^\ast\|\le \|\bf{A}\|$ 이다. 여기에 $(\bf{A}^\ast)^\ast =\bf{A}$ 임을 이용하면 $\|\bf{A}\|\le \|\bf{A}^\ast\|$ 를 얻는다. 즉 $\|\bf{A}^\ast\|=\bf{A}\|$ 이다. $\square$

:::

</br>

### Approximation by Linear Maps with Lower-Dimensional Range

::: {.callout-caution icon="false"}

#### 특이값 열거 순서

특이값은 0이 아닌 실수이므로 순서대로 열거 할 수 있다. 보통 가장 큰 값부터 중복을 허용하여 열거한다. 특이값을 $s_1,\,s_2,\ldots$ 로 표현하면 가장 큰 값이 $s_1$ 이 된다. 

:::


$L\in \mathcal{L}(U,\,V)$ 의 양의 특이값을 $s_1 \ge s_2 \ge \ldots,\ge s_m>0$ 이라고 하자. 이것을 $k<m$ 의 $\text{rank}$ 를 갖는 어떤 선형사상으로 근사(approximation) 하고자 하며, 가장 좋은 근사인 선형사상을 $L_k$ 라고 하자. 이 때 특이값 분해를 사용 할 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_approximation_using_svd}

$\bf{A} \in \mathcal{M}_{m \times n}(\mathbb{F})$ 가 양의 특이값 $s_1 \ge s_2 \ge \ldots \ge s_m>0$ 을 갖는다고 하자. $k \le m$ 에 대해 다음이 성립한다.

$$
\min \{ \|\bf{A}-\bf{B} \| : \bf{B}\in \mathcal{M}_{m \times n}(\mathbb{F}),\, \text{rank}(\bf{B})\le k\} = s_{k+1}.
$$

또한 $\|\bf{A}-\bf{B}\| = s_{k+1}$ 을 만족하는 그 $\text{rank}$ 가 $k$ 보다 작은 행렬이 존재한다.

:::

</div></br>

::: {.proof}

@thm-LA_svd_2 를 생각하자. $\bf{v}\in \mathcal{M}_n(\mathbb{F})$ 에 대해 $\bf{A}=\bf{U\Sigma V}^\ast$ 이다. 이 때 $\bf{V}_k = \begin{bmatrix} \bf{e}_1 & \cdots & \bf{e}_k & 0 & \cdots & 0\end{bmatrix}$ 라고 하고 $\bf{A}_k = \bf{U\Sigma V}_k^\ast$ 라고 하자. 

$$
(\bf{A}-\bf{A}_k)\bf{v} = \bf{U\Sigma} \begin{bmatrix}  \bf{0} \\ \langle \bf{v},\, \bf{e}_{k+1} \rangle \\ \vdots \\ \langle \bf{v},\,\bf{e}_{m} \rangle \\ \bf{0}\end{bmatrix} =  \sum_{i=k+1}^m s_{i} \langle \bf{v},\, \bf{e}_i\rangle \bf{f}_i
$$


이며, 따라서 $\|(\bf{A}-\bf{A}_k)\bf{v}\|^2 \le {s_{k+1}}^2 \|\bf{v}\|^2$ 이며 이로부터 

$$
\|\bf{A}-\bf{A}_k\| \le s_{k+1}
$$ {#eq-svd_1}

을 얻는다.

이제 임의의 $\bf{B}\in \mathcal{M}_{m \times n}(\mathbb{F})$, $\text{rank}(\bf{B})\le k$ 를 생각하자. $\{\bf{Be}_1,\ldots,\,\bf{Be}_{k+1}\}$ 벡터의 갯수가 $\text{rank}(\bf{B})$ 보다 크기 때문에 선형종속이며, 따라서, 

$$
a_1 \bf{Be}_1 + \cdots + a_{k+1}\bf{Be}_{k+1} = \bf{0}
$$

을 만족하는, nontrivial 한 $a_1,\ldots,\,a_{k+1}$ 이 존재한다. 이제 $a_1,\ldots,\,a_{k+1}$ 을 이용하여 다음의 계산을 수행한다. 

$$
\begin{aligned}
(\bf{A}-\bf{B})\left(\sum_{j=1}^{k+1}a_j \bf{e}_j\right) = \bf{A}\left(\sum_{j=1}^{k+1}a_j \bf{e}_j\right) = \sum_{j=1}^{k+1} a_j s_j \bf{f}_j 
\end{aligned}
$$

이로부터 
$$
\begin{aligned}
\left\|(\bf{A}-\bf{B})\left(\sum_{j=1}^{k+1}a_j \bf{e}_j\right)\right\|^2 &= \sum_{j=1}^{k+1} {s_j}^2 |a_j|^2 \\
&\ge {s_{k+1}}^2(|a_1|^2 + \cdots + |a_{k+1}|^2) \\
&= {s_{k+1}}^2 \| a_1\bf{e}_1 + \cdots + a_{k+1}\bf{e}_{k+1}\|^2
\end{aligned}
$$

이다. $a_1\bf{e}_1+\cdots +a_{k+1}\bf{e}_{k+1} \ne \bf{0}$ 이므로, 

$$
\|\bf{A} -\bf{B}\| \ge s_{k+1}
$$ {#eq-svd_2}

을 얻는다. @eq-svd_1 의 $\bf{A}_k$ 는 $\text{rank}(\bf{A}_k) \le k$ 이므로 @eq-svd_2 를 만족해야 한다. 따라서 

$$
\|\bf{A}-\bf{A}_k\| = s_{k+1}
$$

이다. 

:::

</br>

### 극분해 {#sec-LA_polar_decomposition}

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_polar_decomposition}

정사각행렬 $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 는 어떤 유니타리 행렬 $\bf{U}$ 에 대해 $\bf{A}=\bf{S}\sqrt{\bf{A}^\ast\bf{A}}$ 이다.

:::

</div>

::: {.proof}

@thm-LA_svd_2 형식의 특이값 분해 $\bf{A}= \bf{U\Sigma V}^\ast$ 를 사용한다. $\bf{A}$ 가 정사각 행렬이므로 $\bf{U},\,\bf{\Sigma},\, \bf{V}$ 모두 정사각 행렬이다. $\bf{\Sigma}$ 는 실수 성분의 대각행렬이다. $\bf{A}^\ast\bf{A} = \bf{V}\bf{\Sigma}^2\bf{V}^\ast$ 이므로, $\sqrt{\bf{A}^\ast\bf{A}} = \bf{V\Sigma V}^\ast$ 이다. 따라서 $\bf{S}=\bf{UV}^\ast$ 라고 하면 $\bf{A} = \bf{S}\sqrt{\bf{A}^\ast\bf{A}}$ 이다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-polar_decomposition}

#### 행렬의 극분해

@prp-LA_polar_decomposition 에 따라 정사각 행렬을 유니타리 행렬과 non-negative 행렬의 곱으로 표현하는 것을 행렬의 **극분해(polar decomposition)** 이라고 한다. 
:::
:::