---
title: "내적벡터공간에서의 연산자"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

</br>

## Adjoint 연산자와 행렬

### Adjoint operator {#sec-adjoint_operator}

$L\in \mathcal{L}(U,\,V)$ 에 대해 다음의 성질을 만족하는 $L^\ast : V \to U$ 를 $L$ 에 대한 adjoint function 이라고 한다.

$$
\langle L (u),\,v \rangle = \langle u,\, L^\ast (v) \rangle.
$$

우선 고정된 $v$ 에 대해 $\phi (u) = \langle Lu,\,v\rangle$ 는 선형 범함수(@exr-adjoint_operator_1) 이며 @thm-Reisz_representaion_theorem 에 의해 $\phi(u) = \langle u, w\rangle$ 인 $w\in U$ 가 유일하게 존재한다. 이제 함수 $L^\ast : V \to U$ 를 $L^\ast( v)= w$ 인 함수로 생각 할 수 있다. (뭔가 이상한가? 이상해야 하는데..) 이 $L^\ast$ 를 $L$ 에 대한 adjoint function 이라고 한다.


</br>

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-adjoint_operator_1}

$L\in \mathcal{L}(U, V)$ 일 때 고정된 $v\in V$ 에 대해 $\phi (u) = \langle L(u),\,v\rangle$ 이 선형범함수임을 보여라.

:::

</div></br>

::: {.solution}

$u_1,\,u_2\in U,\, c\in \mathbb{F}$ 에 대해 다음이 성립한다.
$$
\begin{aligned}
\phi(u_1+cu_2) = \langle L(u_1+cu_2),\, v\rangle  = \langle L(u_1),\,v\rangle + c\langle L(u_2),\,v\rangle = \phi(u_1)+c\phi(u_2).
\end{aligned}
$$

따라서 $\phi$ 는 선형범함수이다. 

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-adjoint_transformation}

위에서 정의된 $L\in \mathcal{L}(U,\,V)$ 에 대한 adjoint function $L^\ast$ 는 선형사상이다.

:::

</div></br>

::: {.proof}

$$
\begin{aligned}
\langle u,\, L^\ast (v_1+cv_2)\rangle &= \langle L(u), v_1+cv_2\rangle \\
&= \langle L(u),\,v_1\rangle + \overline{c}\langle L(u),\,v_2\rangle  \\
&=\langle u,\, L^\ast(v_1) + c L^\ast(v_2)\rangle &\square 
\end{aligned}
$$

:::


즉 $L\in \mathcal{L}(U, V)$ 이면 $L^\ast \in \mathcal{L}(U, V)$ 이다. 이제 $L^\ast$ 를 $L$ 에 대한 adjoint transformation 이라고 한다. 여기서 한가지 짚어야 할 것이 있다. 우리는 리츠의 표현정리(@thm-Reisz_representaion_theorem) 를 이용하였는데 이 정리는 유한차원 벡터공간에서만 성립한다. 실제로 adjoint 는 유한차원 벡터공간에서만 유일하게 정해지며, 무한차원벡터공간에서는 유일하지 않을 수 있다$^1$.[$^1$ K. Hoffman, R. Kunze, *Linear Algebra*, 2nd Ed. pp 295]{.aside} 

::: {.callout-note appearance="simple" icon="false"}
::: {#def-adjoint}

#### Adjoint

내적벡터공간 $U,\,V$ 에서 정의된 $L\in \mathcal{L}(U,\,V)$ 에 대해 $\langle L(u),\, v\rangle = \langle u,\,L^\ast(v)\rangle$ 을 만족하는 $L^\ast \in \mathcal{L}(V,\,U)$ 가 존재하며 $L^\ast$ 를 $L$ 의 **adjoint** 라고 한다. 

:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-adjoint_matrix}

$L\in \mathcal{L}(U,\,V)$ 이며 $\mathcal{B}_U=(e_1,\ldots,\,e_n)$, $\mathcal{B}_V=(f_1,\ldots,\,f_n\)$ 이 각각 $U,\,V$ 에서의 정규직교기저라고 하자. $\boldsymbol{A} = [L]_{\mathcal{B}_U,\mathcal{B}_V}$, $\boldsymbol{A}^\ast = [L^\ast]_{\mathcal{B}_V,\mathcal{B}_U}$ 라면 다음이 성립한다.

$$
(\boldsymbol{A}^\ast)_{ij} = \overline{(\boldsymbol{A})_{ji}}.
$$

:::

</div></br>

::: {.proof}

$$
A_{ji}=\langle L(e_i),\, f_j\rangle = \langle e_i,\, L^\ast(f_j)\rangle = \overline{\langle L^\ast(f_j),\, e_i\rangle}=\overline{(\boldsymbol{A}^\ast)_{ij}} \qquad \square
$$

:::


</br>

따라서 행렬 $\boldsymbol{A}$ 에 대한 adjoint 를 adjoint matrix 라고 하여 아래와 같이 정의 할 수 있다.

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-adjoint_matrix}

#### Adjoint matrix

행렬 $\boldsymbol{A} \in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 

$$
(\boldsymbol{A}^\ast)_{ij} = \overline{A_{ji}}
$$

를 만족하는 $\boldsymbol{A}^\ast \in  \mathcal{M}_{m \times n}(\mathbb{F})$ 을 $\boldsymbol{A}$ 에 대한 **adjoint matrix** 라고 한다. [행렬 $\boldsymbol{A}$ 의 adjoint matrix 에 대해서는 $\boldsymbol{A}^\ast$, $\boldsymbol{A}^\dagger$, $\boldsymbol{A}^H$ 등의 표기법이 사용된다. 물리학 특히 양자역학에서는 adjoint matrix 에 대해 $\boldsymbol{A}^\ast$ 보다는 $\boldsymbol{A}^\dagger$ 의 표현을 더 많이 사용하기도 한다.]{.aside}


:::
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-adjoint_matrix}
정규직교기저에서 정의된 $\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$, $\boldsymbol{v}\in\mathcal{M}_{m }(\mathbb{F})$, $\boldsymbol{u}\in \mathcal{M}_{n }(\mathbb{F})$ 에 대해 $\langle \boldsymbol{Au},\, \boldsymbol{v} \rangle = \langle \boldsymbol{u},\, \boldsymbol{A}^\ast \boldsymbol{v} \rangle$ 임을 보여라.
:::

</div></br>

::: {.solution}

$\mathcal{M}_{n \times n}(\mathbb{F})$ 의 정규직교기저 $\{\boldsymbol{e}_i\}$ 와 $\mathcal{M}_{m }(\mathbb{F})$ 의 정규직교기저 $\{\boldsymbol{f}_j\}$ 를 생각하자. $\boldsymbol{u}=\sum_i u_i \boldsymbol{e}_i$, $\boldsymbol{v}= \sum_j v_j \boldsymbol{f}_j$ 라고 하면,
$$
\begin{aligned}
\langle \boldsymbol{Au},\,\boldsymbol{v}\rangle &= (\boldsymbol{Au})\cdot \boldsymbol{v} = \sum_i (\boldsymbol{Au})_i\overline{v_i} = \sum_{i, j} A_{ij}u_j\overline{v}_i \\
\langle \boldsymbol{u},\,\boldsymbol{A}^\ast \boldsymbol{v}\rangle &= \boldsymbol{u} \cdot (\boldsymbol{A}^\ast \boldsymbol{v}) = \sum_j u_j \overline{\left(\sum_i (\boldsymbol{A}^\ast)_{ji}v_i\right)} \\
&= \sum_j u_j u_j \overline{\left(\sum_i \overline{A_{ij}}v_i\right)} = \sum_{i, j} A_{ij}u_j\overline{v}_i 
\end{aligned}
$$

이다. 따라서 정규직교기저에서 $\langle \boldsymbol{Au},\, \boldsymbol{v} \rangle = \langle \boldsymbol{u},\, \boldsymbol{A}^\ast \boldsymbol{v} \rangle$ 이다. $\square$ 

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-properties_of_adjoint_operator}

다음이 성립한다.

&emsp; ($1$) $S,\, T\in \mathcal{L}(U,\,V)$ 일 때 $(S+T)^\ast = S^\ast + T^\ast$ 이다.

&emsp; ($2$) $L \in \mathcal{L}(U,\,V)$, $\lambda \in \mathbb{F}$ 일 때 $(\lambda L)^\ast = \overline{\lambda}L^\ast$.

&emsp; ($3$) $L \in \mathcal{L}(U,\,V)$ 일 때 $(L^\ast)^\ast = L$.

&emsp; ($4$) 항등연산자 $I\in \mathcal{L}(V)$ 에 대해 $I^\ast =I$.

&emsp; ($5$) $S\in \mathcal{L}(U, V),\, T\in \mathcal{L}(V,\,W)$ 에 대해 $(TS)^\ast = S^\ast T^\ast$ 이다.

:::

</div></br>

::: {.proof}

($1$) 에서 ($4$) 는 생략한다. 

$\langle TS(u),\,w\rangle = \langle u,\, (TS)^\ast (w)\rangle$ 이다. 또한
$$
\langle TS(u),\,w\rangle = \langle S(u),\, T^\ast(w)\rangle = \langle u,\, S^\ast T^\ast (w)\rangle
$$

이므로 $(TS)^\ast = S^\ast T^\ast$ 이다. $\square$


:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-kernel_image_of_adjoint_operator}
#### Adjoint 의 kernel 과 치역

$L\in \mathcal{L}(U,\,V)$ 일 때 다음이 성립한다.

&emsp; ($1$) $\ker (L^\ast) = (\text{im} (L))^\perp$

&emsp; ($2$) $\text{im} (L^\ast) = (\ker (L))^\perp$,

&emsp; ($3$) $\ker (L) = (\text{im}\, (L^\ast))^\perp$,

&emsp; ($4$) $\text{im} (L) = (\ker (L^\ast))^\perp$.
:::

</div></br>

::: {.proof}

($1$) 다음과 같이 보일 수 있다.
$$
\begin{aligned}
v\in \ker (L^\ast) & \iff L^\ast v=0_V  \\
&\iff \forall u\in U,\, \langle u,L^\ast(v)\rangle = 0 \\
&\iff \forall u\in U, \langle L(u),v\rangle = 0 \\
&\iff v \in \left(\text{im}(L)\right)^\perp
\end{aligned}
$$

($2$) ($1$) 의 결과에 $L$ 대신 $L^\ast$ 를 넣으면 $\ker(L) = (\text{im}(L^\ast))^\perp$ 이다. @cor-dimension_relation_of_orthogonal_complement 에서 부분공간 $U$ 에 대해 $(U^\perp)^\perp = U$ 임을 이용하면 $2$ 를 얻는다. 

($3$), ($4$) 는 ($1$), ($2$) 의 결과에서 $L$ 대신에 $L^\ast$ 를 넣으면 보일 수 있다. $\square$ 

:::

</br>

## 에르미트 행렬 (Hermitian matrix) {#sec-hermitian_matrix}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-hermitian_matrix}

#### 에르미트 연산자, 에르미트 행렬, 대칭행렬

$L\in \mathcal{L}(V)$ 에 대해 $L^\ast = L$ 일 때 $L$ 을 **에르미트 연산자(hermitian operator)** 혹은 **self-adjoint operator** 라고 한다. $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\boldsymbol{A}^\ast = \boldsymbol{A}$ 이면 이 행렬을 **에르미트 행렬(Hermitian matrix)** 혹은 **self-adjoint matrix** 이라 한다. 특별히 $\mathbb{F}=\mathbb{R}$ 일 경우에는 **대칭행렬 (Symmetric matrix)** 이라 한다.  

:::
:::

</br>

$\boldsymbol{A}$ 가 에르미트 행렬일 경우 $(\boldsymbol{A}^\ast)_{ij} = \overline{A_{ji}} = A_{ij}$ 를 만족한다. 대칭행렬의 경우에는 $A_{ij} = A_{ji}$ 이다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-peroperties_hermitian_operator}

#### 에르미트 연산자의 성질

에르미트 연산자 $L \in \mathcal{L}(V)$ 에 대해 대해 다음이 성립한다.

&emsp; ($1$) $\langle L(v_1),\, v_2\rangle = \langle v_1,\, L(v_2)\rangle$ 이다.

&emsp; ($2$) 고유값은 항상 실수이다.

&emsp; ($3$) 서로 다른 고유값을 갖는 두 고유벡터는 직교한다.
:::

</div></br>

::: {.proof}

($1$) $\langle L(v_1),\, v_2\rangle = \langle v_1,\, L^\ast (v_2) \rangle = \langle v_1,\, L(v_2)\rangle$.

($2$) 고유벡터 $v\in V$ 에 대한 고유값을 $\lambda$ 라 하자. 

$$
\lambda \|v\|^2 = \lambda \langle v,\, v\rangle  = \langle L(v),\, v\rangle = \langle v,\, L^\ast(v) \rangle = \langle v,\, L(v) \rangle = \overline{\lambda}\|v\|^2\,.
$$
이므로 $\lambda = \overline{\lambda}$ 이다. 즉 $\lambda$ 는 실수이다.

($3$) $\lambda_1,\,\lambda_2$ 가 서로 다른 고유벡터이며 $v_1,\,v_2$ 를 각각에 대한 고유벡터라 하자. 에르미트 행렬의 고유값은 항상 실수이므로 $\overline{\lambda_2}=\lambda_2$ 이다.

$$
\begin{aligned}
&\lambda_1 \langle v_1,\, v_2\rangle = \langle L(v_1),\,v_2\rangle = \langle v_1,\,L(v_2)\rangle  = \overline{\lambda_2} \langle v_1,\,v_2\rangle  = \lambda_2 \langle v_1,\,v_2 \rangle \\
\implies & (\lambda_1-\lambda_2) \langle v_1,\, v_2\rangle   = 0 \\
\implies & \langle v_1,\,v_2 \rangle = 0 \qquad \square
\end{aligned}
$$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-hermite_tvv}

복소내적벡터공간 $U$ 에서 정의된 연산자 $L\in \mathcal{L}(U)$ 에 대해 다음 두 명제는 동치이다.

&emsp; ($1$) 임의의 $u\in U$ 에 대해 $\langle L(u),\, u\rangle$ 은 실수이다.

&emsp; ($2$) $L$ 는 에르미트 연산자이다.

:::

</div></br>

::: {.proof}

($1\implies 2$) $\langle L(u),\, u\rangle$ 이 실수이면 $\langle L(u),\, u\rangle = \overline{\langle L(u),\, u\rangle }$ 이다. 따라서,

$$
\begin{aligned}
0 &= \langle L(u),\, u\rangle - \overline{\langle L(u),\, u\rangle } = \langle L(u),\, u\rangle - \langle u,\, L(u)\rangle = \langle L(u),\, u\rangle - \langle L^\ast(u),\, u\rangle \\
&= \langle (L-L^\ast)(u),\, u\rangle
\end{aligned}
$$

임을 안다. @exr-operator_orthogonal_to_every_vector 로 부터 $L=L^\ast$ 임을 알 수 있다. 즉 $L$ 는 에르미트 연산자이다.
 
($2 \implies 1$) $L$ 이 에르미트 연산자라고 하자.

$$
\langle L(u),\, u\rangle - \overline{\langle L(u),\, u\rangle} = \langle L(u),\, u\rangle - \langle L^\ast(u),\, u\rangle =0
$$

이므로 $\langle L(u),\, u\rangle$ 는 실수이다. $\square$
:::

</br>

## Linear Isometry {#sec-linear_isometry}


::: {.callout-note appearance="simple" icon="false"}
::: {#def-linear_isometry}
행렬 $\boldsymbol{S} \in \mathcal{M}_{n \times n}(\mathbb{F})$ 이 임의의 $\boldsymbol{v} \in \mathcal{M}_{n }(\mathbb{F})$ 에 대해

$$
\|\boldsymbol{Sv}\|^2 = \|\boldsymbol{v}\|^2
$$

일 때 $\boldsymbol{S}$ 를 **linear isometry** 라 한다. 즉 Linear isometry는 거리를 보존시키는 선형 변환을 나타내는 행렬이다.

:::
:::


많은 선형대수학 교재에서 linear isometry 를 isometry 라고 소개한다. 정확한 의미의 isometry 는 거리공간에서 거리를 보존하는 함수이며 여기에 대해서는 [Isometry](../part2/ch2_04_symmetry.qmd#sec-isometry) 에서 다루기로 한다. 


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-properties_of_isometry}

행렬 $\boldsymbol{S}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 다음은 동치이다.  

&emsp; ($1$) $\boldsymbol{S}$ 는 linear isometry이다.

&emsp; ($2$) $\langle \boldsymbol{Su},\, \boldsymbol{Sv}\rangle = \langle \boldsymbol{u},\,\boldsymbol{v}\rangle$

&emsp; ($3$) 정규직교벡터의 집합 $\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n \}$ 에 대해 $\{ \boldsymbol{Se}_1,\ldots,\,\boldsymbol{Se}_n\}$ 도 정규직교벡터의 집합이다.

&emsp; ($4$) $\boldsymbol{S}^\ast = \boldsymbol{S}^{-1}$ 이다.

:::

</div></br>

::: {.proof}
($1\implies 2$) 다음 두 식을 생각하자.

$$
\|\boldsymbol{Su}-\boldsymbol{Sv}\|^2 = \|\boldsymbol{S}(\boldsymbol{u}-\boldsymbol{v})\|^2=\|\boldsymbol{u}-\boldsymbol{v}\|^2 = \|\boldsymbol{u}\|^2 + \|\boldsymbol{v}\|^2 - \langle\boldsymbol{u},\,\boldsymbol{v}\rangle - \langle\boldsymbol{v},\,\boldsymbol{u}\rangle
$$

이다. 또한
$$
\begin{aligned}
\|\boldsymbol{Su}-\boldsymbol{Sv}\|^2 &=  \|\boldsymbol{Su}\|^2 + \| \boldsymbol{Sv}\|^2 - \langle \boldsymbol{Su},\, \boldsymbol{Sv} \rangle - \langle \boldsymbol{Sv},\, \boldsymbol{Su} \rangle \\
&=\|\boldsymbol{u}\|^2 + \|\boldsymbol{v}\|^2 - \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle - \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle
\end{aligned}
$$

이다. 이로부터 다음 결과를 얻을 수 있다.
$$
\langle\boldsymbol{u},\,\boldsymbol{v}\rangle + \langle\boldsymbol{v},\,\boldsymbol{u}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle + \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle \tag{1} 
$$

$\mathbb{F}=\mathbb{R}$ 이라면 $\langle\boldsymbol{u},\,\boldsymbol{v}\rangle = \langle\boldsymbol{v},\,\boldsymbol{u}\rangle$, $\langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle = \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle$ 이므로 $\langle\boldsymbol{u},\,\boldsymbol{v}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle$ 이다.

$\mathbb{F}=\mathbb{C}$ 라면 다음을 더 생각하자.

$$
\begin{aligned}
\|\boldsymbol{Su}-i\boldsymbol{Sv}\|^2 & = \|\boldsymbol{S}(\boldsymbol{u}-i\boldsymbol{v})\|^2=\|\boldsymbol{u}-i\boldsymbol{v}\|^2 \\
&= \|\boldsymbol{u}\|^2 + \|\boldsymbol{v}\|^2 + i\langle\boldsymbol{u},\,\boldsymbol{v}\rangle -i \langle\boldsymbol{v},\,\boldsymbol{u}\rangle
\end{aligned}
$$

또한
$$
\begin{aligned}
\|\boldsymbol{Su}-i\boldsymbol{Sv}\|^2 &=  \|\boldsymbol{Su}\|^2 + \| \boldsymbol{Sv}\|^2 + i\langle \boldsymbol{Su},\, \boldsymbol{Sv} \rangle -i \langle \boldsymbol{Sv},\, \boldsymbol{Su} \rangle \\
&=\|\boldsymbol{u}\|^2 - \|\boldsymbol{v}\|^2 + i\langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle -i \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle
\end{aligned}
$$

이다. 이로부터 다음 결과를 얻는다.
$$
\langle\boldsymbol{u},\,\boldsymbol{v}\rangle - \langle\boldsymbol{v},\,\boldsymbol{u}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle - \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle\tag{2}
$$

식 ($1$), ($2$) 로부터 $\langle\boldsymbol{u},\,\boldsymbol{v}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle$ 임을 알 수 있다.


($2\implies 3$) $\langle \boldsymbol{e}_i, \boldsymbol{e}_i\rangle = \delta_{ij}$ 이므로 ($2$) 에 의해 $\langle \boldsymbol{Se}_i, \boldsymbol{Se}_j \rangle = \langle \boldsymbol{e}_i, \boldsymbol{e}_i\rangle = \delta_{ij}$ 이다.

($3 \implies 4$) $(\boldsymbol{S}^\ast\boldsymbol{S})_{ij}= \langle \boldsymbol{S}^\ast \boldsymbol{Se}_j,\, \boldsymbol{e}_i\rangle = \langle \boldsymbol{Se}_j,\,\boldsymbol{Se}_i\rangle = \delta_{ij}$ 이므로 $\boldsymbol{S}^\ast\boldsymbol{S}=\boldsymbol{I}_n$ 이다.

($4 \implies 1$) $\|\boldsymbol{v}\|^2 = \langle \boldsymbol{Iv},\,\boldsymbol{v} \rangle =  \langle \boldsymbol{S}^\ast\boldsymbol{Sv},\,\boldsymbol{v} \rangle = \|\boldsymbol{Sv}\|^2$.   $\square$

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-cojugate_of_isometry}
$\boldsymbol{S}$ 가 linear isometry 이면 $\boldsymbol{S}^\ast$ 도 linear isometry 임을 보여라.
:::

</div></br>

::: {.solution}

@prp-properties_of_isometry 에서 보였듯이 $\boldsymbol{S}$ 가 linear isometry 이면 $\boldsymbol{S}^\ast = \boldsymbol{S}^{-1}$ 이다. 따라서
$$
\|\boldsymbol{S}^\ast \boldsymbol{u}\|^2 = \langle \boldsymbol{S}^\ast\boldsymbol{u},\, \boldsymbol{S}^\ast\boldsymbol{u}\rangle = \langle \boldsymbol{u} | \boldsymbol{SS}^\ast \boldsymbol{u}\rangle = \|\boldsymbol{u}\|^2
$$

이므로 $\boldsymbol{S}^\ast$ 도 linear isometry 이다. $\square$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-product_of_isometries}
$\boldsymbol{S},\,\boldsymbol{T}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이 linear isometry 이면 $\boldsymbol{ST}$ 도 linear isometry 임을 보여라.
:::

</div></br>

::: {.solution}

@prp-properties_of_isometry 에 의해 $\boldsymbol{S}^{-1}=\boldsymbol{S}^\ast$ 이면 $\boldsymbol{S}$ 가 linear isometry 인 것을 이용한다.
$$
(\boldsymbol{ST})^{-1}= \boldsymbol{T}^{-1}\boldsymbol{S}^{-1}= \boldsymbol{T}^\ast \boldsymbol{S}^\ast = (\boldsymbol{ST})^\ast
$$

:::

</br>

### Unitary and Orthogonal Operator/Matrix

::: {.callout-caution}

여러번 강조하고 또 강조했지만 선형사상과 벡터의 행렬표현은 특정 기저에 대한 표현이다. 우리는 정규직교기저를 배웠지만 지금까지는 굳이 행렬표현의 기저를 정규직교기저로 한정짓지 않았다. 하지만 이제부터는 특별한 언급이 없는 한 정규직교기저로 한정짓고자 한다. 즉 내적벡터공간에 대한 행렬과 벡터의 표현은 정규직교기저에 대한 표현이다. 따라서 내적은 dot product 와 같아진다. 

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-orthogonal_operator}

#### 유니타리행렬과 직교행렬

$\mathbb{C}$-벡터공간에서 정의된 linear isometry 를 **유니타리 연산자/행렬 (unitary operator/matrix)** 라 하고 $\mathbb{R}$-벡터공간에서 정의된 linear isometry 를 **직교 연산자/행렬 (orthogonal operator/matrix)** 라 한다. 유니타리 행렬에 의한 행렬/벡터의 변환을 **유니타리 변환 (unitary transformation)**, 직교행렬에 의핸 행렬/벡터의 변환을 **직교 변환 (orthogonal transformation)**이라고 한다.

:::
:::

</br>

### Isometry 와 정규직교기저

정규직교기저간의 기저 변환과 isometry 에 대한 두가지를 보인다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-isometry_orthonormal_basis}
$\boldsymbol{S}$ 가 linear isometry 일 때 $\boldsymbol{S}$ 의 각 열벡터의 집합은 정규직교기저이며, 정규직교기저를 각 열벡터로 갖는 행렬은 linear isometry 이다.
:::

</div></br>

::: {.proof}

$\boldsymbol{S}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이 linear isometry 이면 $\boldsymbol{S}^\ast\boldsymbol{S} = \boldsymbol{I}$ 임을 안다. 따라서, 

$$
\delta_{ij} = (\boldsymbol{S}^\ast\boldsymbol{S})_{ij} = \sum_k (\boldsymbol{S}^\ast)_{ik}(\boldsymbol{S})_{kj} = \sum_k \overline{\boldsymbol{S}_{ki}}\boldsymbol{S}_{kj} = \boldsymbol{S}_{:j}\cdot \boldsymbol{S}_{:i}
$$

이므로 $\boldsymbol{S}$ 의 열벡터의 집합은 정규직교기저이다. 또한 $\boldsymbol{S}$ 의 각 열벡터가 정규직교기저이면, $\boldsymbol{S}_{:j}\cdot \boldsymbol{S}_{:i} =\delta_{ij}$ 이므로

$$
 (\boldsymbol{S}^\ast\boldsymbol{S})_{ij} = \sum_k (\boldsymbol{S}^\ast)_{ik}(\boldsymbol{S})_{kj} = \sum_k \overline{\boldsymbol{S}_{ki}}\boldsymbol{S}_{kj} = \boldsymbol{S}_{:j}\cdot \boldsymbol{S}_{:i} = \delta_{ij}
$$

이다. 즉 $\boldsymbol{S}^\ast \boldsymbol{S}=\boldsymbol{I}$ 이므로 $\boldsymbol{S}$ 는 linear isometry 이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-transform_between_orthonormal_basis_is_linear_isometry}
정규직교기저간의 변환행렬은 linear isometry 이다.
:::

</div></br>

::: {.proof}

 $\{\boldsymbol{u}_i\}$, $\{\boldsymbol{v}_j\}$ 가 정규직교기저라 하자.

$$
\boldsymbol{v}_j = \sum_{k=1}^n S_{kj}\boldsymbol{u}_k
$$

라면

$$
\begin{aligned}
\delta_{ij} &= \langle \boldsymbol{v}_i,\, \boldsymbol{v}_j \rangle = \sum_k \sum_l S_{ki}\overline{S_{lj}} \langle \boldsymbol{u}_k,\, \boldsymbol{u}_l \rangle \\
&= \sum_k \sum_l  S_{ki}\overline{S_{lj}} \delta_{kl}= \sum_l (S^\ast)_{jl}S_{li} \\
&= (\boldsymbol{S}^\ast \boldsymbol{S}) _{ij}
\end{aligned}
$$

이다. 즉 $\boldsymbol{P}^\ast \boldsymbol{P}=\boldsymbol{I}$ 이므로 $\boldsymbol{P}$ 는 linear isometry 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-determinant_of_isometry}

직교행렬의 행렬식은 $1$ 혹은 $-1$ 이다. Unitary 행렬의 행렬식은 크기가 $1$ 인 복소수임을 보여라.
:::

</div></br>

::: {.solution}
$\det(\boldsymbol{S}^\ast \boldsymbol{S})=\det(\boldsymbol{S}^\ast) \det(\boldsymbol{S}) = \det(\boldsymbol{I})=1$ 임을 이용한다. 직교행렬이라면, 즉 실행렬이라면 $\boldsymbol{S}^\ast = \boldsymbol{S}^T$ 이며 $\det (\boldsymbol{S}^T) = \det (\boldsymbol{S})$ 이므로 $(\det(\boldsymbol{S})))^2=1$ 이다. 따라서 $\det (\boldsymbol{S})= \pm 1$ 이다. Unitary 행렬이라면, 즉 복소행렬이라면 $\det(\boldsymbol{S}^\ast) = \overline{\det (\boldsymbol{S}^T)} = \overline{\det (\boldsymbol{S})}$ 이다. 즉 $|\det (\boldsymbol{S})|^2=1$ 이다. $\square$ 

:::

</br>

### Linear Isometry 와 행렬의 변환

$n$ 차원 벡터공간 $V$ 에서 정의된 연산자 $T$ 와 정규직교기저 $\{u_1,\ldots,\,u_n\}$ 를 생각하자. 이 정규직교기저에서 $T$ 의 행렬표현이 $\boldsymbol{A}$ 이며, 닮을변환을 나타내는 $\boldsymbol{P}$ 에 의해 기저가 변화했을 때의 행렬표현은 $\boldsymbol{P}^{-1}\boldsymbol{AP}$ 임을 안다. $\boldsymbol{P}$ 가 isometry 이면 $\boldsymbol{P}^{-1}=\boldsymbol{P}^\ast$ 이므로 기저가 변환된 행렬은 $\boldsymbol{P}^\ast \boldsymbol{AP}$ 이다.

</br>

## 연습문제

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_7_A_2}

$\lambda$ 가 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 의 고유값이라면 $\overline{\lambda}$ 는 $\boldsymbol{A}^\ast$ 의 고유값임을 보여라.

:::

</div></br>

::: {.solution}

$c\in \mathbb{F}$ 가 고유값이 아닐 필요충분조건은 $\boldsymbol{A}-c\boldsymbol{I}_n$ 이 가역행렬인 것이다. $\boldsymbol{S}_c = (\boldsymbol{A}-c\boldsymbol{I}_n)^{-1}$ 이라 하면, $\boldsymbol{S}_c(\boldsymbol{A}-c\boldsymbol{I}_n) = (\boldsymbol{A}-c\boldsymbol{I}_n)\boldsymbol{S}_c=\boldsymbol{I}_n$ 이며 이로부터,

$$
\boldsymbol{S}_c^\ast(\boldsymbol{A}^\ast-\overline{c}\boldsymbol{I}_n)^\ast = (\boldsymbol{A}^\ast-\overline{c}\boldsymbol{I}_n)^\ast\boldsymbol{S}_c^\ast=\boldsymbol{I}_n
$$

를 얻는다. 즉 $\boldsymbol{A}-c\boldsymbol{I}_n$ 이 가역일 필요충분조건은 $\boldsymbol{A}^\ast -\overline{c}\boldsymbol{I}_n$ 이 가역인 것이다. $\square$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_7_A_3}

$\boldsymbol{A}=\mathcal{M}_{n \times n}(\mathbb{F})$ 이며 $U\le \mathcal{M}_n(\mathbb{F})$ 라고 하자. $U$ 가 $\boldsymbol{A}$-불변 일 필요충분조건은 $\boldsymbol{U}^\perp$ 가 $\boldsymbol{A}^\ast$-불변인것임을 보여라.

:::

</div></br>

::: {.solution}

모든 $\boldsymbol{u}\in U$, $\boldsymbol{w}\in U^\perp$ 에 대해 $\langle \boldsymbol{Au}, \boldsymbol{w}\rangle = 0$ 이면 $\langle \boldsymbol{u}, \boldsymbol{A}^\ast \boldsymbol{w}\rangle = 0 = \langle \boldsymbol{A}^\ast \boldsymbol{w}, \boldsymbol{u} \rangle$ 이다. 
:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_7_A_4}

$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 다음을 보여라.

&emsp;($1$) $\boldsymbol{A}$ 가 단사일 필요충분조건은 $\boldsymbol{A}^\ast$ 가 전사인 것이다.

&emsp;($2$) $\boldsymbol{A}$ 가 전사일 필요충분조건은 $\boldsymbol{A}^\ast$ 가 단사인 것이다.

:::

</div></br>

::: {.solution}

$(\boldsymbol{A}^\ast)^\ast = \boldsymbol{A}$ 이므로 둘중 하나만 보이면 된다. ($1$) 은 @thm-kernel_image_of_adjoint_operator ($3$) 으로부터 쉽게 보일 수 있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_7_A_5}

$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 다음을 보여라.

&emsp; ($1$) $\text{nullity}(\boldsymbol{A}^\ast) = \text{nullity}(\boldsymbol{A}) + m - n$, 

&emsp; ($2$) $\text{rank}(\boldsymbol{A}^\ast) = \text{rank}(\boldsymbol{A})$.

:::

</div></br>

::: {.solution}

($1$)  @thm-rank_nullity 에 의해 $m=\text{nullity}(\boldsymbol{A}^\ast) + \text{rank}(\boldsymbol{A}^\ast)$ 이며 @thm-kernel_image_of_adjoint_operator 에 의해 $\text{nullity} (\boldsymbol{A}) = n-\text{rank}(\boldsymbol{A}^\ast)$ 이므로 ($1$) 이 성립한다.


($2$) $\text{ker} (\boldsymbol{A}^\ast) = (\text{im} (\boldsymbol{A}))^\perp$ 이므로 $\text{nullity}(\boldsymbol{A}^\ast) = m - \text{rank}(\boldsymbol{A})$ 이다. ($1$) 에 $\text{nullity} (\boldsymbol{A}) = n-\text{rank}(\boldsymbol{A}^\ast)$ 과 함께 대입하면 ($2$) 를 얻는다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_7_A_7}

$\boldsymbol{A},\, \boldsymbol{B} \in \mathcal{M}_{n \times n} (\mathbb{F})$ 가 에르미트 행렬이라고 하자. $\boldsymbol{AB}$ 가 에르미트 행렬일 필요충분조건은 $\boldsymbol{AB}=\boldsymbol{BA}$ 임을 보여라.

:::

</div></br>

::: {.solution} 
$(\boldsymbol{AB})^\ast = \boldsymbol{AB} \iff \boldsymbol{B}^\ast \boldsymbol{A}^\ast = \boldsymbol{AB} \iff \boldsymbol{BA}= \boldsymbol{AB}$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_7_A_8_9}

$\mathcal{M}_{m \times n}(\mathbb{R})$ 에서의 에르미트 행렬의 집합은 벡터공간을 이룸을 보여라. $\mathcal{M}_{m \times n}(\mathbb{C})$ 에서의 에르미트 행렬의 집합은 벡터공간을 이루지 않음을 보여라. 

:::

</div></br>

::: {.solution}

$\mathcal{M}_{m \times n}(\mathbb{R})$ 에서의 에르미트 행렬의 집합은 대칭행렬의 집합이며 벡터공간을 이룬다는 것은 쉽게 보일 수 있다. $\mathcal{M}_{m \times n}(\mathbb{C})$ 의 경우,

$$
\left[\begin{array}{rr} 1 & i \\ -i & 1 \end{array}\right] + i \left[\begin{array}{rr} 1 & 1 \\ 1 & 2 \end{array}\right] = \left[\begin{array}{rr} 1+i & 2i \\ 0 & 1+i \end{array}\right]
$$

는 에르미트 행렬이 아니다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_7_A_11}

Projection $\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\boldsymbol{P}=\boldsymbol{P}_U$ 인 $U\le \mathcal{M}_{n}(\mathbb{F})$ 가 존재할 필요충분조건은 $\boldsymbol{P}$ 가 에르미트 행렬임을 보여라.

:::

</div></br>

::: {.solution}

$\boldsymbol{P}=\boldsymbol{P}_U$ 인 $U \le \mathcal{M}_n (\mathbb{F})$ 가 존재한다고 하자. $\boldsymbol{v}_1,\, \boldsymbol{v}_2\in \mathcal{M}_n(\mathbb{F})$ 에 대해 $\boldsymbol{v}_1 = \boldsymbol{u}_1 + \boldsymbol{w}_1$, $\boldsymbol{v}_2 = \boldsymbol{u}_2 + \boldsymbol{w}_2$ 를 만족하는 $\boldsymbol{u}_1,\, \boldsymbol{u}_2\in U$, $\boldsymbol{w}_1,\,\boldsymbol{w}_2 \in U^\perp$ 가 존재한다.

$$
\langle \boldsymbol{Pv}_1,\,\boldsymbol{v}_2\rangle = \langle \boldsymbol{u}_1,\, \boldsymbol{v}_2\rangle = \langle \boldsymbol{u}_1,\,\boldsymbol{u}_2 + \boldsymbol{w}_2 \rangle = \langle \boldsymbol{u}_1,\, \boldsymbol{u}_2\rangle = \langle \boldsymbol{u}_1,\boldsymbol{Pv}_2\rangle = \langle \boldsymbol{v}_1,\, \boldsymbol{Pv}_2\rangle 
$$

이므로 $\boldsymbol{P}$ 는 에르미트 행렬이다.

역으로 $\boldsymbol{P}$ 가 에르미트 행렬이라고 하고 $U=\text{im}(\boldsymbol{P})$ 라고 하자. $\boldsymbol{P}$ 가 projection 이면 $U\le \mathcal{M}_n(\mathbb{F})$ 에 대해 $\boldsymbol{P}= \boldsymbol{P}_U$ 임은 이미 보였다. 

:::