---
title: "고유값과 고유벡터"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

</br>

## 고유값, 고유벡터, 고유공간

함수 $f:X \to Y$ 와 $A \subset X$ 에 대해 $f(A) := \{f(a):a\in A\}$ 라고 하는 것처럼 선형사상 $L\in \mathcal{L}(V,\,W)$ 와 $U\subset V$ 에 대해 $L(U) = \{Lu:u\in U\}$ 라고 하자.

</br>

### 고유값, 고유벡터, 고유공간 {#sec-LA_eigens}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_invariant_subspace}

#### 불변부분공간

$L\in \mathcal{L}(V)$ 이고 $U \le V$ 일 때

$$
L(U) \le U
$$

이면 $U$ 를 $L$ 에 대한 $V$ 의 **불변부분공간(invariant subspace)** 라고 한다.
:::
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_invariant_subspace}

$L\in \mathcal{L}(V)$ 에 대해 다음이 성립한다.

&emsp;($1$) $V$ 는 $L$ 에 대한 불변부분공간이다.

&emsp;($2$) $\ker (L)$ 는 $L$ 에 대한 불변부분공간이다. 

&emsp;($3$) $\text{im} (L)$ 은 $L$ 에 대한 불변부분공간이다.
:::

</div>

::: {.proof}
($1$) 은 자명하다. 

($2$) $u\in L(\ker (L))$ 이면 어떤 $v\in \ker L$ 에 대해 $u=Lv=0_V\in \ker L$. 

($3$) $u\in L(\im (L)) \implies u \in \im L$. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_eigenvector}

#### 고유값, 고유벡터, 고유공간

$\mathbb{F}$-벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 에 대해 어떤 벡터 $v\ne O_V$ 와 스칼라 $\lambda\in \mathbb{F}$ 가 존재하여,

$$
L(v) = \lambda v
$$

일 때 $v$ 를 $L$ 의 **고유벡터 (eigenvector)**, $\lambda$ 를 $L$ 에 대한 $v$ 의 **고유값(eigenvalue)** 이라 한다. 연산자 $L$ 이 고유값 $\lambda$ 를 가질 때, 이 고유값 $\lambda$ 를 갖는 고유벡터와 영벡터의 집합을 $\lambda$ 에 대한 $L$ 의 **고유공간(eigenspace)** 이라고 하며 $E(\lambda, L)$ 라 쓴다. 
:::
:::

</br>

즉 $v$ 가 $\lambda$ 의 고유값을 갖는 $L$ 의 고유벡터라면 $(L-\lambda I)v=0_V$ 이다. @thm-LA_isomorphic_linear_map 로부터 다음과 같은 결론을 얻게 된다.

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_finite_dimensional_vector_space_and_eigenvector}

유한차원 $\F$-벡터공간 $V$ 에서의 선형연산자 $L$ 과 $\lambda\in \mathbb{F}$ 에 대해 다음은 동치이다.

&emsp;($1$) $\lambda$ 는 $L$ 의 고유값이다.

&emsp;($2$) $L-\lambda I$ 는 가역사상이 아니다.

&emsp;($3$) $L-\lambda I$ 는 전사도 단사도 아니다.

:::

</div></br>

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_diagonal_matrix_and_eigenvalue}

$\bf{D}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 대각행렬, 즉 대각성분을 제외한 모든 성분이 $0$ 인 행렬이라고 하자. 표준기저 $\hat{\bf{e}}_i$ 에 대해 $\bf{D}\hat{\bf{e}}_i = D_{ii} \hat{\bf{e}}_i$ 이므로 $\hat{\bf{e}}_i$ 는 $D_{ii}$ 를 고유값으로 갖는 $\bf{D}$ 의 고유벡터이다. 

:::
</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_eigenspace_invariant}

$E(\lambda,\, L)$ 은 $L$ 에 대한 불변부분공간이다.

:::

</div>

::: {.proof}
$L\in \mathcal{L}(V)$ 라고 하고 우선 고유공간이 부분공간임을 보이자. 고유공간은 정의상 영벡터를 포함한다. 즉 $0_V\in E(\lambda, L)$ 이다. $v_1,\,v_2 \in E(\lambda, L)$ 이며 $c\in \mathbb{F}$ 일 때

$$
L(v_1 + cv_2) = \lambda(v_1 + cv_2)
$$

이므로 $v_1 + cv_2 \in E(\lambda, L)$ 이다. 따라서 $E(\lambda,L)$ 은 부분공간이다. $v\in E(\lambda,L)$ 이면 $L(v)=\lambda v\in E(\lambda, L)$ 이다. 따라서 고유공간은 불변부분공간이다. $\square$

:::

</br>

### 고유값과 행렬식 {#sec-LA_eigenvalue_and_determinant}

이제 선형사상/행렬의 고유값을 찾는 방법을 알아보자. 다음 정리는 선형사상/행렬의 고유값을 찾는 가장 중요한 방법을 알려준다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_eigenvalues_determinant}

$\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\det (\lambda \bf{I}-\bf{A}) \ne 0$ 을 만족하는 $\lambda \in \mathbb{F}$ 는 행렬 $\bf{A}$ 의 고유값이며, 이 $\lambda$ 에 대한 고유벡터가 항상 존재한다.

:::

</div>

::: {.proof}

$\det (\lambda \bf{I}-\bf{A})  = 0$ 이면 $\text{nullity} (\lambda \bf{I}-\bf{A})  \ne 0$ 이므로 $\bf{A}v=\lambda \bf{v}$ 를 만족하는 영벡터가 아닌 벡터 $\bf{v}$ 가 항상 존재한다. $\square$

:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-LA_eigenvalues_for_Field}

예를 들어 $\bf{A}_1 = \begin{bmatrix} 1 & 1 \\ -1 & 1 \end{bmatrix}$ 라 하자. $\det(\lambda \bf{I}-\bf{A})  = (\lambda-1)^2 +1$ 이므로 $\det (\lambda \bf{I}-\bf{A}) =0$ 을 만족하는 $\lambda$ 는 $1 \pm i$ 이다. 만약 $\bf{A}$ 가 $\mathbb{C}$ 위에서 정의된 행렬이라면 고유값과 고유벡터가 존재하지만 $\mathbb{R}$ 위에서 정의된 행렬이라면 고유값이 존재하지 않는다. 

:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_eigenvector_linear_independence}
$L\in \mathcal{L}(V)$ 의 고유벡터의 집합 $\{v_1,\ldots,\, v_m\}$ 에 대해 고유벡터가 각각 서로 다른 고유값 $\lambda_1,\ldots,\lambda_m$ 을 갖는 고유벡터라면 이 벡터의 집합은 선형독립이다.
:::

</div>

::: {.proof}
$V_0=\{v_1, \ldots,\,v_m\}$ 가 선형종속임을 가정하자. $v_k$ 가 $\{ v_1, \ldots, v_{k-1}\}$ 의 선형결합으로 표현되는 첫번째 벡터라고 하자. 이런 $v_k$ 가 존재하지 않으면 $V_0$ 는 선형독립이므로 $v_k$ 는 항상 존재한다. 이 때, 당연히도 $\{v_1,\ldots,\,v_{k-1}\}$ 은 선형독립이다. 이 때

$$
\begin{aligned}
v_k = c_1 v_1 + \cdots + c_m v_{k-1} \implies & L(v_k) = c_1 L(v_1) + \cdots + c_{k-1} L(v_{k-1}) \\[0.3em]
\implies & \lambda_k v_k = \lambda_1 c_1 v_1 + \cdots + \lambda_{k-1} c_{k-1}v_{k-1}
\end{aligned}
$$

이다. 또한 $\lambda_k v_k = \lambda_k (c_1 v_1 + \cdots + c_{k-1} v_{k-1})$ 이므로,

$$
c_1 (\lambda_k -\lambda_1) v_1 + \cdots + c_{k-1}(\lambda_k -\lambda_{k-1}) v_{k-1}=0
$$

이다. $\{v_1,\ldots,v_{k-1}\}$ 이 선형독립이며 모든 $\{\lambda_i\}$ 가 서로 다르므로, $c_1 = \cdots = c_{k-1}=0$ 이다. 즉 $\{v_1,\ldots,\,v_k\}$ 는 선형독립이므로 선형종속이라는 가정에 모순된다. 즉 $V_0$ 는 선형독립이다. $\square$
:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_4}

#### Axler4th 5.A.4

유한차원 $\mathbb{F}$-벡터공간 $V$ 에 대해 $U\le V$ 가 $V$ 에 대한 모든 연산자에 대해 불변부분공간이면 $U=\{0_V\}$ 이거나 $U=V$ 임을 보여라.

:::

</div>

::: {.solution}

$U=\{0_V\}$ 이거나 $U=V$ 이면 자명하다. $1 < \dim (U) < \dim (V)$ 라고 하자. $U$ 의 임의의 기저 $(u_1,\ldots,\,u_m)$ 를 확장하여 $V$ 의 기저 $(u_1,\ldots,\,u_m,\,v_1,\ldots,\,v_n)$ 을 구성했다고 하자. $L\in \mathcal{L}(V)$ 를 $L(u_1) = v_1$ 이 되도록 정할 수 있으며 이 경우 $U$ 는 $L$ 의 불변부분공간이 되지 않는다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_8}
#### Axler4th 5.A.8

$P\in \mathcal{L}(V)$ 가 $P^2=P$ 라고 하자. $\lambda$ 가 $P$ 의 고유값이라면 $\lambda = 0$ 이거나 $1$ 임을 보여라.

:::

</div>

::: {.solution}

고유값 $\lambda$ 에 대한 고유벡터를 $v_\lambda$ 라고 하면 $Pv_\lambda = \lambda v_\lambda$ 이며 $P^2v_\lambda = \lambda^2 v_\lambda = \lambda v_\lambda$ 이다. 따라서 $\lambda = 0$ 혹은 $1$ 이다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_9}
#### Axler4th 5.A.9

$L:\R[t] \to \R[t]$ 가 $L(p(t))= p'(t)$ 일 때 모든 고유값과 고유벡터를 구하라.

:::

</div>

::: {.solution}

고유값은 모든 실수가 될 수 있으며 $\lambda\in \R$ 에 대한 고유벡터는 $\displaystyle p(t) = e^{\lambda t}= \sum_{k=0}^\infty \dfrac{(\lambda t)^k}{k!}$ 이다. 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4_5_A_12}

#### Axler4th 5.A.12

유한차원 벡터공간 $V$ 가 $V= U \oplus W$ 이며 $U,\,W$ 는 $\{0_V\}$ 이 아니다. $P\in \mathcal{L}(V)$ 가 모든 $u\in U,\, w\in W$ 에 대해 $P(u+w)= u$  일 때 $P$ 의 모든 고유값과 고유벡터를 구하시오.

:::

</div>

::: {.solution}

$P(u)=u,\, P(w) = 0$ 이므로 $U$ 의 모든 벡터는 고유값 $1$ 을 $W$ 의 모든 벡터는 고유값 $0$ 을 가진다. $u\in U,\, w\in W$ 가 모두 $0_V$ 가 아닐 때 $P(u+w)=u$ 이므로 이런 형태의 벡터는 고유값을 갖지 않는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4_5_A_13}

#### Axler4th 5.A.13

$S,\,L\in \mathcal{L}(V)$ 이며 $S$ 가 가역일 때 $S^{-1}LS$ 는 $L$ 과 같은 고유값을 가짐을 보여라. $L$ 과 $S^{-1}LS$ 의 고유벡터의 관계를 보여라.

:::

</div>

::: {.solution}

$v\in V$ 가 $L$ 의 고유벡터이면 $Lv = \lambda v$ 이다. $u=S^{-1}v$ 에 대해 $S^{-1}LS u= \lambda u$ 이다. 따라서 $v$ 가 $L$ 의 고유벡터이면 $S^{-1}v$ 는 $S^{-1}LS$ 의 같은 고유값을 갖는 고유벡터이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_15}

#### Axler4th 5.A.15

(**주의** : [쌍대사상](../part3/dual_space.qmd) 을 보라) 유한차원 벡터공간 $V$ 와 $L\in \mathcal{L}(V)$ 에 대해 $\lambda$ 가 $L$ 의 고유값이면 $\lambda$ 는 $L$ 의 쌍대연산자의 고유값임을 보여라.

:::

</div>

::: {.solution}

$Lv =\lambda v$ 라고 하고 $v$ 에 대한 쌍대기저를 $\delta_v$ 라고 하자. $L$ 에대한 쌍대연산자를 $L^T$ 라고 하자. $\phi \in V^\ast$ 에 대해 $L^T (\phi) = \phi \circ L$ 이며 $L^T(\delta_v) = \lambda\delta_v (v)$ 이므로 $\lambda$ 는 $L^T$ 의 고유값이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_16}

#### Axler4th 5.A.16

$\mathcal{B}=(v_1,\ldots,\,v_n)$ 이 $V$ 의 기저이며 $L\in \mathcal{L}(V)$ 이고 $[L]_{\mathcal{B}}=\bf{L}$ 일 때 $L$ 의 고유값 $\lambda$ 에 대해 다음이 성립함을 보여라.

$$
|\lambda | \le n \max\{|L_{ij}| :1 \le i,\,j \le n \}
$$ {#eq-exr-axler4_5_A_16}

:::

</div>

::: {.solution}

$\lambda$ 가 $L$ 의 고유값이므로 이에대한 고유벡터를 $v$ 라고 하면 $\lambda v = Lv$ 이다. $v=\sum_{i=1}^n c_i v_i$ 라고 하면

$$
\sum_{i=1}^n \lambda c_i v_i = \lambda v = L\left(\sum_{i=i}^n c_i v_i\right) = \sum_{i=i,\,j}^n c_i L_{ji}v_j
$$

이며 $(v_i)$ 가 선형독립이므로 $\lambda c_i = \sum_{j=1}^n c_j L_{ij}$ 이다. $c_1,\ldots,\,c_n$ 가운데 절대값이 가장 큰 것을 $c_M$ 라고 하면

$$
|\lambda \cdot c_M| = \left|\sum_{j=1}^n c_j L_{Mj}\right| \le \sum_{j=1}^n |c_j||L_{Mj}| \le n|c_M| \max\{|L_{ij}| :1 \le i,\,j \le n \}
$$

이며 따라서 @eq-exr-axler4_5_A_16 이 성립한다.

:::



</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4_5_A_21}

#### Axler4th 5.A.21

$L\in \mathcal{L}(V)$ 가 가역일 때 $\lambda (\ne 0)$ 이 $L$ 의 고유값이면 $L^{-1}$ 은 같은 고유벡터에 대해 $1/\lambda$ 를 고유값으로 갖게 됨을 보여라.

:::

</div>

::: {.solution}

$Lv=\lambda v$ 에 대해 $v=L^{-1}L v = \lambda L^{-1}v$ 이므로 $L^{-1}v = \dfrac{1}{\lambda}v$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4_5_A_23}

#### Axler4th 5.A.23

유한차원 벡터공간 $V$ 에서 $K,\,L\in \mathcal{L}(V)$ 일 때 $KL$ 과 $LK$ 는 같은 고유값을 가진다는 것을 보여라.

:::

</div>

::: {.solution}

$KLv=\lambda v$ 라고 하자. $LK(Lv)= L(\lambda v)= \lambda (Lv)$ 이므로 $LK$ 역시 고유값 $\lambda$ 를 가진다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4_5_A_24}

#### Axler4th 5.A.24

$\bf{A}\in \mathcal{M}_{n\times n}(\F)$ 이고 $T\in \mathcal{L}(\mathcal{M}_n(\F))$ 가 $T(\bf{x}) = \bf{Ax}$ 라고 하자.

($a$) $\bf{A}$ 의 각 행벡터에 대해 성분의 합이 $1$ 이면 $1$ 은 $T$ 의 고유값임을 보여라.

($b$) $\bf{A}$ 의 각 열벡터에 대해 성분의 합이 $1$ 이면 $1$ 은 $T$ 의 고유값임을 보여라.

:::

</div>

::: {.solution}

($a$) $\bf{v} = \begin{bmatrix}1 & \cdots &1 \end{bmatrix}^T$ 에 대해 $T(\bf{x}) = \bf{Ax}= \bf{x}$ 이므로 $1$ 은 $T$ 의 고유값이다.

($b$) $\bf{B}=\bf{A}-\bf{I}$ 라고 하면 $\bf{B}^T = \bf{A}^T-\bf{I}$ 이다. $\bf{A}$ 의 각 열벡터의 성분의 합이 $1$ 이면 $\bf{A}^T$ 에서는 각 행벡터의 성분의 합이 $1$ 이며 ($a$) 에 따라 $\det(\bf{B}^T)=0$ 이고 행렬식의 성질에 따라 $\det(\bf{B}) = 0$ 이므로 $(\bf{A}-\bf{I})\bf{v}=\bf{0}$ 인 $\bf{v}$ 가 존재한다.
 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4_5_A_25}

#### Axler4th 5.A.25

$u,\,v$ 가 벡터공간 $V$ 에서 정의된 연산자 $L$ 의 고유벡터이고 $u+v$ 도 고유벡터이면 $u$ 와 $v$ 는 같은 고유값을 가짐을 보여라.

:::

</div>

::: {.solution}

$Lu=au,\, Lv=bv,\,, L(u+v)=c(u+v)$ 라고 하자. $a\ne b$ 이면 $\{u,\,v\}$ 는 선형독립이다.  

$$
c(u+v) = L(u+v)= Lu+Lv = au+bv
$$

이므로 $(a-c)u+(b-c)v=0$ 이어야 한데 $u,\,v$ 가 선형독립이므로 $a=b=c$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-LA_axler4_5_A_26}

#### Axler4th 5.A.26

벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 를 생각하자. 모든 $V$ 의 벡터가 $L$ 의 고유벡터라면 $L$ 은 항등연산자의 스칼라곱임을 보여라.

:::

</div>

::: {.solution}

@exr-LA_axler4_5_A_25 에 따라 모든 $V$ 의 벡터는 같은 고유값을 가지는 벡터이다. 이 고유값을 $c$ 라고 하자. 모든 기저에 대해 $L$ 의 행렬형식은 $cI_V$ 이므로 $L$ 은 $cI_V$ 이다. .

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_27}

#### Axler4th_5_A_27

유한차원 벡터공간 $V$ 에서 정의된 연산자 $L$ 을 생각하자. 모든 $V$ 의 부분공간이 $L$ 에 대한 불변부분공간이라면 $L$ 은 항등행렬의 스칼라곱임을 보여라.

:::

</div>

::: {.solution}

$v\in V$ 에 대해 $\text{span}\{v_i\}$ 가 $L$ 에 대한 불변부분공간이므로 모든 $v$ 는 $L$ 의 고유벡터이다. @exr-LA_axler4_5_A_26 에 따라 $L$ 은 항등연산자의 스칼라곱이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_34}

#### Axler4th_5_A_34

유한차원 벡터공간 $V$ 와 $V_0=\{v_1,\ldots,\,v_m: v_i\in V\}$ 에 대해 다음은 동치임을 보여라.

&emsp; ($1$) $V_0$ 는 선형독립이다.

&emsp; ($2$) 어떤 $L\in \mathcal{L}(V)$ 가 존재하여 $v_1,\ldots,\,v_m$ 은 각각 다른 고유값을 갖는 $L$ 의 고유벡터이다. 

:::

</div>

::: {.solution}

($\,\Longleftarrow \,$) @prp-LA_eigenvector_linear_independence.

($\implies$) @prp-LA_linearmap_basis 에 따라 $V_0$ 가 선형독립이므로 $Lv_j = j v_j$ 인 선형연산자가 존재한다.
:::


</br>

## 특성다항식 

### 다항식과 연산자 {#sec-LA_polynomials_and_operators}

::: {.callout-note appearance="minimal"}

::: {#def-LA_power_of_operator}

#### $L^m$

$L\in \mathcal{L}(V)$ 이고 $m$ 이 음이 아닌 정수일 때 다음과 같이 정의된다.

&emsp;($1$) $L^m := \underbrace{L\cdots L}_{m\,\text{times}}$.

&emsp;($2$) $L^0 :=I_V$.

&emsp;($3$) $L$ 이 가역일 때 $L^{-m} := (L^{-1})^m$.

:::

:::

</br>

다음 명제는 쉽게 보일 수 있다.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_power_of_operators}

$L\in \mathcal{L}(V)$ 이며 $m,\,n\in \mathbb{Z}$ 일 때 다음이 성립한다.

$$
L^mL^n = L^{m+n},\qquad (L^m)^n = L^{mn}.
$$

:::

</div> </br>

::: {.callout-note appearance="minimal"}

::: {#def-LA_polynomials_on_operator}

#### 다항식과 연산자

$L\in \mathcal{L}(V)$ 라고 하자. 다항식 $p(t) := a_nt^n + a_{n-1}t^{n-1}+ \cdots + a_1 t + a_0$ 에 대해 $p(L)$ 은 다음과 같이 정의된다.

$$
p(L) := a_n L^n + a_{n-1}L^{n-1} + \cdots a_1 L + a_0 I_V.
$$

:::

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_kernal_and_images_of_operator_under_polynomial}

$p(t)\in \mathbb{F}[t]$ 이고 $V$ 가 $\mathbb{F}$-벡터공간이며 $L\in \mathcal{L}(V)$ 일 때 $\ker (p(L)),\, \text{im}(p(L))$ 은 $L$ 에 대한 불변부분공간이다.

:::

</div>

::: {.proof}

$v\in \ker (p(L))$ 에 대해 $p(L)(Lv)= Lp(L)v =0_V$ 이므로 $Lv \in \ker (p(L))$ 이다. 따라서 $\ker (p(L))$ 은 $L$ 에 대한 불변부분공간이다. 

$u\in \text{im}(p(L))$ 이면 $u=p(L)v$ 인 $v\in V$ 가 존재한다. $Lu = Lp(L)v = p(L)(Lv)$ 이므로 $Lu\in \text{im}(p(L))$ 이다. 따라서 $\text{im}(p(L))$ 은 $L$ 에 대한 부분공간이다. $\square$

:::

</br>

### 특성다항식 {#sec-LA_characteristic_polynomial}

::: {.callout-caution appearance="simple"  icon="false"}
여기부터 이 장의 마지막까지 유한차원 벡터공간에서 생각하기로 한다. 그리고 유한차원 벡터공간과 그 연산자가 아니라 그 행렬표현으로 전개하도록 하겠다. 
:::

 $\lambda$ 를 미지수로 간주하면 $n \times n$ 행렬 $\bf{A}$ 에 대해 $\det (\lambda \bf{I}-\bf{A})$ 는 $\lambda$ 에 대한 $n$ 차 다항식이다. 이 다항식의 근이 존재한다면, 그 근이 고유값이 되며, 이 고유값에 대한 고유벡터가 항상 존재한다는 의미이다. 이 다항식은 매우 중요하기 때문에 특별한 이름이 붙어 있다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_characteristic_polynomial}

#### 행렬의 특성다항식

$\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대한 $p_{\bf{A}}(\lambda) = \det (\lambda \bf{I}-\bf{A})$ 를 **특성 다항식(characteristic polynomial)** 이라 한다.

:::
:::

</br>

다음은 행렬식의 성질을 생각하면 너무나도 당연하다.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_degree_of_characteristic_polynomial}
$\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대한 특성다항식은 $n$ 차 다항식이다.
:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_invariance_of_characteristic_polynomial}
특성 다항식은 닮음 변환에 대해 불변이다. 즉 행렬 $\bf{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 과 가역행렬 $\bf{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $p_{\bf{A}}(\lambda) = p_{\bf{P^{-1}AP}}(\lambda)$ 이다.
:::

</div>

::: {.proof}
$$
\begin{aligned}
\det(\lambda \bf{I}-\bf{P^{-1}AP}) & = \det (\bf{P}^{-1}(\lambda \bf{I}-\bf{A})\bf{P}) \\
& = \det(\bf{P}^{-1}) \det (\lambda \bf{I}-\bf{A}) \det (\bf{P}) \\
&=  \det (\lambda \bf{I}-\bf{A}). &\square
\end{aligned}
$$

:::

</br>

@prp-LA_invariance_of_characteristic_polynomial 는 유한차원 벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 에 대한 특성다항식을 정의 할 수 있게 해 준다. 어떤 기저에 대해서도 $[L]$ 의 특성다항식은 같기 때문에 이것은 연산자 $L$ 에 대한 특성다항식이라고 할 수 있다. 즉 연산자 $L$ 에 대한 특성다항식 $p_L(\lambda)$ 를 정의 할 수 있다. 


::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_characteristic_polynomial_of_operator}

#### 연산자의 특성다항식

$L\in \mathcal{L}(V)$ 일 때 $V$ 의 기저 $\mathcal{B}=(v_1,\ldots,\,v_n)$ 에 대해 $p_L(\lambda) = \det (\lambda I - [L]_\mathcal{B})$ 를 연산자 $L$ 에 대한 특성다항식이라고 하고 $p_L(\lambda)$ 로 표기한다.
:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_eigenvalue_characteristic_polynomial}

$L\in \mathcal{L}(V)$ 에 대해 $\lambda$ 가 $L$ 의 고유값이기 위한 필요충분조건은 $p_L(\lambda)=0$ 인 것이다.
:::

</div>

::: {.proof}
$p_{[L]}(\lambda)=0$ 일 때 $\lambda$ 가 $[L]$ 의 고유값이 되는것은 @thm-LA_eigenvalues_determinant 에서 보였다. $\lambda$ 가 $[L]$ 의 고유값이라면 어떤 벡터 $[v] \ne \bf{0}$ 에 대해 $[Av]=\lambda [v]$ 이므로 $(\lambda I-L)v=0_V$ 이다. 즉 $\text{nullity}(\lambda I-L) >0$ 이므로 $p_L(\lambda)= 0$ 이다. $\square$

:::

</br>

::: {.callout-important appearance="simple" icon="false"}

#### 대수학의 기본정리

대수학의 기본정리는 복소수계수를 갖는 $n$ 차 다항식은 $k$ 중근을 $k$ 개의 근으로 간주한다면 $n$ 개의 근을 가진다는 것을 알려준다. 증명은 이 책의 범위를 벗어나므로 생략한다.

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_existance_of_eigenvector_for_complex_field}
유한차원 $\C$-벡터공간에서정의된 연산자에 대해서 항상 고유벡터가 존재한다. 
:::

</div>

::: {.proof}
대수학의 기본정리에 의해 복소수 영역에서는 항상 특성다항식의 해가 존재하며 @prp-LA_eigenvalue_characteristic_polynomial 에 의해 고유벡터가 존재한다. $\square$
:::

</br>

### 연습문제 {.unnumbered}

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_33}

#### Axler4th 5.A.33

$L\in \mathcal{L}(V)$ 이고 $m$ 이 양의 정수이다. 다음을 보여라.

&emsp;($1$) $L$ 이 단사일 필요충분조건은 $L^m$ 이 단사인 것이다.

&emsp;($2$) $L$ 이 전사일 필요충분조건은 $L^m$ 이 전사인 것이다.

:::

</div>

::: {.soltion}

($1$) $L(u)=0$ 이면 $L^m(u)=0$ 이므로 $\ker L \subset \ker L^m$ 이다. 따라서 $L^m$ 이 단사이면 $L$ 은 단사이다. 이제 $L$ 이 단사임을 가정하자. $u\in \ker L^m$ 이면 $L^mu=0=L(L^{m-1}u)=0_V$ 이므로 $L^{m-1}u=0_V$ 이며 따라서 $u\in \ker L^{m-1}$ 이다. 이것을 계속 반복하면 $u\in \ker L = \{0_V\}$ 이다. 즉 $\ker L^m \subset \ker L = \{0_V\}$ 이므로 $\ker L = \ker L^m = \{0_V\}$ 이다. 즉 $L$ 이 단사이면 $L^m$ 도 단사이다.



($2$) $L$ 이 전사이면 $L^m$ 이 전사임은 자명하다. 이제 $L^m$ 이 전사임을 가정하자. $L$ 이 전사가 아니라면 $x\not\in\im (L)$ 인 $x\in V$ 가 존재하는데 $x\not\in \im (L^m)$ 이므로 $L^m$ 이 전사라는 가정에 모순된다. 따라서 $L^m$ 이 전사이면 $L$ 도 전사이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_40}
#### Axler4th 5.A.40

$L,\,K\in \mathcal{L}(V)$ 이고 $K$ 가 가역이다. $p \in \F[t]$ 일 때

$$
p(KLK^{-1})= Kp(L)K^{-1}
$$

임을 보여라.
:::

</div>

::: {.solution}

$m\in \Z_+$ 일 때 $(KLK^{-1})^m = KL^mK^{-1}$ 임은 쉽게 보일 수 있다. $\displaystyle p(t) = \sum_{m=0}^n c_m t^m$ 에 대해

$$
\begin{aligned}
p(KLK^{-1}) &= \sum_{m=0}^n c_m (KLK^{-1})^m = \sum_{m=0}^n c_m KL^mK^{-1} \\[0.3em]
&= K\left(\sum_{m=0}^n c_m L^m\right)K^{-1} = Kp(L)K^{-1}
\end{aligned}
$$

이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_41}
#### Axler4th 5.A.41

$L\in \mathcal{L}(V)$ 이고 $U$ 가 $L$ 에 대한 $V$ 의 불변부분공간이라고 하자. $p\in \F[t]$ 일 때 $U$ 는 $p(L)$ 에 대한 불변부분공간임을 보여라.
:::

</div>

::: {.solution}

$u\in U$ 일 때 $Lu\in U$ 이다. 따라서 임의의 $m=0,\,1,\ldots$ 에 대해 $L^mu\in U$ 이며 $p(L)U\subset U$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5_A_43}

#### Axler4th 5.A.43

$V$ 는 1보다 큰 차원의 유한차원 벡터공간이며 $L\in \mathcal{L}(V)$ 이다. $\{p(L): p(t) \in \F[t]\} \ne \mathcal{L}(V)$ 임을 보여라.

:::

</div>

::: {.solution}

$\text{nullity}(L) >0$ 이며 $M$ 은 $I$ 의 상수배가 아닌 가역사상이라고 하자. $\ker L \subset \ker L^m$ 이므로 $M \not\in \{p(L): p(t) \in \F[t]\}$. 

:::


</br>

## 블록행렬과 불변부분공간


[블록행렬](ch1_03_determinant.qmd#def-LA_block_matrix)의 대각 부분 행렬이 정사각행렬이라면, 행렬의 모든 대각성분은 부분행렬의 대각성분이 된다. 이를 대각 부분행렬이라 하자. 대각 부분행렬을 제외한 부분행렬이 모두 $0$ 행렬인 경우 **블록 대각 행렬 (block diagonal matrix)** 라 한다. 상삼각 행렬/하삼각 행렬처럼 **블록 상삼각 행렬(block upper triangular matrix)** 와 **블록 하삼각 행렬(block lower triangular matrix)** 를 정의 할 수 있다.



</br>

### 불변 부분공간과 블럭 상삼각행렬

우선 @sec-LA_matrix_transform_by_basis_transform 에서 본 행렬의 닮음 변환을 다시 한번 상기하자. $\mathcal{M}_{n}(\mathbb{F})$ 공간에서 정의된 선형독립인 벡터 $\{\bf{u}_1,\ldots,\, \bf{u}_n\}$ 와 $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 을 생각하자. $\bf{u}_i$ 가 $i$ 번째 열이 된 행렬 $\bf{P} = \begin{bmatrix} \bf{u}_1 & \cdots & \bf{u}_n \end{bmatrix}$ 는 기저를 변환하는 행렬, 즉 닮음변환을 정의하는 행렬이 되며 $\bf{P}^{-1}\bf{AP}$ 는 변환된 기저에서의 선형사상이고 변환행렬 $\bf{P}= \begin{bmatrix} \bf{u}_1 & \cdots & \bf{u}_n\end{bmatrix}$ 가 정의되며 아래 표와 같이 변환된다.

| 원래 기저에서의 행렬표현 | 새로운 기저에서의 행렬표현 |
|:-------:|:------:|
| $\bf{e}_i$ | $\bf{P}^{-1}\bf{e}_i$ |
| $\bf{u}_i$ | $\bf{e}_i$ |
| $\bf{A}$  | $\bf{P}^{-1}\bf{AP}$ |



</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_invariant_subspace_block_upperdiagonal_matrix}

#### 불변부분공간과 블럭상삼각행렬

행렬 $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 불변부분공간이 존재하면 $\bf{A}$ 와 닮은 블럭 상삼각 행렬이 존재한다.

:::

</div>

::: {.proof}

$\mathbb{F}$-벡터공간 $\mathcal{M}_{n}(\mathbb{F})$ 의 어떤 부분공간 $U$ 와 행렬 $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $U$ 가 $\bf{A}$ 에 대한 불변부분공간이라고 하자. $U$ 의 기저 $\{\bf{u}_1,\ldots,\,\bf{u}_m\}$ 를 확장하여 $\mathcal{M}_n(\mathbb{F})$ 의 기저 $\{\bf{u}_1,\ldots,\bf{u}_n\}$ 을 구성했다고 하자. 그렇다면 

$$
\bf{Au}_i = \left\{ \begin{array}{ll} B_{1i}\bf{u}_i + \cdots + B_{mi}\bf{u}_m & 1\le i \le m \\
B_{1i}\bf{u}_i + \cdots + B_{mi}\bf{u}_m + \cdots + B_{ni}\bf{u}_n \qquad & m+1 \le i \le n
\end{array} \right.
$$

이다. 즉 $\{\bf{u}_1,\ldots,\,\bf{u}_m\}$ 를 확장하여 $\mathbb{F}^{n }$ 기저에서는 $\bf{A}$ 로 표현된 변환이 블럭 상삼각행렬이 된다. 즉 $\bf{P} = \begin{bmatrix} \bf{u}_1 & \cdots &\bf{u}_n \end{bmatrix}$ 에 대해 $\bf{P}^{-1}\bf{AP}$ 는 블록 상삼각행렬이다. $\square$

:::


</br>

## 행렬의 상삼각행렬로의 변환

### 상삼각 행렬로 닮음변환되는 행렬

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-LA_upper_triangular_matrix}

정사각 행렬 $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 다음은 동치이다.

&emsp;($1$) $\bf{A}$ 가 어떤 상삼각행렬과 닮음이다.

&emsp;($2$) $\mathcal{M}_{n}(\mathbb{F})$ 의 어떤 기저 $(\bf{v}_1,\ldots,\,\bf{v}_n)$ 가 존재하여 $i=1,\ldots,\,n$ 에 대해 $\bf{Av}_i = \text{span}(\bf{v}_1,\ldots,\,\bf{v}_i)$ 이다.

:::

</div>

::: {.proof}

(1 $\implies$ 2) $\bf{B}=\bf{P}^{-1}\bf{AP}$ 가 상삼각행렬이라고 하자. $\hat{\bf{e}}_1,\ldots,\,\hat{\bf{e}}_n$ 에 대해 
$$
\bf{Be}_i \in \text{span} ( \hat{\bf{e}}_1,\ldots,\,\hat{\bf{e}}_i)
$$
이다. $\bf{v}_i = \bf{P}\hat{\bf{e}}_i$ 라 하자.  $\bf{A}= \bf{PBP}^{-1}$ 이므로,
$$
\bf{Av}_i = \bf{PBP}^{-1}\bf{P}\hat{\bf{e}}_i = \bf{PB}\hat{\bf{e}}_i
$$
이다. 따라서 $\bf{Av}_i \in \text{span}(\bf{v}_1,\ldots,\,\bf{v}_i)$ 이다. 

(2 $\implies$ 1) $\bf{P}=\begin{bmatrix} \bf{v}_1 & \cdots & \bf{v}_n\end{bmatrix}$ 라 하자. $\bf{B}=\bf{P}^{-1}\bf{AP}$ 라 하면
$$
\bf{B}\hat{\bf{e}}_i = \bf{P}^{-1}\bf{AP}\hat{\bf{e}}_i = \bf{P}^{-1} \bf{Av}_i 
$$
이다. $\bf{Av}_i \in \text{span}(\bf{v}_1,\ldots,\,\bf{v}_i)$ 이므로 $\bf{B}\hat{\bf{e}}_i \in \text{span}(\hat{\bf{e}}_1,\ldots,\,\hat{\bf{e}}_i)$ 이다. 즉 $\bf{B}$ 는 상삼각행렬이다. $\square$ 

:::

</br>

### 복소수체에서의 행렬과 상삼각행렬 {#sec-LA_matrix_and_upper_triangula_matrix_over_C}

이제 이 장에서 가장 중요한 결론을 낼 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_uppertriangular_matrix_complex_field}
$\bf{A}\in \mathcal{M}_{n\times n}(\mathbb{C})$ 행렬과 닮은 상삼각 행렬이 존재한다. 
:::

</div>

::: {.proof}
$\bf{A}_n \in \mathcal{M}_{n \times n}(\mathbb{C})$ 이라 하고 $n$ 에 대한 귀납법으로 증명한다. $n=1$ 일 때는 자명하다. $k<n$ 에 대해 위의 명제가 성립한다고 가정하자. 우리는 @thm-LA_existance_of_eigenvector_for_complex_field 를 통해 행렬 $\bf{A}_n$ 에 대한 고유값 $\lambda$ 와 고유벡터 $\bf{v}_1$ 이 존재한다는 것을 안다. $\bf{v}_1$ 을 확장하여 $\mathcal{M}_n(\mathbb{F})$ 의 기저를 구성 할 수 있으며, 이 기저로 변환된  블럭 상삼각행렬을 이룬다 (@prp-LA_invariant_subspace_block_upperdiagonal_matrix). 이 블럭 상삼각 행렬의 1 행과 1 열을 제거한 $(n-1)\times (n-1)$ 행렬은 가정에 의해 어떤 상 삼각 행렬과 닮았다. 따라서 $\bf{A}_n$ 은 어떤 상 삼각행렬과 닮았다. $\square$ 
:::

</br>

## 행렬의 대각화

### 고유공간의 성질 {#sec-LA_properties_of_eigen_space}

우리는 연산자 $L\in\mathcal{L}(V)$ 에 대한 고유공간 $E(\lambda, L)$ 을 @def-LA_eigenvector 에서 정의하였다. 또한 서로 다른 고유값을 갖는 벡터의 집합은 선형독립이라는 것도 안다(@prp-LA_eigenvector_linear_independence). 이제 고유공간에 대해 좀 더 알아보자. 

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">
::: {#prp-sum_of_eigenspace}

$L\in \mathcal{L}(V)$ 이고 $\lambda_1,\,\lambda_2,\ldots,\,\lambda_n$ 이 $L$ 의 고유값일 때, 

$$
E(\lambda_1,L) + \cdots + E(\lambda_m,L) = \bigoplus_{i=1}^m E(\lambda_i,L)
$$

이다. 

:::

</div>

::: {.proof}

임의의 $\lambda_i\ne \lambda_j$ 에 대해 $E(\lambda_i, L) \cap E(\lambda_j,L) = \{0_V\}$ 이다. $\square$
:::


</br>

### 대각화가능 행렬 {#sec-LA_diagonalizable_matrix}


::: {.callout-note appearance="simple" icon="false"}
::: {#def-LA_diagonalizable_matrix}

#### 대각화 가능 행렬

정사각 행렬이 어떤 대각행렬과 닮았다면 그 정사각 행렬을 **대각화 가능 행렬 (Diagonalizable matrix)** 라고 한다.

:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-LA_diagonalizability}

정사각 행렬 $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이 서로 다른 고유값 $\lambda_1,\ldots,\,\lambda_m$ 을 가질 때 다음은 동치이다.


&emsp;($1$) $\bf{A}$ 는 대각화 가능 행렬이다.

&emsp;($2$) $\bf{A}$ 의 고유벡터로 이루어진 $\mathcal{M}_{n}(\mathbb{F})$ 의 기저가 존재한다.

&emsp;($3$) $\mathcal{M}_n (\mathbb{F}) = E(\lambda_1, \bf{A}) \oplus \cdots \oplus E(\lambda_m, \bf{A})$
:::

</div>

::: {.proof}
($1 \implies 2$) 대각 행렬 $\bf{D}$ 에 대해 $\bf{D} = \bf{P}^{-1}\bf{AP}$ 라고 하자. $\bf{D}\hat{\bf{e}}_i = D_{ii}\hat{\bf{e}}_i$ 이므로, 

$$
\bf{APe}_i = \bf{PDe}_i = D_{ii}\bf{Pe}_i
$$


이며, 따라서 $\bf{Pe}_i$  는 $D_{ii}$ 를 고유값으로 갖는 $\bf{A}$ 의 고유벡터이다. $\bf{P}$ 가 가역행렬이므로 $\{\bf{P}\hat{\bf{e}}_1,\ldots,\bf{P}\hat{\bf{e}}_1\}$ 는 $\mathcal{M}_n(\mathbb{F})$ 의 기저이다.

($2 \implies 3$) $(\bf{u}_1,\ldots,\,\bf{u}_n)$ 이 $\bf{A}$ 의 고유벡터이며 $\mathcal{M}_n(\mathbb{F})$ 의 기저일 때 같은 고유값 $\lambda_j$ 를 갖는 $\bf{u}_i$ 들은 $E(\lambda_j, \bf{A})$ 의 기저이다. 임의의 $\lambda_{j_1}\le \lambda_{j_2}$ 일 때 $E(\lambda_{j_1}, \bf{A})\cap E(\lambda_{j_2})= \{\bf{0}\}$ 이므로, $\mathcal{M}_n (\mathbb{F}) = E(\lambda_1, \bf{A}) \oplus \cdots \oplus E(\lambda_m, \bf{A})$ 이다. 


($3 \implies 1$) 각각의 $E(\lambda_i, \bf{A})$ 의 기저벡터를 모아 $(\bf{u}_1,\ldots,\bf{u}_n)$ 을 만들었을 때 $\bf{U} = \begin{bmatrix} \bf{u}_1 & \cdots & \bf{u}_n\end{bmatrix}$ 라 하자. $\bf{U}$ 는 가역이며, $\bf{U}^{-1}\bf{AU}$ 는 대각행렬이다. $\square$


:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-LA_diagoalizability_of_dimV_distinct_eigenvalues_1}

$\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 $n$ 개의 서로 다른 고유값을 가지면 $\bf{A}$ 는 대각화 가능 행렬이다.

:::

</div>

::: {.proof}

@prp-LA_eigenvector_linear_independence 에서 보였듯이 서로 다른 고유값을 갖는 고유벡터는 선형독립이므로 이 $n$ 개의 고유벡터는 $\mathcal{M}_n(\mathbb{F})$ 의 기저이다. 따라서 $\bf{A}$ 는 대각화 가능 행렬이다. $\square$
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-LA_diagoalizability_of_dimV_distinct_eigenvalues_2}

$\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 의 특성다항식 $p_{\bf{A}}$ 가 $n$ 개의 서로 다른 해를 $\mathbb{F}$ 에서 가지면 $\bf{A}$ 는 대각화 가능 행렬이다. 
:::

</div></br>

## 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-linearly_independency_and_distict_eigenvalues}

$\{\bf{v}_1,\ldots,\,\bf{v}_m \} \subset \mathcal{M}_n(\mathbb{F})$ 이 선형독립일 필요충분 조건은 위 벡터들이 서로 다른 고유값을 갖는 고유벡터가 되도록 하는 $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 존재하는 것임을 보여라.

:::

</div>

::: {.solution}

서로 다른 고유값을 갖는 고유벡터의 집합은 선형독립이라는 것을 안다(@prp-LA_eigenvector_linear_independence). 따라서 $\{\bf{v}_1,\ldots,\,\bf{v}_m \}$ 가 선형독립이면 이 벡터들이 각각 다른 고유값을 갖는 고유벡터가 되는 행렬 $\bf{A}$ 가 존재함을 보이면 된다. $\bf{v}_1,\ldots,\,\bf{v}_m$ 을 확장하여 기저 $\{\bf{v}_1,\ldots,\,\bf{v}_n\}$ 을 구성하고 $\bf{P}= \begin{bmatrix} \bf{v}_1 & \cdots & \bf{v}_n\end{bmatrix}$ 라 하자. $\bf{P}^{-1}$ 은 $\bf{v}_i$ 를 표준기저 $\hat{\bf{e}}_i$ 로 변환해주는 연산자이다. 

행렬 $\bf{A}$ 를 $1$ 행 $1$ 열 부터 $m$ 행 $m$ 열 까지는 $A_{ij}= j\delta_{ij}$ 가 되도록 하고 $m+1$ 행 $m+1$ 열부터는 임의의 값을 가지는 블럭대각행렬이라 하자. $\bf{e}_1,\ldots,\,\bf{e}_m$ 은 은 각각 $1,\ldots,m$ 의 고유값을 가지므로 $\bf{PAP}^{-1}$ 은 $\bf{v}_1,\ldots,\bf{v}_m$ 이 각각 $1,\ldots,\,m$ 의 고유값을 갖는 행렬이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_5_B_1}

#### Axler 5.B.1
$\bf{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 어떤 자연수 $n$ 에 대해 $\bf{A}^n=\bf{0}$ 이라고 하자. $\bf{I}_n-\bf{A}$ 는 가역행렬이며 다음이 성립함을 보여라.

$$
(\bf{I}_n-\bf{A})^{-1} = \bf{I}_n+ \bf{A} + \cdots + \bf{A}^{n-1}.
$$

:::

</div>

::: {.solution}

$(\bf{I}_n-\bf{A})(\bf{I}_n + \bf{A} + \cdots + \bf{A}^{n-1}) = \bf{I}_n- \bf{A}^n=\bf{I}_n$ 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_5_b_4}

#### Axler 5.B.4

$\bf{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 $\bf{P}^2=\bf{P}$ 일 때 $\bf{P}$ 를 **projection** 이라고 한다. $\bf{P}$ 가 projection 일 때 $\mathcal{M}_n (\mathbb{F})=(\ker (\bf{P})) \oplus (\text{im}(\bf{P}))$ 임을 보여라.

:::

</div>

::: {.solution}

$\bf{u}\in \ker (\bf{P})\cap \text{im}(\bf{P})$ 라 하자. $\bf{Pu}=\bf{0}$ 이며 $\bf{Pv}=\bf{u}$ 인 $\bf{u}$ 가 존재해야 한다. 그런데 $\bf{P}^2\bf{v} = \bf{Pu}=\bf{0}$ 이며 $\bf{P}^2\bf{v} = \bf{Pv}$ 이므로 $\bf{u}=\bf{0}$ 이다. 즉 $\ker (\bf{P})\cap \text{im}(\bf{P}) = \{\bf{0}\}$ 이다. @thm-LA_rank_nullity 에 의해 $\mathcal{M}_n (\mathbb{F})=(\ker (\bf{P})) \oplus (\text{im}(\bf{P}))$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_5_c_1}

### Axler 5.C.1

$\bf{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 대각화 가능 행렬이면 $\mathcal{M}_n(\mathbb{F})=\ker (\bf{A})\oplus \text{im}(\bf{A})$ 임을 보여라.

:::

</div>

::: {.solution}
$\ker (\bf{A})$ 와 $\text{im}(\bf{A})$ 모두 $\mathcal{M}_n(\mathbb{F})$ 의 부분공간이다. $\bf{A}$ 의 고유벡터로 이루어진 $\mathcal{M}_n (\mathbb{F})$ 의 기저 $\{\bf{u}_1, \ldots,\, \bf{u}_n\}$ 을 생각 할 수 있다. $\bf{x}\in \ker (\bf{A})\cap \text{im}(\bf{A})$ 이라고 하자. $\bf{x}\in \ker (\bf{A})$ 이므로 $\bf{Ax}=\bf{0}$ 이며 $\bf{x}\in \text{im}(\bf{A})$ 이므로 $\bf{Ay}=\bf{x}$ 를 만족하는 $\bf{y}$ 가 존재해야 한다. $\bf{A}$ 가 대각화 가능 행렬이므로 고유값 $\lambda_i$ 를 갖는 고유벡터 $\bf{u}_i$ 가 기저가 되며 따라서 $\bf{y}=\sum_i c_i \bf{u}_i$ 로 표현 할 수 있다. $\bf{Ay} = \sum_i c_i \lambda_i \bf{u}_i = \bf{x}$, $\bf{A}^2\bf{y} = \sum_i c_i \lambda_i^2 \bf{u}_i = \bf{0}$ 이므로 $\bf{y}$ 는 $\bf{A}$ 에 대해 고유값이 $0$ 인 벡터의 선형결합이다. 따라서 $\bf{y}\in \ker (\bf{A})$ 이며 $\bf{x}=\bf{0}$ 이다. 

@thm-LA_rank_nullity 에 의해 $n=\text{nullity}(\bf{A})+\text{rank}(\bf{A})$ 이며 $\ker (\bf{A}) \cap \text{im}(\bf{A})=\{\bf{0}\}$ 이므로 $\mathcal{M}_n(\mathbb{F})=\ker (\bf{A})\oplus \text{im}(\bf{A})$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axer_5_c_3}

#### Axler 5.C.3

$\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 다음 세 명제는 동치임을 보여라.

&emsp;($1$) $\mathcal{M}_{n}(\mathbb{F}) = \ker (\bf{A})\oplus \text{im}(\bf{A})$.

&emsp;($2$) $\mathcal{M}_{n}(\mathbb{F}) = \ker (\bf{A}) + \text{im}(\bf{A})$.

&emsp;($3$) $\ker (\bf{A}) \cap \text{im}(\bf{A}) = \{\bf{0}\}$.

:::

</div>

::: {.solution}

($1\implies 2$) 가정에 의해 $\ker (\bf{A})\cap \text{im}(\bf{A})= \{\bf{0}\}$ 이다. @prp-LA_condition_for_direct_sum 의해 $\ker (\bf{A}) + \text{im}(\bf{A}) = \ker (\bf{A})\oplus \text{im}(\bf{A}) = \mathcal{M}_{n}(\mathbb{F})$ 이다.

($2\implies 3$) @thm-LA_rank_nullity 에 의해 $\ker (\bf{A}) \cap \text{im}(\bf{A}) = \{\bf{0}\}$ 이다. 

($3 \implies 1$) $\ker (\bf{A})$ 와 $\text{im}(\bf{A})$ 는 $\mathcal{M}_n(\mathbb{F})$ 의 부분공간이며 가정에 의해 $\ker (\bf{A}) + \text{im}(\bf{A}) = \ker (\bf{A}) \oplus \text{im}(\bf{A})$ 도 부분공간이다. @thm-LA_rank_nullity 에 의해 $\mathcal{M}_{n}(\mathbb{F}) = \ker (\bf{A})\oplus \text{im}(\bf{A})$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_5_c_5}

#### Axler 5.C.5

$\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{C})$ 일 때 다음이 동치임을 보이시오.

&emsp;($1$) $\bf{A}$ 는 대각화 가능 행렬이다.

&emsp;($2$) 모든 $\lambda \in \mathbb{C}$ 에 대해 $\mathcal{M}_{n}(\mathbb{C}) = \ker (\bf{A}-\lambda \bf{I}_n) \oplus \text{im}(\bf{A}-\lambda \bf{I}_n)$

:::

</div>

::: {.solution}
($1 \implies 2$) $\bf{A}\in \mathcal{M}_{n \times n}(\mathbb{C})$ 일 때

$$
\begin{aligned}
\bf{Au}=\lambda_u\bf{u} \iff (\bf{A}-\lambda \bf{I}_n)\bf{u} = (\lambda_u -\lambda)\bf{u}
\end{aligned}
$$

이므로 $\bf{u}$ 가 $\bf{A}$ 의 고유벡터인것과 $\bf{A}-\lambda\bf{I}_n$ 의 고유벡터인것은 동치임을 안다. 따라서 $\bf{A}$ 가 대각화 가능인것과 임의의 $\lambda\in \mathbb{C}$ 에 대해 $\bf{A}-\lambda \bf{I}_n$ 이 대각화 가능인것은 동치이다. $\bf{A}-\lambda\bf{I}_n$ 이 대각화 가능이므로 @exr-axler_5_c_1 에서 보였듯이 $\mathcal{M}_n(\mathbb{C}) = \ker (\bf{A}-\lambda\bf{I}_n) \oplus \text{im} (\bf{A}-\lambda\bf{I}_n)$ 이다. 


($2 \implies 1$) 정해진 $\lambda_1\in \mathbb{C}$ 에 대해 $(\bf{u}_i, \ldots,\,\bf{u}_m)$ 이 $\ker(\bf{A}-\lambda_1 \bf{I}_n)$ 의 기저라고하자. $(\bf{v}_1,\ldots,\,\bf{v}_{n-m})$ 를 $\text{im}(\bf{A}-\lambda_1\bf{I}_n)$ 의 기저라고 하자. 

$$
\bf{U} = \begin{bmatrix} \bf{u}_1 & \cdots & \bf{u}_m & \bf{v}_1 & \cdots & \bf{v}_{n-m}\end{bmatrix}
$$

라고 하면 $\bf{U}$ 은 가역행렬이며 $\bf{U}^{-1}\bf{AU}$ 은 블럭대각행렬이다. 이 때 1행 1열부터 $m$ 행 $m$ 열까지는 대각행렬이라는 것을 알 수 있다. 또한 $\bf{Uv}_j$ 는 1 행부터 $m$ 행 까지의 값이 $0$ 이다.

우리는 모든 복소 행렬은 고유값을 가진다는 것을 알고 있다(@thm-LA_existance_of_eigenvector_for_complex_field). 이것을 이용하여 $n$ 에 대한 induction 을 통해 증명하자. $n=1$ 일 때는 자명하다. 이제 $n$ 보다 작은 양의 정수에 대해 성립함을 가정하자. $\bf{A}$ 는 고유값 $\lambda_1$ 을 가지며 따라서 앞서의 과정에 따라 블럭대각화를 할 수 있다. $\dim(E(\lambda_1, \bf{A}))=m$ 인데 $\bf{U}^{-1}\bf{AU}$ 에서 1 행 1열부터 $m$ 행 $m$ 열 까지를 $0$ 으로 만든 행렬을 $\bf{A}_1$ 이라고 하자. 

이제 모든 $\lambda\in\mathbb{C}$ 에 대해 $\text{im}(\bf{A}_1-\lambda\bf{I}_n) = \ker (\bf{A}_1-\lambda \bf{I}_n) \oplus \text{im}(\bf{A}_1-\lambda \bf{I}_n)$ 임을 보이자. @exr-axer_5_c_3 에 따라 $\ker (\bf{A}_1-\lambda \bf{I}_n) \cap \text{im}(\bf{A}_1-\lambda \bf{I}_n) =\{\bf{0}\}$ 이라는 것을 보이면 된다. 그런데 $\ker (\bf{A}_1-\lambda \bf{I}_n) \in \ker  (\bf{A}-\lambda \bf{I}_n)$ 이며 $\text{im}(\bf{A}_1-\lambda \bf{I}_n) \subset \text{im}(\bf{A}-\lambda \bf{I}_n)$ 이므로 $\ker (\bf{A}_1-\lambda \bf{I}_n) \cap \text{im}(\bf{A}_1-\lambda \bf{I}_n) =\{\bf{0}\}$ 이다. Induction 의 가정에 따라 $\bf{A}_1$ 이 대각화 가능이며 따라서 $\bf{A}$ 는 대각화 가능이다. $\square$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_5_c_6}

#### Axler 5.C.6

$\bf{A},\, \bf{B}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이고 $\bf{A}$ 가 $n$ 개의 서로 다른 고유값을 가지며 $\bf{B}$ 가 $\bf{A}$ 와 같은 고유벡터를 가질 때 $\bf{AB}=\bf{BA}$ 임을 보여라.

:::

</div>

::: {.solution}

$(\bf{u}_1,\ldots,\bf{u}_n)$ 을 각각 $\lambda_i$ 의 고유값을 갖는 $\bf{A}$ 의 고유벡터라고 하면 이 벡터는 각각 다른 고유값을 가지므로 선형독립이며, 따라서 기저이다. $\bf{U} = \begin{bmatrix} \bf{u}_1 & \cdots & \bf{u}_n\end{bmatrix}$ 에 대해 $\bf{U}^{-1}\bf{AU}$ 와 $\bf{U}^{-1}\bf{BU}$ 는 각각 고유값을 대각성분으로 갖는 대각행렬이며, 두 대각행렬의 곱은 순서에 관계 없이 같으므로, 

$$
(\bf{U}^{-1}\bf{AU}) (\bf{U}^{-1}\bf{BU})=(\bf{U}^{-1}\bf{BU}) (\bf{U}^{-1}\bf{AU})
$$

이다. 이로부터 $\bf{AB}=\bf{BA}$ 를 얻는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler_5_c_16}

#### 피보나치 수열

수열 $\langle f_n \rangle$ 이 다음과 같이 정의되었다. (이 수열을 피보나치 수열 (Fibonacci sequence) 이라고 한다.)

$$
f_1 = 1,\qquad f_2=1,\qquad f_{n+2} = f_{n+1} +f_n.
$$

$\bf{F} = \begin{bmatrix} 0 & 1 \\ 1 & 1\end{bmatrix}$ 에 대해 다음을 보여라.

&emsp;($1$) $\bf{F}^n \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \begin{bmatrix} f_n \\ f_{n+1}\end{bmatrix}$ 이다.

&emsp;($2$) $\bf{F}$ 의 고유값을 구하라.

&emsp;($3$) $\bf{F}$ 의 고유벡터로 이루어진 $\mathcal{M}_{2}(\mathbb{R})$ 의 기저를 구하라.

&emsp;($4$) ($3$) 의 해를 이용하여 $\bf{F}^{n} \begin{bmatrix}0 \\ 1 \end{bmatrix}$ 를 계산하라. 

&emsp;($5$) ($4$) 를 이용하여 각각의 양의 정수 $n$ 에 대해 $f_n$ 은 $\dfrac{1}{\sqrt{5}} \left(\dfrac{1+\sqrt{5}}{2}\right)^n$ 에 가장 가까운 정수임을 보여라.
:::

</div>

::: {.solution}

($1$) $n=1$ 일 경우로부터 $f_1=1,\, f_2=2$ 임을 안다. $\bf{F}^n \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \begin{bmatrix} f_n \\ f_{n+1}\end{bmatrix}$ 라고 가정하자.

$$
\bf{F}^{n+1} \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \bf{F}\begin{bmatrix} f_n \\ f_{n+1}\end{bmatrix} = \begin {bmatrix} f_{n+1} \\ f_{n}+f_{n+1}= f_{n+2}\end{bmatrix}
$$

이다. 

($2$) $\det (\lambda \bf{I}_2-\bf{F})=0$ 를 통해 고유값 $\lambda_1 = \dfrac{1+\sqrt{5}}{2}$ 와 $\lambda_2 = \dfrac{1-\sqrt{5}}{2}$ 를 얻을 수 있다.

($3$) $\bf{Fu}_i = \lambda_i \bf{u}_i$ 를 통해, $\bf{u}_1 = \begin{bmatrix}1 \\ \frac{1+\sqrt{5}}2\end{bmatrix}$, $\bf{u}_2 = \begin{bmatrix}1 \\ \frac{1-\sqrt{5}}{2}\end{bmatrix}$ 를 얻으며 둘은 선형독립이므로 $\mathcal{M}_2(\mathbb{R})$ 의 기저이다.

($4$) $\begin{bmatrix} 0 \\ 1 \end{bmatrix} = \dfrac{1}{\sqrt{5}}\left(\bf{u}_1 -\bf{u}_2\right)$ 이며 $\bf{F}^{n}(\dfrac{1}{\sqrt{5}}\bf{u}_1-\dfrac{1}{\sqrt{5}}\bf{u}_2) = \dfrac{1}{\sqrt{5}} (\lambda_1)^n \bf{u}_1 - \dfrac{1}{\sqrt{5}}(\lambda_2)^n \bf{u}_2$ 이다. 즉, 

$$
\bf{F}^n\begin{bmatrix}0 \\ 1 \end{bmatrix} = \dfrac{1}{\sqrt{5}}\left[{\lambda_1}^n \bf{u}_1 - {\lambda_2}^n \bf{u}_2\right] = \dfrac{1}{\sqrt{5}} \begin{bmatrix} \left(\dfrac{1+\sqrt{5}}{2}\right)^n - \left(\dfrac{1-\sqrt{5}}{2}\right)^n  \\ \left(\dfrac{1+\sqrt{5}}{2}\right)^{n+1}  - \left(\dfrac{1-\sqrt{5}}{2}\right)^{n+1} \end{bmatrix} 
$$

이다. 따라서 $f_n =\dfrac{1}{\sqrt{5}} \left[ \left(\dfrac{1+\sqrt{5}}{2}\right)^n - \left(\dfrac{1-\sqrt{5}}{2}\right)^n\right]$ 이다.

($5$) $f_n$ 은 정의에 의해 항상 자연수이다. 또한 $\left|\dfrac{1}{\sqrt{5}}\left(\dfrac{1-\sqrt{5}}{2}\right)^n\right| < 0.277$ 이다. $a,\,b\in \mathbb{R},\, n\in \mathbb{Z}_+$ 에 대해 $a+b=n$ 이며 $|b|<0.3$ 이라면 $|n-a|<0.3$ 이므로 $n$ 은 $a$ 에 가장 가까운 정수 일 수 밖에 없다. 따라서 $f_n$ 은 $\dfrac{1}{\sqrt{5}}\left(\dfrac{1+\sqrt{5}}{2}\right)^n$ 에 가장 가까운 정수일 수 밖에 없다.

::: 