project:
  type: book
  output-dir : docs

book:
  title: "대수학"
  author: "Yebinpapa"
  # language: _language-ko_custom.yml
  date: "3/8/2023"
  page-navigation: true
  
  chapters:
    - index.qmd
    - part: src/part1/part1.qmd
      chapters:
        - src/part1/ch1_01_vectorspace.qmd
        - src/part1/ch1_02_linear_map.qmd
        - src/part1/ch1_03_determinant.qmd
        # - src/part1/ch1_04_gauss_jordan_elimination.qmd
        # - src/part1/ch1_05_matrix.qmd
        - src/part1/ch1_06_eigenvalue.qmd
        - src/part1/ch1_07_innerproduct.qmd
        - src/part1/ch1_08_operators_on_innerproduct_space.qmd
        - src/part1/ch1_09_spectrum_theorem.qmd
        - src/part1/ch1_10_svd.qmd
    - part: src/part2/part2.qmd
      chapters: 
        - src/part2/ch2_01_groups.qmd
        - src/part2/ch2_02_homomorphisms.qmd
        - src/part2/ch2_03_normal_subgroup.qmd
        - src/part2/ch2_04_symmetry.qmd
    - part: src/part3/part3.qmd
      chapters:
        - src/part3/quotient_space.qmd
        - src/part3/dual_space.qmd
        - src/part3/bilinear_form.qmd
        - src/part3/laplacian_form_of_determinant.qmd
        - src/part3/generalized_inverse.qmd
        - src/part3/characteristic_polynomial.qmd
        - src/part3/generalized_eigenspace.qmd


        - src/part3/tensor_product.qmd
        # - src/part3/jordan_form.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fontsize: 0.9em
    toc: true
    #html-math-method: mathml #to be changed to mathjax
  # pdf:
  #   documentclass: scrreprt



