---
title: "군에서의 준동형사상과 동형사상"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

</br>

## 준 동형사상 

### 준 동형 사상 {#sec-MA_group_homomorphsm}

[어떤 집합과 집합에서의 연산이 잘 정의되어 있을때 둘을 같이 묶어서 대수적 구조(algebraic structure) 라고 한다. 대표적인 우리는 이미 체(field), 벡터공간(vector space), 군(groups)이라는 대수적 구조가 존재한다는 것을 알고 있다. 준동형사상은 대수적 구조 사이에 대수적 구조의 연산을 보존하는 함수를 통칭한다. 그리고 이 준동형사상이 전단사일 경우에는 동형사상(isomorphism) 이라고 한다. 우리는 이미 @def-LA_isomorphism_in_vector_space 에서 벡터공간에서의 동형사상에 대해 다루었다. 당연히 군에 대해서도 동형사상이 매우 중요하며 앞으로 나올 것이다.]{.aside}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-MA_homomorphisms_in_groups}
#### 준동형사상


군 $G,\,G'$ 에 대해 함수 $\varphi :G \to G'$ 이 모든 $a,\,b\in G$ 에 대해

$$
\varphi(ab) = \varphi(a)\varphi(b)
$$

일 때 $\varphi$ 를 **준동형사상(homomophism)** 이라고 한다. 또한 선형사상에서와 같이 $\ker \varphi$ 와 $\text{im}\,\varphi$ 를 다음과 같이 정의한다.

$$
\begin{aligned}
\ker (\varphi) &= \{x\in G: \varphi (x) = 1_{G'}\}, \\
\text{im} (\varphi) &= \{\varphi(x) : x\in G\}.
\end{aligned}
$$

$G$ 에서 $G'$ 으로의 준 동형사상의 집합을 $\text{Hom}\, (G,G')$ 이라고 쓴다. 자기 자신으로의 준동형사상일 경우는 $\text{Hom}\, (G)$ 라고 한다.

:::
:::

</br>
<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_homomorphism1}

$\varphi :G \to G'$ 이 $\varphi(g)=1_{G'}$ 일 때 $\varphi$ 를 **사소한 준동형사상 (trivial homomorphism)**이라고 한다. $H \le G$ 일 때 $\psi: H \to G$ 가 포함사상(inclusion map) $\psi (h) = h$ 이라면 $\psi$ 도 준동형사상이다.

:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_properties_of_homomorphism}
$\varphi :G \to G'$ 이 준동형사상일 때 다음이 성립한다.

&emsp;($1$) $a_1,\ldots,\,a_k \in G$ 에 대해 $\varphi(a_1\cdots a_k) = \varphi(a_1)\cdots \varphi(a_k)$ 이다.

&emsp;($2$) $\varphi(1_G)=1_{G'}$ 이다.

&emsp;($3$) $\varphi(a^{-1}) =  (\varphi(a))^{-1}$ 이다.

:::

</div></br>

::: {.proof}
($1$) 은 induction 으로 보일 수 있다.

($2$) $\varphi(1_G)= \varphi(1_G 1_G) = \varphi(1_G)\varphi(1_G)$ 이므로 $\varphi(1_G)=1_{G'}$ 이다.  

($3$) $1_{G'} = \varphi(1_G) = \varphi(aa^{-1}) = \varphi(a)\varphi(a^{-1})$ 이므로 $\varphi(a^{-1})=(\varphi(a))^{-1}$ 이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_kernel_and_images_of_group}

준동형사상 $\varphi : G\to G'$ 에 대해 $\ker \varphi$ 는 $G$ 의 부분군이며 $\text{im}\, \varphi$ 는 $G'$ 의 부분군이다.

:::

</div></br>

::: {.proof}
$\ker \varphi \le G$ 임을 보이자. $a,\, b\in \ker \varphi$ 이면 $\varphi(ab)= \varphi (a)\varphi (b) = 1 \cdot 1 =1$ 이므로 $ab\in \ker \varphi$ 이다. 즉 $\ker \varphi$ 는 연산에 대해 닫혀 있다. 

$1\in \ker \varphi$ 이며 $a\in \ker \varphi$ 일 때 $1 = \varphi (1)= \varphi (aa^{-1}) = \varphi(a) \varphi(a^{-1}) = \varphi(a^{-1})$ 이므로 $a^{-1}\in \ker \varphi$ 이다. 따라서 $\ker \varphi \le G$ 이다. 

이제 $\text{im}\, \varphi \le G'$ 임을 보이자. $x',\,y' \in \text{im}\,\varphi$ 라면 어떤 $x,\,y\in G$ 에 대해 $x'=\varphi (x),\, y'=\varphi (y)$ 이다. $\varphi(xy)=x'y' \in \text{im}\,\varphi$ 이므로 $\text{im}\,\varphi$ 는 연산에 대해 닫혀 있다. $\varphi(1_G)=1_{G'}\in \text{im}\,\varphi$ 이다. $x'\in \text{im}\,\varphi$ 이면 어떤 $x\in G$ 에 대해 $x'=\varphi(x)$ 이며 $\varphi(x^{-1})=(x')^{-1}\in \text{im}\,\varphi$ 이므로 $\text{im}\, \varphi \le G'$ 이다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_5_1}

#### Artin 2.5.1

$\varphi \in \text{Hom}\,(G,\,G')$ 이 전사인 준동형사상이라고 하자. $G$ 가 순환군이면 $G'$ 도 순환군임을 보이시오. $G$ 가 아벨군이면 $G'$ 도 아벨군임을 보이시오.

:::

</div></br>

::: {.solution}

$G=\langle g\rangle$ 이라 하자. $\varphi$ 가 전사이므로 임의의 $y\in G'$ 에 대해 $\varphi (x)=y$ 인 $x\in G$ 가 존재하며 $G$ 가 순환군이므로 어떤 자연수 $n$ 에 대해 $x=g^n$ 이며 $y = (\varphi (g))^n$ 이다. 즉 $G' = \langle \varphi(g) \rangle$ 이다.

$G$ 가 아벨군이라 하자. 임의의 $y_1,\,y_2\in G'$ 에 대해 $\varphi(x_1)=y_1,\, \varphi (x_2)=y_2$ 를 만족하는 $x_1,\,x_2\in G$ 가 존재한다.

$$
y_1y_2 = \varphi (x_1x_2)=\varphi(x_2x_1)= y_2y_1
$$

이므로 $G'$ 은 아벨군이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_5_3}

#### Artin 2.5.3

$U$ 는 $A=\begin{bmatrix} a& b \\ 0 & d\end{bmatrix}$ 꼴의 $2\times 2$ 가역행렬로 이루어진 군이며 $\varphi : U \to \mathbb{R}^\times$ 는 $A \rightsquigarrow a^2$ 인 함수이다. $\varphi$ 는 준동형사상임을 보이고 $\ker \varphi$ 와 $\text{im}\,\varphi$ 를 구하시오.

:::

</div></br>

::: {.solution}

$1_U = \begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix}$ 이다. $U$ 가 군일 조건은 $ad\ne 0$ 이다. 

$$
\begin{aligned}
\varphi \left(\begin{bmatrix} a& b \\ 0 & d\end{bmatrix} \begin{bmatrix} a' & b' \\ 0 & d'\end{bmatrix}\right) & = \varphi \left(\begin{bmatrix} aa' & ab'+bd' \\ 0 & dd'\end{bmatrix}\right) \\
&= (aa')^2 = a^2 a'^2 = \varphi \left(\begin{bmatrix} a& b \\ 0 & d\end{bmatrix}\right) \varphi \left( \begin{bmatrix} a' & b' \\ 0 & d'\end{bmatrix}\right)
\end{aligned}
$$

이므로 $\varphi$ 는 준동형사상이다. 또한 $\mathbb{R}^\times$ 의 항등원은 $1$ 이므로

$$
\begin{aligned}
\ker \varphi &= \left\{ \begin{bmatrix} 1 & b \\ 0 & d\end{bmatrix} : b\in \mathbb{R},\, d\in \mathbb{R}-\{0\}\right\}, \\
\text{im}\, \varphi &= \{x\in \mathbb{R}: x>0\}
\end{aligned}
$$

이다. 

:::

</br>


## 잉여류 (Cosets) 와 라그랑쥬 정리

### 잉여류 {#sec-MA_cosets}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-patt2_osets}
#### 잉여류

군 $G$ 와 그 부분군 $H$, 그리고 $G$ 의 원소 $a$ 에 대해

$$
aH = \{ah:h\in H\}
$$

를 $G$ 에서의 $H$ 의 **왼쪽 잉여류 (left coset)** 이라 한다. 또한, 

$$
Ha = \{ha : h \in H\}
$$

를 **오른쪽 잉여류 (right coset)** 이라고 한다.

[앞으로 잉여류를 이용하여 여러가지를 증명하는데 교과서마다 왼쪽 잉여류를 주로 사용하기도 하고(Artin 등), 오른쪽 잉여류를 주로 사용하기도 한다(Herstein 등). 여기서는 특별히 방향을 지정하지 않았다면 잉여류라고 할 때 왼쪽 잉여류를 말한다.]{.aside}
:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_cosets}

$H\le G$ 이며 $a,\,b\in G$ 에 대해 다음 명제들은 동치이다.

&emsp; ($1$) $a^{-1}b \in H$, 

&emsp; ($2$) $b\in aH$,

&emsp; ($3$) $aH = bH$.

:::

</div></br>

::: {.proof}

($1 \implies 2$) $a^{-1}b=h\in H$ 이면  $b=ah \in aH$.

($2 \implies 3$) $h_1\in H$ 에 대해 $b=ah_1$ 이면 $bh=ah_1h \in aH$ 이므로 $bH\subset aH$ 이다. $ah=bh_1^{-1}h\in bH$ 이므로 $aH \subset bH$ 이다. 즉 $aH=bH$ 이다. 

($3 \implies 1$) $ah_1=bh_2$ 이면 $a^{-1}b=h_1h_2^{-1}\in H$ 이다. $\square$ 

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_kernel_and_image}

$\varphi \in \text{Hom}(G, G')$ 이며 $K=\ker \varphi$ 일 때 $g \in \varphi^{-1}(\{g'\})$ 이라면 $\varphi^{-1}(\{g'\}) = gK$ 이다.

:::

</div></br>

::: {.proof}

$k\in K$ 이면 $\varphi (gk)=\varphi(g)\varphi(k) = g$ 이므로 $gK \subset \varphi^{-1}(\{g'\})$ 이다. $x\in \varphi^{-1}(\{g'\})$ 이면 $\varphi (g^{-1}x) = \varphi(g^{-1})\varphi(x)=(g')^{-1}g=1_{G'}$ 이므로 $g^{-1}x \in \ker \varphi$ 이다. @prp-MA_cosets 에 따라 $x\in gK$ 이므로 $\varphi^{-1}(\{g'\}) \subset gK$. 따라서 $gK = \varphi^{-1}(\{g'\})$. $\square$

:::


</br>

이로부터 다음 따름정리를 알 수 있다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-MA_cosets}

$\varphi \in \text{Hom}\, (G,G')$ 이 단사일 필요충분 조건은 $\ker \varphi = \{1_G\}$ 인 것이다.

:::

</div></br>

### 라그랑쥬 정리 {#sec-lagrange_theorem}

::: {#prp-MA_properties_of_coset}

$H\le G$ 일 때 $H$ 의 두 왼쪽 잉여류는 같거나 교집합이 공집합이다.

:::

::: {.proof}

$a,\,b \in G$ 에 대해 $x\in aH \cap bH$ 라 하자. 어떤 $h_1,\,h_2\in H$ 에 대해 $x=ah_1=bh_2$ 이며, 따라서 $a^{-1}b=h_1h_2^{-1}\in H$ 이므로 @prp-MA_cosets 에 따라 $aH=bH$ 이다. 

:::

</br>

군 $G$ 의 왼쪽 잉여류의 집합을 생각하자. $g\in G$ 에 대해 $g\in gH$ 이므로 모든 $G$ 의 원소는 최소한 하나의 왼쪽 잉여류에 포함된다. 또한 @prp-MA_properties_of_coset 에 의해 두 잉여류는 같거나 그 교집합이 공집합이다. 이로부터 우리는 다음과 같은 결론을 얻는다.

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_partiotion_by_cosets}

$H\le G$ 일 때 $H$ 에 의한 잉여류의 집합은 $G$ 를 분할한다.
:::

</div></br>

이제 각 잉여류의 크기에 대해 다음이 성립한다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_order_of_cosets}

$H\le G$ 일 때 $H$ 에 의한 두 잉여류 사이에 전단사 함수가 존재한다.
:::

</div></br>

::: {.proof}

함수 $f:aH \to bH$ 를 $f(x) = ba^{-1}x$ 로 정의하자. $bh\in bH$ 에 대해 $f(ah)=bh$ 이므로 $f$ 는 전사이다. $ba^{-1}x_1 = ba^{-1}x_2$ 이면 제거규칙에 의해 $x_1=x_2$ 이므로 $f$ 는 단사이다. $\square$

:::

</br>

$H\le G$ 라면 $G$ 는 $H$ 의 잉여류의 집합으로 분할 할 수 있으며, $H$ 의 잉여류 사이에는 일대일 대응관계가 존재하기 때문에 $G$ 가 유한군이라면 $|G|/|H|$ 는 $H$ 의 서로 다른 잉여류의 갯수가 된다. 이 때 $|G|/|H|$ 를 $G$ 에서의 $H$ 의 **인덱스(index)** 라고 하고 $[G:H]$ 라고 쓴다. 우리는 이로부터 다음과 같은 중요한 결론을 얻는다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_lagrange_theorem_for_subgrous}

#### 라그랑쥬 정리

유한군 $G$ 에 대해 $H \le G$ 일 때 $|H|$ 는 $|G|$ 를 나눈다. 
:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-MA_order_of_group_element}

유한군 $G$ 에 대해 $g\in G$ 일 때 $o(g)$ 는 $|G|$ 를 나눈다.
:::

</div></br>

::: {.proof}

$o(g) = |\langle g \rangle |$ 이며 $\langle g\rangle \le G$ 이다. $\square$

:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-prime_order_group}

군 $G$ 의 order 가 소수 $p$ 이면 $G$ 는 항등원이 아닌 $g\in G$ 에 의해 생성되는 순환군이다.
:::

</div></br>

::: {.proof}

$|G|=p$ 가 소수이면 $|G|$ 의 진부분군이 존재하지 않는다. 따라서 $G$ 는 계수가 $p$ 인 $g\in G$ 에 의한 순환군인데 $o(g)$ 가 소수이면 $\langle g\rangle$ $1_G$ 가 아닌 모든 원소의 계수도 $p$ 이다. 따라서 $1_G$ 가 아닌 $g\in G$ 에 의한 순환군이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_orders_in_group_homomorphism}

유한군 $G,\,G'$ 에 대해 $\varphi \in \text{Hom}\,(G,G')$ 일 때 다음이 성립한다. 

&emsp; ($1$) $|G| = |\ker \varphi| \cdot | \text{im}\, \varphi|$, 

&emsp; ($2$) $|\text{im}(\varphi)|$ 는 $|G'|$ 을 나눈다.

:::

</div></br>

::: {.proof}

($1$) @prp-MA_kernel_and_image 와 라그랑쥬 정리(@thm-MA_lagrange_theorem_for_subgrous) 를 보라.

($2$) $\text{im}(\varphi) \le G'$ 이므로 자명하다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_multiplicative_properties_of_the_index}

유한군 $G$ 에 대해 $K \le H \le G$ 일 때 $[G:K]=[G:H][H:K]$ 이다.

:::

</div></br>

::: {.proof}
trivial. 
:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_2}
#### Artin 2.8.2

$\mathbb{R}^m$ 과 이 집합에서의 덧셈을 생각하면 $\mathbb{R}^m$ 은 군이다. $W$ 을 homogeneous 한 선형방정식 $Ax=0$ 의 근의 집합이라고 하자. Inhomogeneous 한 선형 시스템 $Ax=b$ 의 해는 공집합이거나 $W$ 의 (덧셈 연산에 대한) cosets 임을 보이시오.

:::

</div></br>

::: {.solution}
$Ax=b$ 의 해의 집합 $V \ne \varnothing$ 이라 하자. $y\in V$ 라면 각각의 $x\in W$ 에 대해 $A(x+y)=b$ 이므로 $x+y\in V$ 이다. 즉 $W+y \subset V$ 이다. 임의의 $v\in V$ 에 대해 $A(v-y)=0$ 이므로 $v-y\in W$ 이다. 따라서 $V\subset W+y$ 이므로 $W+y = V$ 이다. 

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_3}

#### Artin 2.8.3 

Order 가 소수 $p$ 의 승수인 군은 order 가 $p$ 인 원소를 포함하는가? 

:::

</div></br>

::: {.solution}

$|G|=p^m$ 이라 하자. $1_G$ 가 아닌 $G$ 의 원소 $g$ 를 선택한다. $o(g) = p^n$ 이라면 $o\left(g^{p^{n-1}}\right) = p$ 이다. 
:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_4}

#### Artin 2.8.4
Order 35 인 군은 order 5 나 order 7 원소를 포함하는가?

:::

</div></br>

::: {.solution}

$|G|=35$ 이며 순환군이라면, 즉 $G=\langle g \rangle$ 이라면 $o(g^5)=7$, $o(g^7)=5$ 이다. 이제 순환군이 아닌 order 35 군을 생각하자. $G$ 의 항등원이 아닌 모든 원소는 order 가 5 이거나 7이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_6}
#### Artin 2.8.6
$\varphi \in \text{Hom}(G,\,G')$ 이며 $|G|=18$, $|G'|=15$ 이다. $\phi$ 가 trivial homomorphism 이 아닐 때 $\ker \varphi$ 의 order 는 무엇인가?

:::

</div></br>

::: {.solution}

$|G|=|\ker \varphi| |\text{im}\, \varphi |$ 이며 $|\text{im}\, \varphi |{\large \mid} |G'|$ 이므로 $\ker \varphi|$ 가 될 수 있는 수는 $6$ 뿐이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_7}
#### Artin 2.8.7
군 $G$ 에 대해 $|G|=22$ 이며 $x,\,y\in G$ 에 대해 $x \ne 1_G$ 이며 $y$ 는 power of $x$ 가 아니라고 하자. $x$ 와 $y$ 에 의해 생성되는 군은 $G$ 임을 보여라.

:::

</div></br>

::: {.solution}

$o(x)$ 는 2, 11, 22 중의 하나이다. $o(x)=22$ 라면 $y\in \langle x\rangle$ 이므로 가정에 모순된다. $H$ fmf $x$ 에 의해 생성되는 부분군이라고 하고 $I$ 를 $x$ 와 $y$ 에 의해 생성되는 부분군이라고 하자. $H \le I \le G$ 이며 $|H|<|I|\le |G|$ 이다. $|H|=2$ 이면 $|I|=22$ 만 가능하며 $|H|=11$ 이어도 $|I|=22$ 만 가능하다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_9}
#### Artin 2.8.9

$|G|$ 가 유한군이며 함수 $\phi : G \to G$ 가 $\phi(x)=x^2$ 로 정의되었을 때 $\phi$ 가 자기동형사상일 조건은 무엇인가?

:::

</div></br>

::: {.solution}

$x,\,y\in G$ 에 대해 $\phi(xy)=xyxy$ 이며 $\phi(x)\phi(y)=x^2y^2$ 이므로 $G$ 는 아벨군일 때 $\phi$ 가 준동형 사상이다. $o(x)=2m$ 이라면 $o(x^m)=2$ 이므로 $G$ 는 계수가 짝수인 원소를 가지면 안된다. 즉 $G$ 는 order 가 홀수인 아벨군이다.

$|G|$ 가 홀수이며 아벨군이라고 하자. $x^2=1_G$ 를 만족하는 $x$ 는 $1_G$ 뿐이므로 단사이다. 따라서 $\phi$ 는 자기동형사상이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_11}

$G$ 와 $H$ 는 아래와 같이 정의되는 $GL_2(\mathbb{R})$ 의 부분군이다.

$$
G = \left\{ \begin{bmatrix} x & y \\ 0 & 1 \end{bmatrix} : x>0 \right\}, \qquad H = \left\{ \begin{bmatrix} x & 0 \\ 0 & 1 \end{bmatrix} : x>0 \right\}
$$

$G$ 는 $xy$ 좌표평면상에서 $x>0$ 인 반평면의 원소로 표현 될 수 있다. $H$ 의 왼쪽 잉여류와 오른쪽 잉여류가 이 반평면을 어떻게 분할하는지 설명하라.

:::

</div></br>

::: {.solution}

$H$ 는 반평면상의 $x$ 축 에 포함되는 원소라고 볼 수 있다. $\begin{bmatrix} x' & y' \\ 0 & 1 \end{bmatrix}\in G$ 에 대해 
$$
\begin{aligned}
\begin{bmatrix} x' & y' \\ 0 & 1 \end{bmatrix} \begin{bmatrix} x & 0 \\ 0 & 1 \end{bmatrix}  &= \begin {bmatrix} xx' & y' \\ 0 & 1 \end{bmatrix} \\
\begin{bmatrix} x & 0 \\ 0 & 1 \end{bmatrix}\begin{bmatrix} x' & y' \\ 0 & 1 \end{bmatrix} &=\begin{bmatrix} xx' & xy' \\ 0 & 1\end{bmatrix}
\end{aligned}
$$

이다. $H$ 에 대한 왼쪽 잉여류는 $x$ 축상의 점 즉 $y=0$ 상의 점을 $y=y'$ 상의 점으로 이동시킨다. $H$ 에 대한 오른쪽 잉여류는 원점을 지나며 기울기가 $x'/y'$ 인 직선으로 이동시킨다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_12}

#### Artin 2.8.12

$S$ 가 군 $G$ 의 부분집합이며 $1_G\in S$ 이고 $S$ 에 대한 왼쪽 잉여류의 집합 $\{aS: a\in G\}$ 가 $G$ 를 분할한다면 $S$ 가 $G$ 의 부분군임을 보여라.

:::

</div></br>

::: {.solution}

$x\in S$ 이지만 $x^{-1}\not\in S$ 라고 하자. $1_G \in S$ 이므로 $x^{-1}\in x^{-1}S$ 인데 $x\in S$ 이므로 $1_G\in x^{-1}S$ 이며 이는 왼쪽 잉여류의 집합이 $G$ 를 분할한다는 가정에 위배된다. 따라서 $x\in S\implies x^{-1}\in S$ 이다. 

$x,\,y\in S$ 이지만 $xy\not\in S$ 라면 $xy\in (xy)S$ 이다. 그런데 $y^{-1}\in S$ 이므로 $x\in (xy)S$ 이므로 가정에 위배된다. 따라서 $S$ 는 연산에 대해 닫혀 있다. 따라서 $S\le G$ 이다.

:::

</br>


## 동형사상

### 동형사상 {#sec-MA_group_isomorphism}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-MA_isomorphism_in_group}
#### 동형사상

군 $G,\,G'$ 에 대해 $\varphi \in \text{Hom}\, (G,\,G')$ 이 전단사일 때 $\varphi$ 를 $G$ 에서 $G'$ 으로의 **동형사상(isomorphism)** 이라고 한다. $G$ 에서 $G'$ 으로의 동형사상의 집합을 $\text{Iso}\, (G,\,G')$ 로 표기한다. 두 군 $G,\,G'$ 사이에 동형사상이 존재하면 $G$ 와 $G'$ 이 **동형(isomorphic)** 이라고 하며 $G \cong G'$ 이라고 쓴다.

자기 자신으로의 동형사상을 **자기동형사상(Automorphism)** 이라고 하며 $G$ 에서의 자기동형사상의 집합을 $\text{Aut}\,(G)$ 로 표기한다.

:::
:::

</br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-inverse_of_isomorphism}

$\varphi \in \text{Iso}(G,G')$ 이면 그 역함수 $\varphi^{-1}$ 에 대해 $\varphi^{-1} \in \text{Iso}(G',G)$ 이다.

:::

</div></br>

::: {.proof}
$\varphi^{-1}$ 이 $G'$ 에서 $G$ 로의 전단사 함수이므로 $\varphi^{-1}\in \text{Hom}(G',G)$ 라는 것만 보이면 된다. $x'=\varphi(x),\, y'=\varphi(y)$ 라고 하자. $\varphi(xy)=x'y'$ 이므로 $\varphi^{-1}(x'y')= xy= \varphi^{-1}(x)\varphi^{-1}(y)$ 이다. $\square$ 
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_conjugation_automorphism}

군 $G$ 에서 임의의 정해진 $g\in G$ 에 대해 $\varphi (x) = gxg^{-1}$ 를 **conjugation by $g$** 라고 한다. 이 때 $\varphi (x)$ 는 자기동형사상이다. 

:::

</div></br>

::: {.proof}

$\phi(xy) = gxyg^{-1}= (gxg^{-1})(gyg^{-1})=\phi(x)\phi(y)$ 이므로 $\phi\in \text{Hom}\,(G)$ 이다. 임의의 $y\in G$ 에 대해 $\varphi(g^{-1}yg)= y$ 이므로 $\varphi$ 는 전사이다. 제거규칙에 의해 $gxg^{-1}=gyg^{-1}$ 이면 $x=y$ 이므로 $\varphi$ 는 단사이다. 따라서 $\varphi \in \text{Aut}\, (G)$ 이다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_2}

#### Artin 2.6.2

$\text{Hom}(\mathbb{Z}^{+})$ 를 기술하시오. 각 준동형사상의 전사, 단사, 전단사 여부를 정하시오.
:::

</div></br>

::: {.solution}

$\varphi \in \text{Hom}(\mathbb{Z}^+)$ 이면 $\varphi (a+b)=\varphi (a)+ \varphi(b)$ 이므로 선형 함수이어야 한다. 즉 어떤 정수 $a\in \mathbb{Z}$ 에 대해 $\varphi (x) = ax$ 이다. $a=1$ 이면 전단사이며 $a=0$ 이면 상수함수, 나머지는 단사함수이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_7}

#### Artin 2.6.7

$H \le G$ 일 때 정해진 $g\in G$ 에 대해 $gHg^{-1}= \{ghg^{-1}: h\in H\}$ 을 **conjugate subgroup** 이라고 한다. $gHg^{-1}\le G$ 임을 보이시오.

:::

</div></br>

::: {.solution}

$h_1,\,h_2\in H$ 에 대해 $(gh_1g^{-1})(gh_2g^{-1})= gh_1h_2g^{-1}\in gHg^{-1}$ 이므로 $gHg^{-1}$ 은 연산에 닫혀 있다. $g1g^{-1}=1\in gHg^{-1}$ 이며 $h\in H$ 에 대해 $(ghg^{-1})^{-1}= gh^{-1}g^{-1}\in gHg^{-1}$ 이다. 따라서 $gHg^{-1}\le G$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_8}

#### Artin 2.6.8

$\phi : GL_n(\mathbb{R}) \to GL_n(\mathbb{R})$ 이 $\phi (A) = (A^T)^{-1}$ 로 정의될 때 $\phi$ 가  자기동형사상임을 보이시오.

:::

</div></br>

::: {.solution}

$\phi(AB)= ((AB)^T)^{-1}=(B^TA^T)^{-1} = (A^T)^{-1}(B^T)^{-1}=\phi(A) \phi(B)$ 이므로 $\phi$ 는 준동형사상이다. $\phi(A)=\phi(B)$ 이면 $(A^T)^{-1}= (B^T)^{-1}$ 이며 $A=B$ 이므로 단사이다. 임의의 $B\in GL_n(\mathbb{R})$ 에 대해 $B^T(B^{-1})^T = (B^{-1}B)^T = I_n$ 이므로 $(B^{-1})^T = (B^T)^{-1}$ 이다. 따라서, $\phi ((B^T)^{-1}) = (((B^{-1})^T)^T)^{-1}=B$ 이므로 $\phi$ 는 전사이다. 따라서 $\phi \in \text{Aut}(GL_n(\mathbb{R}))$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_9}

#### Artin 2.6.9
군 $G$ 와 opposite group (@exr-artin_2_2_6) $G^\circ$ 은 동형임을 보여라

::: 

</div></br>

::: {.proof}

$\phi\in \text{Hom}(G,\,G^\circ)$ 를 $\phi (g)=g^{-1}$ 로 정의하자. $\phi$ 는 전사이며, $g_1,\,g_2\in G$ 에 대해 

$$
\begin{aligned}
\phi(g_1g_2) &= (g_1g_2)^{-1} = g_2^{-1}g_1^{-1}= g_1^{-1}\ast g_2^{-1},\\
\phi(g_1)\ast \phi(g_2) &= g_1^{-1} \ast g_2^{-1}
\end{aligned}
$$

이며 $\ker \phi = 1_G$ 이므로 동형이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_10}
#### Artin 2.6.10

모든 자기동형사상을 찾으시오.

&emsp; ($1$) order 가 10 인 순환군, 

&emsp; ($2$) $S_3$

:::

</div></br>

::: {.solution}

우선 다음을 보이자. 

> **명제 1** $\phi \in \text{Aut}(G)$ 일 때 모든 $g\in G$ 에 대해 $o(g)=n$ 이라면 $o(\phi(g))=n$ 이어야 한다

$g^n=1_G$ 이므로 $\phi (g^n)=1_G$ 이다. 따라서 $o(\phi (g)) \mid n$ 이어야 한다. $m=o(\phi(g))<n$ 이면 $g^m\ne 1_G$ 에 대해 $\phi(g^m)=1_G$ 이므로 $\phi$ 는 단사가 아니게 된다. 따라서 $o(g) = o(\phi(g))$ 이다.  

($1$) $o(g)=10,\, G=\langle g\rangle$ 이라 하자. $\phi \in \text{Hom}(G)$ 라 하자. $0 \le k < 10$ 인 양의 정수 $k$ 에 대해 $\phi (g)=g^k$ 라면 

$$
\phi (g^m g^n) = g^{(m+n)k}= g^{mk}g^{nk} = \phi(g^m)\phi(g^n)
$$

이므로 준동형 사상이 정해진다. 앞의 명제에 따라 $\phi(g)$ 가 $g^2,\, g^4,\, g^5,\, g^6,\, g^8$ 이면 앞의 명제에 따라 자기동형사상이 아니다. 남은 가능성은 $\phi(g)$ 가 $g,\,g^3,\,g^7,\,g^9$ 일 때 이다. 즉 10 과 서로소인 $k$ 에 대해 $\phi (g) = g^k$ 일 때 이다. $\phi(g^x) = \phi(g^y)$ 이면 $xk \equiv yk\;(\text{mod}\,10)$ 이므로 @prp-MA_modula 의 ($4$) 에서 보였듯이 $x\equiv y\;(\text{mod}\,10)$ 이므로 $\phi$ 는 단사이다. 즉 $\phi$ 는 자기동형사상이다.

($2$) $S_3 = \{1,\,x,\,x^2,\,y,\,xy,\,x^2y\}$, $x^3=y^2=1$, $x^2y=yx$ 이다. $o(xy)=o(x^2y)=2$ 이다.

따라서 $\phi(x)$ 는 $x$ 이거나 $x^2$ 일 수 밖에 없으며, $\phi(y)$ 는 $y$, $xy$, $x^2y$ 일 수 있다. 이 여섯가지 경우가 모두 자기동형사상임을 보일 수 있다.

:::

</br>

## 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-euler_fermat}

양의 정수 $n$ 에 대해 오일러-$\phi$ 함수 $\phi(n)$ 은 $\phi(1)=$ 이며 $n\ge 2$ 일 때 $n$ 보다 작은 양의 정수 가운데 $n$ 과 서로소인 양의 정수의 갯수이다.

&emsp; ($1$)  $\gcd(n, a)=1$ 일 때 $a^{\phi(n)} \equiv 1\;(\text{mod}\; n)$ 임을 보여라.

&emsp; ($2$) (**페르마의 소정리**) $p$ 가 소수이고 $a$ 가 정수일 때 $a^p \equiv a\;(\text{mod}\;p)$ 임을 보여라.

:::

</div></br>

::: {.solution}

($1$) @exr-herstein_2_3_15 의 ($2$) 에 따라 $K_n = \{[m]: \gcd (m, n)=1\}$ 은 곱셈 연산에 대한 군이다. 이며 $|K_n|=\phi(n)$ 이다. $[a]\in K_n$ 이므로 $[a]^{\phi(n)} = [1]$ 이며, 따라서 $a^{(\phi(n))} \equiv 1 \;(\text{mod}\; n)$ 이다.

($2$) $\phi(p)=p-1$ 이므로 $a^{p-1} \equiv 1\;(\text{mod}\; p)$ 이다. 따라서 $a^p \equiv p\;(\text{mod}\;p)$ 이다. 
:::

</br>