---
title: "정규부분군과 몫군"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

</br>

## 정규부분군

### Conjugate 와 정규부분군 {#sec-MA_normal_subgroup}

::: {.callout-note appearance="simple" icon="false"}
::: {#def-MA_normal_subgroups}
#### Conjugate 와 정규부분군

$a,\,g$ 가 군 $G$ 의 원소일 때 $gag^{-1}$ 을 $g$ 에 의한 $a$ 의 **conjugate** 라고 한다. $N\le G$ 가 모든 $a\in N$ 과 $g\in G$ 에 대해 $gag^{-1}\in N$ 일 때 $N$ 을 $G$ 의 **정규부분군(normal subgroup)** 이라고 하며 $N \trianglelefteq G$ 라고 표기한다.

:::
:::

즉 $G$ 의 부분군 $N$ 이 모든 $g\in G$ 에 대해 $gNg^{-1}\subset N$ 이면 $N \trianglelefteq G$ 이다. 우리는 잠시 후 @prp-MA_normal_subgroup_condition 에서 $gNg^{-1} \subset N$ 이면 $gNg^{-1}= N$ 이라는 것을 알게 된다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_conjugate_subgroup}

$H \le G$ 일 때 $g\in G$ 에 대해 $gHg^{-1}= \{ ghg^{-1}: h\in H\}$ 는 $G$ 의 부분군이다. 이렇게 정의된 $gHg^{-1}$ 을 **cojugate subgroup** 이라고 한다.

:::

</div></br>

::: {.proof}

$1_G\in H$ 이며 $g1_Gg^{-1}=1_G\in gHg^{-1}$ 이다. $h_1,\,h_2\in H$ 에 대해 $(gh_1g^{-1})(gh_2g^{-1}) = g(h_1h_2)g^{-1}\in gHg$ 이며, $(gh_1g^{-1})^{-1}=gh_1^{-1}g^{-1}\in gHg^{-1}$ 이므로 $gHg^{-1} \le G$ 이다. $\square$
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_kernel_and_normal_subgroup}

$\varphi \in \text{Hom}\, (G,\,G')$ 일 때 $\ker \varphi \trianglelefteq G$ 이다.

:::

</div></br>

::: {.proof}
$a \in \ker \varphi$ 이고 $g\in G$ 일 때 $\varphi (gag^{-1})= \varphi (g)1_G \varphi(g^{-1})=1_G'$ 이므로 $gag^{-1}\in \ker \varphi$ 이다. $\square$
:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_normal_subgroup_and_S3}

$S_3 = \{1, x, x^2, y, xy, x^2y\}$ 를 생각하자. $x^2y=yx$ 를 만족한다. 이 때 $\langle x \rangle \trianglelefteq G$ 이지만 $\langle y \rangle$ 은 $G$ 의 정규부분이 아니다. 예를 들어 $xyx^{-1}= xyx^2 =x^2y \not\in \langle y \rangle$ 이다. 
:::

</div></br>


::: {.callout-note appearance="simple" icon="false"}
::: {#def-center_of_group}

#### 군의 Center

군 $G$ 에 대해 다음을 만족하는 집합 $Z_G$ 를 $G$ 의 **중심(center)** 라고 한다.

$$
Z_G = \{ z\in G: \forall g\in G,\, zg = gz \}.
$$

:::
:::


<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_center_of_group_is_normal_subgroup}

$z\in Z_G$ 일 때 $g\in G$ 에 대해 $gzg^{-1}= zgg^{-1}=z\in Z_G$ 이므로 $Z_G \trianglelefteq G$ 이다.
:::

</div>
</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_normal_subgroup_condition}

$H \le G$ 일 때 다음 명제들은 동치이다.

&emsp; ($1$) $H \trianglelefteq G$,

&emsp; ($2$) $\forall g\in G,\, gHg^{-1}=H$, 

&emsp; ($3$) $\forall g\in G,\, gH = Hg$, 

:::

</div></br>

::: {.proof}

($1\implies 2$) 정의에 의해 $H \trianglelefteq G$ 이면 $gHg^{-1}\subset H$ 이다. 또한 $g^{-1}Hg\subset H$ 이다. 이로부터 $g(g^{-1}Hg)g^{-1}\subset gHg^{-1}$ 을 얻는데, $g(g^{-1}Hg)g^{-1}=H$ 이므로 $gHg^{-1}=H$ 이다.

($2 \implies 3$) $x\in gH$ 이면 어떤 $h\in H$ 에 대해 $x=gh$ 이다. $xg^{-1}=ghg^{-1}=h'\in H$ 가 존재하며 따라서 $x=h'g$ 이므로 $x\in Hg$ 이다. 즉 $gH \subset Hg$ 이다. 같은 방법으로 $Hg\subset gH$ 를 보일 수 있으므로 $gH=Hg$ 이다.

($3 \implies 1$) $h\in H,\, g\in G$ 에 대해 $gh=h'g$ 인 $h'\in H$ 가 존재하며 $ghg^{-1}=h'\in H$ 이다. 따라서 $H \trianglelefteq G$ 이다. $\square$
:::

</br>

다음은 별도로 언급할 가치가 있다.

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-MA_normal_subgroup_condition}

$H\le G$ 일 때 $H \trianglelefteq G$ 일 필요충분조건은 $H$ 에 대한 왼쪽 잉여군의 집합과 $H$ 에 대한 오른쪽 잉여군의 집합이 같은 것이다.

:::

</div></br>

::: {.proof}

$H$ 에 대한 왼쪽 잉여군의 집합과 $H$ 에 대한 오른쪽 잉여군의 집합이 같은 것의 필요충분조건은 @prp-MA_normal_subgroup_condition 의 ($3$) 인 것을 보이자. $L_H$ 를 왼쪽 잉여군의 집합, $R_H$ 를 오른쪽 잉여군의 집합이라고 하자.

($3$) 이 성립함을 가정하자. $gH\in L_H$ 이면 $gH=Hg$ 이므로 $gH \in R_H$ 이다. 따라서 $L_H \subset R_H$ 이며 같은 방법으로 $R_H \subset L_H$ 임을 보일 수 있으므로 $L_H = R_H$ 이다. 

이제 $L_H = R_H$ 임을 가정하자. $gH\in L_H$ 이면 어떤 $Hg'\in R_H$ 에 대해 $gH = Hg'$ 이다. 그런데 $g\in gH$ 이므로 $g\in Hg'$ 이어야 하며 따라서 $Hg' = Hg$ 이다. 즉 ($3$) 이 성립한다. $\square$
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_subgroup_of_unique_order_is_normal}

$H\le G$ 이며 $H$ 가 $|H|$ order 를 갖는 $G$ 의 유일한 부분군이면 $H \trianglelefteq G$ 이다.

:::

</div></br>

::: {.proof}
$g\in G$ 에 대해 $gHg^{-1}\le g$ 이며 $|gHg^{-1}|=|H|$ 이다. 만약 $H$ 가 $|H|$ order 를 갖는 유일한 부분군이라면 모든 $g\in G$ 에 대해 $gHg^{-1}=H$ 이므로 $H \trianglelefteq G$ 이다.
:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
::: {#exr-artin_2_5_2}

#### Artin 2.5.2

$G$ 의 두 부분군 $H,\,K$ 에 대해 $H\cap K \le H$ 임을 보여라. $K \trianglelefteq G$ 이면 $(K \cap H)\trianglelefteq H$ 임을 보여라.

:::

</div></br>

::: {.solution}

두 군의 교집합은 각각의 부분군임은 쉽게 보일 수 있다. 이제 $K \trianglelefteq G,\, H\le G$ 일 때 $(K \cap H) \trianglelefteq H$ 임을 보이자. 임의의 $h\in H,\,k\in K \cap H$ 에 대해 $k\in K \trianglelefteq G$ 이므로 $hkh^{-1}\in K$ 이다. 또한 $k\in H$ 이므로 $hkh^{-1}\in H$ 이다. 따라서 $hkh^{-1}\in K \cap H$ 이므로 $(K \cap H)\trianglelefteq H$ 이다. 

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_5_6}

#### Artin 2.5.6

$GL_n(\mathbb{R})$ 의 중심은 무엇인가?

:::

</div></br>

::: {.solution}

$Z_G$ 을 $GL_n(\mathbb{R})$ 의 중심이라고 하자. @exr-artin_2_4_8 로부터 $GL_n(\mathbb{R})$ 은 $E^{(2)}$ 연산과 $E^{(3)}$ 연산으로 부터 생성된다는 것을 안다. 즉 $M\in GL_n(\mathbb{R})$ 은 $E^{(2)}$ 연산과 $E^{(3)}$ 연산을 나타내는 $n \times n$ 행렬의 곱으로 표현된다. $M=E_1\cdots E_m$ 이며 $E_1,\ldots,\,E_m$ 은 두 연산을 나타내는 행렬이라고 하자. 각각의 $E_i,\, i=1,\ldots,m$ 은 $GL_n(\mathbb{R})$ 에 포함된다. $S\in Z_G$ 이면 $SE_i = E_i S$ 이다. 또한 모든 $E^{(2)},\, E^{(3)}$ 행렬에 대해 $E_iS=SE_i$ 라면

$$
MS = E_1 \cdots E_m S = E_1 \cdots E_{m-1}SE_m = \cdots = SE_1 \cdots E_m = SM
$$

이므로 $S\in Z_G$ 이다. 즉 $Z_G$ 는 모든 $E^{(2)},\, E^{(3)}$ 행렬에 대해 교환법칙이 성립하는 행렬의 집합이다. $E^{(2)}(i, t)S$ 는 $S$ 의 $i$ 행에 $t\ne 0$ 를 곱하는 것이며 $SE^{(2)}(i, t)$ 는 $S$ 의 $j$ 행에 $t\ne$ 를 곱하는 것이다. $E^{(2)}(i, t)S=SE^{(2)}(i, t)$, $i=1,\ldots,\,n$ 이어야 하므로 $S$ 의 대각성분을 제외하고는 모두 $0$ 이어야 한다. 이제 $S_{ij}= d_i \delta_{ij}$ 로 놓고 생각 할 수 있다.

$E^{(3)}(i, j, r)S=SE^{(3)}(i, j, r)$ 이어야 하는데 이는 $d_i = d_j$ 이어야 한다. 즉 $S$ 는 $\boldsymbol{I}_n$ 의 스칼라곱 이어야 한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_4}

#### Artin 2.6.4

군에서 $ab$ 와 $ba$ 는 서로 conjugate 이다.

:::

</div></br>

::: {.solution}

$ab = a(ba)a^{-1}$. 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_5}

#### Artin 2.6.5

$2 \times 2$ 행렬 $A=\begin{bmatrix} 3 & \\ & 2\end{bmatrix}$ 와 $B=\left[\begin{array}{rr} 1 & 1 \\ -2 & 4\end{array}\right]$ 는 $GL_2(\mathbb{R})$ 에서 conjugate 인가?

:::

</div></br>

:::{.solution}
$PAP^{-1}=B$ 를 만족하는 $P = \begin{bmatrix}a & b\\ c& d\end{bmatrix}$ 를 구해보자. 

$$
\begin{aligned}
\dfrac{1}{ad-bc}\begin{bmatrix}a & b\\ c& d\end{bmatrix} \begin{bmatrix} 3 & \\ & 2\end{bmatrix} \left[\begin{array}{rr}d & -b\\ -c& a\end{array}\right] & = \dfrac{1}{ad-bc} \begin{bmatrix} 3a & 2b \\ 3c & 2d\end{bmatrix}\left[\begin{array}{rr}d & -b\\ -c& a\end{array}\right] \\
&= \dfrac{1}{ad-bc} \begin{bmatrix} 3ad-2bc & -ab \\ cd & 2ad-3bc \end{bmatrix} = \left[\begin{array}{rr} 1 & 1 \\ -2 & 4\end{array}\right]
\end{aligned}
$$

로부터, 

$$
\dfrac{ad}{ad-bc} = -1,\, \dfrac{bc}{ad-bc}=-2,\, \dfrac{ab}{ad-bc}=-1,\, \dfrac{cd}{ad-bc}=-2
$$

이며,

$$
2ad = bc,\, ab=  ad,\, cd = 2ad
$$

$a=0$ 이거나 $d=0$ 이면 $bc=0$ 이므로 $P$ 는 가역이 아니다. 따라서 $adcd\ne 0$ 이다. $b=d,\, c=2a$ 이므로, $ab\ne 0$ 일 때 $P=\begin{bmatrix} a & b \\ 2a &b\end{bmatrix}$ 에 대해 $PAP^{-1}=B$ 이다.

:::

</br>
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_6_11}
#### Artin 2.6.11

군 $G$ 에 대해 $a\in G$ 이며 $\{1_G,\, a\}\trianglelefteq G$ 이면 $a$ 는 $G$ 의 중심의 원소이다.

:::

</div></br>

::: {.solution}

임의의 $g\in G$ 에 대해 $gag^{-1}\in \{1_G,\,a\}$ 이다. $gag^{-1}=1_G$ 이면 $a=1_G$ 이므로 가정에 위배된다. 따라서 $gag^{-1}=a$ 이므로 $ga=ag$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_8_10}

#### Artin 2.8.10

인덱스가 2 인 부분군, 즉 $H\le G$ 이며 $|G|/|H|=2$ 인 경우 $H\trianglelefteq G$ 임을 보이고 인덱스가 3인경우는 정규부분군이 아닐수도 있다는 것을 예를 들어 보여라.

:::

</div></br>

::: {.solution}

$[G:H]=2$ 인 경우를 보자. $g\in G$ 이며 $g\notin H$ 에 대해 $G$ 의 두 왼쪽 잉여류는 $H$ 와 $gH$ 이며 오른쪽 잉여류는 $H$ 와 $Hg$ 이다. 따라서 $Hg=gH$ 이므로 $H \trianglelefteq G$ 이다.

대칭군 $S_3=\{1,\,x,\,x^2,\,y,\,xy,\,x^2y\}$ 를 생각하자. $H=\{1,\,y\} \le S_3$ 이며, $[G:H]=3$ 이다 $xyx^{-1}=xyx^2=x^y \notin H$ 이므로 $H$ 는 $G$ 의 정규부분군이 아니다. 

:::

</br>

## 대응 정리

### 대응 정리 {#sec-MA_correnspodence_theorem_1}


$\varphi \in \text{Hom}(G,G')$ 이며 $H \le G$ 일 때 $\varphi$ 의 정의역을 $H$ 로 제한하는 함수를 $\varphi|_H$ 로 쓰자. 즉 $h\in H$ 에 대해 $\varphi|_H(h) =\varphi(h)$ 이다. 이 때 (당연하게도) $\ker (\varphi|_H) = \ker \varphi \cap H$ 이다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_restriction_homomorphsm_1}

$G,\,G'$ 이 유한군이고 $H \le G$ 라고 하자. $\varphi \in \text{Hom}(G, G')$ 이며 $\gcd (|H|, |G'|)=1$ 이면 $H \le \ker \varphi$ 이다.

:::

</div></br>

::: {.proof}
@thm-MA_orders_in_group_homomorphism 에 따라 $|\text{im}(\varphi|_H)| {\large \mid} |H|$ 이며 $|\text{im}(\varphi|_H)| {\large \mid} |G'|$ 이어야 한다. 따라서 $\text{im}(\varphi_H) = \{1_G'\}$. $\square$

:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_image_of_sign_homomorphism}

집합 $\{1,\,-1\}$ 은 곱하기 연산에 대해 군이다. 우리는 [행렬식](../part1/ch1_03_determinant.qmd) 에서 $\text{sgn}$ 함수에 대해 알았보았다. $\text{sgn} : S_n \to (\{1,\,-1\}, \times)$ 가 준동형사상이라는 것은 쉽게 보일 수 있다. 만약 $S_n$ 의 부분군이 홀수개의 원소를 포함한다면 @prp-MA_restriction_homomorphsm_1 에 따라 $\ker (\text{sgn})$ 즉, $A_n$ 에 포함된다. 예를 들어 홀수인 $k$ 에 대한 $k$-cycle 의 경우 order $k$ 부분군이며 따라서 짝순열(even pertumation) 이다. 

:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_restriction_homomorphism_2}

$\varphi \in \text{Hom} (G, G')$ 이고 $K=\ker \varphi$ 라 하자. $H'\le G'$ 에 대해 $H=\varphi^{-1}(H')$ 라 하자. 이 때 다음이 성립한다.

&emsp; ($1$) $K \le H\le G$ 이다. 

&emsp; ($2$) $H'\trianglelefteq G'$ 이면 $H \trianglelefteq G$ 이다. 

&emsp; ($3$) $\varphi$ 가 전사이고 $H\trianglelefteq G$ 이면 $H' \trianglelefteq G'$ 이다.

:::

</div></br>

::: {.proof}

($1$) $1_{G'} \in H'$ 이므로 $K \le H$ 이다. $x,\,y\in H$ 일 때 $\varphi(x),\, \varphi(y)\in H'$ 이며 따라서 $\varphi (xy)\in H'$ 이므로 $xy\in H$ 이다. $x\in H$ 이면 $\varphi (x)\in H'$ 이며 $(\varphi(x))^{-1}\in H'$ 이므로 $\varphi(x^{-1})\in H'$ 이다. 따라서 $x^{-1}\in H$ 이다. 따라서 $H\le G$ 이다.

($2$) 임의의 $h'\in H'$ 에 대해 $h\in \varphi^{-1}(\{h'\})$ 이라 하자. 임의의 $g\in G$ 에 대해 

$$
\varphi (ghg^{-1})= \varphi(g)\varphi (h) \varphi (g^{-1}) = \varphi (g)h'(\varphi (g))^{-1} \in H'
$$ 

이므로 $ghg^{-1} \in H$ 이다. 즉 $H \trianglelefteq G$ 이다.

($3$) $\varphi$ 가 전사이므로 $g'\in G',\, h'\in H'$ 에 대해 $g\in \varphi^{-1}(\{g'\}),\, h\in \varphi^{-1}(\{h'\})$ 인 $g,\,h$ 가 존재한다. $ghg^{-1} = h_1\in H$ 라고 하면 $\varphi (ghg^{-1}) = g'h'g'^{-1} = \varphi(h_1) \in H'$ 이므로 $H' \trianglelefteq G'$ 이다. $\square$

:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_correspondence_theorem_of_groups}

#### 대응 정리 (Correspondence Theorem )

$\varphi \in \text{Hom}(G,G')$ 이며 전사이고 $K = \ker \varphi$ 라 하자. 이 때 [$K$ 를 포함하는 $G$ 의 부분군의 집합] 과 [$G'$ 의 부분군의 집합] 사이에 일대일 대응이 존재한다.
:::

</div></br>

::: {.proof} 
$\varphi$ 가 전사이므로 $\varphi (\varphi^{-1}(H')) = H'$ 이다. 또한 $H \subset \varphi^{-1}(\varphi(H))$ 이다 ($\varphi$ 가 단사이면 등호가 성립한다). 이제 $\varphi^{-1}(\varphi (H)) \subset H$ 임을 보이자. $x\in \varphi^{-1}(\varphi (H))$ 이면 $\varphi (x) \in \varphi (H)$ 이어야 하며, 따라서 어떤 $h\in H$ 에 대해 $\varphi (x) = \varphi (h)$ 이어야 한다. $h^{-1}x\in K\le H$ 이며 $h\in H$ 이므로 $x \in H$ 이다. 즉 $\varphi^{-1}(\varphi(H)) = H$ 이다. 

$G'$ 의 부분군의 집합을 $P$, $K$ 를 포함하는 $G$ 의 부분군의 집합을 $Q$ 라고 할 때 @prp-MA_restriction_homomorphism_2 에 의해  함수 $\Psi : P \to Q$ 를 $\Psi(H') = \varphi^{-1}(H')$ 으로 정의 할 수 있다. 임의의 $H\in Q$ 에 대해 $\varphi (H) \in P$ 이며 $\varphi^{-1}(\varphi (H)) = H$ 이므로 $\Psi$ 는 전사이다. $\varphi^{-1}(H'_1) \ne \varphi^{-1}(H'_2)$ 이면 $\varphi$ 가 전사이므로 $H'_1\ne H'_2$ 이다. 즉 $\Psi$ 는 단사이다. 따라서 $P$ 와 $Q$ 사이에 일대일 대응이 존재한다.
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-MA_correnspondence_theorem_of_groups}

@thm-MA_correspondence_theorem_of_groups 조건에서 $|\varphi^{-1}(H') | = |H'||K|$ 이다. 

:::

</div></br>

::: {.proof}

$\varphi|_H \in \text{Hom}(H,\, H')$ 이며 전사이고 $\varphi^{-1}(H')=H$ 이다. 또한 $K = \ker \varphi = \ker \varphi|_H$, $\text{im}\, \varphi|_H = H'$ 이므로 @thm-MA_orders_in_group_homomorphism 에 따라

$$
|H| = |\varphi^{-1}(H')|=|H'|\,|K|
$$

이다. $\square$
:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">
::: {#exr-artin_2_10_2}

#### Artin 2.10.2

$H\le G,\, K\le G$ 일 때 다음을 보여라.

&emsp; ($1$) $H$ 와 $K$ 의 두 잉여류의 교집합 $xH \cap yK$ 는 공집합이거나 $H\cap K$ 의 잉여류이다.

&emsp; ($2$) $[G:H]<\infty$, $[G:K]<\infty$ 라면 $[G:H\cap K]<\infty$ 이다.

:::

</div></br>

::: {.solution}

($1$) $xH \cap yK \ne \varnothing$ 만을 생각한다. $g\in xH \cap yK$ 라면 어떤 $h\in H,\, k\in K$ 에 대해 $g=xh=yk$ 이다. $h=x^{-1}g,\, k = y^{-1}g$ 이다. 따라서 $gH = xH$ 이고 $gK = yK$ 이, 이로부터 $(xH \cap yK) = (gH \cap gK)$ 임을 알 수 있다. 

이제 $gH \cap gK = g(H \cap K)$ 임을 보이자. $z\in gH \cap gK$ 이면 $z=gh = gk$ 를 만족하는 $h\in H,\, k\in K$ 가 존재하며 $h=k$ 이므로 $z\in g(H \cap K)$ 이다. 역으로 $z\in g(H \cap K)$ 이면 $z\in gH \cap gK$ 임은 쉽게 알 수 있다. 따라서 $xH \cap yK \ne \varnothing$ 이라면 $g\in xH \cap yK$ 일 때 $(xH \cap yK) = g(H \cap K)$ 이다.

($2$) $[G:H]=m$ 이라면 $m$ 개의 $H$ 의 잉여류가 존재하며, $[G:K]=n$ 이라면 $n$ 개의 $H$ 의 잉여류가 존재한다. 또한 $G$ 의 원소는 어떤 $H$ 의 잉여류에 포함되며 어떤 $K$ 의 잉여류에 포함되므로, 어떤 $H\cap K$ 의 잉여류에 포함된다. 따라서 $[G:H \cap K] \le m \times n$ 이다.
:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exr-artin_2_10_3}

#### Artin 2.10.3

$G$ 와 $G'$ 이 각각 order 12, 6 순환군이며 $x,\,y$ 로 부터 생성된다고 하자. $\varphi : G \to G'$ 이 $\varphi(x^i) = y^i$ 로 정의되었다고 하자. 대응정리로부터 함수의 대응관계를 설명하라.

:::

</div></br>

::: {.solution}

$\varphi$ 가 준동형사상이며 전사임은 쉽게 보일 수 있다. $\ker (\varphi) = \{1_G, g^6\}$ 이다. 이제 $G'$ 의 부분군의 집합을 $P$ 라 하면, 

$$
P = \{ H'_0 = G', H'_1 = \{1_{G'}, y^2, y^4\}, H'_2= \{1_{G'}, y^3\} \}
$$

$\ker (\varphi)$ 를 포함하는 $G$ 의 부분군은

$$
Q= \{ H_0 = G, H_1 = \{1_G, x^2, x^4, x^6, x^8, x^{10}\}, H_2=\{1_G, x^3, x^6, x^9\} \}
$$

이며 $\Psi : P \to Q$ 를 $\Psi(H') = \varphi^{-1}(H')$ 으로 정의하면 $\Psi (H'_i)= H_i,\, i=1,\,2,\,3$ 이다.

:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exr-artin_2_10_4}

#### Artin 2.10.4

대응정리에 사용된 표기법을 색각하자. $[G:H] = [G':H']$ 임을 보여라.

:::

</div></br>

::: {.proof}

$\varphi \in \text{Hom}(G, G')$ 이 전사이며 $K = \ker (\varphi)$ 라고 하자. $a'\in G'$ 에 대해 $a'=\varphi (a)$ 라고 하자. 이 때 $\varphi^{-1}(a'H') = aH$ 라면 $\varphi$ 가 전사이므로 $H$ 의 잉여류의 갯수와 $H'$ 의 잉여류의 갯수가 같게 되며 따라서 $[G:H] = [G':H']$ 이다. 이제 $\varphi^{-1}(a'H')= aH$ 임을 보이자.

우선 $x\in aH$ 이면 $x=ah$ 를 만족하는 $h\in H$ 가 존재하며 $\varphi (x)=\varphi(a)\varphi(h')= a'h'\in a'H'$ 이다. 즉 $aH \subset \varphi^{-1}(a'H')$ 이다. 

이제 $x'\in a'H'$ 이라  하자.  $x'=a'h'$ 을 만족하는 $h'\in H'$ 이 존재하며  $\varphi (x) = x'$ 를 만족하는 $x\in G$ 가 존재한다. $H$ 의 잉여류의 집합은 $G$ 를 분할하므로 $x\in bH$ 라 하자. $\varphi (x) = \varphi(b)\varphi (h) \in \varphi(b)H'$ 이어야 한다. 따라서 $b\in \varphi^{-1}(\{a'\})$ 이어야 하며, 따라서 $x\in aH$ 이다. 즉 $\varphi^{-1}(a'H') \subset aH$ 이다. 따라서 $\varphi^{-1}(a'H') = aH$ 이다.

:::

</br>

## Product Group


::: {.callout-note appearance="simple" icon="false"}
::: {#def-MA_external_product_of_groups}
#### External product of groups

군 $G,\,G'$ 의 데카르트곱 $G\times G'$ 에 아래와 같은 곱연산을 부여한 것을 $G$ 와 $G'$ 의 **External product** 라고 한다.

$$
(a,\,a')(b,\,b')=(ab,\,ab')
$$

이 때 $i(x) = (x, 1_{G'}),\, i'(y) = (1_G,\,y),\, p(x, y)=x,\, p'(x,\,y)=y$ 로 정의된다.

:::
:::


</br> 

다음은 쉽게 보일 수 있다.

</br>
<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_external_product_of_groups_is_a_group}

@def-MA_external_product_of_groups 에 의해 정의된 $G \times G'$ 은 군이다.

::: 

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_isomorphic_to_external_product}

$r$ 과 $s$ 가 서로소인 두 정수일 때 계수가 $rs$ 인 순환군은 계수가 $r$, $s$ 인 두 순환군의 external product 와 동형이다.

:::

</div></br>

::: {.proof}

$o(g)=rs$ 인 $G=\langle g\rangle$ 을 생각하자. 또한 $o(a)=r,\, o(b)=s$ 일 때 $A=\langle a\rangle$, $B = \langle b \rangle$ 이라 하자. $\phi : G \to A \times B$ 를 $\phi (g^n)= (a^n, b^n)$ 로 정의 할 수 있다. 

$$
\phi (g^m g^n) = \phi (g^{m+n}) = (a^{m+n}, b^{m+n}) = (a^m, b^m)(a^n, b^n) = \phi(g^m)\phi(g^n)
$$

이므로 $\phi$ 는 준동형사상이다.  $(a^m,\, b^n)\in A\times B$ 를 생각하자. 중국인 나머지 정리에 의해 $r$ 로 나누어 나머지가 $m$ 이며 $s$ 로 나누어 나머지가 $n$ 인 자연수 $l$ 이 항상 존재하며 $\phi (g^l) = (a^l,\, b^l) = (a^m,\, b^n)$ 이므로 $\phi$ 는 전사이다. $\phi(g^m) = \phi(g^n)$ 일 때 $a^m=a^n,\, b^m=b^n$ 이려면 $r \mid (m-n)$, $s\mid (m-n)$ 이므로 $rs \mid (m-n)$ 이므로 $g^m=g^n$ 이다. 즉 $\phi$ 는 단사이다. 따라서 $G \cong A \times B$ 이다. $\square$

:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_inner_product_group}

$H\le G,\, K \le G$ 일 때 $f:H \times K \to G$ 를 $f(h, k)=hk$ 로 정의하자. $HK=\{hk|h\in H,\, k \in K\}$ 라 할 때 $\text{im}\, (f) = HK$ 이다. 이 때 다음이 성립한다.

&emsp; ($1$) $f$ 가 단사일 필요충분조건은 $H \cap K = \{1_G\}$ 이다.

&emsp; ($2$) $f$ 가 준동형사상일 필요충분조건은 모든 $h\in H,\, k\in K$ 에 대해 $hk = kh$ 인 것이다.

&emsp; ($3$) $H \trianglelefteq G \implies HK \le G$.

&emsp; ($4$) $f$ 가 동형사상일 필요충분조건은 $H \cap K = \{1_G\}$ 이며 $HK=G$ 이고 $H\trianglelefteq G,\, K \trianglelefteq G$ 이다. 

:::

</div></br>

::: {.proof}

($1$) $x\in H \cap K,\, x \ne 1_G$ 이면 $f(1_G,1_G)=f(x^{-1}, x)=1_G$ 이므로 $f$ 는 단사가 아니다. $H \cap K = \{1_G\}$ 이고 $h_1k_1 = h_2k_2$ 라 하자. $h_2^{-1}h_1 = k_2k_1^{-1} \in H \cap K$ 이므로 $h_1=h_2,\, k_1=k_2$ 이다. 즉 $f$ 는 단사이다.

($2$) $f \in \text{Hom} (H \times K,G)$ 라면 $f(h_1, k_1)f(h_2, k_2) = f(h_1h_2, k_1k_2)$ 이어야 한다. 즉 $h_1k_1h_2k_2 = h_1h_2k_1k_2$ 이어야 하므로 $k_1h_2 = h_2k_1$ 이어야 한다. 즉 임의의 $h \in H,\, k\in K$ 에 대해 $hk=kh$ 이어야 한다. 이 역도 성립한다는 것은 쉽게 보일 수 있다.

($3$) $1_G\in HK$ 임은 자명하다. $H \trianglelefteq G$ 임을 가정하자. $h_1,\,h_2 \in H$, $k_1,\,k_2\in K$ 에 대해 $h_2' = k_1h_2k_1^{-1}\in H$ 라고 하면, 

$$
(h_1k_1)(h_2k_2)=h_1k_1 h_2 k_1^{-1}k_1k_2 = h_1h_2'k_1k_2 \in HK
$$

이다. 즉 연산에 대해 닫혀 있다. $h\in H,\, k\in K$ 에 대해 $h' = k^{-1}h^{-1}k$ 라 하면 $h'\in H$ 이므로 

$$
(hk)^{-1}=k^{-1}h^{-1}= k^{-1}h^{-1}kk^{-1}=h'k^{-1}\in HK
$$

이다. 따라서 $HK \le G$ 이다.

($4$) 우선 $H\cap K = \{1_G\}$ 이며 $HK=G$ 이고 $H\trianglelefteq G,\, K \trianglelefteq G$ 임을 가정하자. $H \cap K = \{1_G\}$ 이므로 $f$ 는 단사이다. $H \trianglelefteq G,\, K \trianglelefteq G$ 이므로 $h\in H,\, k\in K$ 에 대해 $hkh^{-1}k^{-1}$ 은 $(hkh^{-1})k^{-1}\in K$ 이며 $h(kh^{-1}k^{-1})\in H$ 이므로 $hkh^{-1}k^{-1}=1_G$ 이다. 즉 $hk = kh$ 이므로 $f$ 는 준동형사상이다. $HK=G$ 이므로 $f$ 는 동형사상이다.

이제 $f$ 가 동형사상임을 가정하자. $f$ 가 단사이므로 $H \cap K=\{1_G\}$ 이며, 준동형사상이므로 $hk=kh$ 이다. 전사이므로 $HK=G$ 이다. $g\in G$ 에 대해 $g=hk$ 를 만족하는 $h\in H,\, k\in K$ 가 존재한다. $h'\in H$ 에 대해 $gh'g^{-1}=hkh'(hk)^{-1}=hkh'k^{-1}h^{-1}=hh'kk^{-1}h^{-1}=hh'h^{-1}\in H$ 이므로 $H \trianglelefteq G$ 이다. 같은 방식으로 $K \trianglelefteq G$ 임을 보일 수 있다. $\square$
:::

</br><div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-MA_multiplicaiton_map_and_homomorphism}

@prp-MA_inner_product_group 의 $f$ 는 동형사상이 아니더라도 전단사 일 수 있다. 예를 들어 $S_3 = \{1,\, x,\,x^2,\,y,\,xy,\,x^2y\}$ 를 생각하자. 여기서 $x^3=y^2=1$ 이며 $x^2y=yx$ 이다. $H=\langle x\rangle,\, K = \langle y \rangle$ 에 대해 $f:H \times K \to S_3$ 를 $f(h, k) = hk$ 로 정의하자. $f$ 는 전단사이지만 $xy\ne yx$ 이므로 $f \notin \text{Hom}(H \times K,\, G)$ 이다.

:::

</div></br>

### Counting Principle

군의 부분군 $H,\,K$ 과 그 곱집합 $HK$ 을 통해 군에 대해 중요한 것을 알 수 있다. 이제 몇가지를 알아보도록 하자.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_herstein_lem_2_5_1}

$H\le G,\, K\le G$ 일 때, $HK = KH \iff HK \le G$ 이다.

:::

</div></br>

::: {.proof}
우선 $HK=KH$ 임을 가정하자. $h\in H,\, k\in K$ 에 대해 $hk=k'h'$ 인 $h'\in H,\, K'\in K$ 가 존재한다. $h_1,\,h_2\in H,\, k_1,\,k_2\in K$ 에 대해 $h_2k_1 = k_1'h_2'$ 인 $h_2'\in H,\, k_2'\in K$ 가 존재하며 $h_1k_1h_2k_2 = h_1 h_2'k_2'k_2 \in HK$ 이다. 또한 $(hk)^{-1}=k^{-1}h^{-1}\in KH = HK$ 이므로 $HK\le G$ 이다.

이제 $HK \le G$ 임을 가정하자. $h\in H,\, k\in K$ 에 대해 $h^{-1}k^{-1}\in HK$ 이다. 그런데 $kh=(h^{-1}k^{-1})^{-1}\in HK$ 이므로 $KH \subset HK$ 이다. 역으로 $hk \in HK$ 에 대해 $(hk)^{-1} k^{-1}h^{-1} \in KH$ 이므로 $HK \subset KH$ 이다. 즉 $HK=KH$ 이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_herstein_thm_2_5_1}

$H,\, K$ 가 $G$ 의 유한부분군일 때 다음이 성립함을 보여라. 

$$
|HK| = \dfrac{|H||K|}{|H \cap K|}.
$$

:::

</div></br>

::: {.proof}

$f:H \times K \to HK$ 를 $f(h,\,k) = hk$ 로 정의하자. $H \cap K = \{1_G\}$ 이면 @prp-MA_inner_product_group 에 의해 $|H||K|=|HK|$ 이다. 이제 한 $|f^{-1}(\{hk\})| =  |H \cap K|$ 임을 보이면 된다. 

$x\in H\cap K$ 라고 하자. $hk = (hx)(x^{-1}k)$ 이며 $hx\in H,\, x^{-1}k\in K$ 이므로 $f^{-1}(\{hk\})$ 는 최소한 $|H \cap K|$ 개의 원소를 가진다. 이제 $hk = h'k'$ 이라고 하자. $h^{-1}h' = kk'^{-1}\in H\cap K$ 이다. $y=h^{-1}h' = kk'^{-1}$ 이라고 하면, $h'=hy,\, k'=y^{-1}k$ 즉 $hk=h'k'$ 이면 어떤 $y\in H \cap K$ 에 대해 $h'=hy,\, k'=y^{-1}k$ 이다. 따라서 $|f^{-1}(\{hk\})| =  |H \cap K|$ 이며 주어진 식이 성립한다. $\square$

:::

</br>

### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">
::: {#exr-artin_2_11_3}

#### Artin 2.11.3

두 무한 순환군의 product group 은 무한순환군이 아님을 보여라. 

:::

</div></br>

::: {.solution}

$A=\langle a\rangle,\, B=\langle b\rangle$ 이 무한순환군이라고 하자. $A\times B= \{(a^m, b^n)\}$ 가 순환군이려면 $A\times B = \langle (a^p, b^q)\rangle$ 이어야 한다. $a^{p+1}b^q\in A\times B$ 이므로 $a^{p+1}b^q = (a^pb^q)^r = a^{pr}b^{qr}$ 을 만족하는 $r\in \mathbb{Z}$ 가 존재해야 하지만 존재할 수 없다. 따라서 $A \times B$ 는 순환군이 아니다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_11_4}

#### Artin 2.11.4

아래의 경우에 대해 $G \cong H \times K$ 인지 여부를 보여라.

&emsp; ($1$) $G=\mathbb{R}^\times$, $H = \{\pm 1\}$, $K = \{x\in \mathbb{R}: x>0\}$.

&emsp; ($2$) $G$ 는 가역인 $2\times 2$ 상삼각행렬의 집합. $H$ 는 가역인 대각행렬, $K$ 는 대각성분이 $1$ 인 $G$ 의 부분집합.

&emsp; ($3$) $G=\mathbb{C} ^\times$, $H=\{z\in G: |z|=1\}$, $K = \{x\in \mathbb{R}: x>0\}$.

:::

</div></br>

::: {.solution}
@prp-MA_inner_product_group 에 따라 $H\cap K = \{1_G\}$, $HK=G$, $H \trianglelefteq G,\, K \trianglelefteq G$ 임을 보이면 된다.

($1$) OK

($2$) $k=\begin{bmatrix} 1 & a \\ 0 & 1 \end{bmatrix} \in K$, $h = \begin{bmatrix} b & 0 \\ 0 & c \end{bmatrix} \in K$ 에 대해 $k^{-1} = \begin{bmatrix} 1 & -a \\ 0 & 1 \end{bmatrix}$ 이며, $khk^{-1}= \begin{bmatrix} b & ac-ab \\ 0 & c \end{bmatrix} \notin H$ 이므로 $H$ 는 $G$ 의 정규부분군이 아니다. 

($3$) OK
:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_11_5}

#### Artin 2.11.5

군 $G_1, \,G_2$ 에 대해 $Z_1,\,Z_2$ 는 각각의 중심이다. 이 때 $G_1\times G_2$ 의 중심은 $Z_1 \times Z_2$ 임을 보여라. 

:::

</div></br>

::: {.proof}

$g_1\in G_1,\,g_2\in G_2,\,z_1\in Z_1,\,z_2\in Z_2$ 에 대해 

$$
(g_1, g_2)(z_1, z_2) =  (g_1 z_1, g_2 z_2) = (z_1,\,z_2)(g_1, g_2)
$$

이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_11_6}

#### Artin 2.11.6

$G$ 의 정규부분군중 하나는 order 3 이며 다른 하나는 order 5 이다. $G$ 에는 order 15 성분이 존재함을 보여라.

:::

</div></br>

::: {.solution}

order 3 부분군과 order 5 부분군은 cyclic group 이다. $A=\langle a \rangle$ 를 order 3 부분군, $B=\langle b \rangle$ 를 order 5 부분군이라고 하자. $bab^{-1}$ 은 $a$ 이거나 $a^2$ 이다. $bab^{-1}=a$ 이면 $ab=ba$ 이므로 $AB=BA$ 이며, 따라서 @prp-MA_herstein_lem_2_5_1 에 따라 $AB\le G$ 이다. $bab^{-1}=a^2$ 이면  $a^2b=a^{-1}b=ba$ 이다. 따라서 $AB=BA$ 이며 $AB\le G$ 이다. $AB = \langle ab\rangle$ 이며 $o(ab)=15$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_11_7}

#### Artin 2.11.7(?)

$H \le G$ 이고 $\varphi \in \text{Hom}(G, H)$ 이며 $h\in H$ 에 대해 $\varphi (h) = h$ 이다. $K=\ker \varphi$ 일 때 product map $H \times K \to G$ 에 대해 무엇을 알 수 있는가?

:::

</div></br>

::: {.solution}

$H \cap K =\{1_G\}$ 이므로 $f$ 는 단사이다. $K \trianglelefteq G$ 이므로 $HK \le G$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_11_8}

#### Artin 2.11.8

$G, G', H$ 가 군이다. $A,\,B$ 가 아래와 같이 정의되었을 때 $A$ 와 $B$ 사이에 전단사 함수가 존재함을 보여라.

$$
\begin{aligned}
A &=\text{Hom}(H,\, G \times G'), \\
B &= \{ (\varphi,\, \varphi') : \varphi \in \text{Hom}(H, G),\, \varphi' \in \text{Hom}(H, G')\}.
\end{aligned}
$$ 

:::

</div></br>

::: {.solution}

$\pi_1 :G \times G' \to G$ 를 $\pi_1 (g, g')=g$ 로 정의하고 $\pi_2 :G \times G' \to G'$ 을 $\pi_2(g, g')=g'$ 으로 정의하자. 이 때 $\pi_1 (g_1, g_1')\pi_1 (g_2, g_2') = g_1g_2 = \pi_1 ((g_1, g_1')(g_2, g_2'))$ 이므로 $\pi_1 \in \text{Hom}(G\times G', G)$ 이며 같은 방법으로 $\pi_2 \in \text{Hom}(G\times G', G')$ 이다.  

$\Phi \in A$ 에 대해 $\varphi = \pi_1 \circ \Phi$ 라고 하자. 그렇다면

$$
\varphi (h_1)\varphi(h_2) = \pi_1 (\Phi (h_1)) \, \pi_1 (\Phi(h_2)) = \pi_1 (\Phi(h_1)\Phi(h_2)) = \pi_1 (\Phi(h_1h_2)) = \varphi(h_1h_2)
$$

이므로 $\varphi \in \text{Hom}(H, G)$ 이다. 같은 방법으로 $\varphi' = \pi_2 \circ \Phi \in \text{Hom}(H, G')$ 임을 보일 수 있다. 

함수 $f:A \to B$ 를 $f(\Phi) = (\pi_1 \circ \Phi,\, \pi_2 \circ \Phi)$ 로 정의하자. 임의의 $\varphi \in \text{Hom}(H, G)$, $\varphi' \in \text{Hom}(H, G')$ 에 대해 $\Phi = (\varphi, \varphi')$ 이 정해지므로 $f$ 는 전사이며, $f$ 가 단사인것도 쉽게 보일 수 있다. 따라서 $f$ 는 전단사이다. 


:::


</br>

## 몫군과 제1 동형정리

### 몫군과 canonical map

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_product_of_cosets_of_normal_subgroup}

$N \trianglelefteq G$ 이고 $a,\, b\in G$ 일 때 $(aN)(bN) = \{an_1bn_2 : n_1,\,n_2\in N\}=abN$ 이다.

:::

</div></br>

::: {.proof}

$b^{-1}n_1b \in N$ 이므로 $n'=b^{-1}nb$ 라 하자. $an_1bn_2 = abb^{-1}n_1bn_2=abn_1'n_2 \in abN$ 이므로 $(aN)(bN)\subset abN$ 이다. $abn\in abN$ 에 대해 $abn=(a1_G)(bn)\in (aN)(bN)$ 이므로 $(aN)(bN) =abN$ 이다.$\square$
:::

</br>

이로부터 $N \trianglelefteq G$ 일 때 $N$ 에 의한 cosets 의 집합에 @prp-MA_product_of_cosets_of_normal_subgroup 에서와 같이 $(aN)(bN)=abN$ 이라는 연산을 부여할 수 있다는 것을 즉, 이 연산이 잘 정의된다는 것을 알 수 있다. 이 때 $N$ 에 의한 $G$ 의 cosets 의 집합을 $G/N$ 이라고 하자.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_prouct_group}

$N \trianglelefteq G$ 일 때 $G/N$ 에 @prp-MA_product_of_cosets_of_normal_subgroup 의 연산을 부여하면 $G/N$ 은 군이다.

:::

</div></br>

::: {.proof}

$N\in G/N$ 이며 $g\in G$ 에 대해 $(gN)(N) = gN$ 이므로 $gN$ 이 $G/N$ 에서의 항등원이다. $gN\in G/N$ 에 대해 $(gN)(g^{-1}N) = N$ 이므로 $(gN)^{-1} = g^{-1}N$ 이다. 즉 역원이 잘 정의된다. 따라서 $G/N$ 은 군이다.

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-MA_quotient_group}
#### 몫군

군 $G$ 와 그 정규부분군 $N$ 에 대해 $G/N$ 을 그 cosets 의 집합으로 정의하고 $aN,\,bN\in G/N$ 에 대해

$$
(aN)(bN) =  abN
$$

이라는 연산을 부여하면 $G/N$ 은 군이며, 이 때 $G/N$ 을 $N$ 에 의한 $G$ 의 **몫군 (quotient group)** 이라고 한다.

:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-MA_canonical_map_for_quotient_group}

$N \trianglelefteq G$ 일 때 함수 $\pi : G\to G/N$ 을 $\pi (g) = gN$ 으로 정의하면 $\pi\in \text{Hom}(G,\, G/N)$ 이다. 군과 몫군 사이에 정의된 이 준동형사상을 **canonical map** 이라고 한다.

:::

</div></br>

### 제 1 동형정리

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-MA_map_with_homomorphism_property}

$G$ 가 군이고, $Y$ 는 연산에 대해 닫혀있는 집합이라고 하자. 각 군에서의 연산을 곱하기로 표현하자. 함수 $\phi : G \to Y$ 가 전사이며, 준동형사상과 같이 모든 $g_1,\,g_2\in G$ 에 대해 $\phi(g_1)\phi(g_2) = \phi(g_1g_2)$ 를 만족한다면 $Y$ 는 군이며 따라서 $\phi \in \text{Hom}(G, Y)$ 이다.

:::

</div></br>

::: {.proof}

우선 $Y$ 에서의 연산이 결합법칙이 성립함을 보이자. 모든 $\phi$ 가 전사이므로 모든 $y$ 에 대해 $y=\phi(x)$ 인 $x\in G$ 가 존재한다. 따라서, $y_1,\,y_2,\,y_3\in Y$ 에 대해 $y_i = \phi(g_i)$ ($i=1,\,2,\,3$) 라 하면, 

$$
\begin{aligned}
y_1(y_2y_3) &= \phi(g_1)(\phi(g_2)\phi(g_3))=\phi(g_1(g_2g_3))=\phi((g_1g_2)g_3) = \phi(g_1g_2)\phi(g_3) \\
& = (y_1y_2)y_3
\end{aligned}
$$

이다. 즉 $Y$ 에서의 연산은 결합법칙이 성립한다. $1_Y = \phi(1_G)$ 라 하자. $y_11_Y = \phi(g_11_G)=\phi(g_1)=y_1$ 이므로 $1_Y$ 는 $Y$ 에서의 연산의 항등원이다. $y = \phi(g)$ 에 대해 $y'=\phi(g^{-1})$ 이라고 하면 $yy'=\phi(gg^{-1})=1_Y$ 이므로 $y$ 에 대한 역원이 존재한다. 따라서 $Y$ 는 군이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-MA_first_isomorphism_theorem}

#### 제1 동형정리

$\varphi \in \text{Hom}(G,\,G')$ 이 전사이며 $N = \ker \varphi$ 라 하자. 이 때 $G/N$ 과 $G'$ 은 동형이다. 즉 $G/N \cong G'$ 이다.

:::

</div></br>

::: {.proof}


@prp-MA_kernel_and_normal_subgroup 에 따라 $N = \ker \varphi  \trianglelefteq G$ 이므로 몫군 $G/N$ 을 생각 할 수 있다. 함수 $\theta : G/N \to G'$ 을 $\theta (gN)= \varphi(g)$ 로 정의하자. $g_1\ne g_2,\, g_1N=g_2N$ 인 $g_1,\,g_2\in G$ 에 대해 $g_1=g_2n,\, n\in N = \ker \varphi$ 인 $n$ 이 존재하며 $\varphi(g_1)= \varphi(g_2n)=\varphi(g_2)$ 이므로 이 함수 $\theta$ 는 잘 정의된다. 또한 

$$
\theta(g_1N)\theta(g_2N) =  \varphi(g_1)\varphi(g_2) = \varphi(g_1g_2) = \theta(g_1g_2N)
$$

이므로 $\theta \in \text{Hom}(G/N,\, G')$ 이다. 임의의 $\varphi$ 가 전사이므로 임의의 $g'\in G$ 에 대해 $g'=\varphi (g)$ 인 $g\in G$ 가 존재하므로 $\theta$ 는 전사이다. $\varphi (g_1)= \varphi(g_2)$ 이면 $g_1N = g_2N$ 이므로 $\theta$ 는 전사이다. 따라서 $\theta \in \text{Iso} (G/N,\, G')$ 이다 $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-MA_first_isomorphism_theorem}

$\varphi \in \text{Hom}(G,\, G')$ 이며 $N =\ker \varphi$ 이고 $H' = \text{im}\,(\varphi)$ 이면 $G/N \cong H'$ 이다.
:::

</div></br>


### 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_12_1}

#### Artin 2.12.1

$H\le G$ 가 $G$ 의 정규부분군이 아닐 때 어떤 두 왼쪽 잉여류의 곱은 왼쪽 잉여류가 아님을 보여라.

:::

</div></br>

::: {.solution}

$L_H$ 를 $H$ 에 의한 $G$ 의 왼쪽 잉여류의 집합이라고 하고 위 명제의 대우명제를 증명한다. 즉. $\forall a,\,b\in G$ 에 대해 $(aH)(bH) \in L_H$ 이면 $H \trianglelefteq G$ 임을 증명하자. 임의의 $a,\,b\in G$ 에 대해 $(aH)(bH)=cH$ 인 $c\in G$ 가 존재한다고 하자. 즉 임의의 $h_1,\,h_2\in H$ 에 대해 $ah_1bh_2 = ch_3$ 를 만족하는 $h_3$ 가 존재하므로 $h_1 b = a^{-1}c h_3 h_2^{-1}$ 이다. 이로부터 $Hb = a^{-1}cH$ 임을 알며 이는 $H$ 에 대한 $G$ 의 왼쪽 잉여류의 집합과 오른쪽 잉여류의 집합이 같다는것을 뜻한다. @cor-MA_normal_subgroup_condition 로부터 $H \trianglelefteq G$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_12_3}

#### Artin 2.12.3

$P$ 가 군 $G$ 의 분할이며 $\forall A,\,B\in P,\, \exists C\in P,\, AB \subset C$ 라고 하자. $N\in P,\, 1_G\in N$ 이면 $N\trianglelefteq G$ 임을 보여라.

:::

</div></br>

::: {.solution}

$A\in P$ 라고 하자. $a\in A$ 라면 $a\in AN,\, a\in NA$ 이므로 $AN\subset A,\, NA\subset A$ 이다. 이제 $N\le G$ 임을 보이자. $NN \subset N$ 이어야 하므로 $N$ 은 연산에 대해 닫혀 있다. $n\in N$ 에 대해 $n^{-1}\in B$ 라 하면 $1_G\in NB$ 이어야 하므로 $B=N$ 이다. 즉 $N \le G$ 이다. $a,\, a'\in A$ 이라 하자. $x\in aN$ 이면 $x=an,\, n\in N$ 

- to be done -
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_12_4}

$H = \{\pm 1,\, \pm i\}$ 는 $G=\mathbb{C}^\times$ 의 부분군이다. $G$ 에 대한 $H$ 의 잉여류를 기술하라. $G/H$ 는 $G$ 와 동형인가?

:::

</div></br>

::: {.solution}

$H\trianglelefteq G$ 임은 자명하다. $\varphi : \mathbb{C}^\times \to \mathbb{C}^\times$ 를 $\varphi (z) = z^4$ 로 정의하면 $\varphi \in \text{Hom}(\mathbb{C}^\times, \mathbb{C}^\times)$ 임은 쉽게 보일 수 있으며, $\text{im}(\varphi)= \mathbb{C}^\times$ 이므로 $G/H \cong G$ 이다.

:::

</br>


## 연습문제 {.unnumbered}

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-herstein_2_6_38}

#### Herstein 2.6.38$^\ast$

$G$ 가 유한군이며 아벨군라고 하자. 모든 양의 정수 $n$ 에 대해 $x^n=1_G$ 를 만족하는 $x\in G$ 는 $n$ 개 이하라면 $G$ 가 순환군이라는 것을 보여라.

:::

</div></br>

::: {.proof}

$a,\,b \in G$ 에 대해 $\gcd (o(a), o(b))=1$ 이면 $a, b$ 에 의해 생성되는 부분군은 $ab$ 에 의한 순환군이다. 따라서 $G$ 가 순환군이 아니라면 어떤 $a,\,b\in G$ 에 대해 $a^m \notin \langle b\rangle$ 이며 $\gcd(o(a), o(b)) = d>1$ 이어야 한다. 이 때 $o(ab)= \text{lcm}(o(a), o(b))$ 이며, $x^{o(ab)}=1_G$ 를 만족하는 $x$ 의 갯수는 $a, b$ 에 의한 부분군만 생각하더라도 $o(a)\cdot o(b) > \text{lcm}(o(a), o(b))$ 이다.  

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_M_1}

#### Artin 2.M.1

$2 \times 2$ 정수행렬 $A$ 는 역행렬도 정수행렬이다. $A$ 의 첫번째 열에 대해 기술하라.

:::

</div></br>

::: {.solution}

$r=ad-bc$ 라고 하자. $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$ 이면 $A^{-1} = \dfrac{1}{r}\begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$ 이다. $A^{-1}$ 가 정수행렬이므로 $r=(ad-bc)$ 가 $a,\,b,\,c,\,d$ 각각을 나누어야 한다. $r$ 은 $a,\,c$ 의 최대공약수의 배수이므로 $r$ 은 $a, c$ 의 최대공약수 이어야 한다. 즉 $r=ad-bc$ 에서 $r$ 은 $a, c$ 의 최대공약수이며 $b, d$ 는 $\gcd(a, c) = \pm (ad-bc)$ 를 만족하게 해야 한다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_M_2}
#### Artin 2.M.2

유한군 $G$ 에 대해 다음을 보여라.

&emsp;($1$) $|G|$ 가 짝수이면 order 2 인 성분을 포함함을 보여라.

&emsp;($2$) $|G|=21$ 이면 order 3 성분을 포함함을 보여라.

:::

</div></br>

::: {.proof}

($1$) $o(a)=2$ 이면 $a^2=1_G$ 이다. 모든 $g\in G$ 에 대해 $a\ne a^{-1}$ 이라면 $G$ 는 $1_G$ 를 제외하고는 $\{x,\,x^{-1}\}$ 짝을 포함해야 하므로 $|G|$ 는 홀수 order 를 갖는 군일 수 밖에 없다.

($2$) $G$ 가 order 21 순환군이면 $\langle g \rangle = G$ 일 때 $o(g^7)= 3$ 이므로 order 3 성분을 포함한다. 이제 $G$ 가 순환군이 아니며 $1_G$ 를 제외한 모든 성분의 order 가 7 이라면 $|G|=1+6m$, $m\in \mathbb{Z}_+4$ 이어야 한다. 따라서 $G$ 는 order 3 성분을 포함한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_M_3}

#### Artim 2.M.3

$|G|=6$ 일 때 아래의 경우에 대해 $G$ 를 분류하시오.

&emsp;($1$) $G$ 가 order 6 인 성분을 포함한다.

&emsp;($2$) $G$ 는 order 3 성분을 포함하며 order 6 성분을 포함하지 않는다.

&emsp;($3$) $G$ 의 모든 성분은 order 가 1 이거나 2 이다.

:::

</div></br>

::: {.solution}

($1$) Order 6 순환군

($2$) @exr-artin_2_M_2 ($1$) 에 의해 order 2 성분도 포함해야 한다. $o(x)=3,\,o(y)=2$ 라 하자. $G$ 는 $1_G,\,x,\,x^2,\,y$ 를 포함하며 $xy,\, x^2y$ 를 포함해야 한다. 


($3$) $x,\,y \in G$ 일 때 $o(xy)=2$ 이면 $(xy)=(xy)^{-1} = yx$ 이므로 아벨군이다. order 2 성분 2개로 생성되는 아벨군은 $\{1_G,\,x,\,y,\,xy\}$ 의 order $4$ 군이다. order 2 성분 3개로 생성되는 아벨군은 $\{1,\,x,\,y,\,z,\,xy,\,yz,\,zx\}$ 의 order $7$ 군이다. 따라서 모든 성분이 order 1 이거나 order 2인 order 6 군은 존재하지 않는다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_M_4}

#### Artin 2.M.4

[일반적으로 반군(semigroup) 은 이항연산에 결합법칙이 성립하는 집합이며 항등원을 포함하는 반군을 monoid 라고 한다.]{.aside}
**반군(semigroup)** 은 결합법칙이 성립하고 항등원을 포함하는 집합이다. 성분에 대한 역원이 존재할 필요는 없으며 제거규칙도 성립할 필요가 없다. 반군 $S$ 가 $\{1,\,s,\,s^2,\ldots\}$ 와 같이 $s$ 의 non negative power 에 의해 생성되는 집합과 같을 때 $S$ 는 $s$ 에 의해 생성된다고 한다. 하나의 성분에 의해 생성되는 반군을 분류하라.

:::

</div></br>

::: {.solution}

어떤 $m<n$ 에 대해 $s^m=s^n$ 이라면 $s^{(n-m)+k} = s^ms^{-n}s^k = s^k$ 이므로 $S$ 는 유한 반군이다. 모든 $m<n$ 에 대해 $s^m \ne s^n$ 이면 $S$ 는 무한 반군이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_M_5}

#### Artin 2.M.5

$S$ 가 유한 반군이며 제거 규칙이 성립하면 $S$ 가 군임을 보여라.

:::

</div></br>

::: {.solution}

$S = \{1_S=s_1,\,s_2,\ldots,\,s_n\}$ 이라 하자. 임의의 $s\in S$ 에 대해 $ss_i = ss_j \implies s_i = s_j$ 가 성립한다(제거 규칙). 따라서 $s_i \ne s_j \implies ss_i \ne ss_j$ 이므로 모든 $s$ 에 대해 어떤 $s^{-1}\in S$ 가 존재하여 $ss^{-1}=1_S$ 이다. 또한 같은 방법으로 어떤 \overline{s^{-}}\in S$ 가 존재하여 $\overline{s^{-1}}s=1_S$ 임을 보일 수 있다. 

$$
\overline{s^{-1}} = \overline{s^{-1}}(ss^{-1})= (\overline{s^{-1}}s)s^{-1} = s^{-1}
$$

임을 알 수 있다. 즉 $s$ 에 대한 역원이 존재한다. 따라서 $S$ 는 군이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_M_9}

#### Artin 2.M.9

$H,\, K \le G$ 이고 $g\in G$ 일 때 $HgK = \{hgk: h\in H,\, k\in K\}$ 를 **double coset** 이라고 한다. Double cosets 는 $G$ 를 분할하는가?

:::

</div></br>

::: {.solution}

$G$ 에서의 Equivalence relatin $\sim$ 을 다음과 같이 정의한다.

$$
a \sim  b \iff \exists h\in H,\, k\in K,\, \text{s.t.}\, a=hbk
$$

(Reflexivity) 우선 $1_G\in H,\, 1_G\in K$ 이므로 $a\sim a$ 이다.

(Symmetry) $a\sim b$ 이면 $a=hbk$ 이며 $b=h^{-1}ak^{-1}$ 이므로 $b\sim a$ 이다.

(Transivitivy) $a\sim b,\, b \sim c$ 라고 하자. $a=hbk,\, b=h'ck'$ 일 때 $a=hh'ckk'$ 이므로 $a \sim c$ 이다. 

따라서 double coset 의 집합은 $G$ 를 분할한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-artin_2_M_10}

#### Artim 2.M.10

$H \le G$ 일 때 $HgH = gH \iff H \trianglelefteq G$ 임을 보여라.

::: 

</div></br>

::: {.proof}

$H \trianglelefteq G$ 임을 가정하자. $h,\,h'\in H'$ 에 대해 $hgh' = gg^{-1}hgh' \in gH$ 이므로 $HgH \subset gH$ 이다. $gh = 1_G gh\in HgH$ 이므로 $HgH = gH$ 이다.

$HgH = gH$ 임을 가정하자. $gh = h_1gh_2$ 이므로 $ghh_2^{-1} = h_1g$ 이다. 즉 모든 $g\in G$ 에 대해 $gH = Hg$ 이므로 $H \trianglelefteq G$ 이다.

:::

</br>

