---
title: "선형사상과 행렬"
number-sections: true
number-depth : 2
crossref:
  chapters: true
---


우리는 벡터와 선형사상이 특정한 기저에서 행렬로 표현된다는 것을 알았다. 또한 행렬식을 포함하여 행렬을 다루는 데 중요한 함수와 성질을 알았다. 여기서는 선형사상을 행렬로 표현할 때의 다양한 특성에 대해 알아볼 것이다. 이를 위해 우선 행렬에 대해 몇가지 더 알아보기로 하자.

</br>

## 행렬에서의 다양한 개념들

여기서는 앞으로 사용할 다양한 행렬에 관한 기본적인 용어를 정의한다. 앞서 정의한 것도 정리하는 의미에서 다시 서술한다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-basic_matrix_notation}

#### 행렬에서의 기본적인 정의들

1. 행의 갯수와 열의 갯수가 같은 행렬을 **정사각 행렬(square matrix)** 라 한다.

2. 행렬에서 행과 열이 같은 위치의 성분을 **대각성분 (diagonal elements)** 이라 한다.

3. 항등행렬 $\boldsymbol{I}$ 는 정사각행렬로 $(\boldsymbol{I})_{ij}=\delta_{ij}$ 로 정의된다. 즉 대각성분이 $1$ 이고 나머지 성분은 $0$ 인 행렬이다. $n \times n$ 행렬 $\boldsymbol{I}$ 와 $\boldsymbol{v} \in \mathbb{F}^{n}$ 에 대해, $\boldsymbol{Iv}=\boldsymbol{v}$ 이며 $n \times m$ 행렬 $\boldsymbol{A}$ 와 $m \times n$ 행렬 $\boldsymbol{B}$ 에 대해 $\boldsymbol{IA}=\boldsymbol{A},\, \boldsymbol{BI}=\boldsymbol{B}$ 이므로 항등행렬이라 불린다. 항등행렬의 크기를 고려할 때 $n\times n$ 항등행렬을 $\boldsymbol{I}_n$ 으로 표현한다.

4. $m \times n$ 행렬 $\boldsymbol{A}$ 에 대해 $(\boldsymbol{B})_{ij}= (\boldsymbol{A})_{ji}$ 인 $n \times m$ 행렬 $\boldsymbol{B}$ 를 $\boldsymbol{A}$ 의 **전치행렬 (transposed matrix)** 이라 하고 $\boldsymbol{A}^T$ 라 쓴다.  

5. 정사각행렬에서 대각성분을 제외한 모든 성분이 $0$ 일 때 **대각 행렬 (diagonal matrix)** 라 한다. 대각성분의 아래 행이 모두 $0$ 인 행렬을 **상 삼각 행렬 (upper triangular matrix)** 라 한다. 대각성분의 위 행이 모두 $0$ 인 행렬을 **하 삼각 행렬 (lower triangular matrix)** 라고 한다. 예를 들어 아래 행렬에서 $\boldsymbol{D}$ 는 대각행렬, $\boldsymbol{U}$ 는 상삼각행렬, $\boldsymbol{L}$ 은 하삼각행렬이다.

$$
\boldsymbol{D} = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 1\end{pmatrix},\qquad \boldsymbol{U} = \begin{pmatrix} 1 & 3 & 2 \\ 0 & 2 & 1 \\ 0 & 0 & 3 \end{pmatrix} , \qquad \boldsymbol{L} = \begin{pmatrix} 3 & 0 & 0 \\ 1 & 1 & 0 \\ 2 & 5 & 1\end{pmatrix}
$$


6. $n \times n$ 정사각 행렬 $\boldsymbol{A}$ 에 대해 어떤 $n \times n$ 행렬 $\boldsymbol{B}$ 가 존재하여 $\boldsymbol{AB}=\boldsymbol{BA}=\boldsymbol{I}_n$ 일 때 $\boldsymbol{A}$ 를 **가역행렬 (invertible matrix)** 라 하고, $\boldsymbol{B}$ 를 $\boldsymbol{A}$ 의 **역행렬(inverse matrix)** 이라 한다. $\boldsymbol{A}$ 의 역행렬은 $\boldsymbol{A}^{-1}$ 로 표현한다.

:::
:::

</br>


이제 행렬의 몇가지 기본적인 성질들을 보이려고 한다. 이것들은 유용하긴 하지만 Theorem 이나 Lemma, Proposition 등의 좀 거창인 이름을 붙일 정도는 아니기 때문에 **보기** 로 돌린다.

</br>

::: {#exm-multiplication_of_diagonal_matrix}

대각행렬의 곱은 대각행렬이다. 상 삼각 행렬의 곱은 상 삼각 행렬이다. 하 삼각 행렬의 곱은 하 삼각 행렬이다.

:::

::: {.proof}
$\boldsymbol{D},\,\boldsymbol{F}$ 가 모두 $n \times n$ 대각행렬이라 하자. $D_{ij} = d_i \delta_{ij},\, F_{ij} = f_i \delta_{ij}$ 이므로, 

$$
(\boldsymbol{DF})_{ij} = \sum_k D_{ik}F_{kj} = \sum_k d_i \delta_{ik} f_j \delta_{kj} = d_i f_i \delta_{ij} 
$$

이므로 $\boldsymbol{DF}$ 는 대각행렬이다.

$\boldsymbol{U},\, \boldsymbol{V}$ 가 모두 $n \times n$ 상삼각행렬이라 하자. $i>j$ 에 대해 $U_{ij}=0,\, V_{ij}=0$ 이므로,

$$
(\boldsymbol{UV})_{ij} = \sum_k U_{ik}V_{kj} = \sum_{k\ge i, k \le j} U_{ik}V_{kj}
$$

이다. 그런데 $i>j$ 이면 $i \le k \le j$ 인 $k$ 가 존재하지 않으므로 $(\boldsymbol{UV})_{ij} =0$ 이다. 즉 $\boldsymbol{UV}$ 는 상 삼각 행렬이다. 하삼각 행렬의 곱이 하 삼각행렬이라는 것은 비슷한 방법으로 보일 수 있다. $\square$

:::

</br>

::: {#exm-determinant_of_upper_lower_triangular_matrix}

대각 행렬, 상 삼각 행렬과 하삼각 행렬의 행렬식은 그 대각성분의 곱과 같다. $\boldsymbol{A}$ 가 대각행렬, 상 삼각 행렬 혹은 하 삼각 행렬일 때,

$$
\det (\boldsymbol{A}) = \prod_{i=1}^n A_{ii}
$$

이다.
:::

::: {.proof}
$n\times n$ 행렬 $\boldsymbol{A}$ 가 상삼각 행렬 이라 하자. $i>j$ 이면 $A_{ij}=0$ 이다.
$$
\det (\boldsymbol{A}) = \sum_{\sigma \in S_n} \text{sgn}(\sigma) \prod_{i=1}^n A_{i \sigma(i)}
$$
에서 $\displaystyle \prod_{i=1}^n A_{i\sigma(i)} \ne 0$ 이려면 모든 $i=1,\ldots,\,n$ 에 대해 $\sigma(i)\ge i$  이어야 한다. 그런데 가능한 경우는 $\sigma(1) = 1,\, \sigma(2) = 2,\ldots$ 일 수 밖에 없으며 따라서, 
$$
\det (\boldsymbol{A}) = \text{sgn}(i_d) A_{11} \cdots A_{nn} = \prod_{i=1}^n A_{ii}
$$
이다. $\boldsymbol{B}$ 가 하 삼각 행렬이면 $\boldsymbol{B}^T$ 는 상 삼각 행렬이므로 역시 행렬식은 대각성분의 곱이다. 대각행렬은 상삼각행렬이며 하 삼각 행렬이므로 역시 그 행렬식은 대각성분의 곱이다. $\square$ 

:::

</br>

::: {#exm-transpose_matrix}

#### 전치행렬의 성질

$\boldsymbol{A}$ 가 $m \times n$ 행렬 $\boldsymbol{B}$ 가 $n \times l$ 행렬이며 $\lambda \in \mathbb{F}$ 일 때 다음이 성립한다.

&emsp; ($1$) $\left(\boldsymbol{A}^{T}\right)^{T} = \boldsymbol{A}$, 

&emsp; ($2$) $(\lambda \boldsymbol{A})^T = \lambda (\boldsymbol{A})^T$

&emsp; ($3$) $(\boldsymbol{AB})^T = \boldsymbol{B}^T\boldsymbol{A}^T$
:::

::: {.proof} 

($\text{3}$) 만을 증명한다.

$$
\begin{aligned}
\left(\left( \boldsymbol{AB} \right)^T \right)_{ij} = (\boldsymbol{AB})_{ji} = \sum_{k=1}^n A_{jk} B_{ki} = \sum_{k=1}^n \left( \boldsymbol{B}^T\right)_{ik}\left(\boldsymbol{A}^T\right)_{kj} = (\boldsymbol{B}^T\boldsymbol{A}^T)_{ij}
\end{aligned}
$$
$\square$

:::


</br>

::: {#exm-inverse_matrix}

#### 역행열의 성질

$\boldsymbol{A},\,\boldsymbol{B}$ 가 가역행렬이고 $\lambda \in \mathbb{F}$ 일 때 다음이 성립한다.

&emsp; ($1$) $\left(\boldsymbol{A}^{-1}\right)^{-1} = \boldsymbol{A}$, 

&emsp; ($2$) $(\lambda\boldsymbol{A})^{-1} = \dfrac{1}{\lambda} \boldsymbol{A}^{-1}$,

&emsp; ($3$) $(\boldsymbol{AB})^{-1} = \boldsymbol{B}^{-1}\boldsymbol{A}^{-1}$,
:::

</br>

## 행간소 사다리꼴 행렬을 통한 선형사상의 이해

우리는 앞장에서 행 간소 사다리꼴을 구하는 방법을 배웠지만 그것이 얼마나 유용한지, 어디에 사용하는지는 직접접으로 보이지 않았다. 이제 행 간소 사다리꼴이 왜 필요한지에 대해 알아볼 것이다. 그러나 거기까지 가기 전에 조금 준비운동이 필요하다.

</br>

### 행공간과 열공간

행렬의 행벡터와 열벡터에 의해 span 되는 벡터공간을 생각 할 수 있으며 이를 각각 행공간 열공간이라고 한다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-column_space_row_space}

#### 행공간, 열공간

행렬 $\boldsymbol{A}$ 의 모든 행벡터에 의해 span 되는 벡터공간을 $\boldsymbol{A}$ 의 **행공간 (row space)** 이라고 한다. 마찬가지로 모든 열벡터에 의해 span 되는 벡터공간을 행렬 $\boldsymbol{a}$ 의 **열공간 (column space)** 라고 한다. 따라서 $\boldsymbol{A}$ 의 행공간은 $\text{span}(\boldsymbol{A}_{1:},\, \boldsymbol{A}_{2:},\ldots)$ 이며 열공간은 $\text{span}(\boldsymbol{A}_{:1}, \, \boldsymbol{A}_{:2},\ldots)$ 이다.

:::
:::

</br>

::: {#exm-column_space_row_space}

$\boldsymbol{A} \in \mathcal{M}_{m \times n}(\mathbb{F})$ 이라면 $\boldsymbol{A}$ 의 행공간은 $\mathcal{M}_{1 \times n}(\mathbb{F})$ 의 부분공간이며 $\boldsymbol{A}$ 의 열공간은 $\mathcal{M}_{m}(\mathbb{F})$ 의 부분공간이다. 

:::


</br>

선형사상에서 $\ker,\, \text{im},\, \text{nullity},\, \text{rank}$ 를 정의했듯이 행렬에 대해서도 정의 할 수 있다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-kernel_of_matrox}

#### 행렬의 $\ker$ 과 $\text{im}$
$\boldsymbol{A} \in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 $\ker (\boldsymbol{A})$, $\text{im} (\boldsymbol{A})$, $\text{nullity} (\boldsymbol{A})$, $\text{rank} (\boldsymbol{A})$ 를 다음과 같이 정의한다.

$$ 
\begin{aligned}
\ker (\boldsymbol{A}) &= \{ \boldsymbol{x} \in \mathcal{M}_{n}(\mathbb{F}) : \boldsymbol{Ax} = \boldsymbol{0}\}, \\
\text{im} (\boldsymbol{A}) & = \{ \boldsymbol{Ax} : \boldsymbol{x} \in \mathcal{M}_m(\mathbb{F})\}, \\
\text{nullity} (\boldsymbol{A}) &= \dim (\ker (\boldsymbol{A})), \\
\text{rank} (\boldsymbol{A}) & =  \dim (\text{im} (\boldsymbol{A})).
\end{aligned}
$$

:::
:::

</br>

::: {#prp-rank_of_matrix}

행렬 $\boldsymbol{A}$ 에 대해 $\text{im}(\boldsymbol{A})$ 는 $\boldsymbol{A}$ 의 열공간이다.

:::

::: {.proof}
$\boldsymbol{A} = \begin{bmatrix} \boldsymbol{A}_{:1} & \cdots & \boldsymbol{A}_{:n}\end{bmatrix}$ 이고 $\boldsymbol{x} = \begin{bmatrix} x_1  & \cdots & x_n\end{bmatrix}^T$ 라 하면, 

$$
\boldsymbol{Ax} = x_1 \boldsymbol{A}_{:1} + \cdots + x_n \boldsymbol{A}_{:n}
$$

이다. 따라서 (이미 짐작 할 수 있듯이) $\text{im} (\boldsymbol{A}) = \text{span}(\boldsymbol{A}_{:1}, \ldots, \boldsymbol{A}_{:n})$ 이므로 $\text{im}(\boldsymbol{A})$ 는 $\boldsymbol{A}$ 의 열공간이다. $\square$
:::

</br>

우리는 앞서 가역 연산자는 기저를 다른 기저로 바꾸는 연산자라는 것을 알았다(@cor-basis_transformation). 이제 가역변환에 의해 변하는 것과 변하지 않는 것을 알아보자.


::: {#lem-same_range_reduced_echelon_form}
$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 어떤 가역 변환 $\boldsymbol{S}$ 를 수행했을 때 

$$
\begin{aligned} 
\ker (\boldsymbol{A}) &= \ker (\boldsymbol{SA}), \\
\text{rank} (\boldsymbol{A}) &= \text{rank} (\boldsymbol{SA})
\end{aligned}
$$

이다.
:::

::: {.proof}

$\boldsymbol{S}$ 가 가역행렬이므로 $\boldsymbol{Av}=\boldsymbol{0} \iff \boldsymbol{SAv}=\boldsymbol{0}$ 이다. 따라서 $\ker \boldsymbol{A} = \ker (\boldsymbol{EA})$ 이다. 따라서 선형사상의 기본정리(@thm-rank_nullity) 에 의해 $\dim (\text{im} (\boldsymbol{A})) = \dim (\text{im} (\boldsymbol{EA}))$ 이므로 $\text{rank} (\boldsymbol{A}) = \text{rank} (\boldsymbol{EA})$ 이다. $\square$ 


::::

</br>

행렬 $\boldsymbol{A}$ 가 유한번의 기본 행 연산을 통해 행 간소 사다리꼴 $\boldsymbol{A}'$ 이 되었다면 $\boldsymbol{A}'$ 을 $\boldsymbol{A}$ 의 행 간소 사다리꼴 형태라고 부르겠다. 행렬과 행 간소 사다리꼴 형태에 대해 다음이 성립한다.

::: {#prp-rank_of_reduced_echelon_form}
행렬 $\boldsymbol{A}$ 와 행 간소 사다리꼴 형태 $\boldsymbol{A}'$ 에 대해 다음이 성립한다. 

$$
\begin{aligned}
\ker (\boldsymbol{A}) &= \ker (\boldsymbol{A}'), \\
\text{rank} (\boldsymbol{A}) &= \text{rank} (\boldsymbol{A}').
\end{aligned}
$$
:::

::: {.proof}

모든 행 기본 연산 행렬은 가역행렬이므로 $\boldsymbol{A}'$ 은 가역행렬과 $\boldsymbol{A}$ 의 곱이다. 따라서 @lem-same_range_reduced_echelon_form 에 의해 위의 식이 성립한다. $\square$ 
:::

</br>

행 간소 사다리꼴은 다음과 같은 형태이다. 선행 1 선분에는 밑줄을 그었다.

$$
\begin{bmatrix} 0 & \underline{1} & 2 & 0 & 0 & 3 & 1 \\ 0 & 0 & 0 & \underline{1} & 0 & 0 & 3 \\ 0 & 0 & 0 & 0 & \underline{1} & 2 & 3 \\ 0 & 0 & 0 & 0 & 0 & 0 & 0 \end{bmatrix}
$$

행 간소 사다리꼴 행렬의 열벡터는 선행 1 성분을 포함하는 열과 포함하지 않는 열이 있다. 선행 1 성분을 포함하는 열은 1 성분을 제외한 성분이 모두 $0$ 이며, 영벡터를 포함하여 선행 1 성분을 포함하지 않는 열은 그 앞 열들의 선형결합이다. 따라서 우리는 다음을 알 수 있다.

::: {#prp-dimension_of_row_space}

$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 과 그 행 간소 사다리꼴 행렬 $\boldsymbol{A}'$ 에 대해 다음이 성립한다.
$$
\text{rank} (\boldsymbol{A}) =\text{rank} (\boldsymbol{A}') = [\text{선행 1 성분의 개수}]
$$

:::

</br>

### 행렬의 rank

@def-column_space_row_space 에서 정의했듯이 $m\times n$ 행렬 $\boldsymbol{A}$ 에서 $\text{span}(\boldsymbol{A}_{1:},\ldots,\boldsymbol{A}_{:m})$ 을 행렬 $\boldsymbol{A}$ 의 행공간 이라 한다. 행렬의 행 기본 연산이 모두 행벡터들 사이의 선형결합이라는 것을 이해한다면, 아래 명제는 쉽게 이해 할 수 있다.


::: {#prp-invariance_of_rowspace_by_row_operation}
$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 의 행공간은 행 기본연산에 의해 변하지 않는다.
:::

::: {.proof}
$\boldsymbol{A}$ 가 행 기본 연산에 의해 변환된 행렬을 $\boldsymbol{A}'$ 이라 하자. 우리는 $\text{rank}(\boldsymbol{A})=\text{rank}(\boldsymbol{A}')$ 임을 알고 있다. $\boldsymbol{a}$ 가 $\boldsymbol{A}'$ 의 행공간에 포함된다면 모든 $\boldsymbol{A}_{j:}$ 는 $\boldsymbol{A}$ 의 행공간에 포함되므로 $\boldsymbol{a}$ 역시 $\boldsymbol{A}$ 의 행공간에 포함된다. 즉 $\boldsymbol{A}'$ 은 $\boldsymbol{A}$ 의 부분공간이다. 그런데 두 행공간의 차원이 같으므로 두 행공간은 같다. $\square$

:::

</br>

따라서 행렬 $\boldsymbol{A}$ 의 행공간과 그 행 간소 사다리꼴 형태 $\boldsymbol{A}'$ 의 행공간은 일치한다. 

또하나의 중요한 사실은 행 간소 사다리꼴에서 $0$ 행을 제외한 행들은 모두 선형 독립이다. 영벡터가 아닌 행벡터는 모두 선행 1 성분을 가지고 있으며, 선행 1 성분이 있는 열은 선행 1 성분을 제외하면 모두 $0$ 이므로 영벡터가 아닌 행벡터는 선형 독립임을 알 수 있다. 즉

::: {#prp-dimension_of_row_space}
$\boldsymbol{A}$ 의 행 간소 사다리꼴 형태를 $\boldsymbol{A'}$ 이라고 할 때 다음이 성립한다.

$$
\boldsymbol{A} \text{ 의 행공간의 차원} = \boldsymbol{A'} \text{ 의 행공간의 차원 } = [\text{선행 1 성분의 개수}].
$$
:::

</br>

@prp-dimension_of_row_space 를 생각하면 다음과 같은 결론을 얻는다.

::: {#thm-dimension_of_matrix}

$m\times n$ 행렬 $\boldsymbol{A}$ 에 대해 다음이 성립한다.
$$
\text{rank}(\boldsymbol{A}) = \boldsymbol{A} \text{ 의 행공간의 차원 } = \boldsymbol{A} \text{ 의 열공간의 차원 }
$$
:::


</br>

### 행 간소 사다리꼴의 유일성

행렬의 행 간소 사다리꼴은 유일할까? 우리가 행렬을 행 간소 사다리꼴로 바꾸는 일관된 과정을 거쳤지만 다른 과정도 존재할 수 있다. 이제 어떤 방법으로른 행 간소 사다리꼴로 만들었다면 그 형태는 유일하다는 것을 보이고자 한다. 

</br>

::: {#thm-uniqueness_of_reduced_echelon_form}
행렬의 행 간소 사다리꼴은 유일하다.
:::

::: {.proof}
행렬 $\boldsymbol{A}$ 의 두 행간소 사다리꼴 형태를 $\boldsymbol{S}$ 와 $\boldsymbol{T}$ 라 하자. 

($1$) $\text{rank}(\boldsymbol{S}) = \text{rank}(\boldsymbol{T})$ 이며 이 값은 $\boldsymbol{S}$ 와 $\boldsymbol{T}$ 의 $0$ 행이 아닌 행의 갯수이므로 $\boldsymbol{S}$ 와 $\boldsymbol{T}$ 는 같은 수의 $0$ 행이 아닌 행을 가져야 한다. $1$ 행부터 $l$ 행까지가 $0$ 행이 아니라고 가정하자.


($2$) 우리는 행 기본 연산에 의해 행공간이 바뀌지 않는다는 것을 안다. 따라서 $\boldsymbol{S}$ 와 $\boldsymbol{T}$ 의 행공간이 같아야 한다. $\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 일 때 $\boldsymbol{S}$ 와 $\boldsymbol{T}$ 의 각 행은 $\mathcal{M}_{1\times n}(\mathbb{F})$ 벡터이다. 
$s_i,\,i=1,\ldots,l$ 을 행렬 $\boldsymbol{S}$ 의 $i$ 행에서 첫번째 $1$ 이 나오는 열 인덱스 이라 하자. $t_i,\, i=1,\ldots,l$ 도 $\boldsymbol{T}$ 에 대해 마찬가지로 정의하자. $s_1 > t_1$ 이라면 $\boldsymbol{T}_{1:}$ 은 $\boldsymbol{S}$ 의 행공간에 존재하지 않는다. $s_1<t_1$ 이면 $\boldsymbol{S}_{1:}$ 은 $\boldsymbol{T}$ 의 행공간에 존재하지 않는다. 따라서 $s_1=t_1$ 이다. 마찬가지로 $s_2 = t_2, \cdots , s_l = t_l$ 임을 보일 수 있다. 

($3$) ($2$) 로부터 $\boldsymbol{S}_{j:} \in \text{span}(\boldsymbol{T}_{j:},\, \boldsymbol{T}_{(j+1):},\ldots, \boldsymbol{T}_{l:})$ 임을 안다. 따라서

$$
\boldsymbol{S}_{1:} =  a_1 \boldsymbol{T}_{1:} + \cdots + a_l \boldsymbol{T}_{l:}
$$

인 $a_1,\ldots,\,a_l$ 이 존재한다. 여기서 $s_1=t_1$ 이므로 $a_1=1$ 이다. 또한 $s_2,\ldots,\,s_l$ 번째 성분을 고려하면 $a_2=\cdots =a_l=0$ 임을 안다. 따라서 $\boldsymbol{S}_{1:} = \boldsymbol{T}_{1:}$ 이다. 이렇게

$$
\boldsymbol{S}_{j:} = a_j \boldsymbol{T}_{j:} + a_{j+1}\boldsymbol{T}_{(j+1):} + \cdots + a_l \boldsymbol{T}_{l:}
$$

과 $s_j=t_j,\ldots, s_{l}=t_{l}$ 을 생각하면 $\boldsymbol{S}_{j:} =\boldsymbol{T}_{j:}$, $j=1,\ldots, l$ 이다. 즉 $\boldsymbol{S}=\boldsymbol{T}$ 이므로 행 간소 사다리꼴은 유일하다. $\square$

:::

</br>

### 가역행렬의 행 간소 사다리꼴, 역행렬 과 행렬식


::: {#prp-reduced_echelon_form_of_invertible_matrix}

가역행렬의 행 간소 사다리꼴 형태는 항등행렬이다. 또한 가역행렬 $\boldsymbol{A}$ 가  기본행렬의 곱 $\boldsymbol{E}$ 에 의해 항등행렬 이 되었다고 할때 $\boldsymbol{E}$ 는 $\boldsymbol{A}$ 의 역행렬이다.

:::

::: {.proof}
$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 기본행렬의 곱 $\boldsymbol{E}$ 에 의해 행 간소 사다리꼴 $\boldsymbol{A}'$ 으로 변화하였다고 하자. @prp-rank_of_matrix 에 따라 가역행렬이라면 $\text{nullity} (\boldsymbol{A})=0$ 이므로 $\boldsymbol{A}'$ 에 $0$ 으로만 이루어진 행이 없어야 한다. 행 간소 사다리꼴이므로 $i$ 행에서 첫번째 $1$ 의 위치를 $l_i$ 라 하면 $l_i \ge i (i=1,\ldots, n)$ 이다. 또한 $\boldsymbol{A}$ 가 정사각 행렬이며 $0$ 행이 없어야 하므로 $l_n \le n$ 이다. 이 두가지로부터 $l_i = i,\, i = 1,\ldots, n$ 임을 알 수 있으며 이런 행 간소 사다리꼴은 항등행렬 $\boldsymbol{I}_n$ 뿐이다. 즉 $\boldsymbol{EA}=\boldsymbol{I}_n$ 
이므로 $\boldsymbol{E}=\boldsymbol{A}^{-1}$ 이다. $\square$

:::

</br>

이제 이번 장의 마지막인 다음 명제를 보이고자 한다. 우리는 앞서 @prp-zero_determinant_of_linear_dependency 에서 행렬의 행벡터들이 선형종속이면, 혹은 열벡터들이 선형 종속이면 행렬식이 0 이 됨을 보였다. 이제 그 역에 대해서도 보일 수 있다. 

::: {#prp-determinant_of_invertible_matrix}
$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 다음은 동치이다.

1. $\boldsymbol{A}$ 는 가역행렬이다.

2. $\det (\boldsymbol{A}) \ne 0$.
:::

::: {.proof}

$\boldsymbol{A}$ 가 기본 행 연산 $\boldsymbol{E}_1,\ldots,\,\boldsymbol{E}_N$ 을 통해 행 간소 사다리꼴 $\boldsymbol{A}'$ 이 되었다고 하자. 즉,
$$
\det (\boldsymbol{A}') = \det (\boldsymbol{E}_N) \cdots \det (\boldsymbol{E}_1) \det (\boldsymbol{A}) 
$$

임을 안다. @prp-properties_of_determinant 을 다시 한번 보자. $\det (\boldsymbol{E}^{(1)}(i, j))=-1$ 이며 $\det (\boldsymbol{E}^{(2)}(j, t))=t$ 이고 $\det (\boldsymbol{E}^{(3)}(i, j, r))=1$ 이므로, 모든 기본 행 연산의 행렬식은 $0$ 이 아니다. 따라서,

$$
\det (\boldsymbol{A}) \ne 0 \iff \det (\boldsymbol{A}') \ne 0 
$$

이다. 

$\boldsymbol{A}$ 가 가역행렬인 경우 그 행 간소 사다리꼴이 단위행렬이므로 $\det (\boldsymbol{A}') = 1$ 이며, 따라서 $\det (\boldsymbol{A}') \ne 0$ 이다. $\boldsymbol{A}$ 가 가역행렬이 아니라면 $\boldsymbol{A}'$ 에 $0$ 으로 이루어진 행이 존재하므로 그 행렬식이 $0$ 이다. $\square$

:::

</br>