---
title: "고유값과 고유벡터"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

## 고유값, 고유벡터, 고유공간

::: {.callout-note appearance="simple" icon="false"}
::: {#def-invariant_subspace}

#### 불변부분공간

$\mathcal{M}_{n}(\mathbb{F})$ 에서 정의된 선형사상을 표현하는 정사각 행렬 $\boldsymbol{A}\in \mathcal{M}_{n \times n} (\mathbb{F})$ 와 $\mathcal{M}_{n}(\mathbb{F})$ 의 부분공간 $V$ 에 대해 

$$
\boldsymbol{v} \in V \implies \boldsymbol{Av} \in V
$$

일 때, $V$ 를 $\boldsymbol{A}$ 에 대한 $\mathcal{M}_{n}(\mathbb{F})$ 의 **불변부분공간 (invariant subspace)** 라 한다.
:::
:::


</br>

::: {#prp-invariant_subspace}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 다음이 성립한다.

&emsp; ($1$) $\mathcal{M}_n(\mathbb{F})$ 는 $\boldsymbol{A}$ 에 대한 불변부분공간이다.

&emsp; ($2$) $\ker (\boldsymbol{A})$ 는 $\boldsymbol{A}$ 에 대한 불변부분공간이다. 

&emsp; ($3$) $\text{im} (\boldsymbol{A})$ 는 $\boldsymbol{A}$ 에 대한 불변부분공간이다.
:::

::: {.proof}
($1$) 은 자명하다. $\boldsymbol{u}\in \ker (\boldsymbol{A}) \implies \boldsymbol{Au}=\boldsymbol{0} \in \ker (\boldsymbol{A})$ 이므로 ($2$) 도 성립한다. $\boldsymbol{v} \in \text{im} (\boldsymbol{A})$ 일 때 $\boldsymbol{Av}\in \text{im}(\boldsymbol{A})$ 이므로 ($3$) 도 성립한다. $\square$

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-eigenvector}

#### 고유값, 고유벡터, 고유공간

정사각 행렬 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 어떤 벡터 $\boldsymbol{v}\ne \boldsymbol{0}$ 과 스칼라 $\lambda\in \mathbb{F}$ 가 존재하여,

$$
\boldsymbol{Av} = \lambda \boldsymbol{v}
$$

일 때 $\boldsymbol{v}$ 를 $\boldsymbol{A}$ 의 **고유벡터 (eigenvector)**, $\lambda$ 를 $\boldsymbol{A}$ 에 대한 $\boldsymbol{v}$ 의 **고유값(eigenvalue)** 이라 한다. 행렬 $\boldsymbol{A}$ 가 고유값 $\lambda$ 를 가질 때, 이 고유값 $\lambda$ 를 갖는 고유벡터와 영벡터의 집합을 $\lambda$ 에 대한 $\boldsymbol{A}$ 의 **고유공간(eigenspace)** 이라고 하며 $E(\lambda, \boldsymbol{A})$ 라 쓴다.
:::
:::


</br>

::: {#prp-diagonal_matrix_and_eigenvalue}

$\boldsymbol{D}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 대각행렬, 즉 대각성분을 제외한 모든 성분이 $0$ 인 행렬이라면 표준기저 $\hat{\boldsymbol{e}}_i$ 는 $\lambda_i = D_{ii}$ 를 고유값으로 갖는 $\boldsymbol{D}$ 의 고유벡터이다.


:::

::: {.proof}

$\boldsymbol{D}\hat{\boldsymbol{e}}_i = \lambda_i \hat{\boldsymbol{e}}_i$ 이다. $\square$

:::


</br>

::: {#prp-eigenspace_invariant}

$E(\lambda,\, \boldsymbol{A})$ 는 행렬 $\boldsymbol{A}$ 에 대한 불변부분공간이다.

:::

::: {.proof}
우선 고유공간이 부분공간임을 보이자. 고유공간은 정의상 영벡터를 포함한다. 즉 $\boldsymbol{0}\in E(\lambda, \boldsymbol{A})$ 이다. $\boldsymbol{v}_1,\,\boldsymbol{v}_2 \in E(\lambda, \boldsymbol{A})$ 이며 $c$ 가 스칼라 일 때

$$
\boldsymbol{A}(\boldsymbol{v}_1 + c\boldsymbol{v}_2) = \lambda(\boldsymbol{v}_1 + c\boldsymbol{v}_2)
$$

이므로 $\boldsymbol{v}_1 + c\boldsymbol{v}_2 \in E(\lambda,\boldsymbol{A})$ 이다. 따라서 $E(\lambda,\boldsymbol{A})$ 는 부분공간이다. $\boldsymbol{v}\in E(\lambda,\boldsymbol{A})$ 이면 $\boldsymbol{Av}=\lambda \boldsymbol{v}\in E(\lambda, \boldsymbol{A})$ 이다. 따라서 고유공간은 불변부분공간이다. $\square$

:::

</br>

이제 선형사상/행렬의 고유값을 찾는 방법을 알아보자. 다음 정리는 선형사상/행렬의 고유값을 찾는 가장 중요한 방법을 알려준다.

::: {#thm-eigenvalues_determinant}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\det (\lambda \boldsymbol{I}-\boldsymbol{A}) \ne 0$ 을 만족하는 $\lambda \in \mathbb{F}$ 는 행렬 $\boldsymbol{A}$ 의 고유값이며, 이 $\lambda$ 에 대한 고유벡터가 항상 존재한다.

:::

::: {.proof}

$\det (\lambda \boldsymbol{I}-\boldsymbol{A})  = 0$ 이면 $\text{nullity} (\lambda \boldsymbol{I}-\boldsymbol{A})  \ne 0$ 이므로 $\boldsymbol{A}v=\lambda \boldsymbol{v}$ 를 만족하는 영벡터가 아닌 벡터 $\boldsymbol{v}$ 가 항상 존재한다. $\square$

:::

</br>

::: {#exm-eigenvalues_for_Field}

예를 들어 $\boldsymbol{A}_1 = \begin{bmatrix} 1 & 1 \\ -1 & 1 \end{bmatrix}$ 라 하자. $\det(\lambda \boldsymbol{I}-\boldsymbol{A})  = (\lambda-1)^2 +1$ 이므로 $\det (\lambda \boldsymbol{I}-\boldsymbol{A}) =0$ 을 만족하는 $\lambda$ 는 $1 \pm i$ 이다. 만약 $\boldsymbol{A}$ 가 $\mathbb{C}$ 위에서 정의된 행렬이라면 고유값과 고유벡터가 존재하지만 $\mathbb{R}$ 위에서 정의된 행렬이라면 고유값이 존재하지 않는다. 

:::

</br>

## 특성다항식 {#sec-characteristic_polynomial}

$\lambda$ 를 미지수로 간주하면 $n \times n$ 행렬 $\boldsymbol{A}$ 에 대해 $\det (\lambda \boldsymbol{I}-\boldsymbol{A})$ 는 $\lambda$ 에 대한 $n$ 차 다항식이다. 이 다항식의 근이 존재한다면, 그 근이 고유값이 되며, 이 고유값에 대한 고유벡터가 항상 존재한다는 의미이다. 이 다항식은 매우 중요하기 때문에 특별한 이름이 붙어 있다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-characteristic_polynomial}

#### 특성다항식

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대한 $p_{\boldsymbol{A}}(\lambda) = \det (\lambda \boldsymbol{I}-\boldsymbol{A})$ 를 **특성 다항식(characteristic polynomial)** 이라 한다.

:::
:::


</br>

::: {#exm-degree_of_characteristic_polynomial}
$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대한 특성다항식은 $n$ 차 다항식이다.
:::

</br>

::: {#prp-invariance_of_characteristic_polynomial}
특성 다항식은 닮음 변환에 대해 불변이다. 즉 행렬 $\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 과 가역행렬 $\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $p_{\boldsymbol{A}}(\lambda) = p_{\boldsymbol{P^{-1}AP}}(\lambda)$ 이다.
:::

::: {.proof}
$$
\begin{aligned}
\det(\lambda \boldsymbol{I}-\boldsymbol{P^{-1}AP}) & = \det (\boldsymbol{P}^{-1}(\lambda \boldsymbol{I}-\boldsymbol{A})\boldsymbol{P}) \\
& = \det(\boldsymbol{P}^{-1}) \det (\lambda \boldsymbol{I}-\boldsymbol{A}) \det (\boldsymbol{P}) \\
&=  \det (\lambda \boldsymbol{I}-\boldsymbol{A}). &\square
\end{aligned}
$$

:::


</br>

::: {#prp-eigenvalue_characteristic_polynomial}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\lambda\in \mathbb{F}$ 가 $\boldsymbol{A}$ 의 고유값이기 위한 필요충분조건은 $p_{\boldsymbol{A}}(\lambda)=0$ 인 것이다.
:::

::: {.proof}
$p_{\boldsymbol{A}}(\lambda)=0$ 일 때 $\lambda$ 가 $\boldsymbol{A}$ 의 고유값이 되는것은 @thm-eigenvalues_determinant 에서 보였다. $\lambda$ 가 $\boldsymbol{A}$ 의 고유값이라면 어떤 벡터 $\boldsymbol{v} \ne \boldsymbol{0}$ 에 대해 $\boldsymbol{Av}=\lambda \boldsymbol{v}$ 이므로 $(\lambda \boldsymbol{I}-\boldsymbol{A})\boldsymbol{v}=0$ 이다. 즉 $\text{nullity}(\lambda \boldsymbol{I}-\boldsymbol{A}) >0$ 이므로 $\det (\lambda \boldsymbol{I}-\boldsymbol{A}) = p_{\boldsymbol{A}}(\lambda)= 0$ 이다. $\square$

:::

</br>

::: {.callout-important appearance="simple" icon="false"}

#### 대수학의 기본정리

대수학의 기본정리는 복소수계수를 갖는 $n$ 차 다항식은 $k$ 중근을 $k$ 개의 근으로 간주한다면 $n$ 개의 근을 가진다는 것을 알려준다. 증명은 이 책의 범위를 벗어나므로 생략한다.

:::

</br>

::: {#thm-existance_of_eigenvector_for_complex_field}
복소수체에서 정의된 정사각 행렬에 대해 항상 고유벡터가 존재한다.
:::

::: {.proof}
대수학의 기본정리에 의해 복소수 영역에서는 항상 특성다항식의 해가 존재하며 @prp-eigenvalue_characteristic_polynomial 에 의해 고유벡터가 존재한다. $\square$
:::

</br>

::: {#prp-eigenvector_linear_independence}
$\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 의 고유벡터의 집합 $\{\boldsymbol{v}_1,\ldots,\, \boldsymbol{v}_m\}$ 에 대해 고유벡터가 각각 서로 다른 고유값 $\lambda_1,\ldots,\lambda_m$ 을 갖는 고유벡터라면 이 벡터의 집합은 선형독립이다.
:::

::: {.proof}
$V_0=\{\boldsymbol{v}_1, \ldots,\,\boldsymbol{v}_m\}$ 가 선형종속임을 가정하자. $\boldsymbol{v}_k$ 가 $\{ \boldsymbol{v}_1, \ldots, \boldsymbol{v}_{k-1}\}$ 의 선형결합으로 표현되는 첫번째 벡터라 하면 이것을 만족하는 $k$ 가 항상 존재한다. (존재하지 않으면 $V_0$ 는 선형독립이다) 이 때, 당연히도 $\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_{k-1}\}$ 은 선형독립이다.

$$
\begin{aligned}
& \boldsymbol{v}_k = c_1 \boldsymbol{v}_1 + \cdots + c_m \boldsymbol{v}_{k-1} \\
\implies & \boldsymbol{Av}_k = c_1 \boldsymbol{Av}_1 + \cdots + c_{k-1} \boldsymbol{Av}_{k-1} \\
\implies & \lambda_k \boldsymbol{v}_k = \lambda_1 c_1 \boldsymbol{v}_1 + \cdots + \lambda_{k-1} c_{k-1} \boldsymbol{v}_{k-1}
\end{aligned}
$$

이다. 또한 $\lambda_k \boldsymbol{v}_k = \lambda_k (c_1 \boldsymbol{v}_1 + \cdots + c_{k-1} \boldsymbol{v}_{k-1})$ 이므로,

$$
c_1 (\lambda_k -\lambda_1) \boldsymbol{v}_1 + \cdots + c_{k-1}(\lambda_k -\lambda_{k-1}) \boldsymbol{v}_{k-1}=0
$$

이다. $\{\boldsymbol{v}_1,\ldots,\boldsymbol{v}_{k-1}\}$ 이 선형독립이며 모든 $\{\lambda_i\}$ 가 서로 다르므로, $c_1 = \cdots = c_{k-1}=0$ 이다. 즉 $\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_k\}$ 는 선형독립이므로 가정에 모순이다. 즉 $V_0$ 는 선형독립이다. $\square$
:::

</br>


## 블록행렬과 불변부분공간


[블록행렬](ch1_03_determinant.qmd#def-block_matrix)의 대각 부분 행렬이 정사각행렬이라면, 행렬의 모든 대각성분은 부분행렬의 대각성분이 된다. 이를 대각 부분행렬이라 하자. 대각 부분행렬을 제외한 부분행렬이 모두 $0$ 행렬인 경우 **블록 대각 행렬 (block diagonal matrix)** 라 한다. 상삼각 행렬/하삼각 행렬처럼 **블록 상삼각 행렬(block upper triangular matrix)** 와 **블록 하삼각 행렬(block lower triangular matrix)** 를 정의 할 수 있다.



</br>

### 불변 부분공간과 블럭 상삼각행렬

우선 @sec-matrix_transform_by_basis_transform 에서 본 행렬의 닮음 변환을 다시 한번 상기하자. $\mathcal{M}_{n}(\mathbb{F})$ 공간에서 정의된 선형독립인 벡터 $\{\boldsymbol{u}_1,\ldots,\, \boldsymbol{u}_n\}$ 와 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 을 생각하자. $\boldsymbol{u}_i$ 가 $i$ 번째 열이 된 행렬 $\boldsymbol{P} = \begin{bmatrix} \boldsymbol{u}_1 & \cdots & \boldsymbol{u}_n \end{bmatrix}$ 는 기저를 변환하는 행렬, 즉 닮음변환을 정의하는 행렬이 되며 $\boldsymbol{P}^{-1}\boldsymbol{AP}$ 는 변환된 기저에서의 선형사상이고 변환행렬 $\boldsymbol{P}= \begin{bmatrix} \boldsymbol{u}_1 & \cdots & \boldsymbol{u}_n\end{bmatrix}$ 가 정의되며 아래 표와 같이 변환된다.

| 원래 기저에서의 행렬표현 | 새로운 기저에서의 행렬표현 |
|:-------:|:------:|
| $\boldsymbol{e}_i$ | $\boldsymbol{P}^{-1}\boldsymbol{e}_i$ |
| $\boldsymbol{u}_i$ | $\boldsymbol{e}_i$ |
| $\boldsymbol{A}$  | $\boldsymbol{P}^{-1}\boldsymbol{AP}$ |

</br>

</br>


::: {#prp-invariant_subspace_block_upperdiagonal_matrix}

#### 불변부분공간과 블럭상삼각행렬

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 행렬에 대해 불변부분공간이 존재하면 $\boldsymbol{A}$ 와 닮은 블럭 상삼각 행렬이 존재한다.

:::

::: {.proof}

$\mathbb{F}$-벡터공간 $\mathcal{M}_{n}(\mathbb{F})$ 의 어떤 부분공간 $U$ 와 행렬 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $U$ 가 $\boldsymbol{A}$ 에 대한 불변부분공간이라고 하자. $U$ 의 기저 $\{\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_m\}$ 를 확장하여 $\mathcal{M}_n(\mathbb{F})$ 의 기저 $\{\boldsymbol{u}_1,\ldots,\boldsymbol{u}_n\}$ 을 구성했다고 하자. 그렇다면 

$$
\boldsymbol{Au}_i = \left\{ \begin{array}{ll} B_{1i}\boldsymbol{u}_i + \cdots + B_{mi}\boldsymbol{u}_m & 1\le i \le m \\
B_{1i}\boldsymbol{u}_i + \cdots + B_{mi}\boldsymbol{u}_m + \cdots + B_{ni}\boldsymbol{u}_n \qquad & m+1 \le i \le n
\end{array} \right.
$$

이다. 즉 $\{\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_m\}$ 를 확장하여 $\mathbb{F}^{n }$ 기저에서는 $\boldsymbol{A}$ 로 표현된 변환이 블럭 상삼각행렬이 된다. 즉 $\boldsymbol{P} = \begin{bmatrix} \boldsymbol{u}_1 & \cdots &\boldsymbol{u}_n \end{bmatrix}$ 에 대해 $\boldsymbol{P}^{-1}\boldsymbol{AP}$ 는 블록 상삼각행렬이다. $\square$

:::


</br>

## 행렬의 상삼각행렬로의 변환

### 상삼각 행렬로 닮음변환되는 행렬

::: {#prp-upper_triangular_matrix}

정사각 행렬 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 다음은 동치이다.

&emsp; ($1$) $\boldsymbol{A}$ 가 어떤 상삼각행렬과 닮음이다.

&emsp; ($2$) $\mathcal{M}_{n}(\mathbb{F})$ 의 어떤 기저 $(\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_n)$ 에 대해 $\boldsymbol{Av}_i = \text{span}(\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_i)$ 이다.

:::

::: {.proof}

(1 $\implies$ 2) $\boldsymbol{B}=\boldsymbol{P}^{-1}\boldsymbol{AP}$ 가 상삼각행렬이라고 하자. $\hat{\boldsymbol{e}}_1,\ldots,\,\hat{\boldsymbol{e}}_n$ 에 대해 
$$
\boldsymbol{Be}_i \in \text{span} ( \hat{\boldsymbol{e}}_1,\ldots,\,\hat{\boldsymbol{e}}_i)
$$
이다. $\boldsymbol{v}_i = \boldsymbol{P}\hat{\boldsymbol{e}}_i$ 라 하자.  $\boldsymbol{A}= \boldsymbol{PBP}^{-1}$ 이므로,
$$
\boldsymbol{Av}_i = \boldsymbol{PBP}^{-1}\boldsymbol{P}\hat{\boldsymbol{e}}_i = \boldsymbol{PB}\hat{\boldsymbol{e}}_i
$$
이다. 따라서 $\boldsymbol{Av}_i \in \text{span}(\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_i)$ 이다. 

(2 $\implies$ 1) $\boldsymbol{P}=\begin{bmatrix} \boldsymbol{v}_1 & \cdots & \boldsymbol{v}_n\end{bmatrix}$ 라 하자. $\boldsymbol{B}=\boldsymbol{P}^{-1}\boldsymbol{AP}$ 라 하면
$$
\boldsymbol{B}\hat{\boldsymbol{e}}_i = \boldsymbol{P}^{-1}\boldsymbol{AP}\hat{\boldsymbol{e}}_i = \boldsymbol{P}^{-1} \boldsymbol{Av}_i 
$$
이다. $\boldsymbol{Av}_i \in \text{span}(\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_i)$ 이므로 $\boldsymbol{B}\hat{\boldsymbol{e}}_i \in \text{span}(\hat{\boldsymbol{e}}_1,\ldots,\,\hat{\boldsymbol{e}}_i)$ 이다. 즉 $\boldsymbol{B}$ 는 상삼각행렬이다. $\square$ 

:::

</br>

### 복소수체에서의 행렬과 상삼각행렬

이제 이 장에서 가장 중요한 결론을 낼 수 있다.

</br>

::: {#thm-uppertriangular_matrix_complex_field}
$\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{C})$ 행렬과 닮은 상삼각 행렬이 존재한다. 
:::

::: {.proof}
$\boldsymbol{A}_n \in \mathcal{M}_{n \times n}(\mathbb{C})$ 이라 하고 $n$ 에 대한 귀납법으로 증명한다. $n=1$ 일 때는 자명하다. $k<n$ 에 대해 위의 명제가 성립한다고 가정하자. 우리는 @thm-existance_of_eigenvector_for_complex_field 를 통해 행렬 $\boldsymbol{A}_n$ 에 대한 고유값 $\lambda$ 와 고유벡터 $\boldsymbol{v}_1$ 이 존재한다는 것을 안다. $\boldsymbol{v}_1$ 을 확장하여 $\mathcal{M}_n(\mathbb{F})$ 의 기저를 구성 할 수 있으며, 이 기저로 변환된  블럭 상삼각행렬을 이룬다 (@prp-invariant_subspace_block_upperdiagonal_matrix). 이 블럭 상삼각 행렬의 1 행과 1 열을 제거한 $(n-1)\times (n-1)$ 행렬은 가정에 의해 어떤 상 삼각 행렬과 닮았다. 따라서 $\boldsymbol{A}_n$ 은 어떤 상 삼각행렬과 닮았다. $\square$ 
:::

</br>

## 행렬의 대각화

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-diagonalizable_matrix}

#### 대각화 가능 행렬

정사각 행렬이 어떤 대각행렬과 닮았다면 그 정사각 행렬을 **대각화 가능 행렬 (Diagonalizable matrix)** 라고 한다.

:::
:::

</br>

::: {#prp-diagonalizability}

정사각 행렬 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이 서로 다른 고유값 $\lambda_1,\ldots,\,\lambda_m$ 을 가질 때 다음은 동치이다.


&emsp; ($1$) $\boldsymbol{A}$ 는 대각화 가능 행렬이다.

&emsp; ($2$) $\boldsymbol{A}$ 의 고유벡터로 이루어진 $\mathcal{M}_{n}(\mathbb{F})$ 의 기저가 존재한다.

&emsp; ($3$) $\mathcal{M}_n (\mathbb{F}) = E(\lambda_1, \boldsymbol{A}) \oplus \cdots \oplus E(\lambda_m, \boldsymbol{A})$
:::

::: {.proof}
($1 \implies 2$) 대각 행렬 $\boldsymbol{D}$ 에 대해 $\boldsymbol{D} = \boldsymbol{P}^{-1}\boldsymbol{AP}$ 라고 하자. $\boldsymbol{D}\hat{\boldsymbol{e}}_i = D_{ii}\hat{\boldsymbol{e}}_i$ 이므로, $\boldsymbol{P}\hat{\boldsymbol{e}}_i = \boldsymbol{P}_{:i}$ 는 $D_{ii}$ 를 고유값으로 갖는 $\boldsymbol{A}$ 의 고유벡터이다. $\boldsymbol{P}$ 가 가역행렬이므로 $\{\boldsymbol{P}\hat{\boldsymbol{e}}_1,\ldots,\boldsymbol{P}\hat{\boldsymbol{e}}_1\}$ 는 $\mathcal{M}_n(\mathbb{F})$ 의 기저이다.

($2 \implies 3$) $(\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_n)$ 이 $\boldsymbol{A}$ 의 고유벡터이며 $\mathcal{M}_n(\mathbb{F})$ 의 기저일 때 같은 고유값 $\lambda_j$ 를 갖는 $\boldsymbol{u}_i$ 들은 $E(\lambda_j, \boldsymbol{A})$ 의 기저이다. 임의의 $\lambda_{j_1}\le \lambda_{j_2}$ 일 때 $E(\lambda_{j_1}, \boldsymbol{A})\cap E(\lambda_{j_2})= \{\boldsymbol{0}\}$ 이므로, $\mathcal{M}_n (\mathbb{F}) = E(\lambda_1, \boldsymbol{A}) \oplus \cdots \oplus E(\lambda_m, \boldsymbol{A})$ 이다. 


($3 \implies 1$) 각각의 $E(\lambda_i, \boldsymbol{A})$ 의 기저벡터를 모아 $(\boldsymbol{u}_1,\ldots,\boldsymbol{u}_n)$ 을 만들었을 때 $\boldsymbol{U} = \begin{bmatrix} \boldsymbol{u}_1 & \cdots & \boldsymbol{u}_n\end{bmatrix}$ 라 하자. $\boldsymbol{U}$ 는 가역이며, $\boldsymbol{U}^{-1}\boldsymbol{AU}$ 는 대각행렬이다. $\square$


:::

</br>

::: {#cor-diagoalizability_of_dimV_distinct_eigenvalues_1}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 $n$ 개의 서로 다른 고유값을 가지면 $\boldsymbol{A}$ 는 대각화 가능 행렬이다.

:::

::: {.proof}

@prp-eigenvector_linear_independence 에서 보였듯이 서로 다른 고유값을 갖는 고유벡터는 선형독립이므로 이 $n$ 개의 고유벡터는 $\mathcal{M}_n(\mathbb{F})$ 의 기저이다. 따라서 $\boldsymbol{A}$ 는 대각화 가능 행렬이다. $\square$
:::


</br>

::: {#cor-diagoalizability_of_dimV_distinct_eigenvalues_2}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 의 특성다항식 $p_{\boldsymbol{A}}$ 가 $n$ 개의 서로 다른 해를 $\mathbb{F}$ 에서 가지면 $\boldsymbol{A}$ 는 대각화 가능 행렬이다. 
:::



</br>

## 연습문제

::: {#exr-invariant_subspace_1}

$\boldsymbol{A},\,\boldsymbol{B}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\boldsymbol{AB}=\boldsymbol{BA}$ 일 때 다음을 보여라 

&emsp; ($1$) $\ker (\boldsymbol{A})$ 는 $\boldsymbol{B}$ 에 대한 불변부분공간이다.

&emsp; ($2$) $\text{im}\,(\boldsymbol{A})$ 는 $\boldsymbol{B}$ 에 대한 불변부분공간이다.

:::

::: {.solution}

($1$) $\boldsymbol{u}\in \ker (\boldsymbol{A})$ 일 때 $\boldsymbol{ABu}=\boldsymbol{BAu}= \boldsymbol{0}$ 이므로 $\boldsymbol{Bu}\in \ker (\boldsymbol{A})$ 이다. 즉 $\ker(\boldsymbol{A})$ 는 $\boldsymbol{B}$ 에 대한 불변부분공간이다.

($2$) $\boldsymbol{v}\in \text{im} \,(\boldsymbol{A})$ 라고 하자. $\boldsymbol{v} = \boldsymbol{Au}$ 인 벡터 $\boldsymbol{v}$ 가 존재하며, $\boldsymbol{Bv}= \boldsymbol{BAu}= \boldsymbol{ABu} \in \text{im}\, (\boldsymbol{A})$ 이다. 따라서 $\text{im}\, (\boldsymbol{A})$ 는 $\boldsymbol{B}$ 에 대한 불변부분공간이다.

:::

</br>

::: {#exr-invarant_subspace_2}

$V=\mathcal{M}_{n }(\mathbb{F})$ 이고 $U \le V$ 이며 모든 $V$ 에 대한 연산자에 대해 불변이면 $U=\{\boldsymbol{0}\}$ 이거나 $U=V$ 임을 보이시오.

:::

::: {.solution}
$U=\{\boldsymbol{0}\}$ 이거나 $U=V$ 이면 불변부분공간임은 자명하다. $\dim U < \dim V$ 일 때 $U$ 의 기저 $\{\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_m\}$ 을 생각하자. 이 기저를 확장하여 $V$ 의 기저 $\{\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_m,\,\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_{n-m}\}$ 를 이루었을 때 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 를 $\boldsymbol{Au}_1 = \boldsymbol{v}_1$ 이 되도록 할 수 있으며 $U$ 는 $\boldsymbol{A}$ 에 대한 불변부분공간이 아니다. 

:::

</br>

::: {#exr-axler_5_a_14}

$V= U \oplus W \le \mathcal{M}_n(\mathbb{F})$ 이며 $U,\,W$ 는 $\{\boldsymbol{0}\}$ 이 아니다. $\boldsymbol{P}\in \mathcal{M}_{n\times n} (\mathbb{F})$ 가 모든 $\boldsymbol{u}\in U,\, \boldsymbol{w}\in W$ 에 대해 $\boldsymbol{P}(\boldsymbol{u}+\boldsymbol{w})= \boldsymbol{u}$ 일 때 $\boldsymbol{P}$ 의 모든 고유값과 고유벡터를 구하시오.

:::

::: {.solution}

$U = E(1, \boldsymbol{P})$ 이며 $W=E(0, \boldsymbol{P})$ 이다.

:::

</br>

::: {#exr-similar_transformation_and_eigenvectors}

$\boldsymbol{T},\, \boldsymbol{S}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이고 $\boldsymbol{S}$ 가 가역이다. 이 때 $\boldsymbol{S}^{-1}\boldsymbol{TS}$ 는 $\boldsymbol{T}$ 와 같은 고유값을 가짐을 보여라. $\boldsymbol{T}$ 와 $\boldsymbol{S}^{-1}\boldsymbol{TS}$ 의 고유벡터의 관계를 밝혀라.

:::

::: {.solution}

$\boldsymbol{Tv}=\lambda \boldsymbol{v}$ 이면 

$$
(\boldsymbol{S}^{-1}\boldsymbol{TS})\boldsymbol{S}^{-1}\boldsymbol{v} = \lambda \boldsymbol{S}^{-1}\boldsymbol{v}
$$

이다. 즉 $\boldsymbol{v}$ 가 $\lambda$ 의 고유값을 갖는 $\boldsymbol{T}$ 의 고유벡터이면 $\boldsymbol{S}^{-1}\boldsymbol{v}$ 는 $\lambda$ 의 고유값을 갖는 $\boldsymbol{S}^{-1}\boldsymbol{TS}$ 의 고유벡터이다.

:::


</br>

::: {#exr-eigenvalue_and_inverse_matrix}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가역일 때 $\lambda \ne 0$ 이 $\boldsymbol{A}$ 의 고유값이면 $1/\lambda$ 는 $\boldsymbol{A}^{-1}$ 의 고유값이며 $\boldsymbol{A}$ 와 $\boldsymbol{A}^{-1}$ 은 같은 고유벡터를 갖는다는 것을 보여라.

:::



::: {.solution}

우선 $0$ 을 고유값으로 갖는 행렬은 가역이 아님을 확인한다. 

$$
\boldsymbol{Av}=\lambda \boldsymbol{v} \implies \boldsymbol{A}^{-1}\boldsymbol{Av} = \lambda \boldsymbol{A}^{-1}\boldsymbol{v} \implies \boldsymbol{A}^{-1}\boldsymbol{v} = \dfrac{1}{\lambda}\boldsymbol{v}.$$ 

:::

</br>

::: {#exr-eigenvalue_of_product_matrix}

$\boldsymbol{A},\,\boldsymbol{B}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 일 때 $\boldsymbol{AB}$ 와 $\boldsymbol{BA}$ 는 같은 고유값을 가진다는 것을 보여라.

:::

::: {.solution}

$\boldsymbol{ABv}=\lambda \boldsymbol{v}$ 라 하자. $\boldsymbol{BA}(\boldsymbol{Bv})=\lambda (\boldsymbol{Bv})$ 이므로 $\boldsymbol{Bv}$ 는 같은 고유값을 갖는 $\boldsymbol{BA}$ 의 고유벡터이다. 

:::

</br>

::: {#exr-sum_of_eigenvector_is_eigenvector}

$\boldsymbol{u},\, \boldsymbol{v}\in \mathcal{M}_n(\mathbb{F})$ 가 $\boldsymbol{A}\in \mathbb{M}_{n \times n}(\mathbb{F})$ 의 고유벡터이고 $\boldsymbol{u}+\boldsymbol{v}$ 도 $\boldsymbol{A}$ 의 고유벡터이면 $\boldsymbol{u}$ 와 $\boldsymbol{v}$ 는 같은 고유값을 가진다는 것을 보여라.

:::

::: {.solution}

$\boldsymbol{Au}=\lambda_U \boldsymbol{u},\, \boldsymbol{Av}=\lambda_V \boldsymbol{v}$ 일 때, $\boldsymbol{A}(\boldsymbol{u}+\boldsymbol{v})= \lambda(\boldsymbol{u}+\boldsymbol{v})$ 라 하자. $\lambda_U \boldsymbol{u}+ \lambda_V \boldsymbol{v}= \lambda \boldsymbol{u}+\lambda \boldsymbol{v}$ 이다. $\lambda_U \ne \lambda_V$ 라면 서로 다른 고유값을 갖는 고유벡터는 선형독립인데, $(\lambda-\lambda_U)\boldsymbol{u}+(\lambda -\lambda_V)\boldsymbol{v} = \boldsymbol{0}$ 이므로 $\lambda = \lambda_U = \lambda_V$ 인데 이는 가정에 모순된다. 따라서 $\lambda_U = \lambda_V$ 이다.
:::

</br>

::: {#exr-scalar_multiple_of_identity_matrix}

모든 $\boldsymbol{v}\in \mathcal{M}_n(\mathbb{F})$ 가 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 의 고유벡터라면 $\boldsymbol{A}$ 는 항등행렬 혹은 어떠 $c\in \mathbb{F}$ 에 대해 $c\boldsymbol{I}_n$ 임을 보여라. $\dim (U)= n-1$ 인 모든 $U\le \mathcal{M}_{n}(\mathbb{F})$ 가 $\boldsymbol{A}$ 의 불변부분공간이라면 역시 $\boldsymbol{A}$ 는 항등행렬의 스칼라곱임을 보여라.

:::

::: {.solution}

@exr-sum_of_eigenvector_is_eigenvector 에 따라 모든 $\boldsymbol{v}\in \mathcal{M}_n(\mathbb{F})$ 는 같은 고유값을 갖는 $\boldsymbol{A}$ 의 고유벡터이다. 이 고유값을 $c$ 라고 하자. 모든 표준기저 $\hat{\boldsymbol{e}}_i$ 에 대해 $\boldsymbol{A}\hat{\boldsymbol{e}}_i = c\hat{\boldsymbol{e}}_i$ 이므로 $\boldsymbol{AI}_i = c\boldsymbol{I}_n$ 이다. 즉 $\boldsymbol{A}=c\boldsymbol{I}_n$ 이다.


$U,\,V$ 가 $\boldsymbol{A}$ 의 불변부분공간이라고 하자. $\boldsymbol{x}\in U \cap V$ 이면 $\boldsymbol{Ax}\in U\cap V$ 이므로 $U \cap V$ 도 불변부분공간이다. 즉 유한개의 불변부분공간의 교집합도 불변부분공간이다.

$$
U_j = \text{span} (\{\hat{\boldsymbol{e}}_i: i=1,\ldots,j-1,\,j+1,\ldots,\,n\})
$$

이라 하자. $\displaystyle \bigcup_{j=2}^n U_j = \text{span}(\hat{\boldsymbol{e}}_1)$ 이므로 $\hat{\boldsymbol{e}}_1$ 은 $\boldsymbol{A}$ 의 불변부분공간이다. 즉 $\hat{\boldsymbol{e}}_1$ 은 $\boldsymbol{A}$ 의 고유벡터이다. 같은 방법으로 모든 표준기저가 고유벡터임을 보일 수 있으며 따라서 $\boldsymbol{A}$ 는 항등행렬의 스칼라곱이다. 

:::

</br>

::: {#exr-linearly_independency_and_distict_eigenvalues}

$\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_m \} \subset \mathcal{M}_n(\mathbb{F})$ 이 선형독립일 필요충분 조건은 위 벡터들이 서로 다른 고유값을 갖는 고유벡터가 되도록 하는 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 존재하는 것임을 보여라.

:::

::: {.solution}

서로 다른 고유값을 갖는 고유벡터의 집합은 선형독립이라는 것을 안다(@prp-eigenvector_linear_independence). 따라서 $\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_m \}$ 가 선형독립이면 이 벡터들이 각각 다른 고유값을 갖는 고유벡터가 되는 행렬 $\boldsymbol{A}$ 가 존재함을 보이면 된다. $\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_m$ 을 확장하여 기저 $\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_n\}$ 을 구성하고 $\boldsymbol{P}= \begin{bmatrix} \boldsymbol{v}_1 & \cdots & \boldsymbol{v}_n\end{bmatrix}$ 라 하자. $\boldsymbol{P}^{-1}$ 은 $\boldsymbol{v}_i$ 를 표준기저 $\hat{\boldsymbol{e}}_i$ 로 변환해주는 연산자이다. 

행렬 $\boldsymbol{A}$ 를 $1$ 행 $1$ 열 부터 $m$ 행 $m$ 열 까지는 $A_{ij}= \delta_{ij}$ 가 되도록 하고 $m+1$ 행 $m+1$ 열부터는 임의의 값을 가지는 블럭대각행렬이라 하자. $\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_m$ 은 은 각각 $1,\ldots,m$ 의 고유값을 가지므로 $\boldsymbol{PAP}^{-1}$ 은 $\boldsymbol{v}_1,\ldots,\boldsymbol{v}_m$ 이 각각 $1,\ldots,\,m$ 의 고유값을 갖는 행렬이다. 

:::


</br>

::: {#exr-axler_5_B_1}

$\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 어떤 자연수 $n$ 에 대해 $\boldsymbol{A}^n=\boldsymbol{0}$ 이라고 하자. $\boldsymbol{I}_n-\boldsymbol{A}$ 는 가역행렬이며 다음이 성립함을 보여라.

$$
(\boldsymbol{I}_n-\boldsymbol{A})^{-1} = \boldsymbol{I}_n+ \boldsymbol{A} + \cdots + \boldsymbol{A}^{n-1}.
$$

:::

::: {.solution}

$(\boldsymbol{I}_n-\boldsymbol{A})(\boldsymbol{I}_n + \boldsymbol{A} + \cdots + \boldsymbol{A}^{n-1}) = \boldsymbol{I}_n- \boldsymbol{A}^n=\boldsymbol{I}_n$ 

:::

</br>

::: {#exr-axler_5_b_4}

$\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 $\boldsymbol{P}^2=\boldsymbol{P}$ 일 때 $\boldsymbol{P}$ 를 **projection** 이라고 한다. $\boldsymbol{P}$ 가 projection 일 때 $\mathcal{M}_n (\mathbb{F})=(\ker (\boldsymbol{P})) \oplus (\text{im}(\boldsymbol{P}))$ 임을 보여라.

:::

::: {.solution}

$\boldsymbol{u}\in \ker (\boldsymbol{P})\cap \text{im}(\boldsymbol{P})$ 라 하자. $\boldsymbol{Pu}=\boldsymbol{0}$ 이며 $\boldsymbol{Pv}=\boldsymbol{u}$ 인 $\boldsymbol{u}$ 가 존재해야 한다. 그런데 $\boldsymbol{P}^2\boldsymbol{v} = \boldsymbol{Pu}=\boldsymbol{0}$ 이며 $\boldsymbol{P}^2\boldsymbol{v} = \boldsymbol{Pv}$ 이므로 $\boldsymbol{u}=\boldsymbol{0}$ 이다. 즉 $\ker (\boldsymbol{P})\cap \text{im}(\boldsymbol{P}) = \{\boldsymbol{0}\}$ 이다. @thm-rank_nullity 에 의해 $\mathcal{M}_n (\mathbb{F})=(\ker (\boldsymbol{P})) \oplus (\text{im}(\boldsymbol{P}))$ 이다.

:::

</br>

::: {#exr-axler_5_c_1}

$\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 가 대각화 가능 행렬이면 $\mathcal{M}_n(\mathbb{F})=\ker (\boldsymbol{A})\oplus \text{im}(\boldsymbol{A})$ 임을 보여라.

:::

::: {.solution}
$\ker (\boldsymbol{A})$ 와 $\text{im}(\boldsymbol{A})$ 모두 $\mathcal{M}_n(\mathbb{F})$ 의 부분공간이다. $\boldsymbol{A}$ 의 고유벡터로 이루어진 $\mathcal{M}_n (\mathbb{F})$ 의 기저 $\{\boldsymbol{u}_1, \ldots,\, \boldsymbol{u}_n\}$ 을 생각 할 수 있다. $\boldsymbol{x}\in \ker (\boldsymbol{A})\cap \text{im}(\boldsymbol{A})$ 이라고 하자. $\boldsymbol{x}\in \ker (\boldsymbol{A})$ 이므로 $\boldsymbol{Ax}=\boldsymbol{0}$ 이며 $\boldsymbol{x}\in \text{im}(\boldsymbol{A})$ 이므로 $\boldsymbol{Ay}=\boldsymbol{x}$ 를 만족하는 $\boldsymbol{y}$ 가 존재해야 한다. $\boldsymbol{A}$ 가 대각화 가능 행렬이므로 고유값 $\lambda_i$ 를 갖는 고유벡터 $\boldsymbol{u}_i$ 가 기저가 되며 따라서 $\boldsymbol{y}=\sum_i c_i \boldsymbol{u}_i$ 로 표현 할 수 있다. $\boldsymbol{Ay} = \sum_i c_i \lambda_i \boldsymbol{u}_i = \boldsymbol{x}$, $\boldsymbol{A}^2\boldsymbol{y} = \sum_i c_i \lambda_i^2 \boldsymbol{u}_i = \boldsymbol{0}$ 이므로 $\boldsymbol{y}$ 는 $\boldsymbol{A}$ 에 대해 고유값이 $0$ 인 벡터의 선형결합이다. 따라서 $\boldsymbol{y}\in \ker (\boldsymbol{A})$ 이며 $\boldsymbol{x}=\boldsymbol{0}$ 이다. 

@thm-rank_nullity 에 의해 $n=\text{nullity}(\boldsymbol{A})+\text{rank}(\boldsymbol{A})$ 이며 $\ker (\boldsymbol{A}) \cap \text{im}(\boldsymbol{A})=\{\boldsymbol{0}\}$ 이므로 $\mathcal{M}_n(\mathbb{F})=\ker (\boldsymbol{A})\oplus \text{im}(\boldsymbol{A})$ 이다.

:::

</br>

::: {#exr-axer_5_c_3}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 다음 세 명제는 동치임을 보여라.

&emsp; ($1$) $\mathcal{M}_{n}(\mathbb{F}) = \ker (\boldsymbol{A})\oplus \text{im}(\boldsymbol{A})$.

&emsp; ($2$) $\mathcal{M}_{n}(\mathbb{F}) = \ker (\boldsymbol{A}) + \text{im}(\boldsymbol{A})$.

&emsp; ($3$) $\ker (\boldsymbol{A}) \cap \text{im}(\boldsymbol{A}) = \{\boldsymbol{0}\}$.

:::

::: {.solution}

($1\implies 2$) 가정에 의해 $\ker (\boldsymbol{A})\cap \text{im}(\boldsymbol{A})= \{\boldsymbol{0}\}$ 이다. @prp-condition_for_direct_sum 의해 $\ker (\boldsymbol{A}) + \text{im}(\boldsymbol{A}) = \ker (\boldsymbol{A})\oplus \text{im}(\boldsymbol{A}) = \mathcal{M}_{n}(\mathbb{F})$ 이다.

($2\implies 3$) @thm-rank_nullity 에 의해 $\ker (\boldsymbol{A}) \cap \text{im}(\boldsymbol{A}) = \{\boldsymbol{0}\}$ 이다. 

($3 \implies 1$) $\ker (\boldsymbol{A})$ 와 $\text{im}(\boldsymbol{A})$ 는 $\mathcal{M}_n(\mathbb{F})$ 의 부분공간이며 가정에 의해 $\ker (\boldsymbol{A}) + \text{im}(\boldsymbol{A}) = \ker (\boldsymbol{A}) \oplus \text{im}(\boldsymbol{A})$ 도 부분공간이다. @thm-rank_nullity 에 의해 $\mathcal{M}_{n}(\mathbb{F}) = \ker (\boldsymbol{A})\oplus \text{im}(\boldsymbol{A})$ 이다.

:::

</br>

::: {#exr-axler_5_c_5}
$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{C})$ 일 때 다음이 동치임을 보이시오.

&emsp; ($1$) $\boldsymbol{A}$ 는 대각화 가능 행렬이다.

&emsp; ($2$) 모든 $\lambda \in \mathbb{C}$ 에 대해 $\mathcal{M}_{n}(\mathbb{C}) = \ker (\boldsymbol{A}-\lambda \boldsymbol{I}_n) \oplus \text{im}(\boldsymbol{A}-\lambda \boldsymbol{I}_n)$

:::

::: {.solution}
($1 \implies 2$) $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{C})$ 일 때

$$
\begin{aligned}
\boldsymbol{Au}=\lambda_u\boldsymbol{u} \iff (\boldsymbol{A}-\lambda \boldsymbol{I}_n)\boldsymbol{u} = (\lambda_u -\lambda)\boldsymbol{u}
\end{aligned}
$$

이므로 $\boldsymbol{u}$ 가 $\boldsymbol{A}$ 의 고유벡터인것과 $\boldsymbol{A}-\lambda\boldsymbol{I}_n$ 의 고유벡터인것은 동치임을 안다. 따라서 $\boldsymbol{A}$ 가 대각화 가능인것과 임의의 $\lambda\in \mathbb{C}$ 에 대해 $\boldsymbol{A}-\lambda \boldsymbol{I}_n$ 이 대각화 가능인것은 동치이다. $\boldsymbol{A}-\lambda\boldsymbol{I}_n$ 이 대각화 가능이므로 @exr-axler_5_c_1 에서 보였듯이 $\mathcal{M}_n(\mathbb{C}) = \ker (\boldsymbol{A}-\lambda\boldsymbol{I}_n) \oplus \text{im} (\boldsymbol{A}-\lambda\boldsymbol{I}_n)$ 이다. 


($2 \implies 1$) 정해진 $\lambda_1\in \mathbb{C}$ 에 대해 $(\boldsymbol{u}_i, \ldots,\,\boldsymbol{u}_m)$ 이 $\ker(\boldsymbol{A}-\lambda_1 \boldsymbol{I}_n)$ 의 기저라고하자. $(\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_{n-m})$ 를 $\text{im}(\boldsymbol{A}-\lambda_1\boldsymbol{I}_n)$ 의 기저라고 하자. 

$$
\boldsymbol{U} = \begin{bmatrix} \boldsymbol{u}_1 & \cdots & \boldsymbol{u}_m & \boldsymbol{v}_1 & \cdots & \boldsymbol{v}_{n-m}\end{bmatrix}
$$

라고 하면 $\boldsymbol{U}$ 은 가역행렬이며 $\boldsymbol{U}^{-1}\boldsymbol{AU}$ 은 블럭대각행렬이다. 이 때 1행 1열부터 $m$ 행 $m$ 열까지는 대각행렬이라는 것을 알 수 있다. 또한 $\boldsymbol{Uv}_j$ 는 1 행부터 $m$ 행 까지의 값이 $0$ 이다.

우리는 모든 복소 행렬은 고유값을 가진다는 것을 알고 있다(@thm-existance_of_eigenvector_for_complex_field). 이것을 이용하여 $n$ 에 대한 induction 을 통해 증명하자. $n=1$ 일 때는 자명하다. 이제 $n$ 보다 작은 양의 정수에 대해 성립함을 가정하자. $\boldsymbol{A}$ 는 고유값 $\lambda_1$ 을 가지며 따라서 앞서의 과정에 따라 블럭대각화를 할 수 있다. $\dim(E(\lambda_1, \boldsymbol{A}))=m$ 인데 $\boldsymbol{U}^{-1}\boldsymbol{AU}$ 에서 1 행 1열부터 $m$ 행 $m$ 열 까지를 $0$ 으로 만든 행렬을 $\boldsymbol{A}_1$ 이라고 하자. 

이제 모든 $\lambda\in\mathbb{C}$ 에 대해 $\text{im}(\boldsymbol{A}_1-\lambda\boldsymbol{I}_n) = \ker (\boldsymbol{A}_1-\lambda \boldsymbol{I}_n) \oplus \text{im}(\boldsymbol{A}_1-\lambda \boldsymbol{I}_n)$ 임을 보이자. @exr-axer_5_c_3 에 따라 $\ker (\boldsymbol{A}_1-\lambda \boldsymbol{I}_n) \cap \text{im}(\boldsymbol{A}_1-\lambda \boldsymbol{I}_n) =\{\boldsymbol{0}\}$ 이라는 것을 보이면 된다. 그런데 $\ker (\boldsymbol{A}_1-\lambda \boldsymbol{I}_n) \in \ker  (\boldsymbol{A}-\lambda \boldsymbol{I}_n)$ 이며 $\text{im}(\boldsymbol{A}_1-\lambda \boldsymbol{I}_n) \subset \text{im}(\boldsymbol{A}-\lambda \boldsymbol{I}_n)$ 이므로 $\ker (\boldsymbol{A}_1-\lambda \boldsymbol{I}_n) \cap \text{im}(\boldsymbol{A}_1-\lambda \boldsymbol{I}_n) =\{\boldsymbol{0}\}$ 이다. Induction 의 가정에 따라 $\boldsymbol{A}_1$ 이 대각화 가능이며 따라서 $\boldsymbol{A}$ 는 대각화 가능이다. $\square$
:::

</br>

::: {#exr-axler_5_c_6}

$\boldsymbol{A},\, \boldsymbol{B}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이고 $\boldsymbol{A}$ 가 $n$ 개의 서로 다른 고유값을 가지며 $\boldsymbol{B}$ 가 $\boldsymbol{A}$ 와 같은 고유벡터를 가질 때 $\boldsymbol{AB}=\boldsymbol{BA}$ 임을 보여라.

:::

::: {.solution}

$(\boldsymbol{u}_1,\ldots,\boldsymbol{u}_n)$ 을 각각 $\lambda_i$ 의 고유값을 갖는 $\boldsymbol{A}$ 의 고유벡터라고 하면 이 벡터는 각각 다른 고유값을 가지므로 선형독립이며, 따라서 기저이다. $\boldsymbol{U} = \begin{bmatrix} \boldsymbol{u}_1 & \cdots & \boldsymbol{u}_n\end{bmatrix}$ 에 대해 $\boldsymbol{U}^{-1}\boldsymbol{AU}$ 와 $\boldsymbol{U}^{-1}\boldsymbol{BU}$ 는 각각 고유값을 대각성분으로 갖는 대각행렬이며, 두 대각행렬의 곱은 순서에 관계 없이 같으므로, 

$$
(\boldsymbol{U}^{-1}\boldsymbol{AU}) (\boldsymbol{U}^{-1}\boldsymbol{BU})=(\boldsymbol{U}^{-1}\boldsymbol{BU}) (\boldsymbol{U}^{-1}\boldsymbol{AU})
$$

이다. 이로부터 $\boldsymbol{AB}=\boldsymbol{BA}$ 를 얻는다.

:::

</br>

::: {#exr-axler_5_c_16}

#### 피보나치 수열

수열 $\langle f_n \rangle$ 이 다음과 같이 정의되었다. (이 수열을 피보나치 수열 (Fibonacci sequence) 이라고 한다.)

$$
f_1 = 1,\qquad f_2=1,\qquad f_{n+2} = f_{n+1} +f_n.
$$

$\boldsymbol{F} = \begin{bmatrix} 0 & 1 \\ 1 & 1\end{bmatrix}$ 에 대해 다음을 보여라.

&emsp; ($1$) $\boldsymbol{F}^n \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \begin{bmatrix} f_n \\ f_{n+1}\end{bmatrix}$ 이다.

&emsp; ($2$) $\boldsymbol{F}$ 의 고유값을 구하라.

&emsp; ($3$) $\boldsymbol{F}$ 의 고유벡터로 이루어진 $\mathcal{M}_{2}(\mathbb{R})$ 의 기저를 구하라.

&emsp; ($4$) ($3$) 의 해를 이용하여 $\boldsymbol{F}^{n} \begin{bmatrix}0 \\ 1 \end{bmatrix}$ 를 계산하라. 

&emsp; ($5$) ($4$) 를 이용하여 각각의 양의 정수 $n$ 에 대해 $f_n$ 은 $\dfrac{1}{\sqrt{5}} \left(\dfrac{1+\sqrt{5}}{2}\right)^n$ 에 가장 가까운 정수임을 보여라.
:::

::: {.solution}

($1$) $n=1$ 일 경우로부터 $f_1=1,\, f_2=2$ 임을 안다. $\boldsymbol{F}^n \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \begin{bmatrix} f_n \\ f_{n+1}\end{bmatrix}$ 라고 가정하자.

$$
\boldsymbol{F}^{n+1} \begin{bmatrix} 0 \\ 1 \end{bmatrix} = \boldsymbol{F}\begin{bmatrix} f_n \\ f_{n+1}\end{bmatrix} = \begin {bmatrix} f_{n+1} \\ f_{n}+f_{n+1}= f_{n+2}\end{bmatrix}
$$

이다. 

($2$) $\det (\lambda \boldsymbol{I}_2-\boldsymbol{F})=0$ 를 통해 고유값 $\lambda_1 = \dfrac{1+\sqrt{5}}{2}$ 와 $\lambda_2 = \dfrac{1-\sqrt{5}}{2}$ 를 얻을 수 있다.

($3$) $\boldsymbol{Fu}_i = \lambda_i \boldsymbol{u}_i$ 를 통해, $\boldsymbol{u}_1 = \begin{bmatrix}1 \\ \frac{1+\sqrt{5}}2\end{bmatrix}$, $\boldsymbol{u}_2 = \begin{bmatrix}1 \\ \frac{1-\sqrt{5}}{2}\end{bmatrix}$ 를 얻으며 둘은 선형독립이므로 $\mathcal{M}_2(\mathbb{R})$ 의 기저이다.

($4$) $\begin{bmatrix} 0 \\ 1 \end{bmatrix} = \dfrac{1}{\sqrt{5}}\left(\boldsymbol{u}_1 -\boldsymbol{u}_2\right)$ 이며 $\boldsymbol{F}^{n}(\dfrac{1}{\sqrt{5}}\boldsymbol{u}_1-\dfrac{1}{\sqrt{5}}\boldsymbol{u}_2) = \dfrac{1}{\sqrt{5}} (\lambda_1)^n \boldsymbol{u}_1 - \dfrac{1}{\sqrt{5}}(\lambda_2)^n \boldsymbol{u}_2$ 이다. 즉, 

$$
\boldsymbol{F}^n\begin{bmatrix}0 \\ 1 \end{bmatrix} = \dfrac{1}{\sqrt{5}}\left[{\lambda_1}^n \boldsymbol{u}_1 - {\lambda_2}^n \boldsymbol{u}_2\right] = \dfrac{1}{\sqrt{5}} \begin{bmatrix} \left(\dfrac{1+\sqrt{5}}{2}\right)^n - \left(\dfrac{1-\sqrt{5}}{2}\right)^n  \\ \left(\dfrac{1+\sqrt{5}}{2}\right)^{n+1}  - \left(\dfrac{1-\sqrt{5}}{2}\right)^{n+1} \end{bmatrix} 
$$

이다. 따라서 $f_n =\dfrac{1}{\sqrt{5}} \left[ \left(\dfrac{1+\sqrt{5}}{2}\right)^n - \left(\dfrac{1-\sqrt{5}}{2}\right)^n\right]$ 이다.

($5$) $f_n$ 은 정의에 의해 항상 자연수이다. 또한 $\left|\dfrac{1}{\sqrt{5}}\left(\dfrac{1-\sqrt{5}}{2}\right)^n\right| < 0.277$ 이다. $a,\,b\in \mathbb{R},\, n\in \mathbb{Z}_+$ 에 대해 $a+b=n$ 이며 $|b|<0.3$ 이라면 $|n-a|<0.3$ 이므로 $n$ 은 $a$ 에 가장 가까운 정수 일 수 밖에 없다. 따라서 $f_n$ 은 $\dfrac{1}{\sqrt{5}}\left(\dfrac{1+\sqrt{5}}{2}\right)^n$ 에 가장 가까운 정수일 수 밖에 없다.

::: 