---
title: "스펙트럼 정리"
number-sections: true
number-depth : 2
crossref:
  chapters: true
---

## 복소수체($\mathbb{C}$) 에서 정의된 행렬에 대한 스펙트럼 정리

아마 선형대수학에서 가장 중요한 것을 꼽으라면 스펙트럼 정리일 것이다. 

</br>

### 정규행렬

::: {.callout-note appearance="simple" icon="false"}
::: {#def-normal_matrix}
### 정규 행렬 (Normal Matrix)

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이 $\boldsymbol{AA}^\ast = \boldsymbol{A}^\ast \boldsymbol{A}$ 일 때 $\boldsymbol{A}$ 를 **정규 행렬(normal matrix)** 라 한다. 정규행렬이 나타내는 연산자를 **정규 연산자(normal operator)** 라 한다.
:::
:::

</br>

에르미트 행렬은 당연히 정규 행렬이다. 정규행렬은 다음과 같은 성질을 가진다.

::: {#prp-condition_of_normal_matrix}

$\boldsymbol{A}$ 가 정규행렬일 필요충분인 조건은 모든 $\boldsymbol{v}\in \mathcal{M}_{n \times 1}(\mathbb{F})$ 에 대해 $\|\boldsymbol{Av}\| = \|\boldsymbol{A}^\ast \boldsymbol{v}\|$ 이다.
:::

::: {.proof}
$$
\begin{aligned}
\boldsymbol{A} \text{ is normal} &\iff  \boldsymbol{A}^\ast \boldsymbol{A} - \boldsymbol{A}\boldsymbol{A}^\ast = \boldsymbol{0} \\
&\iff \langle (\boldsymbol{A}^\ast \boldsymbol{A} - \boldsymbol{A}\boldsymbol{A}^\ast)\boldsymbol{v} ,\, \boldsymbol{v} \rangle  = \boldsymbol{0} \\
&\iff \langle \boldsymbol{A}^\ast \boldsymbol{A} \boldsymbol{v},\, \boldsymbol{v} \rangle = \langle \boldsymbol{AA}^\ast \boldsymbol{v} ,\, \boldsymbol{v}\rangle \\
& \iff \|\boldsymbol{Av}\|^2 = \|\boldsymbol{A}^\ast \boldsymbol{v}\|^2
\end{aligned}
$$

:::

</br>


::: {#prp-eigenvectors_or_normal_matrix_and_adjoint}
$\boldsymbol{A}$ 가 정규행렬이면 $\boldsymbol{A}$ 와 $\boldsymbol{A}^\ast$ 는 같은 고유벡터를 가진다.
:::

::: {.proof}
$\boldsymbol{A}$ 가 정규행렬이면, $\boldsymbol{A}-\lambda \boldsymbol{I}$ 도 정규행렬임을 보일 수 있다.

$$
\begin{aligned}
(\boldsymbol{A}-\lambda \boldsymbol{I})^\ast & (\boldsymbol{A}-\lambda \boldsymbol{I}) -(\boldsymbol{A}-\lambda \boldsymbol{I}) (\boldsymbol{A}-\lambda \boldsymbol{I})^\ast \\
&= \boldsymbol{A}^\ast \boldsymbol{A} -\lambda \boldsymbol{A}^\ast -\overline{\lambda}\boldsymbol{A} +|\lambda|^2 \boldsymbol{I} - \boldsymbol{AA}^\ast +\lambda \boldsymbol{A}^\ast + \overline{\lambda}\boldsymbol{A} -|\lambda|^2\boldsymbol{I} \\
&= \boldsymbol{0}.
\end{aligned}
$$

따라서 $\lambda$ 와 $\boldsymbol{v}$ 가 $\boldsymbol{A}$ 의 고유값과 고유벡터라 하면 @prp-condition_of_normal_matrix 에 의해

$$
0 = \| (\boldsymbol{A}-\lambda \boldsymbol{I})\boldsymbol{v}\| = \| (\boldsymbol{A}^\ast -\overline{\lambda}\boldsymbol{I})\boldsymbol{v}\|
$$

이다. 즉 정규행렬 $\boldsymbol{A}$ 에 대해 $\boldsymbol{v}$ 가 고유값 $\lambda$ 를 갖는 고유벡터이면 $\boldsymbol{v}$ 는 $\boldsymbol{A}^\ast$  에 대해 $\overline{\lambda}$ 를 고유값으로 갖는 고유벡터이다. $\square$

:::

</br>

::: {#prp-orthogonality_of_normal_matrix}
정규행렬 $\boldsymbol{A}$ 의 서로 다른 고유값을 갖는 두 고유벡터는 직교한다.
:::

::: {.proof}
$\lambda_1,\,\lambda_2$ 가 서로 다른 $\boldsymbol{A}$ 의 고유값이고 이에 대한 고유벡터가 $\boldsymbol{v}_1,\,\boldsymbol{v}_2$ 라 하자.

$$
\begin{aligned}
(\lambda_1-\lambda_2)\langle \boldsymbol{v}_1,\,\boldsymbol{v}_2\rangle &= \langle \boldsymbol{Av}_1,\,\boldsymbol{v}_2\rangle - \langle \boldsymbol{v}_1,\, \boldsymbol{A}^\ast \boldsymbol{v}_2 \rangle =  \langle \boldsymbol{Av}_1,\,\boldsymbol{v}_2\rangle - \langle \boldsymbol{A} \boldsymbol{v}_1,\, \boldsymbol{v}_2 \rangle = \boldsymbol{0}
\end{aligned}
$$

이며 $\lambda_1 \ne \lambda_2$ 이므로 $\langle \boldsymbol{v}_1,\,\boldsymbol{v}_2\rangle = 0$ 이다. $\square$
:::

</br>

::: {#prp-diagonality_of_norma_matrix}

정규행렬의 상삼각행렬꼴은 대각행렬이다.

:::

::: {.proof} 

우리는 [슈어 정리](#슈어-정리-schurs-theorem) 로부터 모든 복소행렬이 어떤 정규직교기저에서 상삼각행렬꼴로 나타남을 안다. 이 상삼각행렬을 $\boldsymbol{A}$ 라 하면 정규직교기저의 행렬형식은 표준직교기저 $\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n\}$ 가 된다. $\boldsymbol{Ae}_i$ 는 $\boldsymbol{A}$ 의 $i$ 번째 열벡터 $A_{:i}$ 이며, $\boldsymbol{A}$ 가 상삼각행렬 이므로,

$$
\begin{aligned}
\boldsymbol{Ae}_i &= \sum_{j=1}^n A_{ji}\boldsymbol{e}_j = \sum_{j=1}^i A_{ji}\boldsymbol{e}_j  \\
\boldsymbol{A}^\ast \boldsymbol{e}_i &= \sum_{j=1}^n  (\boldsymbol{A}^{\ast})_{ji} \boldsymbol{e}_j  = \sum_{j=1}^n  \overline{A_{ij}}\boldsymbol{e}_j = \sum_{j=i}^n \overline{A_{ij}}\boldsymbol{e}_j
\end{aligned}
$$

이다. 이를 이용하면,

$$
\begin{aligned}
\|\boldsymbol{Ae}_{i}\|^2 &=  \langle \boldsymbol{Ae}_i,\, \boldsymbol{Ae}_i\rangle = \sum_{j,\,k=1}^i A_{ji}\overline{A_{ki}} \langle \boldsymbol{e}_j,\,\boldsymbol{e}_k\rangle = \sum_{j=1}^i |A_{ji}|^2 \\
\|\boldsymbol{A}^\ast \boldsymbol{e}_i\|^2 &= \langle \boldsymbol{A}^\ast \boldsymbol{e}_i,\, \boldsymbol{A}^\ast \boldsymbol{e}_i \rangle  =
\sum_{j,\,k=i}^n \overline{A_{ij}}A_{ik} \langle \boldsymbol{e}_j,\,\boldsymbol{e}_k \rangle = \sum_{j=i}^n |A_{ij}|^2
\end{aligned}
$$

이다. $i=1$ 인 경우 $\|\boldsymbol{Ae}_1\|^2 = |A_{11}|^2$, $\|\boldsymbol{A}^\ast \boldsymbol{e}_1\|^2 = |A_{11}|^2+\cdots + |A_{1n}|^2$ 이므로, $A_{12} = \cdots = A_{1n}=0$ 이다. $i=2$ 인 경우 $\|\boldsymbol{Ae}_2\|^2=|A_{12}|^2+|A_{22}|^2 = |A_{22}|^2$ ($A_{12}=0$ 임은 바로 앞에) $|\boldsymbol{A}^\ast \boldsymbol{e}_2\|^2 = |A_{22}|^2 + \cdots + |A_{2n}|^2$ 이므로, $A_{23} = \cdots A_{2n}=0$ 이다. 이것을 $n$ 까지 반복하면 $\boldsymbol{A}$ 가 대각행렬임을 보일 수 있다. $\square$

:::

</br>



::: {#thm-spectrum_theorem_for_complex_field}

#### 복소수체에서 정의된 행렬에 대한 스펙트럼 정리

$\boldsymbol{A} \in \mathcal{M}_{n \times n}(\mathbb{C})$ 행렬에 대해 다음 세 명제는 동치이다.

&emsp; ($1$) $\boldsymbol{A}$ 는 정규행렬이다.

&emsp; ($2$) $\boldsymbol{A}$ 는 unitary 변환에 의해 대각행렬로 표현된다.

&emsp; ($3$) $\boldsymbol{A}$ 의 고유벡터로 $\mathcal{M}_{n \times 1}(\mathbb{C})$ 의 정규직교기저를 구성 할 수 있다.
:::


::: {.proof}

($1 \implies 2$) 는 @prp-diagonality_of_norma_matrix 에서 보였다.

($2\implies 3$) $\boldsymbol{A}$ 가 unitary 행렬 $\boldsymbol{P}$ 에 의해 대각행렬로 변환된다고 하자. 즉 $\boldsymbol{P}^{-1}\boldsymbol{AP}=\boldsymbol{D}$ 는 대각행렬이다. 대각행렬이 주어졌을 때, 표준정규직교벡터 $\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n\}$ 는 $\lambda_i = D_{ii}$ 를 고유값으로 갖는 대각행렬의 고유벡터이다. 여기서

$$
\boldsymbol{APe}_i = \boldsymbol{P}\boldsymbol{P}^{-1}\boldsymbol{APe}_i= \boldsymbol{PDe}_i=\lambda_i \boldsymbol{Pe}_i
$$

이므로 $\boldsymbol{Pe}_i$ 는 $\boldsymbol{A}$ 의 고유벡터이다. $\boldsymbol{P}$ 가 isometry 이므로 $\{\boldsymbol{Pe}_1,\ldots,\,\boldsymbol{Pe}_n\}$ 은 $\boldsymbol{A}$ 의 고유벡터로 이루어진 $\mathbb{C}^n$ 의 정규직교기저이다.

($3. \implies 1.$) $\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n\}$ 이 $\boldsymbol{A}$ 의 고유벡터로 이루어진 $\mathcal{M}_{n \times 1}(\mathbb{C})$ 의 정규직교기저라 하자. 이 때 $\boldsymbol{u}_i$ 의 고유값은 $\lambda_i$ 라 하자.  

$$
\langle \boldsymbol{A}^\ast \boldsymbol{e}_i,\,\boldsymbol{e}_j\rangle = \langle \boldsymbol{e}_i,\, \boldsymbol{Ae}_j\rangle = \overline{\lambda_j} \delta_{ij}
$$

이다. 즉,

$$
\boldsymbol{A}^\ast \boldsymbol{e}_i = \overline{\lambda_i} \boldsymbol{e}_i
$$

이다. $\boldsymbol{u} = \sum_i u_i \boldsymbol{e}_i$ 에 대해,

$$
\begin{aligned}
\|\boldsymbol{A}^\ast \boldsymbol{u} \|^2 &=  \left\langle \boldsymbol{A}^\ast \left(\sum_i u_i \boldsymbol{e}_i \right),\, \boldsymbol{A}^\ast \left(\sum_j u_j \boldsymbol{e}_j \right) \right\rangle \\
&=\sum_{i,\,j} u_i \overline{u_j} \left\langle \boldsymbol{A}^\ast\boldsymbol{e}_i,\, \boldsymbol{A}^\ast \boldsymbol{e}_j\right\rangle \\
&= \sum_{i} |u_i|^2 |\lambda_i|^2 \\
&= \|\boldsymbol{A}\boldsymbol{u}\|^2
\end{aligned}
$$

이므로 $\boldsymbol{A}$ 는 정규행렬이다. $\square$

:::

</br>

::: {.callout-important appearance="minimal"}
에르미트 행렬과 정규행렬은 고유벡터로 이루어진 정규직교기저가 존재하며, 따라서 이 기저에서 대각행렬로 변환된다는 공통점을 갖는다. 차이점은 에르미트 행렬의 고유값은 항상 실수이지만 정규행렬은 복소수라는 것이다.
:::

</br>


::: {#exr-hermitian_normal}

복소 정사각 행렬 $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{C})$ 이 정규행렬이며 그 고유값이 모두 실수이면 $\boldsymbol{A}$ 는 에르미트 행렬이다.

:::

::: {.solution}

$\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n\}$ 이 $\boldsymbol{A}$ 의 고유벡터로 이루어진 $\mathcal{M}_{n \times 1}(\mathbb{C})$ 의 정규직교기저이고 $\boldsymbol{e}_i$ 의 고유값은 $\lambda_i$ 라 하자. @prp-hermite_tvv 에서 보았듯이 임의의 $\boldsymbol{u} \in \mathcal{M}_{n \times 1}(\mathbb{C})$ 에 대해 $\langle \boldsymbol{Au},\boldsymbol{u}\rangle$ 이 실수이면 $\boldsymbol{A}$ 는 에르미트 행렬이다. $\boldsymbol{u}= \sum_i^n u_i \boldsymbol{e}_i$ 라 하면,

$$
\begin{aligned}
\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle = \sum_i \lambda_i |u_i|^2 \in \mathbb{R}
\end{aligned}
$$

이다. 즉 $\boldsymbol{A}$ 는 에르미트 행렬이다. $\square$
:::

</br>


## 실수체($\mathbb{R}$) 에서 정의된 행렬에 대한 스펙트럼 정리

### 미리 알아야 할 것들

실수체에서 정의된 행렬 $\boldsymbol{A}$ 가 에르미트 행렬이면 대칭행렬이며, 대칭행렬이면 에르미트 행렬이다. 실수체에서 정의된 스펙트럼 정리를 증명하기 위해서는 몇가지 미리 증명해야 할 것이 있다.

</br>

::: {#lem-invirtible_deformation}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{R})$ 행렬에 대해 $\boldsymbol{A}$ 가 대칭행렬이고 실수 $b,\,c$ 가 $b^2-4c <0$ 일 때 

$$
\boldsymbol{A}^2+b\boldsymbol{A}+c\boldsymbol{I}_n
$$

은 가역행렬이다.
:::


::: {.proof}

영벡터가 아닌 벡터 $\boldsymbol{v}\in \mathbb{R}^{n\times 1}$ 에 대해

$$
\begin{aligned}
\langle (\boldsymbol{A}^2+b\boldsymbol{A}+c\boldsymbol{I}_n) \boldsymbol{v},\, \boldsymbol{v} \rangle &= \langle \boldsymbol{Av},\,\boldsymbol{Av} \rangle + b\langle \boldsymbol{Av},\,\boldsymbol{v} \rangle + c\langle \boldsymbol{v},\,\boldsymbol{v} \rangle \\
&= \|\boldsymbol{Av}\|^2 + b\langle \boldsymbol{Av}, \,\boldsymbol{v}\rangle + c\langle \boldsymbol{v},\,\boldsymbol{v}\rangle
\end{aligned}
$$

이다. 코시-슈바르츠 부등식으로부터,

$$
|b\langle \boldsymbol{Av},\,\boldsymbol{v}\rangle | \le |b| \cdot \|\boldsymbol{Av}\|\|\boldsymbol{v}\|
$$

임을 안다. 즉 $b\langle \boldsymbol{Av},\,\boldsymbol{v}\rangle  \ge -|b| \|\boldsymbol{Av}\|\|\boldsymbol{v}\|$ 이며,

$$
\begin{aligned}
\langle (\boldsymbol{A}^2+b\boldsymbol{A}+c\boldsymbol{I}_n) \boldsymbol{v},\, \boldsymbol{v} \rangle  & = \|\boldsymbol{Av}\|^2 + b\langle \boldsymbol{Av} ,\,\boldsymbol{v}\rangle + c\langle \boldsymbol{v},\,\boldsymbol{v}\rangle \\
& \ge \|\boldsymbol{Av}\|^2-|b|\|\boldsymbol{Av}\|\|\boldsymbol{v}\| + c\|\boldsymbol{v}\|^2 \\
&= \left(\|\boldsymbol{Av}\| - \dfrac{|b|\|\boldsymbol{v}\|}{2}\right)^2 + \left(c-\dfrac{b^2}{4}\right)\|\boldsymbol{Av}\|^2 >0
\end{aligned}
$$

이다. $\ker (\boldsymbol{A}^2+b\boldsymbol{A}+c\boldsymbol{I}_n) =\{0\}$ 이므로 $\boldsymbol{A}^2+b\boldsymbol{A}+c\boldsymbol{I}_n$ 는 가역행렬이다. $\square$

:::

</br>

::: {#lem-factorization_of_polinomial}
$n$ 차 실계수 다항식 $p(x)$ 는 1차식들과 2차식의 곱들로, 2차식의 경우 $f(x)$ 라 했을 때 $f(x)=0$ 을 만족하는 실수가 존재하지 않도록 아래와 같이 분해된다.

$$
p(x) = c(x-\lambda_1) \cdots (x-\lambda_m)(x^2 + b_1x + c_1)\cdots (x^2 + b_M x + c_M)
$$

이 때, $c,\,\lambda_1,\ldots,\,\lambda_m,\,b_1,\ldots,\,b_M,\,c_1,\ldots,\,c_M$ 은 실수이며, $i=1,\ldots,\,M$ 에 대해 $b_i^2<4c$ 이다.
:::


::: {.proof}

$p(x) = a_0 +a_1x + \cdots + a_nx^n,\, a_i\in \mathbb{R}$ 가 실수근 $\lambda_1,\ldots,\,\lambda_m$ 을 가지면 $\prod_{i=1}^m (x-\lambda_i)$ 로 우선 분해되고, 나머지는 2차식의 곱으로 분해된다는 의미이다. 대수학의 기본정리에 의해 $n$ 차 다항식은 (중근을 중복하여 세면) $n$ 개의 근을 가진다. 실수가 아닌 복소수 $\lambda$ 를 근으로 가진다고 하자.

$$
p(\lambda) = a_0 + a_1 \lambda + \cdots + a_n \lambda^n = 0
$$

이며 위의 식에 켤레복소수를 취하면

$$
\overline{p(\lambda)} = a_0 + a_1 \overline{\lambda} + \cdots + a_n \overline{\lambda^n} = 0
$$

이므로 $\overline{\lambda}$ 를 근으로 가진다. 즉 실계수 다항식 $p(x)$ 의 근은 실수이거나 복소수와 켤레복소수의 쌍이다. 복소수를 근으로 갖기 위해서는 $b_i^2<4c_i$ 이어야 한다. $\square$

:::

</br>

### 실수체에서 정의된 행렬에 대한 스펙트럼 정리

::: {#lem-hermitian_real_matrix_eigenvalue}
$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{R})$ 이 대칭행렬이면 고유값을 가진다.
:::

::: {.proof}

영벡터가 아닌 $\boldsymbol{v} \in \mathcal{M}_{n \times 1}(\mathbb{R})$ 을 생각하자. $\{\boldsymbol{v},\, \boldsymbol{Av},\ldots,\, \boldsymbol{A}^n \boldsymbol{v}\}$ 는 포함된 벡터의 갯수가 $n$ 보다 많으므로 선형종속이며, 따라서

$$
0=c_0 v + c_1 \boldsymbol{Av} + \cdots + c_n \boldsymbol{A}^n \boldsymbol{v}
$$

를 만족하는 nontrivial 한 $\{c_i\}$ 가 존재한다. @lem-factorization_of_polinomial 에 의해,

$$
\begin{aligned}
c_0 \boldsymbol{v} + & c_1 \boldsymbol{Av} + \cdots + c_n \boldsymbol{A}^n\boldsymbol{v} \\
&= c(\boldsymbol{A}-\lambda_1 \boldsymbol{I})\cdots (\boldsymbol{A}-\lambda_m \boldsymbol{I}) (\boldsymbol{A}^2 +b_1 \boldsymbol{A}+c_1\boldsymbol{I})\cdots (\boldsymbol{A}^2 +b_M \boldsymbol{A}+c_M\boldsymbol{I})
\end{aligned}
$$

로 분해 할 수 있다. 이 때 $i=1,\ldots,\,M$ 에 대해 $b_i^2<4c_i$ 이다. @lem-invirtible_deformation 에 의해 $(\boldsymbol{A}^2 +b_i\boldsymbol{A}+c_i\boldsymbol{I})$ 꼴의 행렬은 가역이다. 그렇다면 최소한 하나의 $\boldsymbol{A}-\lambda_j \boldsymbol{I}$ 꼴의 행렬이 가역행렬이 아니며, 이 때의 $\lambda_j$ 가 고유값이다. 즉 $\boldsymbol{A}$ 는 고유값을 가진다.$\square$

:::

</br>

::: {#lem-self_adjoint_matrix_and_invariable_space}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{R})$ 이 대칭행렬 이고 $U$ 가 $\boldsymbol{A}$ 에 대한 $\mathcal{M}_{n \times 1}(\mathbb{R})$ 에서의 불변부분공간일 때,

($1$) $U^\perp$ 도 $\boldsymbol{A}$에 대한 불변부분공간이다.

($2$) $\boldsymbol{A}|_U$ 도 대칭행렬 이다.

($3$) $\boldsymbol{A}|_{U^\perp}$ 도 대칭행렬 이다.

:::

::: {.proof}
($1$) $\boldsymbol{u}\in U,\, \boldsymbol{v}\in U^\perp$ 라 하자. $\boldsymbol{Au}\in U$ 이며 $\boldsymbol{A}$ 가 self-adjoint 이므로,

$$
\langle \boldsymbol{Av},\, \boldsymbol{u}\rangle = \langle \boldsymbol{v},\, \boldsymbol{Au}\rangle =0
$$

이다. 따라서 $U^\perp$ 도 $\boldsymbol{A}$ 에 대한 불변부분공간이다.

($2$) $\boldsymbol{u}_1,\,\boldsymbol{u}_2\in U$ 에 대해,

$$
\langle \boldsymbol{A}|_U \boldsymbol{u}_1,\,\boldsymbol{u}_2\rangle = \langle \boldsymbol{Au}_1,\, \boldsymbol{u}_2 \rangle = \langle \boldsymbol{u}_1,\, \boldsymbol{Au}_2\rangle = \langle \boldsymbol{u}_1,\,\boldsymbol{A}|_U\boldsymbol{u}_2\rangle
$$

이므로 $\boldsymbol{A}|_U$ 도 대칭행렬 이다.

($3$) ($1$), ($2$) 로 부터 자명하다. $\square$

:::

</br>

<!-- ::: {#lem-invariant_subspace_and_block_diagonal_form}

유한차원 벡터공간 $U$ 가 $\mathbb{F}^{n \times 1}$ 의 $\boldsymbol{A}\in \mathbb{F}^{n \times n}$ 에 대한 불변부분공간일 때 $\boldsymbol{A}$ 는 어떤 블록대각행렬과 닮았다.

:::

::: {.proof}
$U$ 에 대한 정규직교기저 $\mathcal{B}_\parallel$ 와 $U^\perp$ 에 대한 정규직교기저 $\mathcal{B}_\perp$ 에 대해 $\mathcal{B} = \mathcal{B}_\parallel \cup \mathcal{B}_\perp$ 는 정규직교기저이다. 이 때 $\dim U = m$ 이면, $\dim U^\perp = n-m$ 이다. 이 정규직교 기저로 $\boldsymbol{A}$ 를 닮음변환하면 $m\times m$ 행렬과 $(n-m)\times (n-m)$ 행렬로 블록대각화된다. $\square$

:::


참고 : [직교 여공간과 직합](#직교-여공간과-직합)

</br> -->

::: {#lem-matrix_under_two_invariant_subspace}

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{R})$ 가 대칭행렬이고 $U,\,V$ 가 $\mathcal{M}_{n \times 1}(\mathbb{R})$ 의 $\boldsymbol{A}$ 에 대한 불변부분공간이며 $\mathcal{M}_{n \times 1}(\mathbb{R})= U \oplus V$ 이면 $\boldsymbol{A}$ 는 어떤 직교변환에 의해 블럭대각행렬이 된다.
:::

::: {.proof}

$\boldsymbol{u}\in U$ 이면 $\boldsymbol{Au}\in U$ 이고 $\boldsymbol{v}\in V$ 이면 $\boldsymbol{Av}\in V$ 이다. $\mathcal{M}_{n \times 1}(\mathbb{R}) = U \oplus V$ 이므로 $U$ 의 정규직교기저 $\{\boldsymbol{e}_i\}$ 와 $V$ 의 정규직교기저 $\{\boldsymbol{f}_j\}$ 에 대해 $\{\boldsymbol{e}_i\}\cup \{\boldsymbol{f}_j\}$ 는 $\mathcal{M}_{n \times 1}(\mathbb{R})$ 의 기저이며 이 기저로의 직교변환에 대해 $\boldsymbol{A}$ 는 블럭대각행렬이 된다. $\square$ 
:::

</br>

::: {#lem-symmetric_matrix_digoalization} 
$\boldsymbol{A}$ 가 대칭행렬이면 어떤 직교 변환에 의해 대각행렬이 된다.
:::


::: {.proof}

$n$ 에 대한 수학적 귀납법을 이용한다. $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{R})$ 이 대칭행렬이라고 하자. $n=1$ 일 때는 스스로 대각행렬이다. 이제 $k<n$ 인 대칭행렬은 어떤 직교 변환에 의해 대각행렬이 된다고 가정하자.

$\boldsymbol{A}$ 가 $n \times n$ 대칭 행렬일 때 고유값이 항상 존재하며 고유값에 대한 고유벡터 가운데 하나 $\boldsymbol{u}_1$ 를 이용하여 $U=\text{span}(\boldsymbol{u}_1)$ 를 만들면 $U$ 은 불변부분공간이며 @lem-self_adjoint_matrix_and_invariable_space 에서 보였듯이 $U^\perp$ 도 불변부분공간이다. $\mathcal{M}_{n \times n}(\mathbb{R}) = U \otimes U^\perp$ 이므로 @lem-matrix_under_two_invariant_subspace 에서 보였듯이 어떤 직교 변환에 의해 $1\times 1$ 행렬과 $(n-1)\times (n-1)$ 행렬로 블록대각행렬이 된다. $(n-1)\times (n-1)$ 행렬은 귀납법의 가정에 의해 대각행렬이 되므로 $\boldsymbol{A}$ 는 대각행렬이 된다. $\square$

:::

</br>

::: {#thm-spectrum_theorem_of_real_vector_space}

#### 실수체($\mathbb{R}$) 에서 정의된 행렬의 스펙트럼 정리

$\boldsymbol{A} \in \mathcal{M}_{n \times n}(\mathbb{R})$ 행렬에 대해 다음 세 명제는 동치이다.

&emsp; ($1$) $\boldsymbol{A}$ 는 대칭행렬이다.

&emsp; ($2$) $\boldsymbol{A}$ 는 직교변환에 의해 대각행렬로 표현된다.

&emsp; ($3$) $\boldsymbol{A}$ 의 고유벡터로 $\mathcal{M}_{n \times 1}(\mathbb{R})$ 의 정규직교기저를 구성 할 수 있다.

:::


::: {.proof}
($1\implies 2$) 는 앞에서 보였다.

($2 \implies 3$) $\boldsymbol{A}$ 가 orthognal 행렬 $\boldsymbol{P}$ 에 의해 대각행렬로 변환된다고 하자. 즉 $\boldsymbol{P}^{-1}\boldsymbol{AP}=\boldsymbol{D}$ 는 대각행렬이다. 대각행렬이 주어졌을 때, 표준정규직교벡터 $\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n\}$ 는 $\lambda_i = D_{ii}$ 를 고유값으로 갖는 대각행렬의 고유벡터이다. 여기서

$$
\boldsymbol{APe}_i = \boldsymbol{P}\boldsymbol{P}^{-1}\boldsymbol{APe}_i= \boldsymbol{PDe}_i=\lambda_i \boldsymbol{Pe}_i
$$

이므로 $\boldsymbol{Pe}_i$ 는 $\boldsymbol{A}$ 의 고유벡터이다. $\boldsymbol{P}$ 가 isometry 이므로 $\{\boldsymbol{Pe}_1,\ldots,\,\boldsymbol{Pe}_n\}$ 은 $\boldsymbol{A}$ 의 고유벡터로 이루어진 $\mathcal{M}_{n \times 1}(\mathbb{R})$ 의 정규직교기저이다.

($3 \implies 1$) $\{\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_n\}$ 이 $\boldsymbol{A}$ 의 고유벡터로 이루어진 $\mathbb{R}^n$ 의 정규직교기저라 하자. 이 때 $\boldsymbol{u}_i$ 의 고유값은 $\lambda_i$ 라 하자.  $\lambda_i$ 는 실수이므로,

$$
\langle \boldsymbol{A}^\ast \boldsymbol{u}_i,\,\boldsymbol{u}_j\rangle = \langle \boldsymbol{u}_i,\, \boldsymbol{Au}_j\rangle = \lambda_j \delta_{ij} = \lambda_i \delta_{ij} = \langle \boldsymbol{Au}_i,\, \boldsymbol{u}_j\rangle
$$

이다. 즉 $\boldsymbol{A}=\boldsymbol{A}^\ast$ 이며 $\boldsymbol{A}$ 가 실행렬이므로 $\boldsymbol{A}$ 는 대칭행렬이다. $\square$

:::

</br>
