---
title: "내적벡터공간에서의 연산자"
number-sections: true
number-depth : 2
crossref:
  chapters: true
---

</br>

## Adjoint matrix

### Adjoint matrix

::: {.callout-note appearance="simple" icon="false"}
::: {#def-adjoint_operator}

#### Adjoint matrix

행렬 $\boldsymbol{A} \in \mathbb{F}^{m \times n}$ 에 대해 

$$
(\boldsymbol{A}^\ast)_{ij} = \overline{A_{ji}}
$$

를 만족하는 $\boldsymbol{A}^\ast \in \mathbb{F}^{n \times m}$ 을 $\boldsymbol{A}$ 에 대한 adjoint matrix 라고 한다. [행렬 $\boldsymbol{A}$ 의 수반행렬에 대해서는 $\boldsymbol{A}^\ast$, $\boldsymbol{A}^\dagger$, $\boldsymbol{A}^H$ 등의 표기법이 사용된다. 물리학 특히 양자역학에서는 수반행렬에 대해 $\boldsymbol{A}^\ast$ 보다는 $\boldsymbol{A}^\dagger$ 의 표현을 더 많이 사용하기도 한다.]{.aside}


:::
:::

</br>

::: {#exr-adjoint_matrix}
정규직교기저에서 정의된 $\boldsymbol{A}\in \mathbb{F}^{m \times n}$, $\boldsymbol{v}\in \mathbb{F}^{m\times 1}$, $\boldsymbol{u}\in \mathbb{F}^{n \times 1}$ 에 대해 $\langle \boldsymbol{Au},\, \boldsymbol{v} \rangle = \langle \boldsymbol{u},\, \boldsymbol{A}^\ast \boldsymbol{v} \rangle$ 임을 보여라.
:::

::: {.proof}

$\mathbb{F}^{n\times 1}$ 의 정규직교기저 $\{\boldsymbol{e}_i\}$ 와 $\mathbb{F}^{m \times 1}$ 의 정규직교기저 $\{\boldsymbol{f}_j\}$ 를 생각하자. $\boldsymbol{u}=\sum_i u_i \boldsymbol{e}_i$, $\boldsymbol{v}= \sum_j v_j \boldsymbol{f}_j$ 라고 하면,
$$
\begin{aligned}
\langle \boldsymbol{Au},\,\boldsymbol{v}\rangle &= \boldsymbol{Au}\cdot \boldsymbol{v} = \sum_i (\boldsymbol{Au})_i\overline{v_i} = \sum_{i, j} A_{ij}u_j\overline{v}_i \\
\langle \boldsymbol{u},\,\boldsymbol{A}^\ast \boldsymbol{v}\rangle &= \boldsymbol{u} \cdot (\boldsymbol{A}^\ast \boldsymbol{v}) = \sum_j u_j \overline{\left(\sum_i (\boldsymbol{A}^\ast)_{ji}v_i\right)} \\
&= \sum_j u_j u_j \overline{\left(\sum_i \overline{A_{ij}}v_i\right)} = \sum_{i, j} A_{ij}u_j\overline{v}_i 
\end{aligned}
$$

이다. 따라서 정규직교기저에서 $\langle \boldsymbol{Au},\, \boldsymbol{v} \rangle = \langle \boldsymbol{u},\, \boldsymbol{A}^\ast \boldsymbol{v} \rangle$ 이다. $\square$ 

:::

</br>


::: {#prp-properties_of_adjoint_operator}

다음이 성립한다.

1. $\boldsymbol{A},\, \boldsymbol{B}\in \mathbb{F}^{m\times n}$ 일 때 $(\boldsymbol{A}+\boldsymbol{B})^\ast = (\boldsymbol{A}^\ast + \boldsymbol{B}^\ast)$ 이다.

2. $\boldsymbol{A} \in \mathbb{F}^{m\times n}$, $\lambda \in \mathbb{F}$ 일 때 $(\lambda \boldsymbol{A})^\ast = \overline{\lambda}\boldsymbol{A}^\ast$.

3. $(\boldsymbol{A}^\ast)^\ast = \boldsymbol{A}$.

4. $\boldsymbol{I}^\ast = \boldsymbol{A}$.

5. $\boldsymbol{A} \in \mathbb{F}^{m \times n},\, \boldsymbol{B}\in \mathbb{F}^{n \times l}$ 일 때 $(\boldsymbol{AB})^\ast = \boldsymbol{B}^\ast \boldsymbol{A}^\ast$ 이다.

:::

::: {.proof}

$1$ 에서 $4$ 는 생략한다. 
$$
(\boldsymbol{AB}^{\ast})_{ij} =\overline{\boldsymbol{AB}_{ji}} = \sum_k \overline{A_{jk}}\overline{B_{ki}}= \sum_k (\boldsymbol{A}^\ast)_{kj}(\boldsymbol{B}^\ast)_{ik} = (\boldsymbol{B}^\ast \boldsymbol{A}^\ast)_{ij}
$$ 

이므로  $(\boldsymbol{AB})^\ast = \boldsymbol{B}^\ast \boldsymbol{A}^\ast$ 이다. $\square$

:::

</br>

::: {#thm-kernel_image_of_adjoint_operator}
#### Adjoint metrix 의 kernel 과 치역

$\boldsymbol{A}\in \mathbb{F}^{m \times n}$ 일 때 다음이 성립한다.

1. $\ker (\boldsymbol{A}^\ast) = (\text{im} (\boldsymbol{A}))^\perp$

2. $\text{im} (\boldsymbol{A}^\ast) = (\ker (\boldsymbol{A}))^\perp$,

3. $\ker (\boldsymbol{A}) = (\text{im}\, (\boldsymbol{A}^\ast))^\perp$,

4. $\text{im} (\boldsymbol{A}) = (\ker (\boldsymbol{A}^\ast))^\perp$.
:::

::: {.proof}

$1$ 은 다음과 같이 보일 수 있다.
$$
\begin{aligned}
\boldsymbol{v}\in \ker (\boldsymbol{A}^\ast) & \iff \boldsymbol{A}^\ast\boldsymbol{v}=\boldsymbol{0}  \\
&\iff \forall\boldsymbol{u}\in \mathbb{F}^{n \times 1},\, \langle \boldsymbol{u},\boldsymbol{A}^\ast\boldsymbol{v}\rangle = 0 \\
&\iff \forall\boldsymbol{u}\in \mathbb{F}^{n \times 1}, \langle \boldsymbol{Au},\boldsymbol{v}\rangle = 0 \\
&\iff \boldsymbol{v} \in \left(\text{im}(\boldsymbol{A})\right)^\perp
\end{aligned}
$$

$2$ 를 보이자 $1$ 의 결과에 $\boldsymbol{A}$ 대신 $\boldsymbol{A}^\ast$ 를 넣으면 $\ker(\boldsymbol{A}) = (\text{im}(\boldsymbol{A}^\ast))^\perp$ 이다. @prp-properties_of_orthogonal_complement 에서 부분공간 $U$ 에 대해 $(U^\perp)^\perp = U$ 임을 이용하면 $2$ 를 얻는다. 

$3$, $4$ 는 $1$, $2$ 의 결과에서 $\boldsymbol{A}$ 대신에 $\boldsymbol{A}^\ast$ 를 넣으면 보일 수 있다. $\square$ 

:::

</br>

## 에르미트 행렬 (Hermitian matrix)

::: {.callout-note appearance="simple" icon="false"}
::: {#def-hermitian_matrix}

복소행렬 $\boldsymbol{A}$ 에 대해 $A_{ji} = \overline{A_{ij}}$ 이면,  즉 $\boldsymbol{A}^\ast = \boldsymbol{A}$ 이면 이 행렬을 **에르미트 행렬(Hermitian matrix)** 이라 한다. 

:::
:::

</br>


::: {#prp-peroperties_hermitian_operator}

#### 에르미트 행렬의 성질

에르미트 행렬 $\boldsymbol{A}$ 에 대해 대해 다음이 성립한다.

1. $\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle = \langle \boldsymbol{u},\, \boldsymbol{Au}\rangle$ 이다.

2. 고유값은 항상 실수이다.

3. 서로 다른 고유값을 갖는 두 고유벡터는 직교한다.

4. 모든 $\boldsymbol{u}\in \mathbb{F}^{n \times 1}$ 에 대해 $\langle \boldsymbol{Au},\,\boldsymbol{u}\rangle =0$ 이면 $\boldsymbol{A}=0$ 이다.

:::

::: {.proof}

$1$. $\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle = \langle \boldsymbol{u},\, \boldsymbol{A}^\ast \boldsymbol{u}\rangle = \langle \boldsymbol{u},\, \boldsymbol{Au}\rangle$.


$2$. 고유벡터 $\boldsymbol{u}\in \mathbb{F}^{m\times 1}$ 에 대한 고유값을 $\lambda$ 라 하자. 

$$
\lambda \|\boldsymbol{u}\|^2 = \lambda \langle \boldsymbol{u},\, \boldsymbol{u}\rangle  = \langle \boldsymbol{Au},\, \boldsymbol{u}\rangle = \langle \boldsymbol{u},\, \boldsymbol{A}^\ast \boldsymbol{u} \rangle = \langle \boldsymbol{u},\, \boldsymbol{Au} \rangle = \overline{\lambda}\|\boldsymbol{u}\|^2\,.
$$
이므로 $\lambda = \overline{\lambda}$ 이다. 즉 $\lambda$ 는 실수이다.

$3$. $\lambda_1,\,\lambda_2$ 가 서로 다른 고유벡터이며 $\boldsymbol{u}_1,\,\boldsymbol{u}_2$ 를 각각에 대한 고유벡터라 하자. 에르미트 행렬의 고유값은 항상 실수이므로 $\overline{\lambda_2}=\lambda_2$ 이다.

$$
\begin{aligned}
&\lambda_1 \langle \boldsymbol{u}_1,\, \boldsymbol{u}_2\rangle = \langle \boldsymbol{Au}_1,\,\boldsymbol{u}_2\rangle = \langle \boldsymbol{u}_1,\, \boldsymbol{A}^\ast \boldsymbol{u}_2 \rangle = \langle \boldsymbol{u}_1,\,\boldsymbol{Au}_2\rangle  = \overline{\lambda_2} \langle \boldsymbol{u}_1,\,\boldsymbol{u}_2\rangle  = \lambda_2 \langle \boldsymbol{u}_1,\,\boldsymbol{u}_2 \rangle \\
\implies & (\lambda_1-\lambda_2) \langle \boldsymbol{u}_1,\, \boldsymbol{u}_2\rangle   = 0 \\
\implies & \langle \boldsymbol{u}_1,\,\boldsymbol{u}_2 \rangle = 0
\end{aligned}
$$

$4$. $\mathbb{F}=\mathbb{C}$ 일 경우와 $\mathbb{R}$ 일 경우로 분리하여 증명한다. $\mathbb{C}$ 일 경우는 굳이 에르미트 연산자가 아니어도 성립한다.

$\boldsymbol{A}\in \mathbb{R}^{m \times n}$ 이면 임의의 $\boldsymbol{u},\,\boldsymbol{u}'\in \mathbb{R}^{n \times 1}$ 에 대해

$$
\begin{aligned}
0&=\dfrac{\langle \boldsymbol{A}(\boldsymbol{u}+\boldsymbol{u}'),\, \boldsymbol{u}+\boldsymbol{u}'\rangle -\langle \boldsymbol{A}(\boldsymbol{u}-\boldsymbol{u}'),\, \boldsymbol{u}-\boldsymbol{u}'\rangle}{4} \\
&= \dfrac{1}{2} \left( \langle \boldsymbol{Au},\, \boldsymbol{u}'\rangle + \langle \boldsymbol{Au}',\, \boldsymbol{u}\rangle\right) = \dfrac{1}{2} \left(\langle \boldsymbol{Au},\, \boldsymbol{u}' \rangle + \langle \boldsymbol{u}',\, \boldsymbol{A}^\ast \boldsymbol{u}\rangle  \right) \\
&= \dfrac{1}{2} \left(\langle \boldsymbol{Au},\,\boldsymbol{u}'\rangle  + \langle \boldsymbol{u}',\, \boldsymbol{Au}\rangle \right) \\
&= \langle \boldsymbol{Au},\, \boldsymbol{u}'\rangle
\end{aligned}
$$

이다. 이제 $\boldsymbol{A}\in \mathbb{C}^{m \times n}$ 이라면,

$$
\begin{aligned}
0 & = \dfrac{1}{4} \left(\langle \boldsymbol{A}(\boldsymbol{v}+\boldsymbol{v}'),\, \boldsymbol{v}+\boldsymbol{v}' \rangle - \langle \boldsymbol{A}(\boldsymbol{v}-\boldsymbol{v}'),\, \boldsymbol{v} - \boldsymbol{v}'\rangle \right) \\
&\qquad + \dfrac{i}{4} \left( \langle \boldsymbol{A}(\boldsymbol{v}+i\boldsymbol{v}'),\, \boldsymbol{v}+i\boldsymbol{v}'\rangle  - \langle \boldsymbol{A}(\boldsymbol{v}-i\boldsymbol{v}'),\, \boldsymbol{v}-i\boldsymbol{v}'\rangle \right) \\
&= \dfrac{1}{4} \left(2 \langle \boldsymbol{Av},\,\boldsymbol{v}'\rangle  + 2 \langle \boldsymbol{Av}',\, \boldsymbol{v}\rangle +2 \langle \boldsymbol{Av},\,\boldsymbol{v}'\rangle -2 \langle \boldsymbol{Av}',\,\boldsymbol{v}\rangle \right) \\
&= \langle \boldsymbol{Av},\, \boldsymbol{v}'\rangle
\end{aligned}
$$

이다. 임의의 $\boldsymbol{v},\, \boldsymbol{v}'\in V$ 에 대해 $\langle \boldsymbol{Av},\,\boldsymbol{v}'\rangle =0$ 이므로 $\boldsymbol{A}=0$ 이다. $\square$
:::

</br>

::: {#prp-hermite_tvv}

복소연산자 $\boldsymbol{A}\in \mathbb{C}^{n\times n}$ 에 대해 다음 두 명제는 동치이다.

1. 임의의 $\boldsymbol{u}\in \mathbb{C}^{n\times 1}$ 에 대해 $\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle$ 은 실수이다.

2. $\boldsymbol{A}$ 는 hermitian 이다.

:::


::: {.proof}

($1\implies 2$) $\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle$ 이 실수이면 $\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle = \overline{\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle}$ 이다. 따라서,

$$
\begin{aligned}
0 &= \langle \boldsymbol{Au},\, \boldsymbol{u}\rangle - \overline{\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle} = \langle \boldsymbol{Au},\, \boldsymbol{u}\rangle - \langle \boldsymbol{u},\, \boldsymbol{Au}\rangle = \langle \boldsymbol{Au},\, \boldsymbol{u}\rangle - \langle \boldsymbol{A}^\ast\boldsymbol{u},\, \boldsymbol{u}\rangle \\
&= \langle (\boldsymbol{A}-\boldsymbol{A}^\ast)\boldsymbol{u},\, \boldsymbol{u}\rangle
\end{aligned}
$$

임을 안다. @prp-peroperties_hermitian_operator 의 ($4$) 로 부터 $\boldsymbol{A}=\boldsymbol{A}^\ast$ 임을 알 수 있다. 즉 $\boldsymbol{A}$ 는 hermitian matrix 이다.
 
($2 \implies 1$) $\boldsymbol{A}$ 가 hermitian 이라 하자. 

$$
\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle - \overline{\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle} = \langle \boldsymbol{Au},\, \boldsymbol{u}\rangle - \langle \boldsymbol{A}^\ast\boldsymbol{u},\, \boldsymbol{u}\rangle =0
$$

이므로 $\langle \boldsymbol{Au},\, \boldsymbol{u}\rangle$ 는 실수이다. $\square$
:::


</br>

## Isometry

::: {.callout-note appearance="simple" icon="false"}
::: {#def-isometry}
행렬 $\boldsymbol{S} \in \mathbb{F}^{n \times n}$ 이 임의의 $\boldsymbol{v} \in \mathbb{F}^{n \times 1}$ 에 대해

$$
\|\boldsymbol{Sv}\|^2 = \|\boldsymbol{v}\|^2
$$

일 때 $\boldsymbol{S}$ 를 **isometry** 라 한다. 즉 Isometry는 거리를 보존시키는 선형 변환을 나타내는 행렬이다.

:::
:::

</br>

::: {#prp-properties_of_isometry}

행렬 $\boldsymbol{S}\in \mathbb{F}^{n \times n}$ 에 대해 다음은 동치이다.  

1. $\boldsymbol{S}$ 는 Isometry이다.

2. $\langle \boldsymbol{Su},\, \boldsymbol{Sv}\rangle = \langle \boldsymbol{u},\,\boldsymbol{v}\rangle$

3. 정규직교벡터의 집합 $\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n \}$ 에 대해 $\{ \boldsymbol{Se}_1,\ldots,\,\boldsymbol{Se}_n\}$ 도 정규직교벡터의 집합이다.

4. $\boldsymbol{S}^\ast = \boldsymbol{S}^{-1}$ 이다.

:::


::: {.proof}
($1\implies 2$) 다음 두 식을 생각하자.

$$
\|\boldsymbol{Su}-\boldsymbol{Sv}\|^2 = \|\boldsymbol{S}(\boldsymbol{u}-\boldsymbol{v})\|^2=\|\boldsymbol{u}-\boldsymbol{v}\|^2 = \|\boldsymbol{u}\|^2 + \|\boldsymbol{v}\|^2 - \langle\boldsymbol{u},\,\boldsymbol{v}\rangle - \langle\boldsymbol{v},\,\boldsymbol{u}\rangle
$$

이다. 또한
$$
\begin{aligned}
\|\boldsymbol{Su}-\boldsymbol{Sv}\|^2 &=  \|\boldsymbol{Su}\|^2 + \| \boldsymbol{Sv}\|^2 - \langle \boldsymbol{Su},\, \boldsymbol{Sv} \rangle - \langle \boldsymbol{Sv},\, \boldsymbol{Su} \rangle \\
&=\|\boldsymbol{u}\|^2 + \|\boldsymbol{v}\|^2 - \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle - \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle
\end{aligned}
$$

이다. 이로부터 다음 결과를 얻을 수 있다.
$$
\langle\boldsymbol{u},\,\boldsymbol{v}\rangle + \langle\boldsymbol{v},\,\boldsymbol{u}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle + \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle \tag{1} 
$$

실수체에서 정의된 행렬와 벡터공간이라면 $\langle\boldsymbol{u},\,\boldsymbol{v}\rangle = \langle\boldsymbol{v},\,\boldsymbol{u}\rangle$, $\langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle = \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle$ 이므로 $\langle\boldsymbol{u},\,\boldsymbol{v}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle$ 이다.

복소수체에서 정의된 행렬과 벡터공간이라면 다음을 더 생각하자.

$$
\begin{aligned}
\|\boldsymbol{Su}-i\boldsymbol{Sv}\|^2 & = \|\boldsymbol{S}(\boldsymbol{u}-i\boldsymbol{v})\|^2=\|\boldsymbol{u}-i\boldsymbol{v}\|^2 \\
&= \|\boldsymbol{u}\|^2 + \|\boldsymbol{v}\|^2 + i\langle\boldsymbol{u},\,\boldsymbol{v}\rangle -i \langle\boldsymbol{v},\,\boldsymbol{u}\rangle
\end{aligned}
$$

또한
$$
\begin{aligned}
\|\boldsymbol{Su}-i\boldsymbol{Sv}\|^2 &=  \|\boldsymbol{Su}\|^2 + \| \boldsymbol{Sv}\|^2 + i\langle \boldsymbol{Su},\, \boldsymbol{Sv} \rangle -i \langle \boldsymbol{Sv},\, \boldsymbol{Su} \rangle \\
&=\|\boldsymbol{u}\|^2 - \|\boldsymbol{v}\|^2 + i\langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle -i \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle
\end{aligned}
$$

이다. 이로부터 다음 결과를 얻는다.
$$
\langle\boldsymbol{u},\,\boldsymbol{v}\rangle - \langle\boldsymbol{v},\,\boldsymbol{u}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle - \langle\boldsymbol{Sv},\,\boldsymbol{Su}\rangle\tag{2}
$$

식 ($1$), ($2$) 로부터 $\langle\boldsymbol{u},\,\boldsymbol{v}\rangle = \langle\boldsymbol{Su},\,\boldsymbol{Sv}\rangle$ 임을 알 수 있다.


($2\implies 3$) $\langle \boldsymbol{e}_i, \boldsymbol{e}_i\rangle = \delta_{ij}$ 이므로 ($2$) 에 의해 $\langle \boldsymbol{Se}_i, \boldsymbol{Se}_j \rangle = \langle \boldsymbol{e}_i, \boldsymbol{e}_i\rangle = \delta_{ij}$ 이다.

($3 \implies 4$) 정규직교기저 $\{\boldsymbol{e}_1,\ldots,\,\boldsymbol{e}_n\}$ 에 대해 $\langle \boldsymbol{S}^\ast\boldsymbol{Se}_i,\,\boldsymbol{e}_j\rangle = \langle \boldsymbol{Se}_i,\boldsymbol{Se}_j\rangle = \delta_{ij}$ 임을 가정한다. 임의의 $\boldsymbol{u}\in \mathbb{F}^{n \times 1}$ 에 대해 $\boldsymbol{u}=\sum_i u_i \boldsymbol{e}_i$ 이고 $\boldsymbol{S}^\ast\boldsymbol{Su} = \sum_i u'_i \boldsymbol{e}_i$ 라 하자.

$$
\begin{aligned}
u'_j &= \langle \boldsymbol{S}^\ast \boldsymbol{Su}, \boldsymbol{e}_j \rangle = \langle \boldsymbol{Su}, \boldsymbol{Se}_j\rangle  \\
&= \sum_{i=1}^n u_i \langle \boldsymbol{Se}_i ,\boldsymbol{Se}_j \rangle = u_i \delta_{ij} = u_j
\end{aligned}
$$
 
이다. 임의의 $\boldsymbol{u}\in \mathbb{F}^{n \times 1}$ 에 대해 $\boldsymbol{S}^\ast \boldsymbol{Su} =  \boldsymbol{u}$ 이므로 $\boldsymbol{S}^\ast \boldsymbol{S}=\boldsymbol{I}$ 이다. 즉 $\boldsymbol{S}^\ast = \boldsymbol{S}^{-1}$ 이다. 


($4 \implies 1$) 임의의 벡터 $\boldsymbol{u}$ 에 대해 $\boldsymbol{S}^\ast =\boldsymbol{S}^{-1}$ 이라면

$$
\|\boldsymbol{Su}\|^2=\langle \boldsymbol{Su},\,\boldsymbol{Su}\rangle = \langle \boldsymbol{u}, \boldsymbol{S}^\ast\boldsymbol{Su}\rangle = \|\boldsymbol{u}\|^2
$$

이므로 $\boldsymbol{S}$ 는 isometry 이다. $\square$

:::

</br>

::: {#exr-cojugate_of_isometry}
$\boldsymbol{S}$ 가 isometry 이면 $\boldsymbol{S}^\ast$ 도 isometry 이다.
:::

::: {.proof}

@prp-properties_of_isometry 에서 보였듯이 $\boldsymbol{S}$ 가 isometry 이면 $\boldsymbol{S}^\ast = \boldsymbol{S}^{-1}$ 이다. 따라서
$$
\|\boldsymbol{S}^\ast \boldsymbol{u}\|^2 = \langle \boldsymbol{S}^\ast\boldsymbol{u},\, \boldsymbol{S}^\ast\boldsymbol{u}\rangle = \langle \boldsymbol{u} | \boldsymbol{SS}^\ast \boldsymbol{u}\rangle = \|\boldsymbol{u}\|^2
$$

이므로 $\boldsymbol{S}^\ast$ 도 isometry 이다. $\square$
:::




::: {#exr-product_of_isometries}
$\boldsymbol{S},\,\boldsymbol{T}\in \mathbb{F}^{n\times n}$ 이 isometry 이면 $\boldsymbol{ST}$ 도 isometry 이다.
:::


::: {.solution}

@prp-properties_of_isometry 에 의해 $\boldsymbol{S}^{-1}=\boldsymbol{S}^\ast$ 이면 $\boldsymbol{S}$ 가 isometry 인 것을 이용한다.
$$
(\boldsymbol{ST})^{-1}= \boldsymbol{T}^{-1}\boldsymbol{S}^{-1}= \boldsymbol{T}^\ast \boldsymbol{S}^\ast = (\boldsymbol{ST})^\ast
$$

:::

</br>

### Unitary and Orthogonal Operator/Matrix

::: {.callout-caution}

여러번 강조하고 또 강조했지만 선형사상과 벡터의 행렬표현은 특정 기저에 대한 표현이다. 우리는 정규직교기저를 배웠지만 지금까지는 굳이 행렬표현의 기저를 정규직교기저로 한정짓지 않았다. 하지만 이제부터는 특별한 언급이 없는 한 정규직교기저로 한정짓고자 한다. 즉 내적벡터공간에 대한 행렬과 벡터의 표현은 정규직교기저에 대한 표현이다. 따라서 내적은 dot product 와 같아진다. 

:::

</br>

::: {#def-orthogonal_operator}

#### 유니타리행렬과 직교행렬

복소공간에서 정의된 isometry 를 **유니타리 연산자/행렬 (unitary operator/matrix)** 라 하고 실수공간에서 정의된 isometry 를 **직교 연산자/행렬 (orthogonal operator/matrix)** 라 한다. 유니타리 행렬에 의한 행렬/벡터의 닮을 변환을 **유니타리 변환 (unitary transformation)**, 직교행렬에 의핸 행렬/벡터의 변환을 **직교 변환 (orthogonal transformation)**이라고 한다.

::::




</br>

### Isometry 와 정규직교기저

정규직교기저간의 기저 변환과 isometry 에 대한 두가지를 보인다.

::: {#prp-isometry_orthonormal_basis}
$\boldsymbol{S}$ 가 isometry 일 때 $\boldsymbol{S}$ 의 각 열벡터의 집합은 정규직교기저이며, 정규직교기저를 각 열벡터로 갖는 행렬은 isometry 이다.
:::

::: {.proof}

$\boldsymbol{S}\in \mathbb{F}^{n \times n}$ 이 isometry 이면 $\boldsymbol{S}^\ast\boldsymbol{S} = \boldsymbol{I}$ 임을 안다. 따라서, 

$$
\delta_{ij} = (\boldsymbol{S}^\ast\boldsymbol{S})_{ij} = \sum_k (\boldsymbol{S}^\ast)_{ik}(\boldsymbol{S})_{kj} = \sum_k \overline{\boldsymbol{S}_{ki}}\boldsymbol{S}_{kj} = \boldsymbol{S}_{:j}\cdot \boldsymbol{S}_{:i}
$$

이므로 $\boldsymbol{S}$ 의 열벡터의 집합은 정규직교기저이다. 또한 $\boldsymbol{S}$ 의 각 열벡터가 정규직교기저이면, $\boldsymbol{S}_{:j}\cdot \boldsymbol{S}_{:i} =\delta_{ij}$ 이므로

$$
 (\boldsymbol{S}^\ast\boldsymbol{S})_{ij} = \sum_k (\boldsymbol{S}^\ast)_{ik}(\boldsymbol{S})_{kj} = \sum_k \overline{\boldsymbol{S}_{ki}}\boldsymbol{S}_{kj} = \boldsymbol{S}_{:j}\cdot \boldsymbol{S}_{:i} = \delta_{ij}
$$

이다. 즉 $\boldsymbol{S}^\ast \boldsymbol{S}=\boldsymbol{I}$ 이므로 $\boldsymbol{S}$ 는 isometry 이다. $\square$

:::
</br>

::: {#prp-2}
정규직교기저간의 변환행렬은 isometry 이다.
:::


::: {.proof}

 $\{\boldsymbol{u}_i\}$, $\{\boldsymbol{v}_j\}$ 가 정규직교기저라 하자.

$$
\boldsymbol{v}_j = \sum_{k=1}^n S_{kj}\boldsymbol{u}_k
$$

라면

$$
\begin{aligned}
\delta_{ij} &= \langle \boldsymbol{v}_i,\, \boldsymbol{v}_j \rangle = \sum_k \sum_l S_{ki}\overline{S_{lj}} \langle \boldsymbol{u}_k,\, \boldsymbol{u}_l \rangle \\
&= \sum_k \sum_l  S_{ki}\overline{S_{lj}} \delta_{kl}= \sum_l (S^\ast)_{jl}S_{li} \\
&= (\boldsymbol{S}^\ast \boldsymbol{S}) _{ij}
\end{aligned}
$$

이다. 즉 $\boldsymbol{P}^\ast \boldsymbol{P}=\boldsymbol{I}$ 이므로 $\boldsymbol{P}$ 는 isometry 이다.

:::

</br>

::: {#exr-determinant_of_isometry}

직교행렬의 행렬식은 $1$ 혹은 $-1$ 이다. Unitary 행렬의 행렬식은 크기가 $1$ 인 복소수이다.
:::

::: {.solution}
$\det(\boldsymbol{S}^\ast \boldsymbol{S})=\det(\boldsymbol{S}^\ast) \det(\boldsymbol{S}) = \det(\boldsymbol{I})=1$ 임을 이용한다. 직교행렬이라면, 즉 실행렬이라면 $\boldsymbol{S}^\ast = \boldsymbol{S}^T$ 이며 $\det (\boldsymbol{S}^T) = \det (\boldsymbol{S})$ 이므로 $(\det(\boldsymbol{S})))^2=1$ 이다. 따라서 $\det (\boldsymbol{S})= \pm 1$ 이다. Unitary 행렬이라면, 즉 복소행렬이라면 $\det(\boldsymbol{S}^\ast) = \overline{\det (\boldsymbol{S}^T)} = \overline{\det (\boldsymbol{S})}$ 이다. 즉 $|\det (\boldsymbol{S})|^2=1$ 이다. $\square$ 

:::

</br>

### Isometry 와 행렬의 변환

$n$ 차원 벡터공간 $V$ 에서 정의된 연산자 $T$ 와 정규직교기저 $\{u_1,\ldots,\,u_n\}$ 를 생각하자. 이 정규직교기저에서 $T$ 의 행렬표현이 $\boldsymbol{A}$ 이며, 닮을변환을 나타내는 $\boldsymbol{P}$ 에 의해 기저가 변화했을 때의 행렬표현은 $\boldsymbol{P}^{-1}\boldsymbol{AP}$ 임을 안다. $\boldsymbol{P}$ 가 isometry 이면 $\boldsymbol{P}^{-1}=\boldsymbol{P}^\ast$ 이므로 기저가 변환된 행렬은 $\boldsymbol{P}^\ast \boldsymbol{AP}$ 이다.

</br>

