---
title: "내적"
number-sections: true
number-depth : 2
crossref:
  chapters: true
---

## 내적 (Inner product) 과 노름 (norm)

::: {.callout-note appearance="simple" icon="false"}
::: {#def-innerproduct}

#### 내적과 내적 공간

$\mathbb{F}$-벡터공간 $V$ 에서 정의된 $\phi : V \times V \to \mathbb{F}$ 가 모든 $u,\,u',\,v\in V$ 와 $c\in \mathbb{F}$ 에 대해 다음 성질을 만족하면 $\phi$ 를 $V$ 에서 정의된 **내적(Inner product)** 이라 한다.

&emsp; ($1$) $\phi (v,\,v) \ge 0$;

&emsp; ($2$) $\phi (v,\,v) = 0 \iff v = 0$;

&emsp; ($3$) $\phi (u + u', v)  = \phi (u,\, v) + \phi (u',\, v)$;

&emsp; ($4$) $\phi (cu,\,v) = c \phi (u,\,v)$;

&emsp; ($5$) $\phi (v,\, u) = \overline{\phi (u,\,v)}$.

[$x,\,y \in \mathbb{R}$ 에 대해 복소수 $z=x+iy$ 의 켤레복소수 $\overline{z}$ 는 $x-iy$ 이다. 즉 $\overline{x+iy}= x-iy$ 이다.]{.aside}

이것을 만족하는 함수는 어떤 것이든 내적이 될 수 있으며, 내적이 정의된 벡터공간을 **내적 벡터 공간(Inner product vector space)** 혹은 **내적 공간(Inner product space)**라 한다. 필드를 명시할 경우 $\mathbb{F}$-**내적 벡터 공간** 이라고 한다.흔히 두 백터의 내적을 $\langle u,\,v\rangle$ 로 쓰며 그 정의는 위의 $\phi$ 함수에 대해 $\langle u,\, v\rangle = \phi (u,\,v)$ 이다. 
:::
:::


</br>

대표적인 내적 벡터 공간으로는 다음과 같은 것들이 있다.

::: {#exm-innerproduct_R1_C1}
$\mathbb{C}^1$, 즉 1차원 복소벡터공간에서의 내적을

$$
\langle c_1,\, c_2\rangle = c_1\overline{c_2}
$$

로 정의 할 수 있다. $\mathbb{R}^1$ 에서는

$$
\langle r_1,\, r_2 \rangle = r_1r_2
$$

로 정의할 수 있다.
:::

</br>

::: {#exm-euclidean_innerproduct}

#### 유클리드 공간 (Euclidean sapce)

$\mathcal{M}_n(\mathbb{R})$ 에서의 내적을 $\langle \boldsymbol{x},\, \boldsymbol{y} \rangle =  \sum_{i=1}^n x_i y_i$ 로 정의할 수 있으며 이렇게 내적이 정의된 공간을 유클리드 공간이라고 한다. 
:::

</br>

::: {#exm-innerproduct_definded_by_intergration_in_R}

$[0,\,1]$ 구간에서 연속인 실함수로 이루어진 벡터공간에서의 내적을 아래와 같이 정의 할 수 있다.
$$
\langle f,\,g \rangle = \displaystyle \int_0^1 f(x)g(x)\, dx
$$
:::


</br>

::: {#prp-basic_properties_of_inner_product}

$V$ 가 $\mathbb{F}$-내적벡터공간이며 $u,\,v,\,w \in V,\, c \in \mathbb{F}$ 일 때 다음이 성립한다.

&emsp; ($1$) 정해진 $u\in V$ 에 대해 $T(v) = \langle v,\,u \rangle$ 는 선형사상이다.

&emsp; ($2$) $\langle 0,\, u\rangle = 0 = \langle u,\,0\rangle$.

&emsp; ($3$) $\langle u,\, v+w \rangle = \langle u,\, v\rangle + \langle u,\, w \rangle$.

&emsp; ($4$) $\langle u,\,c v\rangle = \overline{c} \langle u,\, v \rangle$.

&emsp; ($5$) $\langle u,\, v \rangle = \overline{\langle v,\, u\rangle}$.
:::

</br>


::: {.callout-note appearance="simple" icon="false"}
::: {#def-orthogonality_of_vector}

#### 벡터의 직교

두 벡터의 내적이 $0$ 일 때 두 벡터는 서로 **직교한다(be orthogonal, be perpendicular)** 고 한다. $\{v_1,\ldots,\,v_n\}$ 의 서로 다른 두 벡터가 모두 직교한다면 $\{v_1,\ldots,\,v_n\}$ 을 직교하는 벡터의 집합이라고 한다. 
:::
:::



</br>

::: {#prp-orthogonal_linearity}
내적벡터 공간 $V$ 에서의 영벡터가 아닌 벡터의 집합 $\{v_1,\ldots,\,v_n\}$ 이 직교하는 벡터의 집합이면 선형 독립이다.
:::
 
::: {.proof}
$\sum_i c_i v_i = 0$ 이라 하자. 선택된 $v_j$ 에 내적을 취하면,

$$
0 = \left\langle \sum c_i v_i,\, v_j \right\rangle = \sum_i c_i \langle v_i,\,v_j \rangle = c_j \langle v_j,\,v_j\rangle
$$

이다. $\langle v_j,\, v_j\rangle >0$ 이므로 $c_1=\cdots = c_n = 0$ 이다. 즉 $\{v_1,\ldots,\,v_n\}$ 은 선형독립이다. $\square$
:::

</br>

이로부터 다음 명제가 자연스럽게 나온다.

::: {#cor-number_of_orthogonal_vectors}
유한차원 내적벡터공간에서 직교하는 벡터의 갯수는 그 차원보다 많을 수 없다.
:::

:::{.proof}
@lem-number_of_basis 를 보라.
:::


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-norm}
#### 노름 과 거리함수

$\mathbb{F}$-벡터공간 $V$ 에서 벡터의 **노름(norm)** 은 다음을 만족하는 함수이다.

&emsp; ($1$) $\forall v\in V,\, \|v\| \ge 0$, 

&emsp; ($2$) $\|v\| = 0 \iff v=0$,  

&emsp; ($3$) $\forall c\in \mathbb{F},\, \|cv\|= |c|\|v\|$, 

&emsp; ($4$) $\forall u,\,v\in V,\, \|u+v\| \le \|u\| + \|v\|$.

노름이 부여된 벡터공간을 **노름공간(normed space)** 이라고 한다. 노름공간 $V$ 에서의 **거리함수** 혹은 **metric** $d:V \times V \to [0, \infty)$ 는

$$
d(u, v) = \|u-v\|
$$

로 정의된다. 

:::
:::

</br>

벡터공간에서의 내적과 마찬가지로 노름 역시 특정 조건을 만족하는 함수 가운데 공간에 부여되는 성질이다. 내적벡터공간은 그 자체로 거리공간인데 이것은 내적에 의해 노름과 거리함수가 자연스럽게 정의 될 수 있기 때문이다. 참고로 노름공간은 벡터공간이지만 거리공간은 벡터공간의 부분집합이 아니며 적절한 거리함수가 정의된 집합이면 거리공간이다.


::: {#exm-norm_space_1}

#### $L_p$ 노름

$V=\mathbb{R}^n$ 에 대해 $v=(v_1,\ldots,\,v_n)$ 일 때 $p\in \mathbb{Z}_+$ 에 대해 

$$
\|v\|_p = \left(\sum_{i=1}^n |v_i|^p\right)^{1/p}
$$

도 노름이다. 이것을 $L_p$ 노름이라고 한다. 유클리드 노름은 $L_2$ 노름이다.

$$
\|v\|_\infty = \max\{ |v_1|, \ldots,\,|v_n|\}
$$

역시 노름이며 $L_\infty$ 노름이라고 한다. $L_p$ 노름과 $L_\infty$ 노름이 @def-norm 의 조건을 만족한다는 것을 보이는 것은 독자에게 맡긴다. $L_p$ 노름에서 $\|u+v\|_p\le \|u\|_p+\|v\|_p$ 를 [민코프스키 부등식](https://en.wikipedia.org/wiki/Minkowski_inequality) 이라고 한다.

:::

</br>

::: {#prp-innerproduct_norm}

내적 백터공간 $V$ 의 두 벡터 $u,\,v$ 에 대해 다음이 성립한다. 

&emsp; ($1$)  $\langle u,\,v \rangle = 0 \implies \langle u + v, u+v\rangle = \langle u, u\rangle^2 + \langle v, v\rangle^2$.

&emsp; ($2$) $|\langle u,\,v \rangle | \le \sqrt{\langle u, u\rangle \langle v,v \rangle}$.

:::

::: {.proof}

뒤에 사용하겠지만 일단은 임시방편으로 $\langle v, v\rangle = \|v\|^2$ 라고 하자. @def-innerproduct 에 의해 $\|v\|\ge 0$ 이며 $\|v\|=0 \iff v=0$ 임을 알 수 있다. ($1$) 은 쉽게 보일 수 있다. ($2$) $v=0$ 일 때는 자명하다. 이제 $v\ne 0$ 일 경우만을 생각하자. $w=\|v\|^2 u - \langle u,\, v\rangle v$ 라고 하면, $\|w\|^2\ge 0$ 이므로, 

$$
\begin{aligned}
\|w\|^2 = \langle w, w\rangle &= \|v\|^4 \|u\|^2- \|v\|^2 \overline{\langle u, v\rangle}\langle u, v\rangle - \|v\|^2 \langle u, v \rangle \langle v, u \rangle + \|v\|^2 |\langle v, u\rangle |^2\\
& = \|v\|^2(\|u\|^2 \|v\|^2 -  |\langle u,v\rangle| ) \ge 0
\end{aligned}
$$

이다. 즉 $\|u\|^2\|v\|^2 \ge |\langle u, v\rangle|$ 이다. $\square$

:::

</br>

위에서는 임시변통으로 $\langle v, v\rangle = \|v\|^2$ 라고 했지만 이렇게 정의된 함수는 실제로 거리함수이다. 

</br>

::: {#prp-norm_of_innerproduct_space}

#### 내적 공간의 노름

$\mathbb{F}$-내적벡터공간에서 $\sqrt{\langle v,\, v\rangle}$ 은 거리함수이다.

:::

::: {.proof}

@def-innerproduct 에서의 ($1$), ($2$) 로부터 @def-norm 의 ($1$), ($2$) 가 성립함을 알 수 있다. @def-innerproduct 의 ($4$) 로 부터 $\|cv\|^2= |c|^2 \|v\|^2$ 라는 것을 알 수 있으며 $\|cv\|\ge 0$ 이므로 $\|cv\| = |c|\|v\|$ 이다.

이제 ($4$) 를 보이자. 

$$
(\|u\|+\|v\|)^2 - \|u+v\|^2 = 2\|u\|\|v\|- \langle u, v\rangle - \langle v, u \rangle
$$

인데 $\mathbb{R}$-내적벡터공간에서는 

$$
\langle u, v\rangle = \langle v, u\rangle \le |\langle u, v\rangle |
$$

이며 $\mathbb{C}$-벡터공간에서는 

$$
\langle u, v\rangle + \langle v, u\rangle = \text{Re}(\langle u, v\rangle) \le |\langle u, v\rangle|
$$

이므로 @prp-innerproduct_norm 의 ($2$) 를 이용하면

$$
(\|u\|+\|v\|)^2 - \|u+v\|^2 = 2\|u\|\|v\|- \langle u, v\rangle - \langle v, u \rangle \ge 2\|u\|\|v\| - |\langle u, v\rangle| \ge 0
$$

임을 알 수 있다. $\square$

:::

</br>

실제로 내적벡터공간은 거리공간이지만 내적 없이 거리함수만 정의된 공간도 있다. 여기서는 주 관심사가 내적벡터공간이기 때문에 노름 혹은 거리함수를 말할 때는 내적에 의해 정의된 $\|v\| = \sqrt{\langle v, v \rangle}$ 만을 의미한다. 

</br>

::: {#prp-norm_in_innerproduct_space}

내적 백터공간 $V$ 의 두 벡터 $u,\,v$ 에 대해 다음이 성립한다. 

&emsp; ($1$) 피타고라스 정리 : $\langle u,\,v \rangle = 0 \implies \|u + v\|^2 = \|u\|^2 + \|v\|^2$.

&emsp; ($2$) 코시-슈바르츠 부등식 :$|\langle u,\,v \rangle | \le \|u\| \|v\|$.

&emsp; ($3$) 삼각부등식 : $\|u+v\| \le \|u\|+ \|v\|$.

&emsp; ($4$) 평행사변형 공식 : $\|u+v\|^2+\|u-v\|^2 = 2\|u\|^2+2\|v\|^2$.
:::

::: {.proof}
($1$), ($2$), ($3$) 은 이미 보였다. ($4$) 는 쉽게 보일 수 있다.
$\square$
:::

</br>

## 정규직교기저

### 기저와 내적

내적벡터공간 $V$ 의 기저 $\{h_i\}$ 를 생각하자. 두 벡터 $u=\sum_i u_i h_i,\, v= \sum_j v_j h_j$ 의 내적은 다음과 같다.

$$
\begin{aligned}
\langle u,\, v\rangle &= \left\langle \sum_i u_i h_i, \sum_j v_j h_j \right\rangle \\
&= \sum_i u_i\left\langle h_i,\, \sum_j v_j h_j \right \rangle \\
&= \sum_{i, j} u_i \overline{v_j} \langle h_i,\, h_j \rangle .
\end{aligned} 
$$ {#eq-innerproduct}


즉 각각의 기저의 쌍에 대한 내적을 알면 벡터의 내적을 계산 할 수 있다. 그런데 만약 서로 다른 두 기저벡터의 내적이 $0$ 이라면, 즉 기저들이 직교한다면 $\|h_i\|^2$ 만을 생각해도 되기 때문에 계산이 쉬워질 것이다. 거기에 더하여 기저벡터의 노름이 모두 1 이라면 더욱 쉬워질 것이다. 이것을 만족하는 기저를 정규직교기저라고 한다.

</br>

### 정규직교기저

::: {.callout-note appearance="simple" icon="false"}

::: {#def-orthonormal_Basis}

#### 정규직교기저 (Orthonormal basis)

내적벡터공간의 벡터의 집합 $\{v_1,\ldots,\,v_n\}$ 의  직교하는 벡터의 집합이며 벡터의 노름이 모두 $1$ 일 때, 즉 $\langle v_i,\,v_j\rangle = \delta_{ij}$ 일 때 **정규직교벡터 (orthonormal vectors)** 라 한다. 정규직교기저벡터가 선형독립임은 @prp-orthogonal_linearity 에서 보았다. 정규직교벡터가 벡터공간의 기저일 때 이 기저를 **정규직교기저 (orthonormal basis)** 라 한다. 
:::
:::


</br>

### 정규직교기저에서의 벡터의 표현

$\{e_1,\ldots,\,e_n\}$ 이 내적벡터공간 $V$의 정규직교기저라고 하자. $v\in V$ 를 이 기저의 선형결합으로 표현하면 아래와 같다고 하자.

$$
v=\sum_i^n c_i e_i
$$

 여기서

$$
\langle v,\,e_j\rangle  = \sum_{i=1}^n c_i \langle e_i,\,e_j\rangle = c_j
$$

이므로,

$$
v =\sum_{i}^n \langle v,\,e_i \rangle e_i
$$

이다.

</br>

### 정규직교기저와 내적



$\mathcal{B}=(e_i)$ 가 내적벡터공간 $V$ 의 정규직교기저이고 두 벡터 $u,\,v$ 가 $u= \sum_i u_i e_i,\, v=\sum_j v_j e_j$ 라 하자. 이 때 두 벡터의 내적은 

$$
\langle u,\, v\rangle = \sum_i \sum_j \langle u_i e_i,\, v_j e_j \rangle = \sum_i \sum_j u_i \overline{v_j} \langle e_i,\, e_j\rangle= \sum_i u_i \overline{v_j}
$$

이다. 이것을 @eq-innerproduct 와 비교해보면 얼마나 간단해졌는지 느낄 수 있을 것이다. 정규직교기저인 $\mathcal{B}$ 에서의 행렬표현은 $\boldsymbol{u}=[u]_\mathcal{B}= \begin{bmatrix} u_1 \\ \vdots \\ u_n\end{bmatrix}$ $\boldsymbol{v} = [v]_\mathcal{B}= \begin{bmatrix} v_1 \\ \vdots \\ v_n\end{bmatrix}$ 이며 이때의 내적은 $\boldsymbol{v}^\ast \boldsymbol{u}$ 이다. $V$ 가 $\mathbb{R}$-벡터공간 일 때 내적은 $\boldsymbol{v}^T\boldsymbol{u}$ 이다.

</br>

### 정규직교기저벡터에 대한 연산자의 행렬 표현

$T\in \mathcal{L}(V)$ 라 하자. $\mathcal{B}=(e_i)$ 이 정규직교기저벡터일 때 $T$ 는

$$
T(e_j) = \sum_{k=1}^n A_{kj}e_k
$$

라 하자.

$$
\langle T(e_j),\, e_i\rangle = \sum_{k=1}^n \langle A_{kj}e_k,\, e_i\rangle = \sum_{k=1}^n A_{kj} \langle e_k,\, e_i\rangle = A_{ij}
$$

이다. 즉,

$$
A_{ij} = \langle T(e_j),\, e_i \rangle
$$

이다.

</br>


정규직교기저를 이용하면 내적이나 행렬 계산을 포함한 많은 것이 편해진다. 그렇다면 당연한 질문을 던질 수 있다. 어떤 조건에서 정규직교기저를 얻을 수 있는가? 답은 언제나이다. 내적벡터공간에서는 어떤 기저든 한 기저를 구했다면 그 기저를 바탕으로 정규직교기저를 얻을 수 있다. 한 기저에서 정규직교기저를 구하는 방법은 여러가지가 있지만 그중에서 한가지를 알아보도록 하자.


</br>

## 그람-슈미트 과정과 정규직교기저


### 벡터에 대한 정사영 (Projection)

두 벡터의 내적이 $0$ 일 때 두 벡터는 직교한다(be perpendicular)고 하며, 한 벡터가 다른 벡터의 스칼라곱일 때 두 벡터가 **평행하다(be parallel)** 고 한다. 내적벡터공간 $V$ 의 두 벡터 $u,\,v$ 가 주어졌다고 하자. 이 때 $v$ 의 $v$ 에 대한 사영연산자 $\text{Proj}_u v$ 를 아래와 같이 정의하자.

$$
\text{Proj}_{u}v = \dfrac{\langle v,\, u\rangle}{\langle u,\, u\rangle} u
$$

$\text{Proj}_u v$ 는 $u$ 에 평행하며 ($u$ 의 스칼라곱이니 당연하다), $v-\text{Proj}_u v$ 는 $v$ 에 직교한다. 즉

$$
\langle  v , \,v-\text{Proj}_{u} v \rangle  = 0
$$

이다. $v = \text{Proj}_u v + (v - \text{Proj}_u v)$ 이므로 $v$ 를 $u$ 에 대해 수직한 벡터와 평행하는 벡터의 합으로 표현 할 수 있다.

</br>

### 그람-슈미트 과정 (Gram-Schmidt Process)

그람-슈미트 과정을 통해 유한차원 내적 벡터공간에서 주어진 독립 벡터를 이용하여 같은 갯수의 정규 직교 벡터를 얻을 수 있다. $n$ 차원 내적 벡터 공간 $V$ 에서 $m$ 개의 독립벡터 $\{v_1,\ldots,v_m\}$ 이 주어졌다고 하자. (당연히 $m \le n$ 이다). 정규직교벡터의 집합 $\{e_1,\ldots,\,e_m\}$ 을 그람-슈미트 과정을 수행하여 얻을 수 있다. 그람-슈미트 과정을 귀납적으로 표현하면 다음과 같다.

::: {.callout-tip title="그람-슈미트 과정" appearance="minimal"}
$1$. 우선 $u_1 =  v_1$, $e_1 = \dfrac{u_1}{\|u_1\|}$ 라 한다.

$2$. 우리가 $u_1,\ldots,\,u_{k-1}$ 을 얻었을 때 (즉, $e_1,\ldots,e_{k-1}$ 을 얻었을 때) $u_k$ 와 $e_k$ 는 다음과 같이 얻는다.  

$$
u_k = v_{k} - \sum_{j=1}^{k-1} \text{Proj}_{e_j} v_k = v_k-\sum_{j=1}^{k-1} \left\langle v_k,\, e_j \right\rangle e_j,\qquad e_k = \dfrac{u_k}{\|u_k\|} \;.
$$

:::


</br>

이제 이렇게 해서 얻은 $\{e_1,\ldots,\,e_m\}$ 이 정규직교벡터의 집합이라는 것을 보이자.

</br>

::: {#lem-gram_schmidt}
위 과정을 통해 얻은 $\{e_1,\ldots,\,e_m\}$ 은 orthonomal 하다. 즉, $\langle e_i,\, e_j\rangle = \delta_{ij}$ 이다.
:::

::: {.proof}
$e_k = \dfrac{u_k}{\|u_k\|}$ 로 정의되었으므로 $\|e_k\|^2=1$ 이다. 따라서 $i\ne j$ 일 때 $\langle e_i,\, e_j\rangle = 0$ 임을 보이면 된다. 수학적 귀납법을 통해 보일 것이며 우선 $\langle u_2,\,u_1\rangle = 0$ 임을 보이자.

$$
\begin{aligned}
\langle u_2,\, u_1 \rangle &= \langle v_2- \langle v_2,\, e_1\rangle e_1,\, v_1 \rangle  = \langle v_2,\,v_1\rangle - \langle v_2,\,e_1 \rangle \langle e_1,\, v_1\rangle \\
&= \langle v_2,\,v_1\rangle - \dfrac{1}{\|v_1\|} \langle v_2,\,v_1\rangle \|v_1\| = 0
\end{aligned}
$$

이다. 이제 $u_{k}$ 는 $u_1,\ldots,\,u_{k-1}$ 와 모두 직교한다고 가정하자. 임의의 $j\le k$ 에 대해,

$$
\begin{aligned}
\langle u_{k+1},\, u_j\rangle  &= \left\langle v_{k+1}- \sum_{i=1}^{k} \langle v_{k+1},\, e_i\rangle e_i,\, \|u_j\|e_j \right\rangle \\
&= \|u_j\| \langle v_{k+1},\, e_j\rangle  - \|u_j\| \sum_{i=1}^k \langle v_{k+1},\, e_i \rangle \langle e_i,\, e_j\rangle \\
&= \|u_j\| \langle v_{k+1},\,e_j\rangle -\|u_j\|\sum_{i=1}^{k} \langle v_{k+1},\, e_i\rangle \delta_{ij} \\
&= \|u_j\| \langle v_{k+1},\,e_j\rangle -\|u_j\| \langle v_{k+1},\,e_j\rangle  = 0.
\end{aligned}
$$

이다. 따라서 $\{e_1,\ldots,\,e_m\}$ 은 orthonormal 하다. $\square$

:::


</br>

이제 우리는 다음의 중요한 결론을 얻는다.

::: {#thm-orthonormal_basis}
$V$ 가 유한차원 내적벡터공간이며 $\mathcal{B}_V= (v_i)$ 가 $V$ 의 기저일 때 $\mathcal{B}_V$ 로부터 정규직교기저를 얻을 수 있다.
:::


::: {.proof}
$\mathcal{B}_V$ 는 선형독립이므로 Gram-Schmidt 과정을 통해 얻은 정규직교벡터는 $V$ 의 정규직교기저이다. $\square$

:::

</br>

그람-슈미트 과정은 내적벡터공간에 기저가 주어지면 이 기저의 선형결합으로 정규직교기저를 얻을 수 있음을 보장한다. 우리는 앞서 @thm-uppertriangular_matrix_complex_field 에서 유한차원 $\mathbb{C}$-벡터공간에서의 모든 연산자는 어떤 기저에서 상삼각 행렬로 표현된다는 것을 보였다. 유한차원 $\mathbb{C}$-내적벡터공간에서는 정규직교기저에대해 상삼각 행렬로 표현되는 것을 보이자.

</br>


::: {#thm-schure}

#### 슈어 정리 (Schur's Theorem)

유한차원 $\mathbb{C}$-내적벡터공간 $V$ 에서 정의된 연산자 $T\in \mathcal{L}(V)$ 는 어떤 정규직교기저에서 상삼각행렬로 표현된다.
:::

::: {.proof}
$V$ 를 $n$ 차원 $\mathbb{C}$-내적벡터공간이라 하자. @thm-uppertriangular_matrix_complex_field 에서 $T\in \mathcal{L}(V)$ 는 어떤 기저 에서 상삼각행렬로 표현된다는 것을 보였다. 이 기저를 $\mathcal{B}_V = \{v_1,\ldots,\,v_n\}$ 이라 하고, 그람-슈미트 과정을 통해 얻은 정규직교기저를 $\{e_1,\ldots,\,e_n\}$ 이라 하자. 즉 $e_i \in \text{span}(v_1,\ldots,\,v_i)$ 이다. 그렇다면, 그람 슈미트 과정으로부터

$$
\text{span}(e_1,\ldots,\,e_j) = \text{span}(v_1,\ldots,\,v_j), \quad j=1,\ldots, n
$$

임을 안다. $T$ 가 $\mathcal{B}_V$ 에서 상삼각 행렬로 표현되므로 $T(v_i) \in \text{span}(v_1,\ldots,\,v_i)$ 이며, 따라서

$$
T(v_i) \in \text{span}(v_1,\ldots,\,v_i) = \text{span}(e_1,\ldots,\,e_i)
$$

이다. 즉 $T$ 는 정규직교기저에서 상삼각 행렬로 표현된다. $\square$
:::

</br>

::: {.callout-important}

내적벡터공간에서 항상 정규직교기저를 구할 수 있으며, 정규직교기저에서 여러 계산이 편해지기 때문에 정규직교기저를 가정하고 문제를 푸는 경우가 많다.

:::

<br>



::: {#thm-Reisz_representaion_theorem}
### Riesz 의 표현 정리 (Reisz Representation theorem)

유한차원 내적벡터공간 $V$ 에서 정의된 선형 범함수 $\varphi$ 는 어떤 벡터 $u\in V$ 에 대한 내적으로 표현 될 수 있다. 즉,

$$
\varphi (v) = \langle v,\, u\rangle
$$

이다.
:::

::: {.proof}
$\{e_1,\ldots,\,e_n\}$ 이 $V$ 의 정규직교기저라 하자. 그렇다면,

$$
\begin{aligned}
\varphi (v) &= \varphi \left(\sum_i a_i e_i\right) = \sum_i a_i \varphi(e_i) = \sum_i \langle v_i,\,e_i\rangle  \varphi(e_i) \\ 
&= \sum_i \langle v_i,\, \overline{\varphi (e_i)}e_i \rangle \\ 
&= \left\langle v_i,\, \sum_i \overline{\varphi(e_i)} \, e_i \right\rangle
\end{aligned}
$$

이므로, $u = \sum_i \overline{\varphi (e_i)}e_i$ 로 잡으면 된다. $\square$

:::

</br>

## 조르당-폰 노이만 정리 
<!-- {#sec-jordan_von_neumann_theorem} -->

우리는 앞서 @prp-norm_of_innerproduct_space 에서 내적벡터공간에는 자연스러운 거리함수가 존재한다는 것을 보였다. 즉 내적공간은 거리공간이다. 그렇다면 어떤 조건에서 거리공간은 내적공간이 될 수 있을까를 말해주는 것이 조르당-폰 노이만 정리이다. 결론적으로 말하자면 거리공간에 사다리꼴 공식이 성립한다면 내적공간이 되며 이것을 조르당-폰 노이만 정리라고 한다. 우선 실벡터 공간에 대해서 보이고 이후 복소벡터 공간에서 보이도록 하자. 다만 이것의 증명을 위해서는 연속에 대한 해석학적인 지식이 필요하다.

</br>

::: {#lem-jordan_von_neumann_1}

$\mathbb{R}$-거리 공간 $V$ 에서 함수 $\phi : V \times V \to [0, \infty)$ 를 다음과 같이 정의하자.


$$
\phi (u, v)= \dfrac{\|u+v\|^2-\|u-v\|^2}{4}. 
$$ {#eq-innerproduct_from_norm_in_R}

이 때 모든 $u,\,v\in V$ 에 대해 평행사변형 공식 $\|u+v\|^2 + \|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 를 만족한다면 $u,\,u',\,v\in V$ 에 대해 다음이 성립한다.

$$
\phi(u+u', v)= \phi(u, v) + \phi(u', v)
$$

:::

::: {.proof}


평행사변형 공식으로 부터

$$
\|u-v\|^2 = 2\|u\|^2+2\|v\|^2-\|u+v\|^2
$$ 

임을 안다. 이를 이용하면 (다음줄로의 계산에서 변경되는 부분에 밑줄을 그었다.)

$$
\begin{aligned}
\phi(u+u',v) &= \dfrac{1}{4} \left(\underline{\|u+u'+v\|^2} -\|u+u'-v\|^2\right)\\
&=  \dfrac{1}{4} \left( \underline{-\|u-u'+v\|^2}+2\|u+v\|^2+2\|u'\|^2 - \underline{\|u+u'-v\|^2}\right)\\
&=  \dfrac{1}{4} \left( -2\|u\|^2 -2\|u'-v\|^2 +2\|u+v\|^2+2\|u'\|^2 \right)\\
&= \dfrac{1}{2} \left( \|u+v\|^2 + \|u'+v\|^2-\|u\|^2-\|u'\|^2 -2\|v \|^2 \right) \\
\phi(u,v) + \phi(u', v) &=\dfrac{1}{4} \left( \|u+v\|^2-\underline{\|u-v\|^2}+\|u'+v\|^2-\underline{\|u'-v\|^2} \right) \\
&= \dfrac{1}{4} \left[2\|u+v\|^2 - 2\|u\|^2-2\|v\|^2 + 2\|u'+v\|^2 -2\|u'\|^2-2\|v\|^2\right]\\
&= \dfrac{1}{2} \left[ \|u+v\|^2 +\|u'+v\|^2 -\|u\|^2 -\|u'\|^2 - 2\|v\|^2\right] \\
\end{aligned}
$$

이므로 $\phi (u+u',v) = \phi(u,v)+\phi(u', v)$ 이다. $\square$

:::

</br>

::: {#lem-jordan_von_neumann_2}

@lem-jordan_von_neumann_1 과 같은 조건에서 $u,\,v\in V,\, c\in \mathbb{R}$ 일 때 다음이 성립한다.

$$
\phi (cu, v) =  c\phi (u, v).
$$
:::

::: {.proof}

$S= \{c\in \mathbb{R}: \phi (cu,v)=c\phi (u, v)\}$ 일 때 $S=\mathbb{R}$ 임을 보이자. 우선 $0,\, 1\in S$ 임은 자명하다. 또한

$$
0 = \phi (0, v) = \phi (u-u, v) = \phi(u, v) + \phi (-u, v)
$$

으로부터 $\phi (-u, v)=-\phi(u, v)$ 임을 안다. 즉 $-1\in S$ 이다. 

이제 $c\in S\implies c+1\in S$ 임을 보이자. @lem-jordan_von_neumann_1 의 결과를 이용해 다음과 같이 보일 수 있다.

$$
\begin{aligned}
\phi((c+1)u, v) &= \phi (cu+u, v)+ \phi (u, v)  \\
&= \phi (cu, v)+ \phi(u, v) \\ 
&=c\phi (u, v)+ \phi (u, v)= (c+1)\phi(u, v).
\end{aligned}
$$



이제 $c\in S \implies c-1\in S$ 임을 다음과 같이 보일 수 있다.

$$
\phi ((c-1)u, v)= \phi (cu-u, v)= \phi (cu, v) + \phi (-u, v)= (c-1)\phi (u, v)
$$

이로부터 $\mathbb{Z}\subset C$ 임을 안다. $\mathbb{Q}\in S$ 임을 보이자. $m, n\in \mathbb{Z},\, n\ne 0$ 에 대해 $c=m/n$ 이라 하자. 

$$
n\phi (cu, v) = \phi (ncu, v)= \phi (mu, v)= m \phi (u, v)= cn \phi(u, v)
$$

이므로 $\phi (cu, v) = c\phi (u, v)$ 이다. 즉 $\mathbb{Q} \subset S$ 이다.

이제 임의의 정해진 $u,\,v\in V$ 에 대해 $\mathbb{R}\mapsto \mathbb{R}$ 함수 $f,\,g$ 를 $f(x) = x\phi (u, v)$, $g(x) = \phi(xu, v)$ 로 정의하자. 앞서의 결과로부터 $x\in \mathbb{Q}$ 일 때 $f(x)=g(x)$ 임을 안다. $f(x)$ 는 연속함수이다. 

$$
g(x)-g(x_0) = \phi(xu, v) - \phi (x_0u, v) = \phi((x-x_0)u, v)
$$

이므로 $\displaystyle \lim_{x \to x_0} g(x) = g(x_0)$ 이다. 즉 $g$ 도 연속함수이다. $\mathbb{Q}$ 는 $\mathbb{R}$ 에 대해 조밀한 부분집합이며 모든 $x\in \mathbb{Q}$ 에 대해 $f(x)=g(x)$ 이므로 모든 $x\in \mathbb{R}$ 에 대해 $f(x) = g(x)$ 이다. (@Rudin1976, Chapter 4, Exercises 4) $\square$

:::

</br>

::: {#thm-jordan_von_neumann_theorem}

#### 실벡터공간에서의 조르당-폰 노이만 정리

$\mathbb{R}$-거리벡터공간 $V$ 에 대해 다음은 동치이다.

&emsp; ($1$) $V$ 는 $\mathbb{R}$-내적벡터공간이다.

&emsp; ($2$) 모든 $u,\,v\in V$ 에 대해 평행사변형 공식이 성립한다.

:::

::: {.proof}

($1 \implies 2$) 는 @prp-norm_in_innerproduct_space 에서 보였다.

($2 \implies 1$) @eq-innerproduct_from_norm_in_R 가 @def-innerproduct 를 만족한다는 것은 @lem-jordan_von_neumann_1 과 @lem-jordan_von_neumann_2 를 이용하여 보일 수 있다. $\square$

:::


</br>

이제 복소벡터공간에서 증명하자. 


::: {#lem-jordan_von_neumann_3}

$\mathbb{C}$-거리공간 $V$ 에서 함수 $\psi : V \times V \to \mathbb{C}$ 를 다음과 같이 정의한다.

$$
\psi (u, v) = \dfrac{\|u+v\| - \|u-v\| + i\|u+iv\| -i \|u-iv\|}{4}
$$ {#eq-innerproduct_from_norm_in_C}

이 때 모든 $u,\,v\in V$ 에 대해 평행사변형 공식 $\|u+v\|^2 + \|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 를 만족한다면 $u,\,u',\,v\in V$ 에 대해 다음이 성립한다.

$$
\psi(u+u', v)= \psi(u, v) + \psi(u', v)
$$
:::

::: {.proof}

$\psi$ 를 실수부 $\psi_R$ 과 허수부 $\psi_I$ 로 분리하자. 즉

$$
\psi_R (u, v) = \dfrac{\|u+v\| - \|u-v\|}{r},\qquad \psi_I(u, v) = \dfrac{\|u+iv\| -\|u-iv\|}{4}
$$

로 놓으면 $\psi(u, v) = \psi_R(u, v)+ i\psi_I (u, v)$ 이다. $\psi_R(u+u',v)= \psi_R(u,v) + \psi_R(u',v)$ 인것은 @lem-jordan_von_neumann_1 에서 보였다. $\psi_I(u, v) = \psi_R(u, iv)$ 이므로 $\psi_I(u+u',v)= \psi_I(u,v) + \psi_I(u',v)$ 이다. $\square$

:::

</br>

::: {#lem-jordan_von_neumann_4}

$\mathbb{C}$-거리공간 $V$ 에서 @lem-jordan_von_neumann_3 에서 정의된 함수 $\psi$ (@eq-innerproduct_from_norm_in_C) 는 $c \in \mathbb{F}$ 에 대해 다음을 만족한다.

$$
\psi (cu, v) = c\psi(u, v). 
$$

:::

::: {.proof}
@lem-jordan_von_neumann_3 의 증명과 같이 $\psi_R$ 과 $\psi_I$ 를 정의하자. $\psi_R(cu, v) = c\psi_R (u, v)$ 는 실벡터 거리공간에서의 경우와 마찬가지이다. $\psi_I (u, v) = \psi _I (u, iv)$ 이므로 $\psi_I (cu, v) = c\psi_I (u, v)$ 이다. 따라서 $\psi (cu, v) =  c\psi (u, v)$ 이다. $\square$


:::

</br>

이제 우리는 다음과 같은 결론을 내릴 수 있다.


::: {#thm-jordan_von_neumann_theorem2}

#### 복소벡터공간에서의 조르당-폰 노이만 정리

$\mathbb{C}$-거리벡터공간 $V$ 에 대해 다음은 동치이다.

&emsp; ($1$) $V$ 는 $\mathbb{C}$-내적벡터공간이다.

&emsp; ($2$) 모든 $u,\,v\in V$ 에 대해 평행사변형 공식이 성립한다.

:::


</br>

이제 우리는 $\mathbb{F}$-벡터공간에서 내적과 노름의 관계에 대해 알게 되었다. 즉 내적벡터공간은 노름공간이며, 노름공간에서 정의된 거리함수가 평행사변형 공식을 만족하면 내적을 정의 할 수 있다. $\mathbb{F}^n$ 에 대해서는 다음을 보자.


::: {#exm-L1_not_innerproduct_space}

@exm-norm_space_1 에서 정의된 $L_p$ 노름은 $p\ne 2$ 일 경우를 제외하면 내적을 정의 할 수 없다. $V=\mathbb{C}^n$  에 대해 $u=(1, 0, \ldots, 0)$, $v=(0, 1, 0, \ldots,\,0)$ 이라고 하자.

$$
\begin{aligned}
{\| u+v \|_p}^2 + {\| u-v \|_p}^2 &= 2^{1+2/p} , \\
2({\| u \|_p}^2 + {\| v \|_p}^2) &= 4
\end{aligned}
$$

이므로 조르당-폰 노이만 정리를 만족하기 위해서는 $p=2$ 이어야 한다.


:::

</br>

## 직교 여공간 (Orthogonal complement) 과 Orthogonal projection

::: {.callout-note appearance="simple" icon="false"}
::: {#def-orthogonal_complement}

#### 직교 여공간

벡터공간 $V$ 의 부분집합 $U$ 에 대해 $U$ 전체 원소에 대해 수직인 벡터의 집합은 벡터공간을 이루며 이를 $U$ 에 대한 **직교 여공간 (orthogonal complement)** 이라 하고 $U^\perp$ 라 쓴다. 즉,

$$
U^\perp = \{ v\in V : \langle v,\, u\rangle = 0 \text{ for every }u\in U\}
$$

이다.
:::
:::

</br>

다음은 쉽게 보일 수 있다.

::: {#prp-orthogonal_complement_is_a_vector_space}
$V$ 의 부분집합 $U$ 에 대해 $U^\perp$ 는 $V$ 의 부분벡터공간이다.
:::

</br>

직교 여공간의 중요한 성질은 다음과 같다.

::: {#prp-properties_of_orthogonal_complement}
직교 여공간에 대해서는 다음이 성립한다.

&emsp; ($1$) $\{0_V\}^\perp = V$,

&emsp; ($2$) $V^\perp = \{0_V\}$,

&emsp; ($3$) $U \cap U^\perp  \subset \{0\}$,

&emsp; ($4$) $U\subset W \implies W^\perp \subset U^\perp$,

&emsp; ($5$) $(U^\perp)^\perp = \langle U \rangle$.
:::

::: {.proof}
($4$) 에 대해서만 증명한다 $v\in W^\perp$ 이면 $v$ 가 모든 $W$ 의 집합에 대해 수직하므로 $U\subset W$ 인 모든 $u\in U$ 에 대해서도 수직하다. 따라서 $v \in U^\perp$ 이다. 즉 $W^\perp \subset U^\perp$ 이다. $\square$
:::

</br>

@sec-generated_subspace 에서 다뤘던 생성된 부분공간 $\langle U \rangle$ 를 생각하자. 우리는 다음을 보일 수 있다.

::: {#prp-generated_subspace_and_orthogonal_compliment}

유한차원 벡터공간 $V$ 의 부분집합 $U$ 에 의해 생성된 부분공간 $\langle U \rangle$ 에 대해 다음이 성립한다.

&emsp; ($1$) $\langle U \rangle \cap U^\perp = \{0_V\}$, 

&emsp; ($2$) $V = \langle U \rangle \oplus U^\perp$,

&emsp; ($3$) $\dim (V) = \dim (\langle U \rangle) + \dim (U^\perp)$

:::


::: {.proof}
$\langle U\rangle$ 의 정규직교기저를 찾아 $\{e_1,\ldots,\,e_n\}$ 이라 하고 이 기저를 확장하여 나머지 정규직교기저를 $\{f_1,\ldots,\, f_m\}$ 이라 하자. $\{f_1,\ldots,\,f_m\}$ 의 선형결합은 $U$ 와 직교하므로 $U^\perp$ 에 포함된다. $U^\perp$ 의 어떤 벡터가 $\{e_i\}$ 기저 성분을 포함한다면 $U$ 와 직교할수 없다. 따라서 $U^{\perp} = \text{span} (f_1,\ldots,f_m)$ 이다. 이를 이용하면 세가지를 모두 보일 수 있다. $\square$
:::

</br>

### Orthogonal projection


::: {.callout-note appearance="simple" icon="false"}
::: {#def-projection_operator}

#### Projection

연산자 $P\in \mathcal{L}(V)$ 가 $P^2=P$ 일 때 $P$ 를 **projection** 이라 한다.

:::
:::

예를 들어 $T\in \mathcal{L}(\mathbb{R}^2)$ 이 $T(x,\,y) = (x, 0)$ 으로 정의되었다고 하자. $T$ 는 선형사상이며 $T^2(x,\,y)= (x,\,0) = T(x,\,y)$ 이므로 $T$ 는 projection 이다. 이처럼 projectiion 은 우리가 기하학적으로 생각하는 그 projection 을 추상화 한 것이다.

</br>

::: {#prp-uniqueness_of_orthogonal_decomposition}

유한차원 벡터공간 $V$ 가 부분공간 $U$ 에 대해 $V=U \oplus U^\perp$ 이다. 이 때 $v\in V$ 는 어떤 $u\in U$ 와 $w\in U^\perp$ 에 대해 $v = u+w$ 로 나타낼 수 있으며, 이를 만족하는 $u,\,w$ 는 유일하다.

:::

::: {.proof}
@prp-generated_subspace_and_orthogonal_compliment 의 증명에서 보인 대로 $U$ 의 정규직교기저 $\{e_1,\ldots,\,e_n\}$ 과 $U^\perp$ 의 정규직교 기저 $\{f_1,\ldots,\,f_m\}$ 에 대해 $u = \sum_i a_i e_i + \sum_j b_j f_j$ 를 만족하는 $a_i,\, b_j$ 가 존재한다. $u= \sum_i a_i e_i$ 이며 $w=\sum_j b_j f_j$ 이다. 이 때 $u,\,w$ 가 유일하게 정해진다는 것은 자명하다. $\square$

:::

</br>

@prp-uniqueness_of_orthogonal_decomposition 에서 보인 것처럼 $v\in V$ 가 $u+w$ 라면 $P_U(v)=u$ 인 함수를 생각 할 수 있다. 이 $P_U$ 는 잘 정의되는 함수이며 선형연산자이다.

::: {#exr-orthogonal_projection_linear_operator}
위에서 정의된 함수 $P_U : V \to V$ 가 선형연산자임을 보이고, projection 임을 보여라. 그리고 $\text{im}(P_U)= U$ 임을 보여라.
::: 

::: {.proof}
$v_1,\,v_2\in V$ 에 대해 $v_1 = u_1+w_1,\, v_2=u_2+w_2$, $u_1,\, u_2\in U$, $w_1,\,w_2 \in U^\perp$ 라 하자. 

$$
P_U(v_1+\lambda v_2) = u_1+ \lambda u_2 = P_U (v_1)+ \lambda P_U (v_2)
$$

이므로 선형연산자이다. 또한

$$
P_U^2 (v_1) = P_U(u_1)= u_1 = P_U (v_1)
$$

이므로 $P$ 는 projection 이다.

$P_U$ 의 정의에 의해 $\text{im}(P_U) \subset U$ 이다. 임의의 $u\in U \le V$ 에 대해 $P_U (u)=u$ 이므로 $U \subset \text{im}(P_U)$ 이다. 따라서 $\text{im}(P_U) = U$ 이다. $\square$ 

:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-orthogonal_projection}
#### Orthogonal projection

@prp-uniqueness_of_orthogonal_decomposition 에서 정의된 $P_U$ 를 $V$ 에 대한 $U$ 로의 **orthogonal projection** 이라 한다.

:::
:::

</br>

::: {#prp-properties_of_orghogonal_projection}
$U$ 가 $V$ 의 유한차원 부분벡터공간 일 때 다음이 성립한다. 증명은 쉬우므로 생략한다.

&emsp; ($1$) $u \in U \implies P_U (u) = u$.

&emsp; ($2$) $w \in U^\perp \implies P_U(w) = 0$.

&emsp; ($3$) $\ker (P_U) = U^\perp, \,\text{im}(P_U) = U$.

&emsp; ($4$) $v-P_U (v) \in U^\perp$.

&emsp; ($5$) $P_U^2 = P_U$.

&emsp; ($6$) $\|P_U (v) \| \le \|v\|$.
:::

</br>

### 부분공간까지의 거리

$U$ 가 $V$ 의 부분공간일 때 $v\in V$ 로부터 $U$ 까지의 거리 $\|v-U\|$ 는

$$
\|v-U\| = \min \{\|v-u\|,\, u\in U\} 
$$

로 정의된다.

</br>

::: {#prp-distance_to_subspace}
$V$ 가 유한차원 내적벡터공간이고 $v\in V$, 이며 $U$ 가 $V$ 의 부분공간일 때, $v$ 에서 $U$ 까지의 거리는 $v$ 에서 $P_U (v)$ 까지의 거리와 같다. 즉, 

$$
\|v-U\| = \|v-P_U(v)\|
$$

이다.
:::

::: {.proof}

임의의 $u\in U$ 에 대해 $\|v-P_U (v)\| \le \|v-u\|$ 임을 보이면 된다. $\|P_Uv - u\| \ge 0$ 이므로,

$$
\begin{aligned}
\|v-P_U (v) \|  &\le \|v-P_U (v) \| +\|P_U(v) - u\| \qquad & &; \|P_U(v) - u\| \ge 0\\
&\le\|v-u\| & &; \text{Triangle inequality}
\end{aligned}
$$

이다. $\square$
:::

</br>

## 연습문제

::: {#exr-axler_6_A_5}
#### Axler 6.A.5

$T\in \mathcal{L}(V)$ 이며 모든 $v\in V$ 에 대해 $\|T(v)\|\le \|v\|$ 이다. 이 때 $T-\sqrt{2}I$ 는 가역임을 보여라.

:::

::: {.solution}

$(T-\sqrt{2}I)(v)=0_V$ 라 하자. $v\ne 0_V$ 이면 $\|\sqrt{2}I(v)\|=\sqrt{2}\|v\| > \|v\| \ge \|T(v)\|$ 이므로 성립하지 않는다. $\ker (T-\sqrt{2}I)=\{0_V\}$ 이므로 가역이다.
::: 

</br>

::: {#exr-axler_6_A_6}
#### Axler 6.A.6

$u,\,v\in V$ 일 때 $\langle u,\,v\rangle=0$ 일 필요충분조건은 모든 $a\in \mathbb{F}$ 에 대해 $\|u\| \le\|u+av\|$ 임을 보여라.

:::

::: {.solution}
$\langle u,\,v\rangle =0$ 이면 $\|u+av\|^2-\|u\|^2 = |a|^2\|v\|^2 \ge 0$ 이다.  따라서 $\|u+av\| \ge \|u\|$ 이다.

모든 $a\in \mathbb{F}$ 에 대해 $\|u\|\le \|u+av\|$ 라고 하자.

$$
\|u+av\|^2-\|u\|^2 = a\langle v,\,u\rangle + \overline{a}\langle u,\,v\rangle + |a|^2 \|v\|^2 \ge 0
$$

이어야 한다. $u,\,v$ 에 대해 $a=t\|v\|\langle u,\,v\rangle$ 이라 놓을 수 있다. 이 때 $t\in \mathbb{R}$ 이라 하자.

$$
0\le \|u+av\|^2-\|u\|^2 = (2t\|v\| - t^2\|v\|^2) |\langle u,v\rangle |^2
$$

이어야 하는데 $t > \|v\|$ 이면 위배된다. 따라서 $\langle u,\,v\rangle = 0$ 이어야 한다. 

:::

</br>

::: {#exr-axler_6_A_9}

#### Axler 6.A.9

$u,\,v\in V$ 이고 $\|u\|\le 1$ 이며 $\|v\|\le 1$ 이면 다음이 성립함을 보여라.

$$
\sqrt{1-\|u\|^2}\sqrt{1-\|v\|^2} \le 1-|\langle u,\,v\rangle |.
$$

:::

::: {.solution}

우선 $\|u\|^2+\|v\|^2 \ge 2\|u\|\|v\|$ 임을 안다. 또한 $\|u\|\|v\| \ge |\langle u,\,v\rangle|$ 임을 안다.

$$
\begin{aligned}
(1-\|u\|)^2 (1-\|v\|^2) &= 1-\|u\|^2-\|v\|^2 + \|u\|^2\|v\|^2  \\
&\le 1-2\|u\|\|v\| + \|u\|^2\|v\|^2 \\
&= (1-\|u\|\|v\|)^2 \le (1-|\langle u,\,v\rangle |)^2.
\end{aligned}
$$

:::


</br>

::: {#exr-axler_6_A_11}

#### Axler 6.A.11

양수 $a,\,b,\,c,\,d$ 에 대해 다음이 성립함을 보여라.

$$
16 \le (a+b+c+d) \left( \dfrac{1}{a}+\dfrac{1}{b}+\dfrac{1}{c}+\dfrac{1}{d} \right)
$$

:::

::: {.solution}

$x,\,y\in \mathbb{R}^4$ 이며 $x=(\sqrt{a},\,\sqrt{b},\,\sqrt{c},\,\sqrt{d})$, $y=(1/\sqrt{a},\,1/\sqrt{b},\,1/\sqrt{c}\,1/\sqrt{d})$ 라 하면, $|\langle x,\,y\rangle|^2 \le \|a\|^2\|b\|^2$ 이므로, 

$$
4^2=16 \le  (a+b+c+d) \left( \dfrac{1}{a}+\dfrac{1}{b}+\dfrac{1}{c}+\dfrac{1}{d} \right).
$$

:::

</br>

::: {#exr-axler_6_A_18}

#### Axler 6.A.18

$p>0$ 라고 하자. $\mathbb{R}^2$ 에서 노름이 $\|(x,\,y)\| = (x^p+y^p)^{1/p}$ 가 되도록 하는 노름은 $p=2$ 일 때만 존재함을 보여라.

:::

::: {.solution}

$u=(1, 0), v=(0, 1)$ 이라 하자. $\|u+v\|^2+\|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 이므로, $2 + (1+(-1)^p)^{2/p}= 4$ 이어야 한다. 즉 $1+(-1)^p = 2^{2/p}$ 이어야 하며, 이를 만족하는 $p$ 는 $2$ 뿐이다.

:::

</br>

::: {#exr-axler_6_A_22}
$a_1,\ldots,\,a_n\in\mathbb{R}$ 에 대해 다음이 성립함을 보이시오.

$$
\left(\dfrac{\sum_{i=1}^n a_n}{n}\right)^2 \le \dfrac{\sum_{i=1}^n a_n^2}{n}
$$

:::

::: {.solution}

$u,\,v\in \mathbb{R}^n$ 을 $u=(a_1,\ldots,\,a_n)$, $v=(1,\ldots,\,1)$ 이라 하자. $\langle u,\,v\rangle = \sum a_n$, $\|u\|\|v\| = \sqrt{n}\left(\sum a_n^2\right)$ 이며 코시-슈바르츠 부등식에 따라 $|\langle u, v \rangle | \le \|u\|$ 이므로, 

$$
\left(\dfrac{\sum_{i=1}^n a_n}{n}\right)^2  = \dfrac{1}{n^2}|\langle u, v\rangle|^2 \le \dfrac{1}{n^2} (\|u\|\|v\|)^2=\dfrac{\sum a_n^2}{n}
$$

이다. 
:::

</br>

::: {#exr-axler_6_A_27}

#### Alxer 6.A.27, 28
벡터공간 $V$ 의 부분집합 $C$ 가 $u,\,v\in C \implies \frac{1}{2}(u+v)\in C$ 를 만족한다고 하자. 이 때 임의의 $w\in V$ 에 대해 $\|w-v\|$ 를 최소로 하는 $u\in C$ 가 많아야 하나만 존재한다는 것을 보여라. 이것을 보이기 위해 우선 $u,\,v,\,w\in V$ 에 대해

$$
\left\|w-\frac{1}{2}(u+v)\right\|^2 = \dfrac{\left(\|w-u\|^2 + \|w-v\|^2\right)}{2} - \dfrac{\|u-v\|^2}{4}
$$

임을 보이고 필요하다면 이것을 이용하시오.

:::

::: {.solution} 

평행사변형 공식 $\|u+v\|^2 +\|u-v\|^2 = 2\|u\|^2+2\|v\|^2$ 를 이용한다.

$$
\begin{aligned}
\left\|w-\frac{1}{2}(u+v)\right\|^2 &= \left\|\dfrac{1}{2}(w-u) + \dfrac{1}{2}(w-v)\right\|^2 \\
&= 2 \left\|\dfrac{1}{2} (w-u) \right\|^2 + 2\left\|  \dfrac{1}{2}(w-v)\right\|^2 - \left\|\dfrac{1}{2}(u-v)\right\|^2 \\
&= \dfrac{\|w-u\|^2 +\|w-v\|^2}{2} - \dfrac{1}{4} \|u-v\|^2.
\end{aligned}
$$

이므로 $u,\,v\in C$ 일 때

$$
\left\|w-\frac{1}{2}(u+v)\right\|^2  \le \dfrac{\|w-u\|^2 +\|w-v\|^2}{2}
$$

이며 등호는 $u=v$ 일 때만 성립한다는 것을 알 수 있다. $v_1,\,v_2$ 가 $\|w-v\|$ 를 최소화 하는 두 벡터이고 $u\ne v$ 라면 위 식에 위배된다. 따라서 $u=v$ 이어야 한다. 즉 $\|w-v\|$ 를 최소화 하는 $C$ 의 벡터는 많아야 하나만 존재 할 수 있다.

:::
</br>
