---
title: "특이값 분해"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

## Positive definite, Positive semidefinite 행렬과 제곱근 행렬

::: {.callout-note appearance="simple" icon="false"}
::: {#def-pisitive_definite_matrix}

#### Positive Definite 행렬 와 제곱근 행렬

에르미트 행렬 $\boldsymbol{A}$ 이 임의의 벡터 $\boldsymbol{v}$ 에 대해,$\langle \boldsymbol{Av},\, \boldsymbol{v} \rangle > 0$ 일 때 $\boldsymbol{A}$ 를 **positive definite** 라 하고 $\langle \boldsymbol{Av},\, \boldsymbol{v} \rangle \ge 0$ 일 때 $\boldsymbol{A}$ 를 **positive semidefinite** 라 한다. $\boldsymbol{A}$ 가 positive 이거나 positive semidefinite 일 때  $\boldsymbol{A}=\boldsymbol{R}^2$ 인 행렬 $\boldsymbol{R}$ 이 존재하면 $\boldsymbol{R}$ 을 $\boldsymbol{A}$ 의 **제곱근 행렬**이고 하고 $\sqrt{\boldsymbol{A}}$ 라고 쓴다. 행렬 $\boldsymbol{A}$ 의 제곱근 행렬이 존재 할 때 $\boldsymbol{A}$ 가 제곱근 행렬을 가진다라고 한다.

:::
:::

</br>


### Positive definite 행렬의 성질

::: {#prp-properties_of_posivive_definite_matrix}

$\boldsymbol{A} \in \mathcal{M}_{n \times n}(\mathbb{C})$ 에 대해 다음은 동치이다.

&emsp; ($1$) $\boldsymbol{A}$ 는 positive semidefinite 이다.

&emsp; ($2$) $\boldsymbol{A}$ 는 에르미트행렬이며 모든 고유값은 non-negative 하다

&emsp; ($3$) $\boldsymbol{A}$ 의 positive semidifinite 제곱근 행렬이 존재한다.

&emsp; ($4$) $\boldsymbol{A}$ 의 에르미트 제곱근 행렬이 존재한다.

&emsp; ($5$) $\boldsymbol{A} = \boldsymbol{R}^\ast \boldsymbol{R}$ 인 행렬 $\boldsymbol{R}$ 이 존재한다.

::: 

::: {.proof}
($1 \implies 2$) $\boldsymbol{A}$ 가 positive definite 이므로 정의에 의해 에르미트 행렬이다. $\lambda$ 가 $\boldsymbol{A}$ 의 고유값이고 $\boldsymbol{v}$ 가 $\lambda$ 에 대한 고유벡터 일 때, $0 \le \langle \boldsymbol{Av},\, \boldsymbol{v}\rangle = \lambda \|\boldsymbol{v}\|^2$ 이므로 $\lambda \ge 0$ 이다.

($2 \implies 3$) 스펙트럼 정리에 의해 $\boldsymbol{P}^\ast\boldsymbol{AP}$ 를 대각행렬 $\boldsymbol{D}$ 로 하는 유니타리 행렬 $\boldsymbol{P}$ 가 존재한다. $\boldsymbol{A}$ 의 고유값 $\lambda_1,\ldots,\,\lambda_n$ 에 대해 $D_{ij} = \lambda_{i}\delta_{ij}$ 일 때, 대각행렬 $\boldsymbol{T}$ 를 $T_{ij}= \sqrt{\lambda_{i}}\delta_{ij}$ 라 하자.  $\boldsymbol{R} = \boldsymbol{P}^\ast\boldsymbol{TP}$ 라 하면 $\boldsymbol{R}^2 = \boldsymbol{A}$ 이다.

($3 \implies 4$) 위에서 정의한 $\boldsymbol{R}$ 은 $\boldsymbol{R}^\ast = \boldsymbol{P}^\ast \boldsymbol{AU} = \boldsymbol{R}$ 이므로 에르미트 행렬이다.

($4 \implies 5$) 앞서 정의한 $\boldsymbol{R}$ 이다.

($5 \implies 6$) $\boldsymbol{A}=\boldsymbol{R}^\ast \boldsymbol{R}$ 이면 $\boldsymbol{A}^\ast = (\boldsymbol{R}^\ast\boldsymbol{R})^\ast = \boldsymbol{R}^\ast \boldsymbol{R}=\boldsymbol{A}$ 이므로 $\boldsymbol{A}$ 는 에르미트 행렬이다. 또한 임의의 $\boldsymbol{v}\in \mathcal{M}_{n }(\mathbb{C})$ 에 대해 $\langle \boldsymbol{v},\, \boldsymbol{A}\boldsymbol{v}\rangle = \langle \boldsymbol{R}^\ast \boldsymbol{R}\boldsymbol{v},\, \boldsymbol{v} \rangle = \|\boldsymbol{Rv}\|^2\ge 0$ 이므로 $\boldsymbol{A}$ 는 positive definite 이다. $\square$

:::


</br>


::: {#prp-uniqueness_of_squareroot_matrix}

Positive semidefinite 행렬 $\boldsymbol{A}$ 의 positive semidefinte 한 제곱근 행렬은 유일하다.

:::

:::{.proof}
우리는 앞서 positive semidifinite 행렬 $\boldsymbol{A}$ 에 대한 positive semidifinite 한 제곱근 행렬이 존재함을 보였다. 여기서는 이것이 유일함을 보인다. 행렬 $\boldsymbol{A}$ 에 대한 positive semidifinite 한 제곱근 행렬을 $\boldsymbol{R}$ 이라 하자. 스펙트럼 정리에 의해 $\boldsymbol{R}$ 에 대한 고유값 $\eta_1,\ldots,\,\eta_n$ 과 그에 대한 정규 고유 벡터 $\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_n$ 이 존재한다. 이 때 $\eta_i \ge 0$ 이다. 임의의 벡터 $\boldsymbol{v} = \sum_i a_i \boldsymbol{u}_i$ 에 대해,

$$
\begin{aligned}
\boldsymbol{R}\boldsymbol{v} &= \sum_i a_i \eta _i \boldsymbol{u}_i \\
\boldsymbol{R}^2\boldsymbol{v}&= \sum_i a_i \eta_i^2 \boldsymbol{u}_i
\end{aligned}
$$

이다. $\boldsymbol{R}^2 = \boldsymbol{A}$ 이므로, $\boldsymbol{v}$ 가 고유값 $\lambda$ 를 갖는 $\boldsymbol{A}$ 의 고유벡터라면

$$
\boldsymbol{A}\boldsymbol{v} = \sum_i a_i \lambda \boldsymbol{u}_i
$$

이며, 따라서 $i=1,\ldots,\,n$ 에 대해 $\eta_i = \sqrt{\lambda}$ 이어야 한다. 즉 $\boldsymbol{A}$ 의 고유벡터는 $\boldsymbol{R}$ 의 고유벡터이어야 하며, 따라서 유일하다. $\square$

:::

</br>

::: {#prp-squareroot_matrix}

임의의 $\boldsymbol{B}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 $\boldsymbol{B}^\ast \boldsymbol{B}$ 를 생각 할 수 있다. 이 때 $\boldsymbol{B}^\ast \in \mathcal{M}_{n \times m}(\mathbb{F})$ 이다. $\boldsymbol{B}^\ast \boldsymbol{B}$ 는

&emsp; ($1$) 에르미트이다.

&emsp; ($2$) positive semidefinite 이다.

&emsp; ($3$) $\sqrt{\boldsymbol{B}^\ast \boldsymbol{B}}$ 를 생각 할 수 있다.

:::

::: {.proof}

($1$) $(\boldsymbol{B}^\ast\boldsymbol{B})^\ast = \boldsymbol{B}^\ast\boldsymbol{B}$ 이다.

($2$) $\langle \boldsymbol{B}^\ast\boldsymbol{Bv},\,\boldsymbol{v}\rangle = \|\boldsymbol{Bv}\|^2 \ge 0$.

($3$) @prp-properties_of_posivive_definite_matrix $\square$
:::

</br>

### 극분해

::: {#prp-polar_decomposition}

$\mathcal{M}_{n \times 1}(\mathbb{F})$ 에서의 두 정규직교기저벡터 $\mathcal{B}_1=\{\boldsymbol{u}_1,\ldots,\,\boldsymbol{u}_n\}$ 과 $\mathcal{B}_2=\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_n\}$ 을 생각하자. 그리고 $\mathcal{B}_1$ 과 $\mathcal{B}_2$ 의 벡터를 열벡터로 갖는 행렬 $\boldsymbol{U},\,\boldsymbol{V}$ 를 생각하자. 이 때,
$$
\boldsymbol{VU}^\ast \boldsymbol{u}_i = \boldsymbol{v}_i
$$

이며 $\boldsymbol{VU}^\ast$ 는 유니타리이다.
:::


::: {.proof}

표준정규기저벡터 $\boldsymbol{e}_i$ 를 생각하자.

$$
\boldsymbol{VU}^\ast \boldsymbol{u}_i = \begin{bmatrix} |& &|\\ \boldsymbol{v}_1 & \cdots & \boldsymbol{v}_n \\ |& &| \end{bmatrix} \begin{bmatrix} -&  \boldsymbol{u}^\ast_1 & -\\ & \vdots &  \\  - &  \boldsymbol{u}^\ast_n & - \end{bmatrix} \boldsymbol{u}_i = \begin{bmatrix} | & & | \\ \boldsymbol{v}_1 & \cdots & \boldsymbol{v}_n \\ | & & | \end{bmatrix} \boldsymbol{e}_i  = \boldsymbol{v}_i
$$

이다. 또한 $\boldsymbol{U},\,\boldsymbol{V}$ 가 유니타리 이므로,

$$
(\boldsymbol{VU}^\ast)^\ast (\boldsymbol{VU}^\ast ) = \boldsymbol{UV}^\ast \boldsymbol{VU}^\ast = \boldsymbol{I}
$$

이므로 $\boldsymbol{VU}^\ast$ 는 유니타리 이다. $\square$

:::

</br>


::: {#prp-polar_decomposition2}

행렬 $\boldsymbol{A}$ 에 대해 어떤 linear isometry $\boldsymbol{S}$ 가 존재하여 $\boldsymbol{A} =\boldsymbol{S}\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 가 된다.

:::

::: {.proof}
우선 $\boldsymbol{A}\in \mathbb{F}^{n \times n}$ 일 때, 임의의 $\boldsymbol{v}\in\mathbb{F}^n$ 에 대해,

$$
\begin{aligned}
\|\boldsymbol{Av}\|^2 &= \langle \boldsymbol{Av},\, \boldsymbol{Av}\rangle = \langle \boldsymbol{A}^\ast \boldsymbol{A}\boldsymbol{v},\, \boldsymbol{v} \rangle = \langle \sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\boldsymbol{v},\,\boldsymbol{v}\rangle \\
&= \langle \sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\boldsymbol{v},\,\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\boldsymbol{v} \rangle = \|\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\boldsymbol{v}\|^2
\end{aligned}
$$

이다. 여기서 $\boldsymbol{Av}=0 \iff \sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\boldsymbol{v}=0$ 이므로, $\ker \boldsymbol{A} = \ker \sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 이며, 따라서

$$
\text{rank} (\boldsymbol{A}) =  \text{rank}\, \left(\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\right)
$$

이다. $V= \text{im} \left(\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\right)$ 라 하면 $\sqrt{\boldsymbol{A}^\ast\boldsymbol{A}}$ 는 에르미트 행렬이므로 $\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 의 고유벡터로 정규직교기저를 찾을 수 있고 이 가운데 $0$ 이 아닌 양수를 고유값으로 갖는 기저벡터만을 찾아 $\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_m\}$ 이라 하고 그 고유값을 각각 $\lambda_1,\ldots,\lambda_m$ 이라 하자. 그렇다면 $\{\boldsymbol{v}_1,\ldots,\,\boldsymbol{v}_m\}$ 은 $\text{im} \left(\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\right)$ 의 정규기저벡터이다.

나머지를 $\{\boldsymbol{v}_{m+1},\ldots,\boldsymbol{v}_n\}$ 이라 하자. 그리고 다음의 벡터의 집합 $B$ 를 만들자.

$$
B=\left\{\dfrac{1}{\lambda_i}\boldsymbol{Av}_i : i=1,\ldots,\,m\right\}
$$

이 때,

$$
\left\langle \dfrac{1}{\lambda_i}\boldsymbol{Av}_i,\, \dfrac{1}{\lambda_j}\boldsymbol{Av}_j\right\rangle = \dfrac{1}{\lambda_i \lambda_j} \langle\boldsymbol{Av}_i,\,\boldsymbol{Av}_j \rangle = \dfrac{1}{\lambda_i \lambda_j} \langle \boldsymbol{A}^\ast \boldsymbol{A}\boldsymbol{v}_i,\,\boldsymbol{v}_j\rangle = \dfrac{1}{\lambda_i\lambda_j} {\lambda_i}^2\delta_{ij}= \delta_{ij}
$$

이다. 즉 $B$ 는 $\text{im}(\boldsymbol{A})$ 의 정규기저벡터이다.

이제 행렬 $\boldsymbol{S}_1$ 을 다음과 같이 두 행렬의 곱으로 정의하자. 이것은 **1**. 에서 했던 것이다.

$$
\boldsymbol{S}_1 = \begin{bmatrix} |& &|\\ \dfrac{1}{\lambda_1}\boldsymbol{Av}_1 & \cdots & \dfrac{1}{\lambda_n}\boldsymbol{v}_m \\ |& &| \end{bmatrix} \begin{bmatrix} -&  \boldsymbol{v}^\ast_1 & -\\ & \vdots &  \\  - &  \boldsymbol{v}^\ast_m & - \end{bmatrix}
$$

이 때 $\boldsymbol{S}_1 \boldsymbol{v}_i = \dfrac{1}{\lambda_i}\boldsymbol{Av}_i$ 이며 $\boldsymbol{S}_1$ 은 linear isometry 이다.

또한 $\{\boldsymbol{v}_{m+1},\ldots,\boldsymbol{v}_n\}$ 은 $\left(\text{im} \left(\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\right)\right)^\perp$  의 기저이다. $B$ 는 $\text{im} (\boldsymbol{A})$ 의 기저이므로 이 기저를 확장하여 원래 벡터공간의 기저를 구성 할 수 있다. 기저에 추가된 벡터를 $\{\boldsymbol{u}_{m+1},\ldots, \boldsymbol{u}_n\}$ 이라 하고, $\boldsymbol{S}_2$ 는

$$
\boldsymbol{S}_2 = \begin{bmatrix} |& &|\\ \boldsymbol{u}_{m+1} & \cdots & \boldsymbol{u}_n \\ |& &| \end{bmatrix} \begin{bmatrix} -&  \boldsymbol{v}^\ast_{m+1} & -\\ & \vdots &  \\  - &  \boldsymbol{v}^\ast_n & - \end{bmatrix}
$$

이라 하자. 이제 블록대각행렬 $\boldsymbol{S}=\begin{bmatrix} \boldsymbol{S}_1 & 0 \\ 0 &\boldsymbol{S}_2 \end{bmatrix}$ 을 생각하면 $\boldsymbol{S}_1,\,\boldsymbol{S}_2$ 가 linear isometry 이므로 $\boldsymbol{S}$ 도 linear isometry 이며, $\boldsymbol{v}_i \not \in \ker \sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 이면,

$$
\boldsymbol{S}\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\boldsymbol{v}_i = \boldsymbol{S} \lambda_i \boldsymbol{v}_i = \boldsymbol{Av}_i
$$

이고 $\text{nullity} (\boldsymbol{A}) = \text{nullity} \left(\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\right)$ 이므로 $\boldsymbol{A} = \boldsymbol{S} \sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 이다. $\square$

:::


</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-polar_decomposition}

#### 극분해

이렇게 임의의 행렬은 linear isometry 와 positive semidefinite 행렬의 곱으로 표현 될 수 있으며, 이것을 **극분해(polar decomposition)** 라고 한다.

:::
:::


</br>

## 특이값 분해 (Singular value decomposition, SVD)

::: {.callout-note appearance="simple" icon="false"}
::: {#def-singular_value}

#### 특이값 (singular value)
$\boldsymbol{A} \in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 의 고유값을 **특이값(singular value)** 라 한다. $\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 가 positive semidefinite 이므로 당연히 모든 특이값은 $0$ 이 아닌 실수이다.
:::
:::

</br>

::: {#thm-singular_value_decomposition}

$\boldsymbol{A}\in \in \mathcal{M}_{n \times n}(\mathbb{F})$ 가 특이값으로 $s_1,\ldots,\,s_n$ 을 가질 때 어떤 linear isometry $\boldsymbol{U},\,\boldsymbol{V} \in \mathcal{M}_{n \times n}(\mathbb{F})$ 와 대각행렬 $\boldsymbol{D} \in\mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해
$$
\boldsymbol{A}=\boldsymbol{UDV}^\ast
$$

이다.
:::


::: {.proof} 

극분해에 의해 $\boldsymbol{A}=\boldsymbol{S}\sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}$ 이다. $\sqrt{\boldsymbol{A}^\ast\boldsymbol{A}}$ 는 positive semidifinite 이므로 어떤 linear isometry $\boldsymbol{V}$ 에 의해 $\boldsymbol{V}^\ast \sqrt{\boldsymbol{A}^\ast \boldsymbol{A}}\boldsymbol{V}=\boldsymbol{D}$ 로 대각화 된다. 따라서,

$$
\boldsymbol{A} = \boldsymbol{S}\sqrt{\boldsymbol{A}^\ast\boldsymbol{A}} = \boldsymbol{S}\boldsymbol{V}\boldsymbol{D}\boldsymbol{V}^\ast =\boldsymbol{UDV}^\ast \,\qquad \text{where } \boldsymbol{U}=\boldsymbol{SV}
$$

이다. 두 linear isometry 의 곱은 linear isometry 이므로 $\boldsymbol{U}$ 도 linear isometry 이다. $\square$

:::


</br>

## 연습문제

::: {#exr-axler_5_A_2}

#### Axler 5.A.2

$\boldsymbol{A},\,\boldsymbol{B}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이고 $\boldsymbol{AB}=\boldsymbol{BA}$ 이면 $\ker \boldsymbol{B}$ 는 $\boldsymbol{A}$ 의 불변부분공간이다.
:::

::: {.solution}

$\boldsymbol{u}\in \ker \boldsymbol{B}$ 라 하자. $\boldsymbol{BAu} =\boldsymbol{ABu} = \boldsymbol{0}$ 이므로 $\boldsymbol{Au}\in \ker \boldsymbol{B}$ 이다.  

:::