 ---
title: "특성다항식과 조르당 형식"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

## 특성다항식

### 특성다항식 {#sec-characteristic_polynomial}

정사각 행렬에 대한 특성다항식은 이미 [특성다항식](../part1/ch1_06_eigenvalue.qmd#sec-characteristic_polynomial) 에서 정의하였지만 환기를 위해 다시 한번 정의한다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-characteristic_polynomial_re}

#### 특성다항식

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대한 $p_{\boldsymbol{A}}(\lambda) = \det (\lambda \boldsymbol{I}-\boldsymbol{A})$ 를 **특성 다항식(characteristic polynomial)** 이라 한다.

:::
:::

</br>

또한 우리는 다음을 보였다.

- @prp-invariance_of_characteristic_polynomial : 특성 다항식은 닮음 변환에 대해 불변이다. 즉 행렬 $\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 과 가역행렬 $\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $p_{\boldsymbol{A}}(\lambda) = p_{\boldsymbol{P^{-1}AP}}(\lambda)$ 이다.

- @prp-eigenvalue_characteristic_polynomial : $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\lambda\in \mathbb{F}$ 가 $\boldsymbol{A}$ 의 고유값이기 위한 필요충분조건은 $p_{\boldsymbol{A}}(\lambda)=0$ 인 것이다.

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-trace_of_matrix}

#### 행렬의 trace

$\text{tr} : \mathcal{M}_{n\times n}(\mathbb{F}) \to \mathbb{F}$ 는 다음과 같이 정의된다.

$$
\text{tr}(\boldsymbol{\boldsymbol{A}}) = \sum_{i=1}^n A_{ii}.
$$

:::
:::


::: {#prp-trace_is_invariant_under_similar_transformation}

정사각 행렬에 대한 trace 는 닮은 변환에 대해 불변이다.

:::

::: {.proof}

$\boldsymbol{A},\,\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이며 $\boldsymbol{P}$ 가 가역이라고 하자. 

$$
\begin{aligned}
\text{tr}(\boldsymbol{P}^{-1}\boldsymbol{AP}) &= \sum_{i=1}^n\left(\boldsymbol{P}^{-1}\boldsymbol{AP}\right)_{ii} = \sum_{i, j, k=1}^n (P^{-1})_{ij}A_{jk}P_{ki} = \sum_{j, k=1}^n A_{jk} (\boldsymbol{PP}^{-1})_{kj} = \sum_{j=1}^n A_{jj} \\
&= \text{tr}(\boldsymbol{A}). \qquad \square
\end{aligned}
$$

:::

</br> 

::: {#exr-SNU_7_4_1}

$L\in \mathcal{L}(V)$ 이고 $p(\lambda) \in \mathbb{F}[\lambda]$ 라고 하자. $v \in E(\lambda, L)$ 이면 $v \in E(p(\lambda), p(L))$ 임을 보여라.

:::

::: {.solution}

$p(t) = a_nt^n + \cdots + a_1t  + a_0$ 라고 하자. $L\in \mathcal{L}(V)$ 이면 

$$
\begin{aligned}
p(L) -p(\lambda)I_V &=  a_n(L^n -\lambda^n I_V) + \cdots + a_1(L-\lambda I_V)   \\
&= (L-\lambda I_V)\left[  \cdots \right]
\end{aligned}
$$ 

이므로 $\left( p(L)-p(\lambda) I_V\right) v = 0$ 이다.
:::

</br>

::: {#exr-SNU_7_4_2}

$L,\,T\in \mathcal{L}(V)$ 이고 $T$ 가 가역사상일 때 $p(t)\in \mathbb{F}[t]$ 이면 $p(T^{-1}LU) = T^{-1}p(t)T$ 임을 보여라.

:::

::: {.solution}

임의의 정수 $m$ 에 대해 $(T^{-1}LT)^m = T^{-1}L^mT$ 임을 이용하여 쉽게 보일 수 있다. 

:::

</br>

### 행렬의 대각화와 특성다항식 {#sec-characteristic_polynomial_and_diagonalization}

@thm-diagonalizability 에서 우리는 행렬의 대각화에 대해 정리하였다. 이제 행렬의 대각화를 특성다항식의 관점에서 보자.

-- to be done -- 


</br>

## 케일리 해밀턴 정리

::: {.callout-note appearance="simple" icon="false"}
::: {#def-annihilator_ideal}

#### Annihilator Ideal

$\mathbb{F}$-벡터공간 $V$ 에 대해 $L\in \mathcal{L}(V)$ 일 때 아래와 같이 정의된 $I_L$ 를 **annihilator ideal** 이라고 한다.

$$
\mathcal{I}_L = \{ p(t) \in \mathbb{F}[t] : p(L)=0 I_V\}
$$

:::
:::

</br>
 
::: {#prp-annihilator_ideal}

$\mathbb{F}$-벡터 $V$ 에 대해 $L\in \mathcal{L}(V)$ 일 때 다음을 보여라.

&emsp; ($1$) $\mathcal{I}_L \le \mathbb{F}[t]$.

&emsp; ($2$) $g(t)\in \mathbb{F}[t],\, p \in \mathcal{I}_L \implies g(t)p(t) \in \mathcal{I}_L$.
:::

::: {.proof}

($1$) $0\in \mathcal{I}_T$ 임은 자명하다. $p,\, q\in \mathcal{I}_L,\,c\in \mathbb{F}$ 에 대해 $(p+cq)(t) = p(t) +cq(t) \in \mathcal{I}_L$ 임은 자명하다. 이로부터 $\mathcal{I}_L\le \mathbb{F}[t]$ 라는 것을 쉽게 보일 수 있다.

($2$) trivial 하다.

:::


</br>

::: {#prp-similarity_relation_in_annihilator_ideal}

$S,\, T\in \mathcal{L}(V)$ 에 대해 $S\sim T$ 이면 $\mathcal{I}_S= \mathcal{I}_T$ 이다.

:::

::: {.proof}

가역연산자 $U\in \mathcal{L}(V)$ 에 대해 $S=U^{-1}TU$ 라고 하자. $p\in \mathcal{I}_T$ 이면, $p(S) = U^{-1}p(T)U$ 이므로 $p \in \mathcal{I}_S$ 이다. $\square$

:::

</br>

::: {#prp-annihilator_ideal_is_nontrivial}

유한차원 벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 에 대해 $\mathcal{I}_L \ne \{0\}$ 이다.

:::

::: {.proof}

$\dim (V) = n$ 이라고 하자. $\dim(\mathcal{L}(V)) = n^2$ 이므로, $\{I_V,\, T, \ldots,\, T^{n^2}\}$ 는 선형종속이다. $\square$

:::


</br>

이제 여기서 가장 중요한 케일리-해밀턴 정리를 증명할 차례이다. 그러나 그 전에 미리 보일 것이 있다. 

::: {#exr-before_cayley_hamilton}

$\boldsymbol{B}_i\in \mathcal{M}_{n \times n}(\mathbb{F})$ 는 상삼각행렬이며 $i$ 번째 대각성분이 $0$ 이라고 하자. 이 때 $\prod_{i=1}^n \boldsymbol{B}_i = \boldsymbol{B}_1 \boldsymbol{B}_2 \cdots \boldsymbol{B}_n = \boldsymbol{0}$ 임을 보여라.

:::

::: {.solution}

상삼각행렬의 곱은 상삼각행렬이다. $\boldsymbol{B}_1\boldsymbol{B}_2$ 는 첫번째열과 두번째 열이 영벡터이다. 이로부터 즉 $k\le n$ 에 대해 $\prod_{i=1}^k \boldsymbol{B}_i$ 는 1열부터 $k$ 번째 열까지 영벡터임을 가정 할 수 있고, 이를 수학적 귀납법으로 보이자. $k=1$ 일 때는 이미 보였다. $k$ 에 대해 성립함을 가정하자. $\prod_{i=1}^{k+1} \boldsymbol{B}_i  = \left(\prod_{i=1}^k \boldsymbol{B}_i\right)\boldsymbol{B}_{k+1}$ 이며 $\left(\prod_{i=1}^k \boldsymbol{B}_i\right)$ 은 $k$ 열까지 영벡터인 상삼각 행렬이고 $\boldsymbol{B}_{k+1}$ 은 $k+1$ 번째 대각성분이 $0$ 인 상삼각행렬이다. $\boldsymbol{C}=\prod_{i=1}^k \boldsymbol{B}_i$ 라고 하자. 

$$
(\boldsymbol{C}\boldsymbol{B}_{k+1})_{j, k+1} = \sum_{m = 1}^{n} C_{jm}(\boldsymbol{B}_{k+1})_{m, k+1} 
$$

이며 $m=1,\ldots,\,k$ 에 대해 $C_{jm}=0$ 이며 $m=k+1, \cdots n$ 에 대해 $(\boldsymbol{B}_{k+1})_{m, k+1}=0$ 이므로 위 식은 $0$ 이 된다. 따라서 $\prod_{i=1}^n \boldsymbol{B}_i = \boldsymbol{B}_1 \boldsymbol{B}_2 \cdots \boldsymbol{B}_n = \boldsymbol{0}$ 이다.


:::

</br>

::: {#thm-cayley_hamilton}

#### 케일리-해밀턴 정리(Cayley-Hamilton Theorem)

유한차원 $\mathbb{F}$-벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 와 특성다항식 $p_L(t) = \det (tI_V - L)$ 에 대해 $p_L \in \mathcal{I}_L$ 이다.

:::

::: {.proof}

$n=\dim (V)$ 라고 하자. 우선 $\mathbb{F}=\mathbb{C}$ 에 대해 증명한다. @thm-uppertriangular_matrix_complex_field 에서 우리는 복소수체에서 정의된 모든 정사각행렬은 상삼각행렬과 닮았다는 것을 보였다. 따라서 우리는 상삼각행렬에 대한 특성다항식에 대해서만 증명하면 된다. $\boldsymbol{A}$ 가 상삼각행렬이라고 하면, $p_\boldsymbol{A}(t) = \prod_{i=1}^n (t-A_{ii})$ 이다. 이제 

$$
p_\boldsymbol{A}(\boldsymbol{A}) = \prod_{i=1}^n (\boldsymbol{A}-A_{ii}\boldsymbol{I}_n)=0
$$ 

임을 보이면 된다. $\boldsymbol{A}$ 가 상삼각행렬이므로 $(\boldsymbol{A}- A_{ii}\boldsymbol{I}_n)_{ii}  = 0$ 이다. 위의 @exr-before_cayley_hamilton 에서 보였듯이 $p_\boldsymbol{A}(\boldsymbol{A}) =0$ 이므로 $p_T(L) \in \mathcal{I}_L$ 이다.

이제 $\mathbb{F}=\mathbb{R}$ 인 경우에 대해 생각하자. $\mathbb{R}\subset \mathbb{C}$ 이므로 성립하지 않을 이유가 없다. $\square$ 

:::


</br>

## 최소다항식 {#sec-minimal_polynomial}

다항식 가운데 최고차 항의 계수가 1인 다항식을 **monic** 이라고 한다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-minimal_polynomial}

#### 최소다항식

$L\in \mathcal{L}(V)$ 에 대한 annihilator ideal $\mathcal{I}_L$ 가운데 1 차 이상의 다항식 중 가장 작은 차수를 갖는 monic 다항식을 $L$ 에 대한 **최소다항식(minimal polynomnial)** 이라고 한다. 

:::
:::

</br>

::: {#thm-existance_and_uniqueness_of_minimal_polynomial}

$L\in \mathcal{L}(V)$ 에 대한 최소다항식은 존재하며, 유일하다.

:::

::: {.proof}

@prp-annihilator_ideal_is_nontrivial 에 의해 $L$ 에 대한 최소다항식은 존재한다. 이제 $p,\,q$ 가 $L$ 에 대한 최소다항식이라고 하자. 당연히 두 다항식은 같은 차수 $m$ 를 가진다. $p \ne q$ 라면 $r=p-q$ 는 $m$ 보다 작은 차수를 가지며 $r(L)=0$ 이다. $p,\,q$ 가 최소다항식이므로 남은 유일한 가능성은 $r=0$ 일 때 뿐이며 따라서 $p=q$ 이다. $\square$
:::

</br>

위의 정리와 @prp-similarity_relation_in_annihilator_ideal 로부터 다음을 알 수 있다.

::: {#cor-minimal_polynomial_and_similar_transformation}

$V$ 에서의 두 연산자가 닮았으면, 두 연산자의 최소다항식은 같다.

:::


</br>


다음은 굳이 증명을 적을 필요는 없을 것이다.

::: {#prp-divisability_of_annihilator_ideal}

$p\in \mathcal{I}_L$ 는 $L$ 에 대한 최소다항식으로 나누어 떨어진다. 또한 최소다항식에 임의의 다항식을 곱한 다항식은 $\mathcal{I}_L$ 포함된다.

:::

</br>





## 일반화된 고유벡터 와 일반화된 고유공간

벡터공간 $V$ 에서의 선형 연산자 $L\in \mathcal{L}(V)$ 에 대해 다음이 성립한다는 것은 쉽게 보일 수 있다.

::: {#prp-kernel_of_power_of_operator}

$L\in \mathcal{L}(V)$ 이며 $L^0 :=I_V$ 라고 하자. 이 때 다음이 성립한다. 

$$
\{0\} \subset \ker (L^0) \subset \ker (L^1)  \subset \cdots \subset \ker (L^k) \subset \ker (L^{k+1})\subset \cdots.
$$
:::

</br>

::: {#prp-equality_in_the_sequence_of_kernel}

$L\in \mathcal{L}(V)$ 에서 어떤 자연수 $m$ 에 대해 $\ker (L^m) = \ker (L^{m+1})$ 이면 $n\ge m$ 에 대해 

$$
\ker (L^n) = \ker (L^m)
$$

이다.
:::

::: {.proof}

@prp-kernel_of_power_of_operator 에 의해 $\ker (L^m)\subset \ker (L^n)$ 이다. 따라서 $\ker (L^n) \subset \ker (L^m)$ 임을 보이면 된다. 만약 우리가 임의의 양의 정수 $k$ 에 대해 $\ker (L^{m+k+1}) \subset \ker (L^{m+k})$ 임을 보인다면 연쇄적으로 $\ker (L^n) = \ker (L^m)$ 라는 것을 보이는 것이 된다. 
$$
\begin{aligned}
v\in \ker (L^{m+k+1}) &\implies L^{m+1}(T^{k}v) = 0\\
&\implies L^k v \in \ker (L^{m+1}) = \ker(L^{m})
\end{aligned}
$$

이므로 $\ker (L^{m+k+1}) \subset \ker (L^{m})$ 이다. $\square$
:::

</br>

::: {#exr-kernel_of_power_of_dimension}

유한차원 벡터공간 $V$ 에서 $n=\dim (V),\, L\in \mathcal{L}(V)$ 일 때 $\ker (L^n) = \ker (L^{n+1}) = \cdots$ 이다.

:::

::: {.proof}
@prp-equality_in_the_sequence_of_kernel 을 생각하면 어떤 $m<n$ 에 대해 $\ker(L^m)= \ker (L^{m+1})$ 이라면 위의 명제가 성립한다는 것을 안다. 이제 각각의 $m<n$ 에 대해 $\ker(L^m) \ne \ker (L^{m+1})$ 라면 $\dim (\ker(L^m)) < \dim (\ker (L^{m+1}))$ 이며 $\ker (L^n)=V$ 이므로 $\ker (L^n)= \ker (L^{n+1})=V$ 이다. $\square$
:::

</br>


::: {#prp-kernel_range_of_power_of_operator}

유한차원 벡터공간 $V$ 에서 $n=\dim (V),\, L\in \mathcal{L}(V)$ 일 때 

$$
V = \ker(L^n)\oplus \text{im}(L^n)
$$

이다.
:::

::: {.proof}

$v\in \ker(T^n) \cap \text{im}(L^n)$ 이면 $L^n(v)=0$ 이며 $v=L^n (u)$ 인 $u\in V$ 가 존재한다. $L^n (v) = L^{2n}(u) = 0$ 이므로 $u \in \ker (L^{2n})$ 이다. 따라서 @exr-kernel_of_power_of_dimension 에 의해 $u\in \ker (L^n)$ 이므로 $v=0$ 이다. 즉 $\ker(L^n) \cap \text{im}(L^n) = \{0\}$ 이다.

우리는 $\text{nullity}(L^n) + \text{rank}(K^n)=n$ 임을 안다. 따라서 $V = \ker (L^n) \oplus \text{im}(L^n)$ 이다. $\square$
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-generalized_eigenvectors_eigenspaces}
#### 일반화된 고유벡터와 일반화된 고유공간

$L\in \mathcal{L}(V)$ 이고 $\lambda$ 가 $L$ 의 고유값일 때 어떤 양의 정수 $k$ 와 영벡터가 아닌 벡터 $v\in V$ 가

$$
(L-\lambda I_V)^k v = 0
$$

를 만족하면 벡터 $v$ 를 고유값 $\lambda$ 를 갖는 연산자 $L$ 에 대한 **일반화된 고유벡터(generalized eigenvector)** 라고 한다. 고유값 $\lambda$ 에 대한 연산자 $L$ 의 집합과 영벡터의 합집합을 고유값 $\lambda$ 를 갖는 연산자 $L$ 에 대한 **일반화된 고유공간(generalized eigenspace)** 라고 한다.

:::
:::

이제 고유값 $\lambda$ 를 갖는 연산자 $L$ 에 대한 일반화된 고유공간을 $G(\lambda, L)$ 라고 쓰기로 하자. 다음 명제는 @exr-kernel_of_power_of_dimension 에 따라 자명하다.


::: {#prp-generalized_eigenspace}
$$
G(\lambda, L) = \ker (L-\lambda I)^{\dim (V)}
$$

이다.
:::


</br>

::: {#prp-linearly_independent_generalized_eigenvectors}

서로 다른 고유값을 갖는 일반화된 고유벡터의 집합은 선형독립이다.

:::

::: {.proof}

$v_1,\ldots,\,v_n$ 이 각각 $\lambda_1,\ldots,\lambda_n$ 의 고유값에 대한 일반화된 고유벡터라고 하자. 

$$
0 = c_1 v_1 + \cdots + c_n v_n
$$

라 놓자. $k_1$ 를 $(L-\lambda_1 I)^{k}v_1$ 가 $0$ 이 되지 않는 가장 큰 자연수라고 하자. 연산자 $S \in \mathcal{L}(V)$ 를 

$$
S:=(L-\lambda_1 I)^k (L-\lambda_2I)^{\dim (V)} \cdots (L-\lambda_mI)^{\dim (V)}
$$

라고 하면, 
$$
0 = S (c_1v_1 + \cdots + c_n v_n) = c_1 S(v) 
$$

이며 $S$ 의 정의에 의해 $c_1 = 0$ 이다. 같은 방법으로 $c_2=\cdots =c_m=0$ 임을 보일 수 있으며, 따라서 $\{v_1,\ldots,\,v_m\}$ 은 선형독립이다. $\square$

::: 


</br>

## Nilpotent Operator


::: {.callout-note appearance="simple" icon="false"}
::: {#def-nilpotent}

#### Nilpotent 연산자

벡터공간에서 정의된 연산자 $N\in \mathcal{L}(V)$ 가 어떤 $n\in \mathbb{Z}_+$ 에 대해 $N^n= 0$ 일 때 $N$ 을 **nilpotent 연산자**라고 한다. 

:::
:::


</br>

::: {#prp-nilpotent_operator_power_of_dimension}

$V$ 가 유한차원 벡터공간이며 $N\in \mathcal{L}(V)$ 가 nilpotent 일 때 $N^{\dim (V)} = 0$ 이다.

:::


::: {.proof}

$G(0,\, N) = V$ 이므로, @prp-generalized_eigenspace 에 의해 성립한다. $\square$
:::


</br>

::: {#prp-eigenvalue_of_nilpotent}

$N\in \mathcal{L}(V)$ 이 nilpotent 이면 $N$ 은 $0$ 이외의 고유값을 갖지 않는다.

:::

::: {.proof}

$\lambda \ne 0$ 이 $N$ 의 고유값이며 $v$ 가 $\lambda$ 에 대한 교유벡터라면 모든 $k\in \mathbb{Z}_+$ 에 대해 $N^kv=\lambda^k v \ne 0$ 이므로 $N$ 은 nilpotent 가 아니다. 따라서 nilpotent 의 고유값은 $0$ 뿐이다. $\square$ 

:::

</br>

## 연산자의 분해


::: {#prp-invariance_of_kernel_and_image_of_operator}

$T\in \mathcal{L}(V)$ 일 때 $T$ 에 대한 다항식으로 정의된 연산자 $p(T)$ 의 $\ker (p(T))$ 와 $\text{im}
(p(T))$ 는 $T$ 에 대한 불변부분공간이다.

:::

::: {.proof}

$v\in \ker (p(T)) \implies p(T)(Tv)=T(p(T)v) = 0 \implies Tv \in \ker (p(T))$ 이므로 $\ker (p(T))$ 는 $T$ 에 대한 불변부분공간이다. 

:::
