---
title: "쌍대공간과 쌍대 사상"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---


## 선형 범함수와 쌍대공간

우리는 앞서 벡터공간 $U,\,V$ 에 대한 선형사상의 집합 $\mathcal{L}(U,\, V)$ 가 벡터공간이라는 것을 알았다. 또한 $\mathbb{F}$ 도 벡터공간이다. 따라서 $\mathbb{F}$-벡터 공간 $V$ 에 대해 $\mathcal{L}(V,\,\mathbb{F})$ 는 $V\mapsto \mathbb{F}$ 인 선형사상의 집합이다. 이 집합은 벡터공간을 이해하는데 매우 중요하다.

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-functional_dualspace} 
#### 선형 범함수와 쌍대공간

$\mathbb{F}$-벡터공간 $V$ 에 대해 $\mathcal{L}(V,\,\mathbb{F})$ 에 속하는 함수를 **선형 범함수(linear functional)** 라 한다. $\mathcal{L}(V,\,\mathbb{F})$ 는 벡터공간이며 이를 $V$ 에 대한 **쌍대공간(dual space)** 이라 하고 $V^\ast$ 이라 쓴다.
:::
:::

</br>

::: {#exm-linear_functional_1}
$\varphi : \mathbb{R}^3 \to  \mathbb{R}$ 을 임의의 $a,\,b,\,c\in \mathbb{R}$ 에 대해 $\varphi (x, y, z) = ax + by + cz$ 라 하면 $\varphi \in (\mathbb{R}^3)^\ast$ 이다.

::: 


</br>

::: {#exm-linear_functional_2}

$n$ 차 다항식 이하의 다항식의 집합 $\mathbb{F}_n[t]$ 는 $\mathbb{F}$ 벡터공간이다. $f\in \mathbb{F}_n[t]$ 와 $c \in \mathbb{F}$ 에 대해 $\varphi (f)=f(c)$ 는 $(\mathbb{F}_n[t])^\ast$ 에 속하는 선형 범함수이다.

:::

</br>

::: {#exm-linear_functional_3}

$[a,\,b]$ 구간에서 연속인 실함수의 집합 $C_{[a,\,b]}$ 는 $\mathbb{R}$-벡터공간이다. 이 때 $\psi : C_{[a,\,b]} \to \mathbb{R}$ 을 다음과 같이 정의한다.

$$
\psi (f) = \int_{a}^b f(t)\, dt.
$$

그렇다면 $\psi \in (C_{[a,\,b]})^\ast$ 이다.

:::



</br>

유한차원 벡터공간 $V$ 에 대해 $V^\ast$ 의 차원을 정의 할 수 있다.

::: {#prp-dim_of_dual_space}
유한차원 벡터공간 $V$ 에 대해 $\dim (V^\ast) = \dim (V)$ 이다.
:::

::: {.proof}
@cor-dimension_of_LUV 에 의해 $\dim (V^\ast) = \dim (\mathcal{L}(V,\,\mathbb{F})) = \dim (V)$. $\square$

:::

</br>


::: {#prp-dual_basis}

유한차원 벡터공간 $V$ 의 기저 $\{v_1,\ldots,\,v_n\}$ 에 대해 범함수 $\varphi_1,\ldots,\,\varphi_n \in V^\ast$ 를 다음과 같이 정의하자.

$$
\varphi_i (v_j) = \delta_{ij}
$$

이 때 $\{\varphi_1,\ldots,\,\varphi_n\}$ 은 $V^\ast$ 의 기저이다.
:::

::: {.proof}

우선 $\varphi(v_i) \in V^\ast$ 이라는 것은 쉽게 알 수 있다. 이제 $\dim V^\ast = \dim V = n$ 이므로 $\{\varphi_1,\ldots,\varphi_n\}$ 이 선형독립임을 보이면 된다.

$$
\begin{aligned}
& c_1 \varphi_1 + \cdots + c_n \varphi_n = 0 \\
\implies & (c_1\varphi_1 + \cdots + c_n \varphi_n)(v_j) = 0, \qquad \text{for }j=1,\ldots,\,n \\
\implies &c_1 = \cdots = c_n = 0
\end{aligned}
$$
$\square$
:::


즉 $n$ 차원 $\mathbb{F}$-벡터공간 $V$ 의 모든 선형 범함수는 $\{\varphi_i,\ldots,\,\varphi_n\}$ 의 선형결합으로 표현할 수 있다는 뜻이다. 

</br>

## 쌍대 기저와 쌍대 사상


::: {.callout-note appearance="simple" icon="false"}
::: {#def-dual_basis}

#### 쌍대 기저 (Dual basis)

@prp-dual_basis 의 $\{\varphi_1,\ldots,\,\varphi_n\}$ 을 $V$ 의 기저 $\{v_1,\ldots,\,v_n\}$ 에 대한 **쌍대 기저(dual basis)** 라 한다. $\{v_1,\ldots,\,v_n\}$ 에 대한 쌍대기저를 $\{v_1^\ast,\ldots,\,v_n^\ast\}$ 라고 표기한다.
 
:::
:::


</br>

벡터공간 $V$ 와 그 기저에 대응하는 쌍대공간, 쌍대기저가 잘 정의된다. 이제 벡터공간에서의 선형사상에 대응하는 쌍대사상에 대해 알하보자.

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-dual_map}
#### 쌍대 사상(Dual map)

$T\in \mathcal{L}(U,\, V)$ 와 $\varphi \in V^\ast$ 에 대해 아래와 같이 정의된 $T^T \in \mathcal{L}(V^\ast,\, U^\ast)$ 를 $L$ 의 **쌍대 사상(dual map)** 이라 한다.

$$
T^T(\varphi) = \varphi \circ T
$$ 
[$T^T$ 의 위첨자 $T$ 는 전치(transpose) 의 $T$ 이다. 이유는 마지막에 나온다.]{.aside}
:::
::: 

</br>

::: {#prp-dual_map}
@def-dual_map 에서 정의된 $T^T$ 은 선형사상이다.
:::

::: {.proof}
$\varphi,\,\psi \in V^\ast,\, c \in \mathbb{F}$ 일 때,

$$
T^T (\varphi + c \psi)  = (\varphi + c \psi )\circ T = \varphi \circ T  +c (\psi \circ T) = T^T (\varphi) + c T^T (\psi) 
$$

이므로 $T'$ 은 선형사상이다. $\square$
:::

</br>

이제 쌍대 사상의 중요한 성질을 알아보자.

::: {#thm-dual-map}

$S,\,T \in \mathcal{L}(U,\,V)$ 일 때 쌍대사상 $S^T ,\,T^T$ 은 다음 성질을 만족한다.

&emsp; ($1$) $(S+T)^T= S^T + T^T$,

&emsp; ($2$) $(\lambda S)^T = \lambda S^T$

또한 $T \in \mathcal{L}(U,\,V),\, S \in \mathcal{L}(V,\,W)$ 일 때 다음 성질을 만족한다.

&emsp; ($3$) $(S\circ T)^T = T^T \circ S^T$
:::

::: {.proof}

($1$), ($2$) 는 아래와 같이 증명한다.

$$
\begin{aligned}
(S+T)^T(\varphi)  &=\varphi \circ (S+T) = \varphi \circ S + \varphi \circ T = S^T + T^T,\\
(\lambda S)^T (\varphi) &= \varphi \circ (\lambda S) = \lambda (\varphi \circ S) = \lambda S^T
\end{aligned}
$$

이제 ($3$) 을 증명하자.

$$
\begin{aligned}
(S\circ T)^T(\varphi) &= \varphi \circ (S \circ T) = (\varphi \circ S)\circ T = T^T (\varphi \circ S) = T^T (S^T(\varphi)) \\
&= (T^T \circ S^T) (\varphi)
\end{aligned}
$$
$\square$
:::

</br>

## Annihilator

::: {.callout-note appearance="simple" icon="false"}
::: {#def-annihilator}
#### Annihilator

$U$ 가 벡터공간 $V$ 의 부분집합 일 때, 아래와 같이 정의되는 집합을 **annihilator** of $U$ 라 하고 $U^0$ 라 쓴다.

$$
U^0 =\{ \varphi \in V^\ast : \varphi (u) = 0 \text{  for all }u\in U\}
$$
:::
:::

</br>

::: {#prp-annihilator}
이 때, $U^0$ 는 $V^\ast$ 의 부분공간이다.
:::

::: {.proof}
영함수 $0\in V^\ast$ 은 $U^0$ 에 속함은 자명하다. $\varphi,\,\psi \in U^0$ 이고 $u\in U,\,\lambda \in \mathbb{F}$ 일 때,

$$
\begin{aligned}
(\varphi + \psi)(u) &= \varphi(u) + \psi (u) = 0,\\
(\lambda \varphi)(u) &= \lambda (\varphi (u)) = 0
\end{aligned}
$$
이므로 $U^0$ 는 $V^\ast$ 의 부분공간이다. $\square$
:::

</br>

::: {#thm-dim_of_annihilator}

$V$ 가 유한차원 벡터공간이고 $U$ 가 $V$ 의 부분공간일 때

$$
\dim (U) + \dim (U^0) = \dim (V)
$$

이다.
:::

::: {.proof}
$U$ 가 $V$ 의 부분공간이므로 $i_U\in \mathcal{L}(U,\,V)$ 를

$$
i_U(u) = u
$$

로 정의하면, $i_U^T \in \mathcal{L}(V^\ast,\, U^\ast)$ 을 생각 할 수 있다. 임의의 $\varphi \in V^\ast$ 에 대해 $i_U^T (\varphi) = \varphi  \circ i_U$ 이며,

$$
\psi \in \ker (i_U^T) \iff \psi \circ i_U = 0 \iff \psi (u) = 0,\;\forall u \in U \iff \psi \in U^0
$$

이므로 $\ker (i_U^T) = U^0$ 이다. Rank-nullity theorem (@thm-rank_nullity)에 의해,

$$
\text{rank} (i_U^T) + \text{nullity} (i_U^T) = \dim (V^\ast)
$$

이며 $\text{nullity} (i_U^T) = \dim (U^0),\, \dim (V^\ast) = \dim (V)$ 이므로,

$$
\text{rank}(i_U^T) + \dim (U^0) = \dim (V)
$$

임을 안다. $U$ 의 기저 $u_1,\ldots,\,u_m$ 을 확장하여 $V$ 의 기저를 구성 할 수 있다. 여기에 추가된 기저가 $v_1,\ldots,\,v_n$ 이라 하자. $u_j$ 의 쌍대기저를 $\varphi_j$, 추가된 $v_k$ 에 대한 쌍대기저를 $\psi_k$ 라 하자.

$$
\begin{aligned}
i_U^T(\varphi_k)(u_j) &= (\varphi_k \circ i_U)(v_j) = \delta_{jk}\\
i_U^T(\psi_k) (u_j) &= (\psi_k \circ i_U)(u_j) = \psi_k (u_j) = 0
\end{aligned}
$$

이므로 $\text{im}(i_U^T) = U^\ast$ 이다. 즉 $\text{rank} (i_U^T) = \dim (U^\ast) = \dim (U)$ 이므로 주어진 식이 성립한다. $\square$
:::

</br>

::: {#thm-ker_Tprime}
$U,\, V$ 가 유한차원 벡터공간이고 $T\in \mathcal{L}(U,\,V)$ 일 때, 다음이 성립한다.

&emsp; ($1$) $\ker (T^T) = (\text{im}\, T)^0$

&emsp; ($2$) $\text{nullity} (T^T) = \text{nullity} (T) + \dim (V) - \dim (U)$

:::


::: {.proof}

($1$)

$$
\begin{aligned}
\varphi \in \ker (T^T) &\iff \varphi \circ T = 0  \\ 
& \iff \forall u\in U,\;(\varphi \circ T)(u) = 0 \\ 
& \iff \varphi \in (\text{im} T)^0
\end{aligned}
$$

($2$)

$$
\begin{aligned}
\text{nullity} (T^T) &= \dim ((\text{im} T)^0) \\ 
& = \dim (V) - \dim (\text{im}(T)) \\ 
&= \dim (V) - (\dim (U) - \text{nullity} (T))
\end{aligned}
$$
$\square$

:::
</br>

::: {#lem-injective_dual_map}

유한차원 벡터공간 $U,\,V$ 에 대해 $T\in \mathcal{L}(U,\,V)$ 가 전사인 것의 필요충분조건은 $T^T$ 이 단사인 것이다.

:::

::: {.proof}

$$
\begin{aligned}
T \text{ 가 전사} & \iff \text{im} (T) = V  \\ 
& \iff (\text{im} (T))^0 = \{0 \}  \\ 
& \iff \ker (T^T) = 0  \\ 
& \iff T^T \text{ 이 단사}. \square
\end{aligned}
$$
:::
</br>

::: {#lem-rank_Tprime}

$U,\,V$ 가 유한차원 벡터공간이고 $T\in \mathcal{L}(U,\,V)$ 일 때 다음이 성립한다.

&emsp; ($1$) $\text{rank} (T^T) = \text{rank} (T)$

&emsp; ($2$) $\text{im} (T^T) = (\ker (T))^0$
:::

::: {.proof}
($1$)

$$
\begin{aligned}
\text{rank} (T^T) & = \dim (V^\ast) - \text{nullity} (T^T) = \dim (W) - \dim ((\text{im} (T))^0) \\ 
&= \dim(W) - \text{nullity}(T) = \text{rank} (T).
\end{aligned}
$$

($2$) $\varphi \in \text{im} (T^T)$ 이면 어떤 $\psi \in V^\ast$ 에 대해 $\psi \circ T = \varphi$ 이다. $u \in \ker (T)$ 이면,

$$
\varphi (u) = \psi \circ T (u) = \psi (0_V) =0
$$

이므로 $\varphi \in (\ker (T))^0$ 이다. 즉 $\text{im}(T^T) \subset  (\ker (T))^0$ 이다.

또한,

$$
\text{rank} (T^T) = \text{rank} (T) = \dim (V) - \text{nullity} (T) = \dim ((\ker (T))^0)
$$

이므로 $\text{im} (T^T) = (\ker (T))^0$ 이다. $\square$
:::

</br>

::: {#lem-tprime_surjective}
$U,\,V$ 가 유한차원 벡터공간이고 $T\in \mathcal{L}(U,\,V)$ 일 때 $T$ 가 단사일 필요충분조건은 $T^T$ 이 전사이다.
:::

::: {.proof}
$$
\begin{aligned}
T \text{ 가 단사} &\iff \text{nullity} (T) = 0  \\ 
& \iff (\ker (T))^0 = U^\ast  \\ 
& \iff \text{im} (T^T) = U^\ast  \\ 
& \iff T^T \text{ 은 전사} \;\square
\end{aligned}
$$
:::

</br>

## 전치행렬과 행렬의 rank

우리는 이미 전치행렬과 행렬의 rank 에 대해 [행간소 사다리꼴 행렬을 통한 선형사상의 이해](../part1/ch1_05_matrix.qmd#sec-linear_map_understood_by_RREM) 알아보았다. 여기서는 그 의미를 다른 방법으로 알아보자.


벡터공간 $U,\,V$ 와 그 기저 $\mathcal{B}_U = (u_1,\ldots,\,u_n),\, \mathcal{B}_V = (v_1,\ldots,\,v_m)$, 그리고 이 기저에 대한 쌍대기저 $\mathcal{B}_{U^\ast} = (\varphi_1,\ldots,\,\varphi_n),\, \mathcal{B}_{V^\ast} = (\psi_1,\ldots,\,\psi_m)$ 를 생각하자. $T\in \mathcal{L}(U, V)$ 와 그 쌍대사상 $T'\in \mathcal{L}(V^\ast, U^\ast)$ 를 생각 할 수 있다. $[T]_{\mathcal{B}_U, \mathcal{B}_V} = \boldsymbol{A}$, $[T^T]_{\mathcal{B}_{V^\ast}, \mathcal{B}_{U^\ast}} =\boldsymbol{B}$ 라고 하자. 

$$
T^T(\psi_j)  =  \sum_{i=1}^n B_{ij}\varphi_i
$$

$T^T(\psi_j) = \psi_j \circ T$ 이므로, 

$$
(\psi_j \circ T)(u_k) = \sum_{i=1}^n B_{ij}\varphi_i(u_k) = B_{kj}
$$

이다. 또한

$$
(\psi_j \circ T)(u_k) =  \psi_j (T(u_k)) = \psi_j \left(\sum_{i=1}^m A_{ik}v_i \right) = A_{jk}
$$

이므로 $\boldsymbol{B}=\boldsymbol{A}^T$ 임을 알 수 있다. 즉 우리는 다음을 보였다.

::: {#prp-transpose_of_matrix}

벡터공간 $U,\,V$ 와 그 기저 $\mathcal{B}_U = (u_1,\ldots,\,u_n),\, \mathcal{B}_V = (v_1,\ldots,\,v_m)$ 에 대한 선형사상 $T\in \mathcal{L}(U, V)$ 의 행렬표현 $\boldsymbol{A}=[T]_{\mathcal{B}_U, \mathcal{B}_V}$ 의 전치행렬 $\boldsymbol{A}^T$ 는 $\mathcal{B}_U$ 와 $\mathcal{B}_V$ 의 쌍대기저에 대한 쌍대사상 $T^T\in \mathcal{L}(V^\ast, U^\ast)$ 의 행렬표현이다.

:::

</br>


이제 $T$ 에 대한 쌍대사상을 $T^T$ 로 표현하는것이 자연스럽다 라는 것을 알게 되었다. 우리는 자연스럽게 다음의 결론에 도달한다. 

::: {#thm-dimension_of_matrix_by_transpose}

행렬 $\boldsymbol{A}$ 의 행공간의 차원과 열공간의 차원은 같다.

:::

::: {.proof}

@prp-transpose_of_matrix 의 표기법을 그대로 사용한다. $\boldsymbol{A}$ 의 열공간의 차원은 $\text{rank}(T)$ 와 같다. @lem-rank_Tprime 에 따라 $\text{rank}(T^T)$ 과도 같다. 이것은 $\boldsymbol{A}^T$ 의 열공간의 차원과 같고 또한 $\boldsymbol{A}$ 의 행공간의 차원과 같다. $\square$ 
:::

결국 우리는 @thm-dimension_of_matrix 과 같은 내용을 다른 방법으로 증명하였다. 

</br>

## 이중 쌍대 공간

우리는 벡터공간 $V$ 에 대해 $V^\ast = \mathcal{L}(V, \mathbb{F})$ 인 벡터공간을 알아보았다. 그렇다면 $\mathcal{L}(V^\ast, \mathbb{F})$ 도 생각 할 수 있을것이다. 그런데 이것은 뜻밖에 매우 중요하다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-double_dual} 
#### 이중 쌍대 공간

$\mathbb{F}$-벡터공간 $V$ 의 쌍대공간 $V^\ast$ 에 대한 쌍대공간 $\mathcal{L}(V^\ast, \mathbb{F})$ 를 $V$ 에 대한 **이중 쌍대 공간 (double dual space)** 이라 하고 ${V^\ast}{}^\ast$ 라 쓴다.

:::
:::

</br>


::: {#thm-isomorphsm_to_dual_space}

유한차원 벡터공간 $V$ 의 이중쌍대공간 $V^\ast{}^\ast$ 에 대해 $\Psi : V \to V^\ast{}^\ast$ 를 다음과 같이 정의하자.

$$
\Psi (v) (\psi) = \psi(v).
$$

이 때 다음이 성립한다.

&emsp; ($1$) $v\in V$ 이면 $\Psi(v) \in V^\ast{}^\ast$ 이다.

&emsp; ($2$) $\Psi$ 는 동형사상이다.

&emsp; ($3$) $V$ 의 기저 $\{v_i\}$ 에 대해 $\Psi (v_i) = (v_i^\ast)^\ast$ 이다.

:::

::: {.proof}

($1$) $\Psi(v)$ 는 $V^\ast \mapsto \mathbb{F}$ 함수여야 한다. $\psi\in V^\ast$ 에 대해 위와 같이 정의된 $\Psi$ 는 $V \mapsto V^\ast{}^\ast$ 함수이다. 이제 선형사상임을 보이자. $v_1,\,v_2\in V,\, c\in \mathbb{F}$ 에 대해,

$$
\begin{aligned}
\Psi(v_1+cv_2)(\psi) &= \psi(v_1+cv_2)= \psi(v_1)+c\psi(v_2) = \Psi(v_1)(\psi) + c\Psi (v_2)(\psi) \\
&= (\Psi (v_1)+ c\Psi(v_2))(\psi)
\end{aligned}
$$

이므로 $\Psi \in \mathcal{L}(V^\ast, \mathbb{F})$ 이다.


($2$) 유한차원 벡터공간이며 $\ker (\Psi)= \{0_{V^\ast}\}$ 이므로 동형사상이다.

($3$) $V$ 의 기저 $\{v_i:i=1,\ldots,\,n\}$ 에 대해 $v_i^\ast$ 는 $v_i^\ast(v_j)= \delta_{ij}$ 를 만족하는 선형사상이다. 따라서 $\Psi_i = (v_i^\ast)^\ast$ 라면 $\Psi_i (v_j^\ast) = \delta_{ij}$ 를 만족한다. $\psi \in V^\ast$ 는 $\{v_i^\ast\}$ 의 선형결합이므로 $\psi = \sum_j c_j \psi_j^\ast$ 로 쓸 수 있다.

$$
\Psi (v_i)(\psi)= \left( \sum_{j}c_j v_j^\ast\right) (v_i) = c_i = v_i^\ast{}^\ast (v_i)(\psi)
$$

이다. 따라서 $\Psi(v_i) = \Psi_i (v_i) = (v_i^\ast){}^\ast (v_i)$ 이다.
:::

</br>

유한차원 벡터공간 $V$ 에 대해 $V$ 와 $V'$ 은 동형지만 동형사상은 보통 $V$ 의 기저를 정하고 난후 찾을 수 있다. 그러나 $V$ 와 $V^\ast{}^\ast$ 사이의 동형사상은 @thm-isomorphsm_to_dual_space 의 ($3$) 에서 보였듯이 매우 직접적이고 자연스럽다. 



</br>


## 연습문제

::: {#exr-axler_3_F_1}

모든 선형 범함수는 0 사상이거나 전사함수임을 보여라.

:::

::: {.solution}

$\varphi \in \mathcal{L}(V)$ 가 $0$ 사상이 아니라고 하자. $\varphi(v) \ne 0$ 인 $v\in V$ 가 존재하며, 모든 $c\in \mathbb{F}$ 에 대해 $cv\in V$ 이고 $\varphi(cv)= c \varphi(v)$ 이므로 $\text{im} (\varphi) = \mathbb{F}$ 이다.

:::

</br>

::: {#exr-alxer-3_F_3}

$V$ 가 유한차원 벡터공간이고 $v\in V,\, v \ne 0_V$ 라고 하자. 이 때 $\varphi\in V^\ast$, $\varphi(v) = 1$ 인 $\varphi$ 가 존재함을 보여라.

:::

::: {.solution}

$v$ 를 포함하는 기저를 만들고 이 기저에 대한 쌍대기저를 만들라.

:::

</br>

::: {#exr-axler_3_F_4}

$V$ 가 유한차원 벡터공간이며 $U\le V,\, U  \ne V$ 라고 하자. $0$ 사상이 아니면서 $\forall u\in U,\, \varphi (u)=0$ 을 만족하는 $\varphi \in V^\ast$ 가 존재함을 보여라.

:::

::: {.solution}

$v\in V-U$ 를 선택하여 $v$ 를 첫번째 원소로 하는 기저를 구성하고 쌍대기저를 만들면 된다.

:::

</br>

::: {#exr-axler_3_F_5}

$V_1,\ldots,\,V_m$ 이 벡터공간일 때 $(V_1\times \cdots \times V_m)^\ast$ 과 $V_1^\ast \times \cdots \times V_m^\ast$ 가 동형임을 보여라.

:::

::: {.solution}

$v_i \in V_i,\, \phi_i \in V_i^\ast$ 에 대해 

$$
\Phi_{1, \ldots, m}(v_1,\ldots, v_m) = \phi_1(v_1) + \cdots + \phi_m(v_m)
$$ 

이라 하자. 

 *-- to be done --*
:::

</br>

::: {#exr-axlr_3_F_6}

유한차원 $\mathbb{F}$-벡터공간 $V$ 에 대해 $v_1,\ldots,\,v_m\in V$ 라고 하자. $\Gamma \in \mathcal{L}(V^\ast,\, \mathbb{F}^m)$ 을 다음과 같이 정의한다.

$$
\Gamma (\varphi) = (\varphi (v_1), \ldots, \varphi(v_m)).
$$

이 때 다음을 보여라.

&emsp; ($1$) $V=\text{span}(v_1,\ldots,\,v_m)$ 일 필요충분조건은 $\Gamma$ 가 단사인 것이다.
 
&emsp; ($2$) $\{v_1,\ldots,\,v_m\}$ 이 선형독립일 필요충분조건은 $\Gamma$ 가 전사인 것이다.

:::

::: {.solution}

($1$) $V=\text{span}(v_1,\ldots,\,v_m)$ 임을 가정하자. $\Gamma(\varphi_1) = \Gamma(\varphi_2)$ 라면 모든 $v_1,\ldots,\,v_m$ 에 대해 $\varphi_1(v_i)= \varphi_2(v_i)$ 이며 가정에 의해 $\varphi_1 = \varphi_2$ 이다. 따라서 $\Gamma$ 는 단사이다.  

$V\ne \text{span}(v_1,\ldots,\,v_m)$ 라면 $v\in V- \text{span}(v_1,\ldots,\,v_m)$ 을 생각 할 수 있으며. $\Gamma (\varphi_1) = \Gamma(\varphi_2)$ 라도 $\varphi_1 \ne \varphi_2$ 일 수 있다. 

($2$) $\{v_1,\ldots,\,v_m\}$ 이 선형독립이라면 $\psi_j (v_i) = \delta_{ij}$ 를 만족하는 $\psi_j\in V^\ast$ ($j=1,\ldots,\,m$) 가 존재한다. $\phi = \sum_{j=1}^m \psi_j \in V^\ast$ 이면 $\Gamma (\phi)$ 는 전사함수이다.

$\Gamma$ 가 전사함수라고 하자. 임의의 $(x_1,\ldots,\,x_m)\in \mathbb{F}^m$ 에 대해 $\psi(v_i) = x_i$ 를 만족하는 $\psi \in V^\ast$ 가 존재한다. $\{v_1,\ldots,\,v_m\}$ 이 선형종속이라면 $c_1 v_1 + \cdots + c_m v_m =0$ 을 만족하는 $0$ 이 아닌 $c_j$ 가 존재한다. 이 때 일반성을 잃지 않고 $c_m \ne 0$ 이라고 할 수 있다. 즉 $v_m = \sum_{j=1}^{m-1} d_j v_j$ 이며, 

$$
x_m=\psi(v_m) = \sum_{j=1}^{m-1} d_j \psi (v_j) = \sum_{j=1}^{m-1}d_j x_j
$$ 

이어야 한다. 이것은 임의의 $(x_1,\ldots,\,x_m)$ 에 대해 성립할 수 없으므로 $\{v_1,\ldots,\,v_m\}$ 은 선형독립이어야 한다. 

:::

</br>



::: {#exr-axler-3_F_9}

$(v_1,\ldots,\,v_n)$ 이 $V$ 의 기저이며 $\{\varphi_1,\ldots,\,\varphi_n\}$ 이 이에 대한 쌍대 기저라고 하자. $\psi\in V'$ 에 대해

$$
\psi = \psi(v_1)\varphi_1 + \cdots + \psi(v_n)\varphi_n
$$

임을 보여라.
:::

::: {.solution}

@prp-dual_basis 에 의해 $\psi$ 는 $\{\varphi_1,\ldots,\,\varphi_n\}$ 의 선형 결합이다. $\psi = \sum_i c_i \varphi_i$ 라고 하면

$$
\psi(v_j) = \sum_{i=1}^n c_i \varphi_i (v_j) = c_j
$$

이므로 $\psi = \sum_i \psi(v_i)\varphi_i$ 이다.

:::

</br>

::: {#exr-axler_3_F_11}

$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$, $\boldsymbol{A}\ne \boldsymbol{0}$ 일 때 $\text{rank}(\boldsymbol{A})=1$ 일 필요충분조건은 어떤 $\boldsymbol{c}\in \mathcal{M}_{m}(\mathbb{F})$, $\boldsymbol{d}\in \mathcal{M}_n(\mathbb{F})$ 가 존재하여 $(\boldsymbol{A})_{ij} = (\boldsymbol{c})_i (\boldsymbol{d})_j$ 를 만족하는 것임을 보이시오.

:::

::: {.solution}

행렬의 행교환에도 rank 는 변화가 없으므로 일반성을 잃지 않고 $\boldsymbol{A}_{1:}\ne \boldsymbol{0}$ 임을 가정 할 수 있다. $\text{rank}(\boldsymbol{A})=1$ 이라면 첫번째 행이 아닌 나머지 행이 모두 첫번째 행의 스칼라배이므로 $\boldsymbol{d}=\boldsymbol{A}_{1:}$, 이며 $\boldsymbol{A}_{i:} = c_i \boldsymbol{A}_{1:}$ 인 $c_i$ 를 성분으로 갖는 $\boldsymbol{c}$ 를 생각하면 $(\boldsymbol{A})_{ij} = (\boldsymbol{c})_i (\boldsymbol{d})_j$ 이다.

역으로 $\boldsymbol{A}_{ij}=(\boldsymbol{c})_i (\boldsymbol{d})_j$ 라면 $\boldsymbol{A}\ne \boldsymbol{0}$ 이므로 $\boldsymbol{A}$ 는 $\boldsymbol{0}$ 벡터가 아닌 $\boldsymbol{d}$ 의 $c_i$ 배를 $i$ 번째 행으로 갖는 행렬이다. 따라서 $\text{rank}(\boldsymbol{A})=1$ 이다.

:::

</br>

::: {#exr-axler_3_F_12}

$V$ 에서의 항등사상의 쌍대사상은 $V^\ast$ 에서의 항등사상임을 보여라.

:::

::: {.solution}

항등사상 $I:V \to V$ 에 대한 쌍대사상 $I^T(\varphi) = \varphi \circ I = \varphi$ 이다. 

:::

</br>

::: {#exr-axler_3_F_13}

$T\in \mathcal{L}(\mathbb{R}^3, \mathbb{R}^2)$ 가 $T(x, y, z) = (4x+5y+6z, 7x+8y+9z)$ 로 정의되었다고 하자. $\varphi_1,\,\varphi_2$ 가 $\mathbb{R}^2$ 에서의 표준기저에 대한 쌍대기저이며 $\psi_1,\,\psi_2,\,\psi_3$ 는 $\mathbb{R}^3$ 에서의 표준기저에 대한 쌍대기저라고 하자. 이 때 $T^T(\varphi_1)$ 과 $T^T(\varphi_2)$ 를 $\psi_1,\,\psi_2,\,\psi_3$ 의 선형결합으로 표현하라.

:::

::: {.solution}

$\mathbb{R}^3$ 의 표준기저를 $\{e_1,\,e_2,\,e_3\}$ 라고 하고 $\mathbb{R}^2$ 의 표준기저를 $\{f_1,\,f_2\}$ 라고 하자. $T(e_1)=4f_1+7f_2$, $T(e_2) = 5f_1 + 8f_2$, $T(e_3)= 6f_1 + 9f_2$ 이다. 

 $T^T(\varphi_i) = \varphi_i\circ T$ 이므로,

$$
\begin{aligned}
T^T(\varphi_1) (e_1) & = 4, \\
T^T(\varphi_1) (e_2) & = 5, \\
T^T(\varphi_1) (e_3) & =6, \\
T^T(\varphi_2)(e_1) & = 7, \\
T^T(\varphi_2)(e_2) & = 8, \\
T^T(\varphi_2)(e_3) & = 9,
\end{aligned}
$$

이다. 즉 $T^T(\varphi_1) = 4\psi_1 + 5 \psi_2 + 6 \psi_3$, $T^T(\varphi_2) =  7\psi_1 + 8 \psi_2 + 9 \psi_3$ 이다.

:::

</br>

::: {#exr-axler_3_F_15}

유한차원 벡터공간 $V$ 에 대해 $T\in \mathcal{L}(U, V)$ 라고 하자. 이때 $T^T=0 \iff T=0$ 임을 보여라.

:::

::: {.solution}

(행렬과 전치행렬의 관계를 생각하면 당연하지만...)


$V$ 의 기저 $\{v_1,\ldots,\,v_m\}$ 에 대한 쌍대기저 $\{\varphi_1,\ldots,\,\varphi_m\}$ 을 생각한다. $T^T=0$ 이라면 모든 $\varphi_i$ 에 대해 $T^T(\varphi_i)= \varphi_i \circ T=0$ 이므로 $T=0$ 이어야 한다. 이제 $T=0$ 이라면 당연히 $T^T=0$ 이 된다.

:::

</br>

::: {#exr-axler_3_F_16}

유한차원 벡터공간 $U,\,V$ 를 생각하자. $\Phi:\mathcal{L}(U, V) \to \mathcal{L}(V^\ast, U^\ast)$ 가 $f(T)=T^T$ 로 정의된다 $\Phi$ 는 동형사상임을 보여라.

:::

::: {.solution}

$\Phi$ 가 선형사상임을 보이자. $T_1,\,T_2 \in \mathcal{L}(U, V),\, c\in \mathbb{F}$ 에 대해 $f(T_1+cT_2) = f(T_1) + cf(T_2)$ 임을 보이면 된다. 

$$
\begin{aligned}
\left[f(T_1) + cf(T_2)\right](\varphi) &= [T_1^T + cT_2^T](\varphi)  \\
&= \varphi \circ T_1 + \varphi \circ (cT_2) \\
&= \varphi \circ (T_1+cT_2) \\
&= [T_1+cT_2]^T(\varphi)\\
&= f(T_1+cT_2)(\varphi)
\end{aligned}
$$

이므로 $\Phi$ 는 동형사상이다. $\mathcal{L}(U, V)$ 와 $\mathcal{L}(V^\ast, U^\ast)$ 가 모두 유한차원 이므로 $\ker (\Phi)=0$ 임을 보이면 되는데 이미 @exr-axler_3_F_15 에서 보였다. 

:::

</br>

::: {#exr-axler_3_F_18}

유한차원 벡터공간 $V$ 에 대해 $U \subset V$ 일 때 $U=\{0_V\} \iff U^0 = V^\ast$ 임을 보여라.

:::

::: {.solution}

$U=\{0_V\}$ 를 가정하자. 모든 $\varphi \in V^\ast$ 에 대해 $\varphi (0_V)=0$ 이므로 $U^0 = V^\ast$ 이다. $U^0 = V^\ast$ 를 가정하자. $v\ne 0_V \in U$ 라면 $v$ 를 포함하는 기저를 구성했을 때(항상 가능하다) $v$ 에 대한 쌍대기저가 존재하므로 $U^0 = V^\ast$ 일 수 없다. 따라서 $U=\{0_V\}$ 이다. 

:::

</br>

::: {#exr-axler_3_F_19}

유한차원 벡터공간 $V$ 에 대해 $U\le V$ 라고 하자. 이 때 $U=V \iff U^0=\{0_V\}$ 임을 보여라.

:::

::: {.solution}

trivial. see @exr-axler_3_F_18

:::

</br>

::: {#exr-axler_3_F_20}

벡터공간 $V$ 에 대해 $U\le V,\, W\le V$ 일 때 $U \subset W \implies W^0 \subset U^0$ 임을 보여라.

:::

::: {.solution}

$$
\psi \in W^0 \implies \forall w\in W, \psi(w)=0 \implies \forall u\in U\subset W,  \psi(u)=0 \implies \psi \in U^0
$$

:::

</br>

:::{#exr-axler_3_F_21}

유한차원 벡터공간 $V$ 에 대해 $U\le V,\,W\le V$ 라고 하자. $W^0 \subset U^0 \implies U \subset W$ 임을 보여라.

:::

::: {.solution}


$$
u\in U \implies \forall \psi \in U^0,  \psi (u) = 0 \implies \forall\phi \in W^0 \subset U^0, \phi(u) =0 \implies u\in W
$$

:::

</br>

::: {#exr-axler_3_F_22}

$U\le V,\, W\le V$ 일 때 $(U+W)^0 = U^0 \cap W^0$ 임을 보여라.

:::

::: {.proof}

$\psi \in (U+W)^0$ 이면 모든 $u\in U,\, w\in W$ 에 대해 $\psi(u+w)=0$ 이어야 한다. $0_V\in U,\, 0_V\in W$ 이므로 $\psi (u)= \psi (v)=0$ 이어야 한다. 따라서 $\psi \in U^0 \cap W^0$ 이다. 즉 $(U+W)^0 \subset U^0 \cap W^0$ 이다.

이제 $\psi \in U^0 \cap W^0$ 라 하자. $v\in U+W$ 는 어떤 $u\in U,\, w\in W$ 에 대해 $v=u+w$ 이며, $\psi(v)= \psi(u+w)= \psi(u)+\psi(w)=0$ 이다. 즉 $U^0 \cap W^0 \subset (U+W)^0$ 이다.

:::


</br>

::: {#exr-axler_3_F_23}

$V$ 가 유한차원 벡터공간이고 $U\le V,\,W\le V$ 일 때 $(U\cap W)^0 = U^0 + W^0$ 임을 보여라.

:::

::: {.solution}

@exr-axler_3_F_22 로 부터 $\dim(U^0 \cap W^0) = \dim (U+W)^0$ 임을 안다. 따라서,

$$
\begin{aligned}
\dim (U^0 + W^0) &= \dim (U^0) + \dim (W^0) - \dim (U^0 \cap W^0) \\
& = \dim (V) - \dim (U) + \dim (V) - \dim (W) - \dim ((U+W)^0) \\
&= \dim (V) - \dim (U) + \dim (V) - \dim (W) - \dim (V) + \dim (U+W) \\
&= \dim (V) - \dim (U) - \dim (W)  + \dim (U) + \dim (W) - \dim (U\cap W)\\
& = \dim (V) - \dim (U\cap W) \\
& = \dim ((U\cap W)^0)
\end{aligned}
$$

이다. 또한 $\psi \in (U^0 + W^0)$ 이면 어떤 $\psi_U\in U^0,\, \psi_W\in W^0$ 에 대해 $\psi = \psi_U+\psi_W$ 이다. 따라서 $v\in U\cap W$ 이면 $\psi(v)= 0$ 이므로 $\psi \in (U\cap W)^0$ 이다. 즉 $U^0 + W^0 \subset (U \cap W)^0$ 이다. 따라서 $(U\cap W)^0 = U^0 + W^0$ 이다. 

:::

</br>

::: {#exr-3_F_25}

유한차원 벡터공간 $V$ 에 대해 $U \le V$ 일 때 $U'$ 을 다음과 같이 정의하자.

$$
U' = \{v\in V: \forall \varphi \in U^0,\, \varphi (v) = 0\}.
$$

$U=U'$ 임을 보여라.
:::

::: {.solution}

$U^0$ 의 정의에 의해 $U \subset U'$ 이다. 이제 $U'\le V$ 임을 보이자. $0_V\in U'$ 은 자명하며, $u_1,\,u_2\in U',\, c\in \mathbb{F}$ 과 $\varphi\in U^0$ 에 대해 $\varphi (u_1 +cu_2)= \varphi (u_1)+ c\varphi (u_2)=0$ 이므로 $U' \le V$ 이다.

$U$ 의 기저 $(u_1,\ldots,\,u_m)$ 을 확장하여 $(u_1,\ldots,\,u_m,\,v_1,\ldots,\,v_n)$ 이 $V$ 의 기저라고 하자. $v\not \in U$ 이면 $v=\sum_{i}a_i u_i + \sum_j b_i v_j$ 이며 $\varphi \in U^0$ 에 대해 $\varphi (v) = \sum_j b_j \varphi (v_j)$ 이며 $\varphi (v)\ne 0$ 이 되도록 하는 $\varphi$ 가 항상 존재한다. 따라서 $\dim U'= \dim U$ 이며 $U' \le U$ 이므로 $U=U'$ 이다.


:::

</br>

::: {#exr-3-F_26}

유한차원 벡터공간 $V$ 에 대해 $\Delta \le V^\ast$ 에 대해 $\Delta'$ 을 다음과 같이 정의하자.

$$
\Delta' = \{v\in V : \forall \varphi \in \Delta,\, \varphi (v)= 0 \}^0.
$$

$\Delta = \Delta'$ 임을 보여라.

:::

::: {.solution}

$D= \{v\in V:   \forall \varphi \in \Delta,\, \varphi(v)=0\}$ 이라 하면 $D \le V$ 임은 쉽게 보일 수 있다. 이 때 $\Delta' = D^0$ 이다. 그렇다면

$$
\phi \in \Delta \implies \forall v\in D,\, \phi(v) = 0 \implies \phi \in D^0=\Delta'
$$

이므로 $\Delta \subset \Delta'$ 이다. $\Delta$ 의 기저를 $\{\varphi_1,\ldots,\,\varphi_m\}$ 이라 하고 이를 확장하여 $V^\ast$ 의 기저 $\{\varphi_1,\ldots,\,\varphi_m,\,\psi_1,\ldots,\,\psi_n\}$ 를 구성 할 수 있다.  

:::