---
title: "일반화된 역행렬과 유사역행렬"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

::: {.callout-warning icon="false"}

#### 참고자료

[1] [STANLEY SAWYER 교수의 강의록](https://www.math.wustl.edu/~sawyer/handouts/GenrlInv.pdf)

:::

## 일반화된 역행렬

::: {.callout-note appearance="minimal" icon="false"}

::: {#def-generalized_inverse}

#### 일반화된 역행렬

행렬 $\boldsymbol{A} \in \mathcal{M}_{m \times n}(\mathbb{F})$ 에 대해 $\boldsymbol{AGA}=\boldsymbol{A}$ 를 만족하는 행렬 $\boldsymbol{G} \in \mathcal{M}_{n \times m}(\mathbb{F})$ 를 $\boldsymbol{A}$ 에 대한 **일반화된 역행렬(generalized inverse matrix)** 라고 한다. $\boldsymbol{A}$ 의 일반화된 역행렬을 $\boldsymbol{A}^{-}$ 로 표기한다. 

:::
:::

</br>

::: {#prp-generalized_inverse_of_invertible_matrix}

$\boldsymbol{A}$ 가 가역행렬이면 $\boldsymbol{G}=\boldsymbol{A}^{-1}$ 이다.

:::

::: {.proof}

$\boldsymbol{A}$ 가 가역행렬이면 $m=n$ 이다.
$$
\boldsymbol{AGA} = \boldsymbol{A} \implies \boldsymbol{AGAA}^{-1} = \boldsymbol{AA}^{-1} \implies \boldsymbol{AG}= \boldsymbol{I}_n \qquad \square
$$

:::

</br>

::: {#prp-gim_1}

$AA^-$ 는 와 $A^-A$ 는 projection 이다. 

:::

::: {.proof}

어떤 정사각 행렬 $M$ 이 $M^2=M$ 을 만족할 때 projection 이라고 한다. 

$$
\begin{aligned}
(A^-A)(A^-A) &=A^-(AA^-A) =  A^-A, \\
(AA^-)(AA^-) &= (AA^-A)A^- = AA^-. 
\end{aligned}
$$

따라서 $AA^-$ 와 $A^-A$ 는 projection 이다. $\square$

:::

</br>


::: {#prp-gim_2}

$A\in \mathcal{M}_{m \times n}(\mathbb{F})$ 이고 $G=A^-$ 일 때 임의의 $y\in \mathcal{M}_m(\mathbb{F})$ 에 대해 다음이 성립한다.

&emsp; ($1$) $Ax=y$ 가 해 $x\in \mathcal{M}_n(\mathbb{F})$ 를 가질 필요충분조건은 $AGy = y$ 이다.

&emsp; ($2$) 




Theorem 1.1. Let A by an m×n matrix and assume that G is a generalized inverse of A (that is, AGA = A). Then, for any fixed y ∈ Rm,
(i) the equation
Ax = y, x ∈ Rn (1.3)
hasasolutionx∈Rn ifandonlyifAGy=y(thatis,ifandonlyifyis
in the range of the projection AG).
(ii) IfAx=yhasanysolutions,thenxisasolutionofAx=yifandonly
if
Remark. If we want a particular solution of Ax = y for y in the range
x = Gy + (I − GA)z for some z ∈ Rn (1.4)

:::


::: {#prp-generalized_inverse_of_invertible_matrix}

$\boldsymbol{A}\in \mathcal{M}_{m \times n}(\mathbb{F})$ 와 $\boldsymbol{G}\in \mathcal{M}_{n \times n}$  에 대해 다음은 동치이다.

&emsp; ($1$) $\boldsymbol{G}$ 는 $\boldsymbol{A}$ 의 일반화된 역행렬이다.

&emsp; ($2$) $\boldsymbol{AG}$ 가 멱등행렬이고 $\operatorname{rank}(\boldsymbol{AG})= \operatorname{rank}(\boldsymbol{A})$ 이거나 $\boldsymbol{GA}$ 가 멱등행렬이며 $\operatorname{rank}(\boldsymbol{GA})= \operatorname{rank}(\boldsymbol{A})$ 이다.

&emsp; ($3$) $\boldsymbol{Ax}=\boldsymbol{y}$ 의 해는 $\boldsymbol{x}=\boldsymbol{Gy}$ 이다.

:::



::: {.proof}

($1\implies 2$) $AGA=A$ 이면 $AGAGA=AGA=A$ 이다. $(AG)^2A=A$  

($2\implies 3$) $Ax=y$ 에 대해 
:::
