 ---
title: "특성다항식, 최소다항식과 케일리-해밀턴 정리"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---


{{< include ../../latexmacros.qmd >}}

</br>

## 다항식 {#sec-polynomials}

여기서는 다항식의 여러가지 성질 중 벡터공간 $\mathbb{F}_n[t]$ 로서의 다항식과 앞으로 벡터공간을 다루는 데 사용될 다항식의 여러가지 성질에 대해 알아보기로 한다.

</br>

### 다항식의 기본적인 성질 {#sec-ALA_basic_properties_of_polynomial}

@exm-LA_vectorspace_polynomial 에서 정의한 바와 같다.

</br>

### 다항식의 영점 {#sec-ALA_zeros_of_polynomials}

::: {.callout-note appearance="minimal"}

::: {#def-ALA_zeros_of_polynomials}

#### 다항식의 영점

다항식 $p(t) \in \mathbb{F}[t]$ 에 대해 $p(c) = 0,\, c\in \mathbb{F}$ 이면 $c$ 를 $p$ 의 **영점(zeros)** 이라고 한다. 
:::

:::

</br>

다시말하자면 다항식 $p(t)$ 의 영점의 집합은 방정식 $p(t)=0$ 의 해의 집합이다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-ALA_degree_one_factor_from_zeros}

$p(t) \in \mathbb{F}_n[t]$ 이며 $c$ 가 $p(x)$ 의 영점이라면 어떤 $q(t)\in \mathbb{F}_{n-1}[t]$ 에 대해 

$$
p(t) = (t-c)\,q(t)
$$

이다.

:::

</div></br>

::: {.proof}

$p(t) = a_0 + a_1t + \cdots + a_nt^n$ 이라고 하자. $p(c)=0$ 이므로 

$$
\begin{aligned}
p(t)-p(c) &= a_1(t-c) + a_2(t^2-c^2) + \cdots + a_n(t^n-c^n) \\
&= (t-c)\left(a_1 + a_2(t+c) + \cdots + a_n \sum_{k=0}^{n-1} t^k c^{n-1-k}\right)
\end{aligned}
$$

이다. $a_n\ne 0$ 이므로 $\deg (q) = n-1$ 이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-ALA_degree_and_zeros}

$p(t)\in \mathbb{F}_n[t]$ 이면 $p(t)$ 는 많아야 $n$ 개의 영점을 가진다.

:::

</div></br>

::: {.proof}

@thm-ALA_degree_one_factor_from_zeros 에 따라 $m>n$ 개의 근을 가지면 $\deg(p) \ge m > n$ 이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_division_of_polynomials}

$p,\,q\in \mathbb{F}[t]$ 이고 $q\ne 0$ 일 때 어떤 $s,\,r\in \mathbb{F}[t],\, \deg (r) <\deg (q)$ 가 존재하여

$$
p(t) = q(t)\,s(t) + r(t)
$$

이며, 이 $s,\,r$ 은 유일하게 정해진다.

:::

</div></br>

::: {.proof}

$n=\deg (p),\, m=\deg (q)$  라고 하자. $m>n$ 이면 $s(t)=0,\, r(t)=p(t)$ 이면 된다. 이제 $n\ge m$ 인 경우를 생각하자. 다항식 $s$ 에 대해

$$
X=\{1,\,t,\,t^2,\ldots,\,t^{m-1},\, q(t),\, q(t)t,\ldots,\, q(t)t^{n-m}\}
$$

은 $\mathbb{F}_n[t]$ 에서 선형독립이며(@exm-LA_linear_dependency_of_polynomials) 또한 $\mathbb{F}_n[t]$ 에 포함된다. $X$ 에 $n+1$ 개의 원소가 포함되므로 $X$ 는 $\mathbb{F}_n[t]$ 의 기저이다. $p(t) \in \mathbb{F}_n[t]$ 이므로, 

$$
p(t) = b_0 + b_1 t + \cdots b_{m-1}t^{n-1} + q(t)\left(a_1 + a_2 t + \cdots + a_{n-m}t^{n-1}\right)
$$

을 만족하는 $a_0,\ldots,\,a_{n-m},\,b_0,\ldots,\,b_{m-1}$ 이 유일하게 결정된다. $\square$

:::

</br>

이제 대수학의 기본정리를 소개한다. 대수학의 기본정리는 여러가지 방법으로 증명 할 수 있지만 여기서는 증명을 싣지는 않겠다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-ALA_fundamental_theorem_of_algebra}

#### 대수학의 기본정리

$p(t) \in \mathbb{C}_n[t]$ 이며 $\deg (p) > 0$ 일 때 $p(t)$ 는 영점을 가진다.

:::

</div></br>

대수학의 기본정리는 다항식의 영점을 어떻게 발견할 것인가에 대해서는 말하지 않는다. 단지 복소계수 다항식의 경우 최소한 하나의 영점을 가진다는 것을 보여준다. @thm-ALA_degree_one_factor_from_zeros 와 대수학의 기본정리(@thm-ALA_fundamental_theorem_of_algebra) 를 이용하면 다음을 알 수 있다. 


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-ALA_fundamental_theorem_of_algebra_2}

$p(t) \in \mathbb{C}_n[t],\, n\ge 1$ 이면 어떤 $c_1,\ldots,\,c_n\in \mathbb{C}$ 에 대해 $p(t)$ 는 다음의 꼴로 표현 될 수 있으며 이 때 $(c,\, c_1,\ldots,\,c_n)$ 은 유일하게 정해진다.

$$
p(t) = c(t-c_1) \cdots (t-c_n).
$$

:::

</div></br>

::: {.proof}

우선 $p\in \mathbb{C}_n[t]$ 일 때 일차식의 곱으로 분해됨을 induction 을 사용하여 보일 수 있다 $n=1$ 일 경우는 자명하다. $n-1$ 에 대해 성립하을 가정하자. 대수학의 기본정리에 의해 $p(t)$ 는 영점 $c_1$ 을 가지며 @thm-ALA_degree_one_factor_from_zeros 에 의해 $p(t) = (t-c)q(t)$ 인 $q(t)$ 가 존재한다. 또한 $\deg (q)= \deg (p)-1$ 이므로 induction 의 가정에 의해 $q(t)$ 는 $n-1$ 개의 일차식의 곱이므로 $p(t)$ 는 $n$ 개의 일차식의 곱이 된다는 것을 알 수 있다.

$\{c,\,c_1,\ldots,\,c_n\}$ 의 유일함을 보이자. 다른 $\{d,\, d_1,\ldots,\,d_n\}$ 에 대해

$$
p_1(t) = c (t-c_1)\cdots (t-c_n),\qquad p_2(t) = d(t-d_1)\cdots (t-d_n)
$$

라고 하면 $p(t) = p_1(t) = p_2(t)$ 이므로 우선 $t^n$ 의 계수를 비교하면 $c=d$ 이다. 또한 $p_1(c_1)=0$ 이므로 $p_2(c_1)=0$ 이어야 하며, 따라서 $c_1 \in (d_1,\ldots,\,d_n)$ 이어야 한다. $d_1=c_1$ 이라고 놓을 수있으며, 그렇다면 $(t-c_2) \cdots (t-c_n) = (t-d_2)\cdots (t-d_n)$ 이어야 한다. 앞서의 방법으로 $c_2=d_2$ 라 놓을 수 있으며 이 방법을 계속 하면 $c_1=d_1,\ldots,\,c_n=d_n$ 이 된다. 즉 $(c,\,c_1,\ldots,\,c_n)$ 이 유일하게 정해진다. $\square$

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_pair_zeros_in_real_polynomial}

실계수 방정식 $p(t)$ 와 $c\in \mathbb{C}-\mathbb{R}$ 에 대해 $p(c)=0$ 이면 $p(\overline{c})=0$ 임을 보여라.

:::

</div></br>

::: {.solution}

$p(t) = a_0 + a_1t + \cdots + a_nt^n$ 이라고 하자. $p(c) = 0$ 이면 $\overline{p(c)}=0$ 인데 $p$ 가 실계수 방정식이면 $\overline{p(c)}= p(\overline{c})$ 이므로 $p(\overline{c})=0$ 이다.

:::

</br></br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_factorization_of_real_polynomial}

$p(t)\in \mathbb{R}_n[t],\, n\ge 1$ 일 때 $p$ 는 아래와 같이 일차다항식과 $x^2+b_jx +c_j,\, (b_j^2 < 4c_j)$ 형태인 이차다항식으로 분해된다.

$$
p(x) = c(x-c_1)\cdots (x-c_m)(x^2+b_1x + c_1) \cdots (x^2 + b_kx + c_k).
$$ {#eq-ALA_factorization_of_real_polynomial}

:::

</div></br>

::: {.proof}

$p(t)\in \mathbb{R}_n[t]$ 와 같은 계수를 갖는 복소계수 다항식 $q(t)$ 을 생각하자. @thm-ALA_fundamental_theorem_of_algebra_2 에 의해 $q(t)$ 는 일차식의 곱으로 분해된다. $q(t)$ 의 영점 가운데 실수인 것을 $c_1,\ldots,\,c_n$ 이라고 하고 복소수인 것들을 $\lambda_1,\ldots,\,\lambda_l$ 이라고 하자. @exr-ALA_pair_zeros_in_real_polynomial 에 의해 $q(\lambda_1)= 0$ 이므로 $q(\overline{\lambda_1})=0$ 이어야 하며 $r_1(t) = x^2 - (\lambda_1 + \overline{\lambda_1}) + |\lambda_1|^2$ 이 $q(t)$ 를 분해해야 하고 $b_1 = (\lambda_1) + \overline{\lambda_1},\, c_1 =|\lambda_1|^2$ 에 대해 $b_1^2<4c_1$ 이어야 한다. $q(t)/r_1(t)$ 에 대해서도 이 방법을 계속 사용 할 수 있다. 따라서 $q(t)$ 는 실수근과 복소수근에 대해 @eq-ALA_factorization_of_real_polynomial 와 같이 분해 할 수 있다. $\square$

:::

</br>

### 연습문제

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_4_12}

#### 라그랑쥬 다항식


$n\in \mathbb{Z}_+$ 에 대해 $p(t)\in \mathbb{C}_n[t]$ 일 때 서로 다른 $t_0,\ldots,\,t_n \in \mathbb{R}$ 에 대해 $p(t_i)\in \mathbb{R}$ 이면 $p$ 의 모든 계수는 실수임을 보여라.

:::

</div></br>

::: {.solution}

$p(t) = a_0 + \cdots + a_n t^n$ 일 때 서로 다른 $t_0,\ldots,\,t_n$ 에 대해 $p(t_i)$ 값을 안다면 $p(t)$ 가 유일하게 정해진다는 것을 보이자. 

$$
\boldsymbol{L} = \begin{bmatrix} 1 & t_0 & t_0^2 & \cdots & t_0^n \\ 1 & t_1 & t_1^2 & \cdots & t_1^n \\ & & \vdots & & \\ 1 & t_n^1 & t_n^2 & \cdots & t_n^n\end{bmatrix},\qquad \boldsymbol{a} = \begin{bmatrix} a_0 \\ a_1 \\ \vdots \\ a_n\end{bmatrix},\qquad \boldsymbol{p}= \begin{bmatrix} p(t_0) \\ p(t_1) \\ \vdots \\ p(t_n)\end{bmatrix}
$$

를 생각하자. $\boldsymbol{La}$ 의 $i$ 번째 성분은 $p(t_i)$ 와 같으므로 $\boldsymbol{La}=\boldsymbol{p}$ 를 만족하는 $\boldsymbol{a}$ 가 $\mathbb{R}$-벡터로서 존재한다면 우리는 원하는 답을 얻는 것이다. 여기서 $\boldsymbol{L}$ 은 Vandermond 행렬로 @exr-determinant_of_vandermond_matrix 에서 보았듯이 서로 다른 $t_0,\ldots,t_n$ 에 대해 $\det(\boldsymbol{L}) \ne 0$ 이다. 즉 $\boldsymbol{L}$ 은 가역행렬이며 따라서 $\boldsymbol{La}=\boldsymbol{p}$ 에 대한 nontrivial solution $\boldsymbol{a}$ 가 존재한다. $\boldsymbol{L}$ 과 $\boldsymbol{p}$ 가 실수에서의 행렬과 벡터이므로 $\boldsymbol{a}$ 도 모든 성분이 실수이다. 

:::


</br>

## 특성다항식 {#sec-characteristic_polynomial}

정사각 행렬에 대한 특성다항식은 이미 [특성다항식](../part1/ch1_04_eigenvalue.qmd#sec-LA_characteristic_polynomial) 에서 정의하였지만 환기를 위해 다시 한번 정의한다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-ALA_characteristic_polynomial_re}

#### 특성다항식

$\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대한 $p_{\boldsymbol{A}}(\lambda) = \det (\lambda \boldsymbol{I}-\boldsymbol{A})$ 를 **특성 다항식(characteristic polynomial)** 이라 한다.

:::
:::

</br>

또한 우리는 다음을 보였다.

- @prp-LA_invariance_of_characteristic_polynomial : 특성 다항식은 닮음 변환에 대해 불변이다. 즉 행렬 $\boldsymbol{A}\in \mathcal{M}_{n\times n}(\mathbb{F})$ 과 가역행렬 $\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $p_{\boldsymbol{A}}(\lambda) = p_{\boldsymbol{P^{-1}AP}}(\lambda)$ 이다.

- @prp-LA_eigenvalue_characteristic_polynomial : $\boldsymbol{A}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 에 대해 $\lambda\in \mathbb{F}$ 가 $\boldsymbol{A}$ 의 고유값이기 위한 필요충분조건은 $p_{\boldsymbol{A}}(\lambda)=0$ 인 것이다.

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-ALA_trace_of_matrix}

#### 행렬의 trace

$\text{tr} : \mathcal{M}_{n\times n}(\mathbb{F}) \to \mathbb{F}$ 는 다음과 같이 정의된다.

$$
\text{tr}(\boldsymbol{\boldsymbol{A}}) = \sum_{i=1}^n A_{ii}.
$$

:::
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_trace_is_invariant_under_similar_transformation}

정사각 행렬에 대한 trace 는 닮은 변환에 대해 불변이다.

:::

</div></br>

::: {.proof}

$\boldsymbol{A},\,\boldsymbol{P}\in \mathcal{M}_{n \times n}(\mathbb{F})$ 이며 $\boldsymbol{P}$ 가 가역이라고 하자. 

$$
\begin{aligned}
\text{tr}(\boldsymbol{P}^{-1}\boldsymbol{AP}) &= \sum_{i=1}^n\left(\boldsymbol{P}^{-1}\boldsymbol{AP}\right)_{ii} = \sum_{i, j, k=1}^n (P^{-1})_{ij}A_{jk}P_{ki} = \sum_{j, k=1}^n A_{jk} (\boldsymbol{PP}^{-1})_{kj} = \sum_{j=1}^n A_{jj} \\
&= \text{tr}(\boldsymbol{A}). \qquad \square
\end{aligned}
$$

:::

</br> 
<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_SNU_7_4_1}

$L\in \mathcal{L}(V)$ 이고 $p(\lambda) \in \mathbb{F}[\lambda]$ 라고 하자. $v \in E(\lambda, L)$ 이면 $v \in E(p(\lambda), p(L))$ 임을 보여라.

:::

</div></br>

::: {.solution}

$p(t) = a_nt^n + \cdots + a_1t  + a_0$ 라고 하자. $L\in \mathcal{L}(V)$ 이면 

$$
\begin{aligned}
p(L) -p(\lambda)I_V &=  a_n(L^n -\lambda^n I_V) + \cdots + a_1(L-\lambda I_V)   \\
&= (L-\lambda I_V)\left[  \cdots \right]
\end{aligned}
$$ 

이므로 $\left( p(L)-p(\lambda) I_V\right) v = 0$ 이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_SNU_7_4_2}

$L,\,T\in \mathcal{L}(V)$ 이고 $T$ 가 가역사상일 때 $p(t)\in \mathbb{F}[t]$ 이면 $p(T^{-1}LU) = T^{-1}p(t)T$ 임을 보여라.

:::

</div></br>

::: {.solution}

임의의 정수 $m$ 에 대해 $(T^{-1}LT)^m = T^{-1}L^mT$ 임을 이용하여 쉽게 보일 수 있다. 

:::

</br>

### 행렬의 대각화와 특성다항식 {#sec-ALA_characteristic_polynomial_and_diagonalization}

@thm-LA_diagonalizability 에서 우리는 행렬의 대각화에 대해 정리하였다. 이제 행렬의 대각화를 특성다항식의 관점에서 보자.

-- to be done -- 


</br>

## 케일리 해밀턴 정리

::: {.callout-note appearance="simple" icon="false"}
::: {#def-ALA_annihilator_ideal}

#### Annihilator Ideal

$\mathbb{F}$-벡터공간 $V$ 에 대해 $L\in \mathcal{L}(V)$ 일 때 아래와 같이 정의된 $I_L$ 를 **annihilator ideal** 이라고 한다.

$$
\mathcal{I}_L = \{ p(t) \in \mathbb{F}[t] : p(L)=0 I_V\}
$$

:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">
 
::: {#prp-ALA_annihilator_ideal}

$\mathbb{F}$-벡터 $V$ 에 대해 $L\in \mathcal{L}(V)$ 일 때 다음을 보여라.

&emsp;($1$) $\mathcal{I}_L \le \mathbb{F}[t]$.

&emsp;($2$) $g(t)\in \mathbb{F}[t],\, p \in \mathcal{I}_L \implies g(t)p(t) \in \mathcal{I}_L$.
:::

</div></part3>

::: {.proof}

($1$) $0\in \mathcal{I}_T$ 임은 자명하다. $p,\, q\in \mathcal{I}_L,\,c\in \mathbb{F}$ 에 대해 $(p+cq)(t) = p(t) +cq(t) \in \mathcal{I}_L$ 임은 자명하다. 이로부터 $\mathcal{I}_L\le \mathbb{F}[t]$ 라는 것을 쉽게 보일 수 있다.

($2$) trivial 하다.

:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_similarity_relation_in_annihilator_ideal}

$S,\, T\in \mathcal{L}(V)$ 에 대해 $S\sim T$ 이면 $\mathcal{I}_S= \mathcal{I}_T$ 이다.

:::

</div></br>

::: {.proof}

가역연산자 $U\in \mathcal{L}(V)$ 에 대해 $S=U^{-1}TU$ 라고 하자. $p\in \mathcal{I}_T$ 이면, $p(S) = U^{-1}p(T)U$ 이므로 $p \in \mathcal{I}_S$ 이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_annihilator_ideal_is_nontrivial}

유한차원 벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 에 대해 $\mathcal{I}_L \ne \{0\}$ 이다.

:::

</div></br>

::: {.proof}

$\dim (V) = n$ 이라고 하자. $\dim(\mathcal{L}(V)) = n^2$ 이므로, $\{I_V,\, T, \ldots,\, T^{n^2}\}$ 는 선형종속이다. $\square$

:::


</br>

이제 여기서 가장 중요한 케일리-해밀턴 정리를 증명할 차례이다. 그러나 그 전에 미리 보일 것이 있다. 

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_before_cayley_hamilton}

$\boldsymbol{B}_i\in \mathcal{M}_{n \times n}(\mathbb{F})$ 는 상삼각행렬이며 $i$ 번째 대각성분이 $0$ 이라고 하자. 이 때 $\prod_{i=1}^n \boldsymbol{B}_i = \boldsymbol{B}_1 \boldsymbol{B}_2 \cdots \boldsymbol{B}_n = \boldsymbol{0}$ 임을 보여라.

:::

</div></br>

::: {.solution}

상삼각행렬의 곱은 상삼각행렬이다. $\boldsymbol{B}_1\boldsymbol{B}_2$ 는 첫번째열과 두번째 열이 영벡터이다. 이로부터 즉 $k\le n$ 에 대해 $\prod_{i=1}^k \boldsymbol{B}_i$ 는 1열부터 $k$ 번째 열까지 영벡터임을 가정 할 수 있고, 이를 수학적 귀납법으로 보이자. $k=1$ 일 때는 이미 보였다. $k$ 에 대해 성립함을 가정하자. $\prod_{i=1}^{k+1} \boldsymbol{B}_i  = \left(\prod_{i=1}^k \boldsymbol{B}_i\right)\boldsymbol{B}_{k+1}$ 이며 $\left(\prod_{i=1}^k \boldsymbol{B}_i\right)$ 은 $k$ 열까지 영벡터인 상삼각 행렬이고 $\boldsymbol{B}_{k+1}$ 은 $k+1$ 번째 대각성분이 $0$ 인 상삼각행렬이다. $\boldsymbol{C}=\prod_{i=1}^k \boldsymbol{B}_i$ 라고 하자. 

$$
(\boldsymbol{C}\boldsymbol{B}_{k+1})_{j, k+1} = \sum_{m = 1}^{n} C_{jm}(\boldsymbol{B}_{k+1})_{m, k+1} 
$$

이며 $m=1,\ldots,\,k$ 에 대해 $C_{jm}=0$ 이며 $m=k+1, \cdots n$ 에 대해 $(\boldsymbol{B}_{k+1})_{m, k+1}=0$ 이므로 위 식은 $0$ 이 된다. 따라서 $\prod_{i=1}^n \boldsymbol{B}_i = \boldsymbol{B}_1 \boldsymbol{B}_2 \cdots \boldsymbol{B}_n = \boldsymbol{0}$ 이다.


:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-ALA_cayley_hamilton_theorem}

#### 케일리-해밀턴 정리(Cayley-Hamilton Theorem)

유한차원 $\mathbb{F}$-벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 와 특성다항식 $p_L(t) = \det (tI_V - L)$ 에 대해 $p_L \in \mathcal{I}_L$ 이다.

:::

</div></br>

::: {.proof}

$n=\dim (V)$ 라고 하자. 우선 $\mathbb{F}=\mathbb{C}$ 에 대해 증명한다. @thm-LA_uppertriangular_matrix_complex_field 에서 우리는 복소수체에서 정의된 모든 정사각행렬은 상삼각행렬과 닮았다는 것을 보였다. 따라서 우리는 상삼각행렬에 대한 특성다항식에 대해서만 증명하면 된다. $\boldsymbol{A}$ 가 상삼각행렬이라고 하면, $p_\boldsymbol{A}(t) = \prod_{i=1}^n (t-A_{ii})$ 이다. 이제 

$$
p_\boldsymbol{A}(\boldsymbol{A}) = \prod_{i=1}^n (\boldsymbol{A}-A_{ii}\boldsymbol{I}_n)=0
$$ 

임을 보이면 된다. $\boldsymbol{A}$ 가 상삼각행렬이므로 $(\boldsymbol{A}- A_{ii}\boldsymbol{I}_n)_{ii}  = 0$ 이다. 위의 @exr-ALA_before_cayley_hamilton 에서 보였듯이 $p_\boldsymbol{A}(\boldsymbol{A}) =0$ 이므로 $p_T(L) \in \mathcal{I}_L$ 이다.

이제 $\mathbb{F}=\mathbb{R}$ 인 경우에 대해 생각하자. $\mathbb{R}\subset \mathbb{C}$ 이므로 성립하지 않을 이유가 없다. $\square$ 

:::


</br>

## 최소다항식 {#sec-minimal_polynomial}

다항식 가운데 최고차 항의 계수가 1인 다항식을 **monic** 이라고 한다.


::: {.callout-note appearance="simple" icon="false"}
::: {#def-ALA_minimal_polynomial}

#### 최소다항식

$L\in \mathcal{L}(V)$ 에 대한 annihilator ideal $\mathcal{I}_L$ 가운데 1 차 이상의 다항식 중 가장 작은 차수를 갖는 monic 다항식을 $L$ 에 대한 **최소다항식(minimal polynomnial)** 이라고 한다. 

:::
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-ALA_existance_and_uniqueness_of_minimal_polynomial}

$L\in \mathcal{L}(V)$ 에 대한 최소다항식은 존재하며, 유일하다.

:::

</div></br>

::: {.proof}

@prp-ALA_annihilator_ideal_is_nontrivial 에 의해 $L$ 에 대한 최소다항식은 존재한다. 이제 $p,\,q$ 가 $L$ 에 대한 최소다항식이라고 하자. 당연히 두 다항식은 같은 차수 $m$ 를 가진다. $p \ne q$ 라면 $r=p-q$ 는 $m$ 보다 작은 차수를 가지며 $r(L)=0$ 이다. $p,\,q$ 가 최소다항식이므로 남은 유일한 가능성은 $r=0$ 일 때 뿐이며 따라서 $p=q$ 이다. $\square$
:::

</br>

위의 정리와 @prp-ALA_similarity_relation_in_annihilator_ideal 로부터 다음을 알 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#cor-minimal_polynomial_and_similar_transformation}

$V$ 에서의 두 연산자가 닮았으면, 두 연산자의 최소다항식은 같다.

:::

</div></br>

[케일리-해밀턴 정리](#thm-ALA_cayley_hamilton_theorem) 로부터 우리는 다음을 알 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_degree_limit_of_minimal_polynonmial}

$n$ 차원 벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 의 최소다항식의 차수는 $n$ 보다 작거나 같다

:::

</div></br>


아래도 역시 굳이 증명을 적을 필요는 없을 것이다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_divisability_of_annihilator_ideal}

$p\in \mathcal{I}_L$ 는 $L$ 에 대한 최소다항식으로 나누어 떨어진다. 또한 최소다항식에 임의의 다항식을 곱한 다항식은 $\mathcal{I}_L$ 포함된다.

:::

</div></br>

우리는 @prp-LA_eigenvalue_characteristic_polynomial 에서 연산자에 대한 특성다항식의 해가 그 연산자의 고유값임을 보였다. 실제로는 특성다항식이 아니라 최소다항식에 대해서도 성립한다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-ALA_minimal_polynomial_and_eigenvalues}

유한차원 벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 에 대해 $L$ 의 최소다항식의 해는 $L$ 의 고유값이다.

:::

</div></br>

::: {.proof}

$\lambda$ 가 $L$ 의 고유값이라면 최소다항식은 $(t-\lambda )$ 로 나누어저여 한다. 따라서 최소다항식은 서로 다른 고유값 $\lambda_1,\ldots,\,\lambda_n$ 에 대해 $(t-\lambda_1)\cdots (t-\lambda_n)$ 으로 나누어져야 한다. 즉 모든 고유값은 최소다항식의 해이다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_minimal_polynomial_and_subspace}

유한차원 벡터공간 $V$ 에 대해 $U\le V$ 이며 $L\in \mathcal{L}(V)$ 에 대해 $L|_U$ 가 $L$ 의 $U$ 에 대한 restriction 일 때 $L$ 의 최소다항식은 $L|_U$ 의 최소다항식으로 나누어진다.

:::

</div></br>

::: {.proof}

$p_L$ 이 $L$ 의 최소다항식이라고 하자. $u\in U$ 이면 $u\in V$ 이므로 $p(T)u=0$ 이다. 따라서 $p$ 는 $L|_U$ 에 대한 annihilator ideal 에 포함된다. $\square$

:::

</br> <div class="border" style="background-color:#FFF0F5 ;padding:5px;">

:::{#prp-ALA_constant_of_minimal_polynomal}

$L\in \mathcal{L}(V)$ 에 대해 다음의 두 명제는 동치이다. 

&emsp;($1$) $L$ 이 가역이 아니다.

&emsp;($2$) $p_L$ 의 상수항은 $0$ 이다.

:::

</div></br>

::: {.proof}
$L$ 이 가역이 아니면 $0$ 은 $L$ 의 고유값이므로 $p_L$ 의 상수항은 $0$ 이다. 역으로 $p_L$ 의 상수항이 $0$ 이라면 $0$ 이 $p_L$ 의 해이므로 $0$ 은 $L$ 의 고유값이다. 따라서 $L$ 은 가역이 아니다. 

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-ALA_even_dimensiona_kernel}

유한차원 $\mathbb{R}$-벡터공간 $V$ 와 $L\in \mathcal{L}(V)$ 를 생각하자. $b,\,c\in \mathbb{R},\, b^2-4c<0$ 일 때 $\text{nullity} (L^2+bL+cI_V)$ 는 짝수이다.

:::

</div></br>

::: {.proof}

$p(t) = t^2+bt+c,\, U = \ker (L^2+bL+cI_V)= \ker p(L)$ 라고 하자. @prp-LA_kernal_and_images_of_operator_under_polynomial 에 따라 $U$ 는 $L$-불변부분공간이다. $K=L|_U$ 라고 하면 $p(K)= p(L|_U)$ 이며 $K^2+bK+cI_U=0$ 이다. $u\in U$ 가 $\lambda$ 의 고유값을 갖는 $K$ 의 고유벡터라고 가정하자. 그렇다면

$$
0_U = (K^2+bK+cI_U)u = (\lambda^2+b\lambda + c)u = \left(\left(\lambda + \dfrac{b}{2}\right)^2 + c-\dfrac{b^2}{4} \right) u
$$

이며 $\left(\left(\lambda + \dfrac{b}{2}\right)^2 + c-\dfrac{b^2}{4} \right) > 0$ 이므로 $u=0$ 이다. 따라서 $K$ 에 대한 고유벡터는 존재하지 않는다. 

이제 $W$ 를 $U$ 의 $K$-불변 부분공간 가운데 짝수 차원을 갖는 가장 큰 부분공간이라고 하자. $W=U$ 이면 더 이상 할 것이 없다. $W\ne U$ 일 때 $w\in U-W$ 에 대해 $X=\text{span}(w,\, Lw)$ 라고 하자. $K(Kw)= K^2w = -bKw-cw \in X$ 이므로 $X$ 는 $K$-불변부분공간이다. $\dim (X)=1$ 이라면 $w$ 가 $K$ 의 고유벡터이므로 $w\in W$ 인데 이는 가정에 모순된다. 따라서 $\dim(X)=2$ 이며 $X \cap W = \{0_V\}$ 이므로

$$
\dim (W+X) =  \dim (W) + \dim (X) - \dim (W\cap X)= \dim (W)+2
$$

이다. $W+X$ 는 $W$ 보다 차원이 2만큼 큰 $K$-불변부분공간이므로 가정에 모순된다. 따라서 $U=W$ 이다. $\square$ $^1$ [<u>홀수 차원을 가질 수 없다는 증명은 안되지 않나?</u>]{.aside}

:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-ALA_odd_dimensional_vector_space_and_eigenvalue}

홀수 차원 벡터공간에서 정의된 연산자는 고유값을 가진다.

:::

</div></br>

::: {.proof}

@thm-LA_existance_of_eigenvector_for_complex_field 에 의해 유한차원 $\mathbb{C}$-공간에서 정의된 모든 연산자는 고유값을 가진다는 것을 안다. 따라서 $\mathbb{R}$-벡터공간에서 생각한다. $n=\dim (V)$ 라고 하자. $n=1$ 이면 당연하게도 성립한다. 이제 $n$ 보다 작은 홀수차원 $\mathbb{R}$-벡터공간 $V$ 에서 성립한다는 것을 가정하자. $L\in \mathcal{L}(V)$ 에 대한 최소다항식 $m(t)\in \mathbb{R}[t]$ 를 생각하자. 

만악 $m(t)$ 가 어떤 $\lambda\in \mathbb{R}$ 에 대해 $(t-\lambda)$ 로 나누어진다면 $\lambda$ 는 $L$ 의 고유값이므로 성립한다. 

:::

</br>

## 연습문제 {.unnumbered}

<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_4}

($1$) $V$ 가 $\mathbb{C}$-벡터공간이며 $L\in \mathcal{L}(V)$ 이라고 하자. $p(t)\in \mathbb{C}[t],\, a\in \mathbb{C}$ 에 대해 $a$ 가 $p(L)$ 의 고유값인 필요충분조건이 어떤 $L$ 의 고유값 $\lambda$ 에 대해 $a=p(\lambda)$ 인 것임을 보여라.

($2$) $V$ 가 $\mathbb{R}$-벡터공간 이면 ($1$) 이 성립하지 않을 수 있다는 것을 예를 들어 보여라.

:::

</div></br>

::: {.solution}
($1$) ($\implies$) $a$ 가 $p(L)$ 의 고유값이라면 $p(L)v=av$ 인 $v\in V$ 가 존재한다. $(p(L)-aI_V)v=0$ 이므로 $p(L)-aI_V$ 는 아래와 같은 일차식의 곱으로 분해된다.

$$
p(L)-aI_V = (L-a_1I_V)\cdots (L-a_mI_V),\qquad \text{where } a_1 \cdots a_m = a.
$$

$a_1,\ldots,\,a_m$ 가운데 어떤 것도 $L$ 의 고유값이 아니라면 $(p(L)-aI_v)v=0_V$ 가 될 수 없으므로 이중 최소한 하나는 $L$ 의 고유값이며 이를 $\lambda$ 라고 하자. 즉 $(p(L)-aI_V)v = (p(\lambda)-a)v = 0$ 이므로 $p(\lambda) =a$ 이어야 한다. 

($\,\Longleftarrow\,$) $L$ 의 고유값 $\lambda$ 에 대한 고유벡터 $v$ 가 존재하며 $p(L)v=p(\lambda)v = av$ 이므로 $v$ 는 $p(L)$ 에 대해 $p(\lambda)$ 의 고유값을 갖는 고유벡터이다.

($2$) ($\Longleftarrow$) 는 항상 성립한다. $\mathcal{M}_{2\times 2}(\mathbb{R})$ 에서 정의된 연산자 $L=\begin{bmatrix} 0 & 1 \\ -1 & 0 \end{bmatrix}$ 에 대해 $L^2=\begin{bmatrix} -1 & 0 \\ 0 & -1\end{bmatrix}$ 이며 $-1$ 을 고유값으로 갖는다. 그러나 $-1=p(\lambda)= \lambda^2$ 를 만족하는 $L$ 의 고유값은 $\mathbb{R}$ 벡터공간에서는 존재하지 않는다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_6}

$L=\mathcal{L}(\mathbb{F}^2)$ 는 $L(w,\,z):=(-z,\,w)$ 로 정의되었다. $L$ 에 대한 최소다항식을 구하라.

:::

</div></br>

::: {.solution}

$L(e_1)=-e_2$, $L^2(e_1)= e_1$ 이며 $L^2+I=0$ 이다. 따라서 최소다항식 $p(t) = t^2+1$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-art3_axler4_5b_7}

($1$) $K,\,L\in \mathcal{L}(\mathbb{F}^2)$ 이며 $KL$ 과 $LK$ 의 최소다항식이 다른 예를 들어라.

($2$) 유한차원 벡터공간 $V$ 에서 정의된 $K,\, L\in \mathcal{L}(V)$ 에 대해 $K,\,L$ 가운데 최소한 하나가 가역이면 $KL$ 과 $LK$ 의 최소다항식이 같다는 것을 보여라.

:::

</div></part3>

::: {.solution}

$K=\begin{bmatrix} 1 & 0 \\ 0 & 0\end{bmatrix},\, L=\begin{bmatrix} 0 & -1 \\ 0 & 0\end{bmatrix}$ 이면 $KL = \begin{bmatrix} 0 & -1 \\ 0 & 0\end{bmatrix},\, LK=\begin{bmatrix} 0 & 0 \\ 0 & 0\end{bmatrix}$ 이다. $KL$ 의 최소다항식 $p(t)= t^2+1$, $LK$ 의 최소다항식 $q(t) = t$ 이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">****

::: {#exr-ALA_axler4_5b_9}

$L\in \mathcal{L}(V)$ 가 어떤 기저에 대해 행렬로 표현했을 때 모든 행렬 성분이 유리수이다. 그렇다면 $L$ 의 최소다항식의 계수는 모두 유리수라는 것을 보여라.

:::

</div></br>

::: {.solution}

$n=\dim(V)$ 라고 하자. 유리행렬로 표현되는 기저에 대한 행렬표현을 $M$ 이라고 하고 최소다항식을 $m(t) = t^m + a_{m-1}t^{m-1}+ \cdots + a_1t + a_0$ 라고 하자. $m(M)$ 은 $n^2$ 개의 유리계수 선형방정식이며, 그 해인 $a_0,\ldots,\,a_{m-1}$ 은 그 해이다. $m(t)$ 가 최소다항식이므로 그 해는 반드시 존재하며, 유리계수 선형방정식이므로 그 해는 당연히 유리수이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_10}

$V$ 가 유한차원 벡터공간이고 $L\in \mathcal{L}(V)$ 이며 $v\in V$ 이다. 모든 $m\ge \dim(V)-1$ 에 대해 다음이 성립함을 보여라.

$$
\text{span}(v,\, Lv,\ldots,\, L^{m}v) = \text{span} (v,\, Lv,\ldots,\, L^{\dim(V)-1}v).
$$

:::

</div></br>

::: {.solution}

@prp-ALA_degree_limit_of_minimal_polynonmial 로 부터 우리는 최소다항식의 차수가 $\dim(V)$ 보다 작거나 같음을 안다. 즉 $n \le \dim (V)$ 을 최소다항식의 차수일 때

$$
t^n = a_{n-1}t^{n-1}+ \cdots + a_1 t + a_0
$$

이며 이것을 이용하면 $k\ge n$ 에 대해 $L^k$ 를 $\{L^{n-1},\ldots,\,L,\, I_V\}$ 의 선형결합으로 표현 할 수 있다. 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_12}

$L\in \mathcal{L}(\mathbb{F}^n)$ 은 $L(x_1,\,x_2,\ldots,\,x_n) := (x_1,\,2x_2,\ldots,\,nx_n)$ 이다. $L$ 에 대한 최소다항식을 구하라.

:::

</div></br>

::: {.solution}

표준기저 $(e_1,\ldots,\,e_n)$ 에 대해 $L(e_k) = ke_k$ 이다. 따라서 최소다항식은 $m_L(t) = \prod_{i=1}^n (t-k)$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_14}

$V$ 가 유한차원 벡터공간이고 $L\in \mathcal{L}(V)$ 에 대한 최소다항식은 

$$
m_L (t) = 4+5t-6t^2-7t^3+2t^4+t^5
$$ 

이다. $L^{-1}$ 에 대한 최소다항식을 구하라.

:::

</div></br>

::: {.solution}

우선 다음 보조정리를 증명하자.

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-ALA_order_of_minimal_polynomial_of_inverse}

$L\in \mathcal{L}(V)$ 가 가역이면 $L$ 과 $L^{-1}$ 의 최소다항식의 order 는 같다.

:::

</div></br>

::: {.proof}

$L$ 의 최소다항식이 $m_L(t) = t^n + a_{n-1}t^{n-1}+ \cdots + a_1 t + a_0$ 라고 하자. $q(t) = a_0 t^n + \cdots + a_{n-1}t + 1$ 에 대해 

$$
q(L^{-1}) = L^{-n}m_L(L) = a_0 \left(L^{-1}\right)^n + a_1 \left(L^{-1}\right)^{n-1} + \cdots + a_{n-1}\left(L^{-1}\right) + I_V
$$

이며, 따라서, $q(L^{-1})v = L^{-n}m_L(L)v = 0$ 이므로 $q(t)\in \mathcal{I}_{L^{-1}}$ 이다. 따라서 $L^{-1}$ 의 최소다항식 $m_{L^{-1}}(t)$ 의 차수는 $L$ 의 최소다항식 $m_L(t)$ 의 차수보다 작거나 같다. 만약 작다면 같은 방법으로 $m_{(L^{-1})^{-1}}(t)$ 을 구할 수 있으며 이 차수가 $m_L(t)$ 의 차수보다 작기 때문에 모순이 된다. 따라서 $\deg(m_{L^{-1}}) = \deg(m_L)$ 이다. $\square$ 

:::

@lem-ALA_order_of_minimal_polynomial_of_inverse 에 따라 $L^{-1}$ 의 최소다항식은 $m_{L^{-1}} = \frac{1}{4}q(t)$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_15}

$V$ 가 유한차원 복소벡터공간이고 $\dim (V)>0$ 이며 $L\in \mathcal{L}(V)$ 라고 하자. 함수 $f:\mathbb{C}\to \mathbb{R}$ 을 $f(\lambda) = \text{rank} (T-\lambda I_V)$ 로 정의하자. $f$ 가 연속함수가 아님을 보여라.

:::

</div></br>

::: {.solution}
$V$ 가 유한차원 복소벡터공간이므로 $L$ 은 반드시 유한개의 고유값을 가진다. $\lambda_0$ 가 고유값이라고 하면 어떤  $\delta>0$ 에 대해 $(\lambda_0 - \delta,\,\lambda_0 + \delta )$ 구간에 다른 $L$ 의 고유값이 존재하지 않는다. 이 경우 $|\lambda -\lambda_0|<\delta \implies f(\lambda) \ne f(\lambda_0)$ 이므로 연속이 아니다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_16}

#### 동반 행렬 (companion matrix)

$n-1$ 차 다항식 

$$
p(t) = a_0 + a_1 t + \cdots + a_{n-2}t^{n-2} + a_{n-1} t^{n-1}  + t^n\in \mathbb{F}[t]
$$  

에 대해 다음과 같이 정의된 $C(p)\in \mathcal{M}(\mathbb{F})_{n\times n}$ 을 $p$ 에 대한 **동반 행렬 (companion matrix)** 라고 한다.


$$
C(p) = \begin{bmatrix} 0  & & & & & -a_0 \\ 1 & 0 & & & & -a_1 \\ & 1 &  \ddots & & & -a_2 \\ & & \ddots & & & \vdots \\ & & & &  0 & -a_{n-2} \\& & & &  1 & -a_{n-1} \end{bmatrix}.
$$


$p(t)$ 가 $C(p)$ 의 최소다항식임을 보여라.

:::

</div></br>

::: {.solution}

표준 기저 $(e_1,\ldots,\,e_n)$ 에 대해

$$
C(p)e_i = \left\{\begin{array}{ll} e_{i+1}, \qquad & \text{if }i < n \\ \displaystyle \sum_{j=1}^n -a_{j-1}e_j \qquad & \text{if } i =n \end{array}\right. .
$$

이다. 이로부터

$$
\left[C(p)^n  +\sum_{j=1}^{n-1} a_{j-1}C(p)^j \right] e_1 = 0
$$

이며, 그 $n$ 보다 작은 계수의 다항식 $q(t)$ 에 대해 $q(C(p))e_1=\ne 0$ 임을 알 수 있다. 또한 

$$
\left[C(p)^n + \sum_{j=1}^{a_j} C(p)\right] e_j = 0
$$

임을 알 수 있다. 따라서 $p(t)$ 는 $C(p)$ 의 최소다항식이다.

::: {.callout-important appearance="minimal"}

이 문제에서 우리는 임의의 $n$ 차 monic 다항식을 최소다항식으로 갖는 $n\times n$ 행렬이 존재한다는 것을 알게 되었다. 따라서 어떤 행렬에 대해 정확한 고유값을 아는 식 혹은 알고리즘이 존재한다면 우리는 다항식의 정확한 해를 항상 구할 수 있게 된다. 우리는 이것이 불가능하다는 것을 이미 알고 있다. 

:::


:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4-5b_17}

유한차원 $\mathbb{F}$-벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 와 $L$ 의 최소다항식 $m_L$ 을 생각하자. $c\in \mathbb{F}$ 일 때 $L-c I_V$ 의 최소다항식은 $m_L(t+c)$ 임을 보여라.

:::

</div></br>

::: {.solution}

$K:=L-cI_V$ 라고 하자. 모든 $v\in V$ 에 대해 $m_L(L)v=0_V$ 이므로 $m_L(K+cI)v=0_V$ 이다. 따라서 $K$ 에 대한 최소다항식 $m_K(t)$ 는 $m_L(t+c)$ 를 나눈다. 또한 모든 $v\in V$ 에 대해 $m_K(K)v=0_V$ 이므로 $m_K(L-cI_V)v=0_V$ 이어야 한다. 따라서 $m_L(t)$ 는 $m_K(t-c)$ 를 나눠야 한다. 즉 $m_L$ 과 $m_K$ 는 같은 차수이다. 이로부터 $m_K(t) = m_{L-cI_V}(t)= m_L(t+c)$ 임을 알 수 있다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_18}

유한차원 $\mathbb{F}$-벡터공간 $V$ 에서 정의된 $L\in \mathcal{L}(V)$ 와 $L$ 의 최소다항식 $m_L$ 을 생각하자. $c\in \mathbb{F},\, c\ne 0$ 에 대해 $cL$ 의 최소다항식은 $c^{\deg (m_L)} m_L(t/c)$ 임을 보여라.

:::

</div></br>

::: {.solution}

$K:=cL$ 이라고 하자. $v\in V$ 에 대해 $m_L(L)v = 0$ 이므로 $m_L(K/c)v=0$ 이다. 또한 $m_K(K)v=0$ 이므로 $m_K(cL)=0$ 이다. 즉 $m_K$ 는 $m_L$ 의 상수배이며 monic 이어야 하므로 $m_K(t)=c^{\deg (m_L)} m_L(t/c)$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_19}

유한차원 $\mathbb{F}$-벡터공간 $V$ 와 $L\in \mathcal{L}(V)$ 에 대해 

$$
X = \{q(L) :q(L) \in \mathbb{F}[L]\}
$$

이면 $\dim (X)$ 는 $L$ 에 대한 최소다항식의 차수와 같음을 보여라.

:::

</div></br>

::: {.solution}

$\dim (X)$ 는 $X$ 에 포함되는 최고차 다항식의 차수이다. $L$ 에 대한 최소다항식을 $m_L$ 이라고 하자. $\deg (p) > \deg (m_L)$ 이라면 $p$ 를 $m_L$ 로 나눈 몫인 다항식과 $p$ 가 같으므로 $\deg(p)$ 를 $\deg (m_L)$ 보다 작거나 같게 할 수 있다. 따라서 $\dim (X) = \deg (m_L)$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_21}

유한차원 $\mathbb{F}$-벡터공간 $V$ 와 $L\in \mathcal{L}(V)$ 를 생각한다. $L$ 의 최소다항식 $m_L$ 에 대해

$$
\deg (m_L) \le 1+ \text{rank}(L)
$$

임을 보여라.

:::

</div></br>

::: {.solution}

$U = \ker (L)$ 이라고 하고 $V/U$ 을 생각하자. $p$ 가 $V/U$ 의 최소다항식일 때 $v\in V-U,\, u\in U$ 에 대해 $Lp(L)(v+u)=0_V$ 이므로 $m_L(t)$ 는 $tp(t)$ 를 나눈다. 즉

$$
\deg (m_L) \le \deg(tp(t)) = 1+ \deg (p) = 1+ \dim (V) - \text{nullity}(L) = 1+ \text{rank}(L)
$$

이다. 
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-axler4_5b_22}

유한차원 $\mathbb{F}$-벡터공간 $V$ 와 $L\in \mathcal{L}(V)$ 를 생각하자. $L$ 이 가역인 것의 필요충분조건이 $I_V \in \text{span}(L,\,L^2,\ldots,\,L^{\dim(V)})$ 인 것임을 보여라.

:::

</div></br>

::: {.solution}

$m_L$ 이 $L$ 의 최소다항식이며 $n=\dim (V)$ 라고 하자. @prp-ALA_constant_of_minimal_polynomal 에 따라 $L$ 이 가역인 것의 필요충분조건은 $m_L$ 의 상수항이 $0$ 이 아닌것이다. 

($\implies$) $L$ 이 가역임을 가정한다. 즉 $m_L$ 의 상수항이 $0$ 이 아니며 $\deg (m_L) \le n=\dim (V)$ 이다. $m_L(L) = a_0I_V + a_1 L + \cdots + a_k L^k\, (k\le n) = 0$ 이며 $a_0 \ne 0$ 이므로 

$$
I_V \in \text{span}(L,\ldots,\, L^k) = \text{span}(L,\ldots,\, L^n)
$$

이다. 

($\,\Longleftarrow\,$) 이제 $I_V \in \text{span}(L,\,L^2,\ldots,\,L^n)$ 임을 가정하자. $I = c_1L + \cdots + c_kL^k$, $k\le n,\, c_k \ne 0$ 이라면 $m_L$ 은 $p(L) = L^k + c_{k-1}/c_k L^{k-1}+ \cdots + c_1/c_k L - 1/c_k$ 를 나눈다. 또한 $p$ 의 상수항이 $0$ 이 아니므로 $m_L$ 의 상수항도 $0$ 이 아니다. 따라서 $L$ 은 가역이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_23}

유한체원 벡터공간 $V$ 와 $L\in \mathcal{L}(V)$ 를 생각하자. $n=\dim (V)$ 라고 하자. $v\in V$ 에 대해 $\text{span}(v,\, Lv,\ldots,\,L^{n-1}v)$ 는 $L$-invariant 함을 보여라.

:::

</div></br>

::: {.soluiton}

$L$ 의 최소다항식 $m_L$ 에 대해 $\deg (m_L)\le n$ 임을 생각하면 자명하다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_28}

유한차원 벡터공간 $V$ 과 $L\in \mathcal{L}(V)$ 에 대한 쌍대공간 $V^\ast$ 와 쌍대사상 $L^T\in \mathcal{L}(V^\ast)$ 를 생각하자. 이 때 $L$ 에 대한 최소다항식은 $L^T$ 에 대한 최소다항식과 같음을 보여라.

:::

</div></br>

::: {.solution}

-- to be done --

$K=L^T$ 라고 하고 $L,\, K$ 에 대한 최소다항식을 각각 $m_L,\, m_K$ 라고 하자. 

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-ALA_axler4_5b_29}

2차원 이상의 유한차원 벡터공간에서 정의된 연산자는 2차원의 불변부분공간을 가짐을 보여라.

:::

</div></br>

::: {.solution}


::: 