 ---
title: "일반화된 고유공간과 조르당 형식"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

::: {.callout-warning appearance="minimal"}

이 장은 [특성다항식, 최소다항식과 케일리-해밀턴 정리](characteristic_polynomial.qmd) 로부터 이어진다.

:::

### 일반화된 고유벡터와 고유공간

벡터공간 $V$ 에서의 선형 연산자 $L\in \mathcal{L}(V)$ 에 대해 다음이 성립한다는 것은 쉽게 보일 수 있다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_kernel_of_power_of_operator}

$L\in \mathcal{L}(V)$ 이며 $L^0 :=I_V$ 라고 하자. 이 때 다음이 성립한다. 

$$
\{0\} \subset \ker (L^0) \subset \ker (L^1)  \subset \cdots \subset \ker (L^k) \subset \ker (L^{k+1})\subset \cdots.
$$
:::

</div>

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_equality_in_the_sequence_of_kernel}

$L\in \mathcal{L}(V)$ 에서 어떤 자연수 $m$ 에 대해 $\ker (L^m) = \ker (L^{m+1})$ 이면 $n\ge m$ 에 대해 

$$
\ker (L^n) = \ker (L^m)
$$

이다.
:::

</div></br>

::: {.proof}

@prp-part3_kernel_of_power_of_operator 에 의해 $\ker (L^m)\subset \ker (L^n)$ 이다. 따라서 $\ker (L^n) \subset \ker (L^m)$ 임을 보이면 된다. 만약 우리가 임의의 양의 정수 $k$ 에 대해 $\ker (L^{m+k+1}) \subset \ker (L^{m+k})$ 임을 보인다면 연쇄적으로 $\ker (L^n) = \ker (L^m)$ 라는 것을 보이는 것이 된다. 
$$
\begin{aligned}
v\in \ker (L^{m+k+1}) &\implies L^{m+1}(L^{k}v) = 0\\
&\implies L^k v \in \ker (L^{m+1}) = \ker(L^{m})
\end{aligned}
$$

이므로 $\ker (L^{m+k+1}) \subset \ker (L^{m})$ 이다. $\square$
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part3_kernel_of_power_of_dimension}

유한차원 벡터공간 $V$ 에서 $n=\dim (V),\, L\in \mathcal{L}(V)$ 일 때 $\ker (L^n) = \ker (L^{n+1}) = \cdots$ 이다.

:::

</div></br>

::: {.solution}
@prp-part3_equality_in_the_sequence_of_kernel 을 생각하면 어떤 $m<n$ 에 대해 $\ker(L^m)= \ker (L^{m+1})$ 이라면 위의 명제가 성립한다는 것을 안다. 이제 각각의 $m<n$ 에 대해 $\ker(L^m) \ne \ker (L^{m+1})$ 라면 $\dim (\ker(L^m)) < \dim (\ker (L^{m+1}))$ 이며 $\ker (L^n)=V$ 이므로 $\ker (L^n)= \ker (L^{n+1})=V$ 이다. $\square$
:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_kernel_range_of_power_of_operator}

유한차원 벡터공간 $V$ 에서 $n=\dim (V),\, L\in \mathcal{L}(V)$ 일 때 

$$
V = \ker(L^n)\oplus \text{im}(L^n)
$$

이다.
:::

</div></br>

::: {.proof}

$v\in \ker(T^n) \cap \text{im}(L^n)$ 이면 $L^n(v)=0$ 이며 $v=L^n (u)$ 인 $u\in V$ 가 존재한다. $L^n (v) = L^{2n}(u) = 0$ 이므로 $u \in \ker (L^{2n})$ 이다. 따라서 @exr-part3_kernel_of_power_of_dimension 에 의해 $u\in \ker (L^n)$ 이므로 $v=0$ 이다. 즉 $\ker(L^n) \cap \text{im}(L^n) = \{0\}$ 이다.

우리는 $\text{nullity}(L^n) + \text{rank}(L^n)=n$ 임을 안다. 따라서 $V = \ker (L^n) \oplus \text{im}(L^n)$ 이다. $\square$
:::

</br>

::: {.callout-note appearance="simple" icon="false"}
::: {#def-part3_generalized_eigenvectors_eigenspaces}
#### 일반화된 고유벡터와 일반화된 고유공간

$L\in \mathcal{L}(V)$ 이고 $\lambda$ 가 $L$ 의 고유값일 때 어떤 양의 정수 $k$ 와 영벡터가 아닌 벡터 $v\in V$ 가

$$
(L-\lambda I_V)^k v = 0
$$

를 만족하면 벡터 $v$ 를 고유값 $\lambda$ 를 갖는 연산자 $L$ 에 대한 **일반화된 고유벡터(generalized eigenvector)** 라고 한다. 고유값 $\lambda$ 에 대한 연산자 $L$ 의 집합과 영벡터의 합집합을 고유값 $\lambda$ 를 갖는 연산자 $L$ 에 대한 **일반화된 고유공간(generalized eigenspace)** 라고 한다.

:::
:::

이제 고유값 $\lambda$ 를 갖는 연산자 $L$ 에 대한 일반화된 고유공간을 $G(\lambda, L)$ 라고 쓰기로 하자. 다음 명제는 @exr-part3_kernel_of_power_of_dimension 에 따라 자명하다.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_generalized_eigenspace}
$$
G(\lambda, L) = \ker (L-\lambda I)^{\dim (V)}
$$

이다.
:::

</div></br>

<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_linearly_independent_generalized_eigenvectors}

서로 다른 고유값을 갖는 일반화된 고유벡터의 집합은 선형독립이다.

:::

</div></br>

::: {.proof}

$v_1,\ldots,\,v_n$ 이 각각 $\lambda_1,\ldots,\lambda_n$ 의 고유값에 대한 일반화된 고유벡터라고 하자. 

$$
0 = c_1 v_1 + \cdots + c_n v_n
$$

라 놓자. $k_1$ 를 $(L-\lambda_1 I)^{k}v_1$ 가 $0$ 이 되지 않는 가장 큰 자연수라고 하자. 연산자 $S \in \mathcal{L}(V)$ 를 

$$
S:=(L-\lambda_1 I)^k (L-\lambda_2I)^{\dim (V)} \cdots (L-\lambda_mI)^{\dim (V)}
$$

라고 하면, 
$$
0 = S (c_1v_1 + \cdots + c_n v_n) = c_1 S(v) 
$$

이며 $S$ 의 정의에 의해 $c_1 = 0$ 이다. 같은 방법으로 $c_2=\cdots =c_m=0$ 임을 보일 수 있으며, 따라서 $\{v_1,\ldots,\,v_m\}$ 은 선형독립이다. $\square$

::: 

</br>

### Nilpotent Operator


::: {.callout-note appearance="simple" icon="false"}
::: {#def-part3_nilpotent}

#### Nilpotent 연산자

벡터공간에서 정의된 연산자 $N\in \mathcal{L}(V)$ 가 어떤 $n\in \mathbb{Z}_+$ 에 대해 $N^n= 0$ 일 때 $N$ 을 **nilpotent**라고 한다. 

:::
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_nilpotent_operator_power_of_dimension}

$V$ 가 유한차원 벡터공간이며 $N\in \mathcal{L}(V)$ 가 nilpotent 일 때 $N^{\dim (V)} = 0$ 이다.

:::

</div></br>


::: {.proof}

$G(0,\, N) = V$ 이므로, @prp-part3_generalized_eigenspace 에 의해 성립한다. $\square$
:::


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_eigenvalue_of_nilpotent}

$N\in \mathcal{L}(V)$ 이 nilpotent 이면 $N$ 은 $0$ 이외의 고유값을 갖지 않는다.

:::

</div></br>

::: {.proof}

$\lambda \ne 0$ 이 $N$ 의 고유값이며 $v$ 가 $\lambda$ 에 대한 고유벡터라면 모든 $k\in \mathbb{Z}_+$ 에 대해 $N^kv=\lambda^k v \ne 0$ 이므로 $N$ 은 nilpotent 가 아니다. 따라서 nilpotent 의 고유값은 $0$ 뿐이다. $\square$ 

:::

</br>

### 연습문제 {.unnumbered}

::: {.callout-warning appearance="minimal"}

모든 벡터공간은 특별한 언급이 없다면 유한차원 벡터공간이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part3_axler4_8a_1}

$L\in \mathcal{L}(V)$ 이며 $\text{nullity}(L^4)=8,\, \text{nullity}(L^6)=9$ 이면 $m\ge 5$ 에 대해 $\text{nullity}(L^m)=9$ 임을 보여라.

:::

</div></br>

::: {.solution}

$\text{nullity}(L^5)$ 는 8 혹은 9이며 @prp-part3_equality_in_the_sequence_of_kernel 에 따라 8 이라면 $\text{nullity}{L^9}=8$ 이어야 하므로 $\text{nullity}(L^5)=9$ 이고 $m\ge 5$ 에 대해 성립한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part3_axler4_8a_2}
$L\in \mathcal{L}(V)$, $m\in \mathbb{Z}_+$ 이다. $v\in V$ 에 대해 $L^{m-1}v\ne 0_V$ 이지만 $L^mv=0_V$ 이다. 이 때 $\{v,\,Lv,\ldots,\,L^{m-1}v\}$ 는 선형 독립임을 보여라.

:::

</div></br>

::: {.solution}

$c_0v + c_1Lv + \cdots + c_{m-1}L^{m-1}v=0_V$ 에 대해 양변에 $L^{m-1}$ 연산을 취하면 $c_0L^{m-1}v=0_V$ 이다. $L^{m-1}v\ne 0$ 이므로 $c_0=0$ 이다. $L^{m-2}$ 를 취하면 $c_1=0$ 임을 알 수 있다. 이를 반복하면 

$$
c_0 = c_1 = \cdots = c_{m-1}=0
$$

이다. 따라서 $\{v,\,Lv,\ldots,\,L^{m-1}v\}$ 는 선형 독립임이다.
:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part3_axler4_8a_3}

$L\in \mathcal{L}(V)$ 일 때 다음을 보여라.

$$
V = \ker(L) \oplus \text{im}(L) \iff \ker (L^2) = \ker (L).
$$

:::

</div></br>

::: {.solution}

$\ker (L)= \ker (L^2)$ 이면 @prp-part3_equality_in_the_sequence_of_kernel 에 따라 모든 $m\ge 1$ 에 대해 $\ker (L^m) = \ker (L)$ 이다. 

($\implies$) $V=\ker (L)\oplus \text{im}(L)$ 임을 가정하자. $\ker (L)\subset \ker (L^2)$ 이므로 $\ker (L^2) \subset \ker (L)$ 임을 보이면 된다. $v\ne 0_V$, $v\in \ker (L^2)$ 라고 하자. $L^2 v=0_V$ 이므로 $Lv\in \ker (L)$ 이다. $v\not\in \ker (L)$ 이라면 $v\in \text{im}(L)$ 이므로 $Lu=v$ 인 $u\in V$ 가 존재한다. $u\not\in \ker (L)$ 이므로 $u\not\in \ker(L^3)$ 이며 따라서 $L^2 v = L^3 u \ne 0_V$ 이다. 그런데 이는 $v\in \ker(L^2)$ 임에 모순된다. 따라서 $v\in \ker(L)$ 이다. 즉 $\ker (L^2) = \ker (L)$ 이다.

($\,\Longleftarrow\,$) $\ker (L^2) = \ker(L)$ 임을 가정하자. 우선 $\ker (L) \cap \text{im}(L) = \{0_V\}$ 임을 보이자. $x\ne 0_V,\, x\in \ker (L)\cap \text{im}(L)$ 이라고 하자. $Lx=0$ 이며 $x=Ly$ 이면 $Lx = L^2 y = 0_V$ 이이다. 조건에 의해 $y\in \ker L$ 이므로 $Ly=x=0_V$ 이어야 하는데 이는 $x\ne 0_V$ 라는 가정에 모순이다. 따라서 $\ker (L) \cap \text{im}(L) = \{0_V\}$ 이다. $V$ 가 유한차원 벡터공간이므로 $\text{nullity} (L) + \text{rank}(L)= \dim (V)$ 이며 $\ker (L)\cap \text{im}(L) = \{0_V\}$ 이므로 $V=\ker (L) \oplus \text{im}(L)$ 이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-part3_axler4_8a_4}

$L\in \mathcal{L}(V),\, c\in \mathbb{F}$ 이며 어떤 양의 정수 $m$ 에 대해 $L$ 의 최소다항식이 $(z-c)^m$ 으로 나누어 떨어진다고 하자. 이 때 

$$
\text{nullity}\left((L-c I_V)^m \right) \ge m
$$

임을 보여라.

:::

</div></br>

::: {.solution}



:::

</br>

## 연산자의 분해

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-part3_invariance_of_kernel_and_image_of_operator}

$T\in \mathcal{L}(V)$ 일 때 $T$ 에 대한 다항식으로 정의된 연산자 $p(T)$ 의 $\ker (p(T))$ 와 $\text{im}
(p(T))$ 는 $T$ 에 대한 불변부분공간이다.

:::

</div></br>

::: {.proof}

$v\in \ker (p(T)) \implies p(T)(Tv)=T(p(T)v) = 0 \implies Tv \in \ker (p(T))$ 이므로 $\ker (p(T))$ 는 $T$ 에 대한 불변부분공간이다. 

:::
